# -*- coding: utf-8 -*-
# ep48 祭风  场景1 beats1-37 C05,C12 场景2 beats1-25 C05,C12
C05="the refined scholar in a feathered white cloak holding a feather fan"
C12="the handsome young commander in silk battle robes and light armor"
EP=48
SEG=[
dict(sceneIndex=1,blocking="帅帐内，周瑜立于帐口居右、帐内案前居左，北风自帐口灌入，旗幡在帐外扯动。",
soundscape="北风呜呜灌入帐口，旗幡被扯得啪啪作响，火折在手间反复开合。",
music="弦乐紧绷，风声作底。",
h3_sound="The north wind moans through the tent mouth, banners slap overhead, and a fire-flint clicks again and again in a restless hand.",
h3_music="Taut strings over a grounding of wind.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，北风卷着枯叶扑进城头，周瑜立在帐中望着天边，一遍遍摸着手里的火折，眉头拧成一团。",
shot="固定全景，一名披轻甲的青年立于帐中望向天边，反复摸着手里火折，眉头拧成一团，枯叶从帐口卷入。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视",composition="三分法",eyeline="天边方向",focus="锁定周瑜神态",stability="stable",
h3="Anchored to Picture 1, a static wide shot finds the young commander at the tent mouth gazing at the sky, turning a fire-flint over and over, brow knotted as dead leaves blow past."),
dict(beats=[2,2],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，帐外的旗幡被北风扯得啪啪作响，一下一下，敲在人心上，天色晦暗。",
shot="固定中景，帐口一面旗幡被北风扯得啪啪作响，一下一下拍着竿，天光晦暗。",
lens="50mm 标准，中浅景深",cameraPosition="旗幡+仰视 20°",composition="三分法",eyeline="翻飞的旗面",focus="锁定扯动的旗幡",stability="stable",
h3="Anchored to Picture 2, a static medium shot watches a banner snap to and fro in the north wind against a darkening sky, its whip striking like a pulse."),
dict(beats=[3,3],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜踱到帐口伸手试了试风向，又眉头一锁退回案前，指尖泛凉。",
shot="固定近景，披甲的青年踱到帐口伸手试风，眉头又锁，缩回指尖退回案前。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="帐外方向",focus="锁定试风的手",stability="stable",
h3="Anchored to Picture 3, a static close-up shows the commander stepping to the tent mouth to test the wind, frowning, and retreating with chilled fingers to the table."),
]),
dict(sceneIndex=1,blocking="周瑜在营帐间来回踱步，将官抱火器立于帐口候令，画面在案前与帐口间摆动。",
soundscape="周瑜踱步的衣声，将官抱火的甲叶声，北风仍呜呜。",
music="弦乐悬着，节奏压抑。",
h3_sound="The commander paces, an officer's armor settles as he waits with fire-locks at the tent mouth, and the wind keeps its low moan.",
h3_music="Strings hang tense, the rhythm pressing inward.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，一名将官抱着一摞火器进来请命，被周瑜摆手让先进去侯着，烛火骤晃。",
shot="固定中景，一名将官抱着一摞火器进帐请命，被打手势让到一侧候着，火光骤晃。",
lens="50mm 标准，中浅景深",cameraPosition="将官+平视",composition="三分法",eyeline="案后方向",focus="锁定一摞火器",stability="stable",
h3="Anchored to Picture 4, a static medium shot sees an officer enter cradling a stack of fire-locks to ask for orders, waved aside to wait, the lamp flame dipping."),
dict(beats=[5,5],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜在营帐间来回踱步，眼角的余光时不时望一眼天色，袍角卷入暗处。",
shot="固定近景，披甲的青年在帐间来回踱步，眼角的余光一次次掠向天色，神色紧绷。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="帐外天色",focus="锁定周瑜侧脸",stability="stable",
h3="Anchored to Picture 5, a static close-up follows the commander pacing between the tents, his glance stealing again and again toward the sky, jaw set tight."),
dict(beats=[6,6],seconds=3.0,size="wide",camera="Push In",chars=["C05","C12"],
frame="全景，料事如神的孔明进了帐，周瑜开口便问东风几时能起，烛火映亮二人。",
shot="镜头 Push In 推向进帐的两道人影，一名执扇儒生步入，案后的青年迎头便问东风几时起。",
lens="35mm 广角，全景深",cameraPosition="孔明+平视",composition="三分法",eyeline="案后青年",focus="锁定进帐的身影",stability="stable",
h3="Anchored to Picture 6, a push in meets the fan-holding scholar entering the tent as the young commander at once demands to know when the east wind will rise."),
]),
dict(sceneIndex=1,blocking="孔明立于帐口探风居左、周瑜案后居右，二人隔数步，北风灌入。",
soundscape="北风灌入帐口，孔明探风的衣袖猎猎，周瑜屏息静待。",
music="风声独奏，弦乐收住。",
h3_sound="The north wind pours in, the scholar's sleeve whips as he tests the air, and the commander holds his breath waiting.",
h3_music="Wind alone sounds, the strings falling silent.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明并不急着答，先走到帐口伸手探了探风，又抬头望了望天，从容不迫。",
shot="固定中景，执扇的儒生不急着答，走到帐口伸手探风，又抬头望天，一副了然在胸的从容。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视侧面",composition="三分法",eyeline="帐外天色",focus="锁定孔明神态",stability="stable",
h3="Anchored to Picture 7, a static medium shot shows the scholar, unhurried, step to the mouth to feel the wind and lift his eyes to the sky, calm as though the answer were his."),
dict(beats=[8,8],seconds=2.9,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明说得平静像在算一桩旧账，今夜子时前后，东南风便起，烛火在他指间。",
shot="镜头 Push In 缓推向开口的儒生，一句子时前后便起，说得平静像在算一桩旧账。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定孔明双目",stability="stable",
h3="Anchored to Picture 8, a slow push in settles on the scholar as he states it as matter-of-factly as doing sums, <d>[Chinese] 今夜子时前后，东南风便起。</d>"),
]),
dict(sceneIndex=1,blocking="周瑜案后居右、孔明帐中居左，二人相对，火折在周瑜手中收住。",
soundscape="周瑜追问的气声，火折收拢的一声轻响，北风忽紧。",
music="弦乐复起，较劲。",
h3_sound="The commander's sharp question hangs in the air, a fire-flint clicks shut, and the wind tightens for a moment.",
h3_music="The strings return, matching wits.",
cuts=[
dict(beats=[9,9],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，周瑜将手里的火折一收，紧紧盯着孔明，问若是风不起来又当如何，目光灼灼。",
shot="固定中景，披甲的青年收拢火折，紧盯着对面的儒生追问风若不起来又当如何，目光灼灼。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定周瑜目光",stability="stable",
h3="Anchored to Picture 9, a static medium shot has the young commander pocket the flint and fix on the scholar, pressing him on what happens should no wind rise."),
dict(beats=[10,10],seconds=2.7,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明神色如常不见半分虚张，一句风若不起甘领军法，答得干脆。",
shot="镜头 Push In 缓推向儒生，他神色如常不见半分虚张，一句甘领军法答得干脆。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定孔明神色",stability="stable",
h3="Anchored to Picture 10, a slow push in nears the scholar who answers without a flicker of bluff, <d>[Chinese] 风若不起，孔明甘领军法。</d>"),
dict(beats=[11,11],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜盯着他看了半晌，末了才缓缓点了点头，眼底仍有犹疑与忌惮交织。",
shot="固定近景，披甲的青年盯着对面看了半晌，末了才缓缓点头，眼底那丝忌惮并未全然退去。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定周瑜眼底",stability="stable",
h3="Anchored to Picture 11, a static close-up sees the young commander hold the scholar's gaze a long moment before finally giving a slow nod, wariness still edging his eyes."),
]),
dict(sceneIndex=1,blocking="孔明立于帐中负手望天、周瑜案后相问，二人由帐内议定转入登坛之约。",
soundscape="孔明负手的衣袍声，周瑜应下的沉音，北风渐弱一瞬。",
music="弦乐舒展一下，随即绷回。",
h3_sound="The scholar folds his hands behind him, the commander voices his assent, and for one beat the north wind eases.",
h3_music="The strings release briefly, then tighten again.",
cuts=[
dict(beats=[12,12],seconds=3.0,size="wide",camera="Static Shot",chars=["C05"],
frame="全景，孔明负手望了望天，转身应下，说愿登坛借三日东南风助公瑾一臂之力，灯影随行。",
shot="固定全景，执扇的儒生负手望天，转身应下登坛之约，愿借三日东南风助一臂之力。",
lens="35mm 广角，全景深",cameraPosition="孔明+平视",composition="三分法",eyeline="帐外天穹",focus="锁定转身的身影",stability="stable",
h3="Anchored to Picture 12, a static wide shot watches the scholar look to the sky, turn back, and undertake to climb the altar and borrow three days of southeast wind."),
dict(beats=[13,13],seconds=3.1,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明说得极是笃定，烦都督诚心筑坛，三更风便到，眉目舒展。",
shot="镜头 Push In 缓推向开口的儒生，一句烦都督筑坛、三更风到，说得极是笃定。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定孔明神情",stability="stable",
h3="Anchored to Picture 13, a slow push in holds the scholar voicing his request with quiet certainty, <d>[Chinese] 烦都督诚心筑坛，三更风便到。</d>"),
]),
dict(sceneIndex=1,blocking="江岸筑坛，众人忙作一团，周瑜立于坛侧督工，夯土立杆在画面铺开。",
soundscape="夯土声、立杆声此起彼伏，兵卒忙碌的脚步与呼喝，北风渐缓。",
music="鼓点催作，进度声。",
h3_sound="Earth is tamped, poles raised amid calls and tramping feet, while the north wind slackens by fractions.",
h3_music="A working drum pushes the labour forward.",
cuts=[
dict(beats=[14,14],seconds=3.0,size="wide",camera="Static Shot",chars=["C12","C05"],
frame="全景，周瑜将信将疑，依言在江岸筑起一座高台，台上立七星旗幡，众人劳作。",
shot="固定全景，江岸一座高台渐起，台上立起七星旗幡，披甲的青年督于坎边，一道儒影遥望。",
lens="35mm 广角，全景深",cameraPosition="周瑜+俯视 20°",composition="三分法",eyeline="立起的幡台",focus="锁定渐成的高台",stability="slight-shake",
h3="Anchored to Picture 14, a static wide shot watches a tall altar rise on the riverbank, seven-star pennons planted atop, the young commander directing the work."),
dict(beats=[15,15],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，众人动手夯土的夯土立杆的立杆，忙到日仄才把高台搭成，汗珠滚落。",
shot="固定中景，兵卒夯土的夯土、立杆的立杆，一直忙到日仄才把高台搭成，人人汗如雨下。",
lens="50mm 标准，中浅景深",cameraPosition="劳作兵卒+平视",composition="三分法",eyeline="渐高的台身",focus="锁定挥锄的身影",stability="slight-shake",
h3="Anchored to Picture 15, a static medium shot catches laborers tamping earth and rearing poles until dusk finally sees the altar finished, sweat streaking every brow."),
dict(beats=[16,16],seconds=3.0,size="medium",camera="Tilt Up",chars=["C12"],
frame="中景，周瑜亲自登台看了一圈，又命人四面点起长明灯把台面照得雪亮，火苗齐亮。",
shot="镜头 Tilt Up 自台脚摇上，披甲的青年登台绕看一圈，命人四面点灯，火苗一层层亮起照雪台面。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+仰视 20°",composition="对称",eyeline="点亮的长明灯",focus="锁定连排点亮的灯",stability="stable",
h3="Anchored to Picture 16, the camera tilts up the altar as the young commander circles the platform and orders every side lit, lamps blooming to flood it white."),
]),
dict(sceneIndex=1,blocking="孔明登台立于坛心，白衣鹤氅被北风扯起，周瑜率高台之下列队，坛上坛下对望。",
soundscape="孔明登台的脚步，坛下兵卒屏息，北风扯动袍袖的猎猎声。",
music="锣鼓转缓，法事凝重。",
h3_sound="The scholar's steps echo up the altar, the men below hold their breath, and the wind snaps at his sleeves.",
h3_music="The gongs turn slow, the rite growing grave.",
cuts=[
dict(beats=[17,17],seconds=3.0,size="wide",camera="Static Shot",chars=["C05"],
frame="全景，孔明这才缓缓步上台阶，在坛心站定，回身望了望台下列队的人群，风鼓鹤氅。",
shot="固定全景，执扇的儒生缓缓步上台阶在坛心站定，回身望一眼台下队列，袍角被风鼓起。",
lens="35mm 广角，全景深",cameraPosition="孔明+平视",composition="中心构图",eyeline="台下列队",focus="锁定坛心的身影",stability="stable",
h3="Anchored to Picture 17, a static wide shot follows the scholar up the steps to the very center, where he turns to survey the ranks below, robe lifted by the wind."),
dict(beats=[18,18],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明登台披散头发仗剑指天，绕着那面旗幡走步做法，剑光划过烛火。",
shot="固定中景，披发仗剑的儒生绕着旗幡走步做法，剑尖指天，剑光切开一片烛火。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+仰视 15°",composition="对角线",eyeline="指天的剑尖",focus="锁定挥动的长剑",stability="stable",
h3="Anchored to Picture 18, a static medium shot shows the loose-haired scholar pacing the rites with a sword leveled at the sky, its glint cutting through the lamps."),
dict(beats=[19,19],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，他时而仰天时而垂首，剑尖划出的圈子一圈比一圈大，烛火在剑下摇曳。",
shot="固定近景，披发的儒生时而仰天时而垂首，剑尖划出一个大过一个的圈，火光在指下摇曳。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="划圈的剑尖",focus="锁定孔明神情",stability="stable",
h3="Anchored to Picture 19, a static close-up watches the scholar sweep his blade in circles that widen each time, tipping his face to the sky and down again, flames swaying."),
]),
dict(sceneIndex=1,blocking="坛上孔明做法居中、坛下周瑜列马候于一侧，烛火在台边连排，画面分上下两层。",
soundscape="台下兵卒屏息，火烛噼啪，周瑜耐着性子等候的衣甲声。",
music="法锣紧促，转暗。",
h3_sound="The watched men below barely breathe, lamps crackle, and armor shifts as the commander waits with forced patience.",
h3_music="The rite-gong quickens, then falls dark.",
cuts=[
dict(beats=[20,20],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，台下的兵卒屏着气，望着那道身影在火烛间来回，大气都不敢出，烛影晃动。",
shot="固定中景，台下兵卒们屏着气，望着那道身影在烛火间往来穿梭，谁也不敢出大气。",
lens="50mm 标准，中浅景深",cameraPosition="兵卒+仰视 15°",composition="中心构图",eyeline="坛上身影",focus="锁定屏息的兵卒",stability="stable",
h3="Anchored to Picture 20, a static medium shot sees the men below staring breathless at the figure threading between the lamps, not one daring to draw a full breath."),
dict(beats=[21,21],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，周瑜在台下列马，看得眉头越锁越深，却也不得不耐着性子等，风撼袍甲。",
shot="固定全景，披甲的青年在台下列马，眉头越锁越深，却只能耐着性子候着，风撼动袍甲。",
lens="35mm 广角，全景深",cameraPosition="周瑜+仰视 20°",composition="三分法",eyeline="坛上之法",focus="锁定周瑜的神情",stability="stable",
h3="Anchored to Picture 21, a static wide shot keeps the young commander mounted at the altar's foot, brow sinking deeper and deeper as he forces himself to wait."),
dict(beats=[22,22],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，孔明脚步一顿，仗剑直指东南，口中低低念了几字又缓缓垂了下去，风一时静。",
shot="固定近景，做法的人脚步一顿，仗剑直指东南，低低念了几字又缓缓垂剑，风也似静了一瞬。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="东南方",focus="锁定直指的剑尖",stability="stable",
h3="Anchored to Picture 22, a static close-up holds the rite-check as the scholar halts, fixes his blade on the southeast, murmurs a few low words, then lets the sword fall."),
]),
dict(sceneIndex=1,blocking="坛下周瑜居中、将官上前探问，画面在坛下众人的焦灼中展开，北风不止。",
soundscape="北风呜呜一阵紧似一阵，将官探问压低的嗓音，周瑜下令的沉音。",
music="鼓点转躁，民心浮动。",
h3_sound="The north wind gusts harder, an officer's question cuts in low, and the commander's answer comes through gritted teeth.",
h3_music="The drums grow restless, the mood shifting.",
cuts=[
dict(beats=[23,23],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，北风依旧呜呜地刮一阵紧一阵，把周瑜心头的火越吹越旺，袍角绷紧。",
shot="固定中景，北风一阵紧过一阵，把候马而立的青年心头的火越吹越旺，衣角绷得笔直。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="北风来处",focus="锁定周瑜紧抿的唇",stability="stable",
h3="Anchored to Picture 23, a static medium shot shows the wind gusting tighter and tighter, fanning the young commander's smoldering temper, his hems pulled taut."),
dict(beats=[24,24],seconds=3.0,size="medium",camera="Static Shot",chars=["C12","C05"],
frame="中景，一名将官上前探问，说风还不来要不要先收兵回营，周瑜立于坛侧闻言皱眉。",
shot="固定中景，一名将官上前探问是否收兵回营，坛侧的披甲青年闻声蹙眉，没有立刻作答。",
lens="50mm 标准，中浅景深",cameraPosition="将官+平视",composition="三分法",eyeline="周瑜方向",focus="锁定探问的将官",stability="stable",
h3="Anchored to Picture 24, a static medium shot sees an officer come up to ask whether they should withdraw while no wind comes, the young commander frowning at the question."),
dict(beats=[25,25],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜摇了摇头只让他传下去任谁都不许下坛乱动，语气冷硬带着决断。",
shot="固定近景，披甲的青年摇头只让传令任谁不许下坛乱动，语气冷硬，带了决断。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="将官方向",focus="锁定周瑜神情",stability="stable",
h3="Anchored to Picture 25, a static close-up has the young commander shake his head and order that no one at all leave the altar until told, his tone flat and final."),
]),
dict(sceneIndex=1,blocking="坛上孔明踱步做法的身影、坛下周瑜候命的剪影，烛火在台边东倒西歪。",
soundscape="袍袖被风扯得猎猎，烛火扑啦啦，周瑜口干咽声。",
music="弦乐悬而未落，风噪渐厚。",
h3_sound="Sleeves snap in the wind, lamps gutter and sputter, and the waiting commander swallows on a dry throat.",
h3_music="Strings hang unresolved over a thickening wind.",
cuts=[
dict(beats=[26,26],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明仍在台上踱步，袍袖被北风扯得猎猎作响，身形却极稳，剑随步走。",
shot="固定中景，坛上那人仍踱着步，袍袖被风扯得猎猎，身形却稳得纹丝不动，剑随手走。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+仰视 15°",composition="对角线",eyeline="翻飞的袍袖",focus="锁定稳立的身影",stability="stable",
h3="Anchored to Picture 26, a static medium shot keeps the scholar pacing the altar, sleeves snapping raggedly yet his step utterly steady, blade riding his stride."),
dict(beats=[27,27],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，台下点起的烛火被风吹得东倒西歪，众人的倒影也跟着晃动，火光明灭。",
shot="固定近景，台边一列烛火被风压得东倒西歪，投射在地的倒影跟着晃，火光明灭不定。",
lens="85mm 长焦，极浅景深",cameraPosition="烛火+平视",composition="对称",eyeline="摇曳的火苗",focus="锁定东倒西歪的烛",stability="slight-shake",
h3="Anchored to Picture 27, a static close-up sees the lamps at the altar's foot bending every which way, their shadows tilting with the flicker, flames trembling on the edge."),
dict(beats=[28,28],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜在台下候到口干舌燥，抬头看那天眉毛越拧越紧，喉结滚动。",
shot="镜头 Push In 缓推向候台的青年，他候得口干舌燥，仰头望天，眉毛越拧越紧，喉结动了动。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+仰视 20°",composition="中心构图",eyeline="晦暗天穹",focus="锁定周瑜眉眼",stability="stable",
h3="Anchored to Picture 28, a slow push in nears the waiting commander as he looks up at the sky, parched and fretful, his brows drawing ever tighter."),
]),
dict(sceneIndex=1,blocking="坛下老卒与周瑜一远一近，北风不止，画面在嘀咕与喝止间起落。",
soundscape="老卒压低嘀咕，北风呜呜，周瑜回头的喝止一记。",
music="风噪为主，弦音几不可闻。",
h3_sound="An aged soldier mutters low, the north wind moans on, and a single sharp gesture quells him at once.",
h3_music="Wind noise carries it, strings nearly inaudible.",
cuts=[
dict(beats=[29,29],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，台下的老卒也忍不住嘀咕，说这么个隆冬哪儿来的东南风，边说边看天。",
shot="固定中景，台边一名老卒忍不住低声嘀咕隆冬哪来东南风，边说边抬头看天。",
lens="50mm 标准，中浅景深",cameraPosition="老卒+平视",composition="三分法",eyeline="晦暗的天",focus="锁定嘀咕的老卒",stability="stable",
h3="Anchored to Picture 29, a static medium shot hears an old soldier grumble that no southeast wind can come in deep winter, his eyes going to the dark sky."),
dict(beats=[30,30],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜回头扫了一眼，那老卒赶紧噤声低下了头，眼神如刀。",
shot="固定近景，披甲的青年回头扫过一眼，那老卒立刻噤声低头，再不敢吱声。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="老卒方向",focus="锁定周瑜眼神",stability="stable",
h3="Anchored to Picture 30, a static close-up catches the young commander glancing back, and the old soldier at once ducks his head, silenced under that look."),
dict(beats=[31,31],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，又过了半晌，那阵北风却像是渐渐有了减弱的迹象，旗角垂落一角。",
shot="固定中景，又过了半晌，猎猎的北风渐渐弱了下去，一面旗角软软垂落。",
lens="50mm 标准，中浅景深",cameraPosition="旗幡+仰视 20°",composition="三分法",eyeline="垂落的旗角",focus="锁定缓下的风势",stability="stable",
h3="Anchored to Picture 31, a static medium shot lets the gusting north wind faint at last, a pennon corner drooping soft as the sky holds its breath."),
]),
dict(sceneIndex=1,blocking="坛下周瑜居中、坛上孔明身影已收，画面由静待转入风将转头的征兆。",
soundscape="风声渐歇的空寂，周瑜心跳一般的衣声，江面方向一阵异响。",
music="弦乐骤收，静待巨响。",
h3_sound="The wind dies into an expectant hush, the commander's pulse shows in a stir of cloth, and from the river comes a strange first sound.",
h3_music="The strings drop away, waiting a deafening turn.",
cuts=[
dict(beats=[32,32],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜心口猛地一跳，仿佛已经嗅到风就要掉头的征兆，瞳孔微缩。",
shot="镜头 Push In 缓推向候立的青年，他心头一跳，眼睫微微一缩，仿佛嗅到风要掉头的预兆。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="前方江面",focus="锁定周瑜目光",stability="stable",
h3="Anchored to Picture 32, a slow push in finds the young commander's heart leaping as his eyes narrow, as if scenting the instant the wind will turn."),
dict(beats=[33,33],seconds=2.0,size="extreme-close",camera="Static Shot",chars=["C12"],
frame="大特写，周瑜低低自语一句，唇间几不可闻，眼底只剩掠向天际的一线光。",
shot="固定大特写，一张近在咫尺的脸低低吐出一句，眼底掠向天际，唇缝几乎未动。",
lens="100mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="天穹方向",focus="锁定周瑜唇齿",stability="stable",
h3="Anchored to Picture 33, a static extreme close-up holds the commander's face as he breathes a near-silent doubt into the wind, <d>[Chinese] 这风，当真会来么？</d>"),
dict(beats=[34,34],seconds=3.0,size="wide",camera="Pan Right",chars=["C12","C05"],
frame="全景，话音方落江面方向忽有一阵异样的响动，众人齐齐回头，孔明立于坛上静望。",
shot="镜头 Pan Right 随众人回头的动作扫过江面，一阵异响自那头传来，坛上的身影却静立不动。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视",composition="三分法",eyeline="江面异响来处",focus="锁定齐回头的人群",stability="slight-shake",
h3="Anchored to Picture 34, the camera pans right as the company turns at a strange stirring from the river, the figure on the altar alone standing motionless."),
]),
dict(sceneIndex=1,blocking="画面集中于棚顶旗幡与满坛旗幡，风声骤紧，众人仰面。",
soundscape="三更铜漏敲响，旗幡被风卷起的炸响，烛火灌风窜起的滋声。",
music="鼓点骤然爆发，风来。",
h3_sound="The third watch sounds, banners snap taut in a single gust, and a lamp flare rushes and roars as the wind arrives.",
h3_music="Drums burst out at the moment the wind comes.",
cuts=[
dict(beats=[35,35],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，三更的铜漏堪堪敲响，棚顶挂着的旗角忽然被风卷得笔直，猎猎炸响。",
shot="固定近景，三更的铜漏刚敲响，棚顶那面旗角忽地被风卷得笔直，猎猎炸响。",
lens="85mm 长焦，极浅景深",cameraPosition="旗幡+仰视 20°",composition="对角线",eyeline="卷直的旗角",focus="锁定绷直的旗布",stability="slight-shake",
h3="Anchored to Picture 35, a static close-up sees the third watch strike as a pennon corner is yanked taut by the wind, cracking like a whip."),
dict(beats=[36,36],seconds=3.0,size="wide",camera="Pan Left",chars=["C12"],
frame="全景，满台的旗幡齐刷刷地朝东偏出，风向硬生生转了个头，众人仰面惊呼。",
shot="镜头 Pan Left 扫过满台旗幡，一排旗角齐刷刷朝东偏出，风向硬生生转了个头，众声哗然。",
lens="35mm 广角，全景深",cameraPosition="旗幡+俯视 15°",composition="对称",eyeline="朝东偏出的旗",focus="锁定整排转头的旗",stability="slight-shake",
h3="Anchored to Picture 36, the camera pans left across the platform as every pennon snaps east in unison, the wind whipping round, voices rising in wonder."),
dict(beats=[37,37],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，帐中灯火被风一灌滋滋地窜了几窜亮得刺眼，窗纸被顶得闷响。",
shot="固定近景，帐中灯焰被风一灌窜起几窜亮得刺眼，窗纸被风顶得发出闷响。",
lens="85mm 长焦，极浅景深",cameraPosition="灯盏+平视",composition="中心构图",eyeline="窜起的火焰",focus="锁定狂窜的火苗",stability="handheld",
h3="Anchored to Picture 37, a static close-up sees the lamp blaze up in a sudden gust, flaring too bright as the paper pane bows under the wind."),
]),
# ============ 场景2 东南风起 ============
dict(sceneIndex=2,blocking="江岸，东南风灌江，周瑜立在风口居中，孔明坛上身影已淡出，兵卒登高远望。",
soundscape="东南风呜呜地自江上灌来，浊浪拍岸，人声压抑不住的低呼。",
music="弦乐骤起，肃杀又转。",
h3_sound="A southeast wind roars in off the river, dark waves slam the bank, and stifled cries can no longer be held in.",
h3_music="Strings surge, turning at once martial.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，东南风果然顺水而来，一时间江面上浊浪翻涌，吹得人站都站不稳，水雾扑面。",
shot="固定全景，江面浊浪翻涌，东南风扑面而至，岸上众人被吹得衣角狂卷、站立不稳。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="翻涌的浪头",focus="锁定翻卷的水雾",stability="slight-shake",
h3="Anchored to Picture 1, a static wide shot sees the southeast wind come full on, the river white with churning waves, everyone on the bank braced and unsteady."),
dict(beats=[2,2],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，有人登高望了望对岸，说风势已稳正是火攻的好时候，声音被风带远。",
shot="固定中景，一名兵卒登高望过对岸，扬声说风势已稳正是火攻时候，话被风扯得忽远忽近。",
lens="50mm 标准，中浅景深",cameraPosition="兵卒+仰视 15°",composition="三分法",eyeline="对岸方向",focus="锁定登高的兵卒",stability="stable",
h3="Anchored to Picture 2, a static medium shot hears a lookout climb to shout that the wind holds steady, now the hour for fire, his words shredded by the gale."),
dict(beats=[3,3],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜的嘴角不易察觉地往上挑了挑，随即又压平了下去，眼底有光一闪。",
shot="固定近景，披甲的青年嘴角极淡地往上挑了一挑，随即又压平，眼底有光一掠即没。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对岸江面",focus="锁定周瑜唇畔",stability="stable",
h3="Anchored to Picture 3, a static close-up catches the faintest upward turn of the young commander's lips, gone in an instant, a light flashing once behind his eyes."),
]),
dict(sceneIndex=2,blocking="周瑜立于江风正中，袍角被灌满，兵卒屏息列于两侧。",
soundscape="东南风灌满袍袖的猎猎声，江水滔滔，众人屏息待号令。",
music="鼓点转密，决战将临。",
h3_sound="The southeast wind fills the commander's sleeves, the river thunders, and every watcher holds breath for the command.",
h3_music="The drums thicken as battle gathers.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，他缓缓舒出一口气，仿佛憋了很久的一桩心事终于落了地，眉眼松了一分。",
shot="固定近景，候立的青年缓缓舒出一口气，像卸下一桩放久的心事，眉间松了一分。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="前方江面",focus="锁定周瑜神情",stability="stable",
h3="Anchored to Picture 4, a static close-up sees the young commander let out a long, slow breath, as if a weight he had carried too long has finally settled."),
dict(beats=[5,5],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，江风猎猎水声滔滔，岸上所有人都在屏息等着那一声号令，江面一片肃整。",
shot="固定全景，江风猎猎、水声滔滔，岸边众人屏息静立，只等那一声号令落下。",
lens="35mm 广角，全景深",cameraPosition="岸线+平视",composition="对称",eyeline="江面纵深",focus="锁定屏息的队列",stability="stable",
h3="Anchored to Picture 5, a static wide shot frames the whole shore holding its breath under roaring wind and river, a line of men rigid, awaiting the word."),
dict(beats=[6,6],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜立在风中，东风灌满袖口，他眼底的杀意被吹起一线，剑眉微挑。",
shot="镜头 Push In 缓推向风口的身影，东风灌满他袖口，眼底一线杀意被风掀起，剑眉微挑。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="对岸船阵",focus="锁定周瑜眼底杀意",stability="slight-shake",
h3="Anchored to Picture 6, a slow push in nears the commander standing into the gale, sleeves full of east wind, a line of killing intent lifted behind his eyes."),
]),
dict(sceneIndex=2,blocking="周瑜回身望向台下旗幡，兵卒低声叫好被喝止，画面在旗与周瑜间起落。",
soundscape="旗幡贴竿的扑打声，兵卒压不住的低呼，周瑜回头的一记压场。",
music="鼓声密中有隙，张弛。",
h3_sound="Pennons slap flat against their poles, a soldier's cheer slips out and is cut short by a glance, tension and slack riding the drums.",
h3_music="Drums run thick with a controlled gap, now tight, now loose.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，他回身朝台下望去，只见那几面旗幡被风压得低低贴向竿身，猎猎不止。",
shot="固定中景，披甲的青年回身望向台下，几面旗幡被风压得低低贴向竿身，扑打不止。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+仰视 20°",composition="三分法",eyeline="贴着竿的旗",focus="锁定压贴的旗幡",stability="stable",
h3="Anchored to Picture 7, a static medium shot has the commander turn to the pennons below, each pressed low and flat against its pole, snapping without cease."),
dict(beats=[8,8],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，有兵卒忍不住低声叫好说风终于来了，被周瑜一个眼神压了回去，立刻噤声。",
shot="固定中景，一名兵卒忍不住低声叫好说风终于来了，立刻被一个眼神压回去，忙低下头。",
lens="50mm 标准，中浅景深",cameraPosition="兵卒+平视",composition="三分法",eyeline="周瑜方向",focus="锁定低声叫好的兵卒",stability="stable",
h3="Anchored to Picture 8, a static medium shot sees a soldier's low cheer for the arriving wind cut dead by a single look, his head snapping down."),
dict(beats=[9,9],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜握拳抵在唇边，强压下心口的翻涌，只把目光远远投向对岸船阵。",
shot="镜头 Push In 缓推向握着拳踏唇的青年，他压住心口翻涌，只把目光远远投向对岸船阵。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="对岸船阵",focus="锁定抵唇的拳",stability="stable",
h3="Anchored to Picture 9, a slow push in finds the commander pressing a fist to his lips, holding down the surge in his chest, gaze fixed far across at the enemy fleet."),
]),
dict(sceneIndex=2,blocking="周瑜立于风中对岸远望，孔明的身影自坛上悄然不见，画面空出一角。",
soundscape="东风猎猎，周瑜沉声吐出的短句，高台方向再无人声。",
music="鼓点一顿，风起事成。",
h3_sound="The east wind roars, the commander lets fall a short, flat line, and from the altar no sound comes at all.",
h3_music="The drums catch on a beat, the deed done in the wind.",
cuts=[
dict(beats=[10,10],seconds=2.2,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜沉声吐出，东风已到火攻可成，字字落入江风，眉眼带着杀气与决断。",
shot="固定近景，披甲的青年沉声吐出两句，字字落进江风，眉宇间杀伐果断。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对岸船阵",focus="锁定周瑜唇齿",stability="stable",
h3="Anchored to Picture 10, a static close-up holds the young commander declaring it in flat, cutting words, <d>[Chinese] 东风已到，火攻可成。</d>"),
dict(beats=[11,11],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，他侧头望去，高台之上孔明的身影却已不在原地，只余空台与猎猎旗幡。",
shot="固定全景，侧头的青年望向高台，那名做法的身影已不在原地，只余一座空台、几面猎猎旗幡。",
lens="35mm 广角，全景深",cameraPosition="周瑜+仰视 20°",composition="三分法",eyeline="空荡荡的坛台",focus="锁定空台上的人去处",stability="stable",
h3="Anchored to Picture 11, a static wide shot follows the commander's glance to the altar, where the ritual figure no longer stands, only an empty platform and whipping pennons."),
]),
dict(sceneIndex=2,blocking="周瑜疾步走下坛台、扒开旗幡寻看，画面空台为主体，众人面面相觑。",
soundscape="周瑜疾步下坛的脚步声，旗幡被扒开的呼啦响，将官低声惊疑。",
music="弦乐悬空，人踪何处。",
h3_sound="The commander's swift steps echo down the altar, a pennon rustles as he pulls it aside, and muffled bewilderment spreads among the officers.",
h3_music="Thin, suspended strings ask where he has gone.",
cuts=[
dict(beats=[12,12],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C12"],
frame="全景，周瑜猛地回头，只见台下早已空空，只有几面被风吹翻的旗幡还在竿上拍打。",
shot="跟拍镜头随疾步的身影穿过坛下，只见那处早已空无一人，只有几面旗幡在竿上拍打。",
lens="35mm 广角，全景深",cameraPosition="周瑜+跟随",composition="三分法",eyeline="空空的坛下",focus="锁定翻卷的旗幡",stability="slight-shake",
h3="Anchored to Picture 12, a tracking shot carries the commander across the empty altar foot, where nothing remains but a few wind-torn pennons slapping their poles."),
dict(beats=[13,13],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，他疾步下坛，扒开那几面旗幡看了又看，确定不是自己看花了眼，指节收紧。",
shot="固定近景，疾步下坛的身影扒开几面旗幡层层看过，确认并非眼花，指节随之收紧。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="翻翻找找的旗后",focus="锁定周瑜神情",stability="stable",
h3="Anchored to Picture 13, a static close-up watches the commander go down in a hurry and pull the pennons aside to look and look again, certain now his eyes played no trick."),
dict(beats=[14,14],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，立在风里的将官也都面面相觑，谁也不知道孔明是何时走脱的，风里只剩低议。",
shot="固定中景，立在风里的将官们面面相觑，谁也说不上那人何时走脱，风里只剩低声议论。",
lens="50mm 标准，中浅景深",cameraPosition="将官+平视",composition="三分法",eyeline="空坛方向",focus="锁定面面相觑的将官",stability="stable",
h3="Anchored to Picture 14, a static medium shot shows the officers eyeing one another, none able to say when the man slipped away, only low talk left in the wind."),
]),
dict(sceneIndex=2,blocking="周瑜立于空坛首，望空一片，身后晨光渐起，画面由寻人转静。",
soundscape="风拂空坛，袍角轻响，周瑜一句低语落入风里。",
music="弦乐极淡，捺下情绪。",
h3_sound="Wind passes over the empty altar, cloth stirs softly, and one quiet line is given up to the sky.",
h3_music="Faint strings, emotion held under.",
cuts=[
dict(beats=[15,16],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜望着那空荡荡的坛台，缓缓捏紧了拳，低声吐出一句，却没有再多问一句。",
shot="镜头 Push In 缓推向望空而立的青年，他望着空台缓缓攥紧拳，低声念一句，再无多言。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="空荡坛台",focus="锁定周瑜攥紧的拳",stability="stable",
h3="Anchored to Picture 15, a slow push in holds the commander staring at the empty altar, fist slowly clenching, as he lets slip a single low remark, <d>[Chinese] 他走了。</d>"),
]),
dict(sceneIndex=2,blocking="周瑜立于江岸居中，火船于江边待命，黄盖立于一侧应声，画面由怅然转军令。",
soundscape="周瑜俯身吩咐的低音，黄盖应声的铁甲声，江风仍猎猎。",
music="鼓声复起，军令如山。",
h3_sound="The commander's low order rides the wind, a veteran's armor rings as he answers, and the gale keeps on.",
h3_music="The drums return, the command binding as iron.",
cuts=[
dict(beats=[17,17],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，周瑜扫了一眼四周，又望向那一片火光中仍矗立的铁索船阵，片刻后缓缓点头。",
shot="固定全景，披甲的青年扫过四周，又望向江上那片铁索船阵，片刻后缓缓颔首。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视",composition="对称",eyeline="江上船阵",focus="锁定缓缓颔首的身影",stability="stable",
h3="Anchored to Picture 17, a static wide shot sees the young commander sweep a glance around, then toward the iron-strung fleet, and after a breath give a slow nod."),
dict(beats=[18,18],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，他回头唤过黄盖，压低声音吩咐一句备好火船，灰甲老将挺立应命。",
shot="固定中景，回头的青年唤过一名灰甲老将，压低声音吩咐备好火船，那道挺立的身影应声上前。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视侧面",composition="三分法",eyeline="挺立的老将",focus="锁定周瑜与老将",stability="stable",
h3="Anchored to Picture 18, a static medium shot has the commander call a grey-haired veteran close and murmur an order to ready the fire-boats, his gaze steady on the old man."),
dict(beats=[19,19],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，灰甲老将应声挺了挺背，领了命转身去点那队早已备下的火船，铁鞭在腰后轻悬。",
shot="固定近景，一名灰甲老将应声挺了挺背，转身大步去点那队备下的火船，旧甲与铁鞭作响。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="火船方向",focus="锁定老将背影",stability="stable",
h3="Anchored to Picture 19, a static close-up sees the grey-haired veteran square his back at the order and turn to muster the waiting fire-boats, old armor and an iron mace sounding."),
]),
dict(sceneIndex=2,blocking="周瑜立于江岸居中分派，多名水军头领聚拢低头受命，火船在江边待发。",
soundscape="周瑜低声分派的细语，水军头领领命的应声，江水涌动。",
music="鼓弦并进，调度森严。",
h3_sound="The commander's quiet orders pass to the gathered fleet leaders, each replying low, the river rolling beneath.",
h3_music="Drum and string move together, dispatch run tight.",
cuts=[
dict(beats=[20,20],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，周瑜又唤来几名水军头领，低声把突袭的次序细细分派下去，指节一步一步点。",
shot="固定中景，披甲的青年唤来几名水军头领，逐项低声分派突袭次序，指节一处处点过。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+俯视 20°",composition="三分法",eyeline="聚拢的头领",focus="锁定点划的手指",stability="stable",
h3="Anchored to Picture 20, a static medium shot sees the young commander gather the fleet leaders and parcel out the order of the strike, tapping to each in turn."),
dict(beats=[21,21],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，他抬手看那被风灌满的袍袖，眼底的火色与风色交叠成一片，杀意已决。",
shot="固定近景，青年抬手看那被风灌满的袍袖，眼底火色与风色叠成一片，杀意落定。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="灌满风的袍袖",focus="锁定眼底交叠的神色",stability="stable",
h3="Anchored to Picture 21, a static close-up shows the young commander lifting his wind-filled sleeve, firelight and wind-flow crossing in his eyes, killing intent settled."),
dict(beats=[22,22],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，黄盖领命退去，江上风一阵紧似一阵越吹越猛，火船在岸沿隐隐待时。",
shot="固定全景，灰甲老将领命退去，江上风一阵紧过一阵，岸沿火船的轮廓在浪里忽隐。",
lens="35mm 广角，全景深",cameraPosition="江岸+平视",composition="三分法",eyeline="待发的火船",focus="锁定越吹越猛的风浪",stability="slight-shake",
h3="Anchored to Picture 22, a static wide shot follows the veteran away as the wind over the river mounts harder, the outlines of fire-boats dipping in the swell."),
]),
dict(sceneIndex=2,blocking="周瑜立于江岸居首，黄盖立于身侧偏后，火船灯火在雾夜尽头若隐。",
soundscape="周瑜沉声放令，旗号翻飞的响动，江风呜咽如备战号角。",
music="鼓点齐鸣，决战开始。",
h3_sound="The commander's orders ring out, signal flags flap up, and the river wind howls like a war cry.",
h3_music="All drums roll at once, the battle begins.",
cuts=[
dict(beats=[23,23],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜望向雾夜尽头那一点将燃未燃的战船灯火，牙关慢慢咬紧，眼底火色跃动。",
shot="镜头 Push In 缓推向远望的青年，他望着尽头一点将燃的灯火，牙关慢慢咬紧，眼底火光跃动。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="尽头的船灯",focus="锁定周瑜眼底火色",stability="stable",
h3="Anchored to Picture 23, a slow push in nears the young commander watching the one lamp not yet lit at the fog's far edge, jaw clenching as fire dances in his eyes."),
dict(beats=[24,24],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，东风灌满他的袍角，他抬手召来传令沉声而令全军备战，灰甲老将立于一侧应命。",
shot="固定全景，风灌满青年的袍角，他抬手召来传令，沉声下令全军备战，一名老将立于一侧应命。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视",composition="对称",eyeline="整肃的全军",focus="锁定下令的身影",stability="stable",
h3="Anchored to Picture 24, a static wide shot has the commander, sleeves full of east wind, summon the signal man and order the whole force to arms, a veteran answering at his side."),
dict(beats=[25,25],seconds=3.6,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜沉声放话，今夜便让曹贼见识见识三江的火，一字一句砸进江风。",
shot="固定近景，披甲的青年一字一句放话出口，字字砸进江风，眼底火与风俱烈。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对岸江面",focus="锁定周瑜唇齿",stability="stable",
h3="Anchored to Picture 25, a static close-up holds the young commander as he lays down the night's word in hard, ringing syllables, <d>[Chinese] 今夜，便让曹贼见识见识三江的火。</d>"),
]),
]