# -*- coding: utf-8 -*-
# ep49 火烧赤壁  场景1 beats1-35 C12,C19 场景2 beats1-27 C04
C12="the handsome young commander in silk battle robes and light armor"
C19="a burly grey-haired veteran in pitted iron armor"
C04="a heavy-build warlord with narrow eyes and a long beard in chancellor robes"
EP=49
SEG=[
dict(sceneIndex=1,blocking="火船被白布蒙住排在江边，黄盖立于船头居前、周瑜立于其后城头较高处，火把映亮。",
soundscape="江风猎猎，白布被扯下的呼啦声，火把噼啪，甲叶碰撞。",
music="战鼓低擂，杀机渐起。",
h3_sound="The wind snaps, canvas tears away with a great rasp, torches crackle, and armor clinks as men take post.",
h3_music="Low war drums gather, killing intent swelling.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Static Shot",chars=["C19"],
frame="全景，三江城头，周瑜一声令下，黄盖登上船头探手扯下盖着船舱的白布，火把映得铁甲发亮。",
shot="固定全景，一名灰甲老将应令登上船头，探手一把扯下蒙舱的白布，火把照亮他的铁甲。",
lens="35mm 广角，全景深",cameraPosition="黄盖+平视",composition="三分法",eyeline="扯下的白布",focus="锁定扯布的动作",stability="slight-shake",
h3="Anchored to Picture 1, a static wide shot sees a grey-haired veteran step to the bow and rip the canvas from the hold at a single command, torchlight flaring off his mail."),
dict(beats=[2,2],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，白布一掀底下整整齐齐码着一排草船，船上浇满油堆满硫磺，明火跃动。",
shot="固定近景，白布掀起，舱下露出一排浸透油料的草船、堆满硫磺，火把的光在油面上跳动。",
lens="85mm 长焦，极浅景深",cameraPosition="舱内草船+俯视 20°",composition="对角线",eyeline="浇油的草船",focus="锁定浸油的草捆",stability="stable",
h3="Anchored to Picture 2, a static close-up reveals, as the canvas comes away, the ranked straw boats drenched in oil and piled with sulfur, torchlight writhing across the surface."),
dict(beats=[3,3],seconds=3.0,size="wide",camera="Static Shot",chars=["C19"],
frame="全景，舱面上每一捆草都浸透了火油，风一过便飘来一股呛人的焦味，兵卒往来检视。",
shot="固定全景，满船草捆都浸透了火油，一阵风过卷起呛人焦味，兵卒在舱面往来检视。",
lens="35mm 广角，全景深",cameraPosition="舱面+俯视 20°",composition="三分法",eyeline="浸油的草捆",focus="锁定往来检视的兵卒",stability="stable",
h3="Anchored to Picture 3, a static wide shot carries the stench of fuel-soaked thatch across the deck as soldiers move to and fro checking every bale."),
]),
dict(sceneIndex=1,blocking="周瑜立于城头较高处、黄盖在船头偏下，二人一令一应，火船列成队形。",
soundscape="黄盖督检的低喝，火把噼啪，周瑜举令旗的风声，战鼓快了一拍。",
music="鼓点收紧，进击亦将发。",
h3_sound="The veteran barks a final check, torches crackle, the young commander lifts the signal flag, and the drum quickens by a beat.",
h3_music="The drums tighten, poised to release.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，黄盖督着兵卒最后检查一遍引火物，又往船尾看那杆顺风的旗，眉眼沉稳。",
shot="固定中景，灰甲老将督着兵卒作最后检查，又回看船尾那杆顺风的旗，眉眼神色沉稳。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视侧面",composition="三分法",eyeline="船尾旗幔",focus="锁定黄盖神情",stability="stable",
h3="Anchored to Picture 4, a static medium shot watches the veteran make a final check of the fuses, then glance back at the favorable flag astern, his lined face steady."),
dict(beats=[5,5],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，周瑜在城头远远望见火船列阵，缓缓举起手中的令旗，却没有立刻落下。",
shot="固定全景，城头的披甲青年远远望见火船列阵，缓缓举起令旗，悬在半空却没有落下。",
lens="35mm 广角，全景深",cameraPosition="周瑜+俯瞰 30°",composition="对称",eyeline="列阵的火船",focus="锁定悬着的令旗",stability="stable",
h3="Anchored to Picture 5, a static wide shot holds the young commander on the city wall, flag lifted slow and held, never quite let fall over the fire-boat line below."),
dict(beats=[6,6],seconds=3.0,size="wide",camera="Pan Left",chars=["C19"],
frame="全景，黄盖举刀一挥，二十条火船借着东风鱼贯朝曹营疾冲而去，船头劈开白浪。",
shot="镜头 Pan Left 自那灰甲老将挥刀随船队扫过，二十条火船借着东风鱼贯冲出，船头一路劈开白浪。",
lens="35mm 广角，全景深",cameraPosition="黄盖+侧随行",composition="三分法",eyeline="曹营方向",focus="锁定乘风的船队",stability="slight-shake",
h3="Anchored to Picture 6, the camera pans left as the veteran sweeps his blade down and the twenty fire-boats surge out on the east wind, bows shearing the whitecaps."),
]),
dict(sceneIndex=1,blocking="火船列成一字排开压向铁索船阵，黄盖立于船头居中，哨兵在对岸喝问。",
soundscape="火船破浪的哗哗声，东风猎猎，角声在对岸骤然响起。",
music="鼓角交鸣，逼近。",
h3_sound="Fire-boats hiss through the waves, the east wind roars, and a warning horn suddenly blares from the far bank.",
h3_music="Drum and horn clash as the line closes in.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C19"],
frame="全景，火船离了岸顺风而下越行越快，转眼便把那片岸远远甩在身后，水花高高溅起。",
shot="跟拍镜头随火船顺风疾驰，岸线迅速后退，水花高高溅上船头，越行越快。",
lens="35mm 广角，全景深",cameraPosition="黄盖+侧随行",composition="三分法",eyeline="远离的岸",focus="锁定疾驰的船头",stability="slight-shake",
h3="Anchored to Picture 7, a tracking shot races with the fire-boats downwind as the shore falls away fast, spray hurled high over the bows."),
dict(beats=[8,8],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=["C19"],
frame="大远景，船头劈开浪花，二十条船排成一线黑压压地压向那片铁索船阵，江面杀气弥漫。",
shot="固定大远景，二十条火船排成一线压向铁索船阵，船头劈开浪花，整个江面杀气沉沉。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="铁索船阵",focus="锁定压城的一线船",stability="stable",
h3="Anchored to Picture 8, a static extreme-wide shot shows the twenty craft bearing down in a single black line on the iron-strung fleet, spray flying, the whole river heavy with menace."),
dict(beats=[9,9],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，曹营水寨的哨兵望见夜里有船逼近，先是发话喝问，紧接着便响起告急的角声。",
shot="固定中景，对岸哨兵望见夜里有船逼来，先是一声喝问，随即一起告急的角声响彻水面。",
lens="50mm 标准，中浅景深",cameraPosition="哨兵+平视",composition="三分法",eyeline="逼来的船",focus="锁定惊起的哨兵",stability="slight-shake",
h3="Anchored to Picture 9, a static medium shot sees the sentry on the far camp spot the approaching craft, shout a challenge, then raise the alarm upon the horn."),
]),
dict(sceneIndex=1,blocking="黄盖立于船头居中，船队疾冲，紧挨铁索船阵。",
soundscape="黄盖放话被风卷走的吼声，火船破浪声，曹营告急角声。",
music="鼓角骤紧，一触即发。",
h3_sound="The veteran's cry is torn off by the wind, the fire-boats thunder over the waves, and the enemy horn keeps sounding the alarm.",
h3_music="Drum and horn lock tight, a hair from release.",
cuts=[
dict(beats=[10,10],seconds=2.7,size="close",camera="Push In",chars=["C19"],
frame="特写，黄盖立在船头放声，一句放箭者我降曹者也是我，声浪几乎要被风卷走仍字字浑沉。",
shot="镜头 Push In 缓推向船头的老将，他放声一句又一句，声浪被风削去大半却仍字字浑沉。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="铁索船阵",focus="锁定黄盖唇齿",stability="slight-shake",
h3="Anchored to Picture 10, a slow push in closes on the veteran at the bow as he shouts it into the teeth of the wind, <d>[Chinese] 放箭者我，降曹者也是我。</d>"),
dict(beats=[11,11],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C19"],
frame="全景，火船乘风破浪直直撞向那一片铁索连环的船阵，撞击前的刹那，所有火把齐齐端起。",
shot="跟拍镜头随火船直冲向铁索船阵，撞击前的一瞬，船上火把齐齐端起，蓄势待发。",
lens="35mm 广角，全景深",cameraPosition="黄盖+侧随行",composition="三分法",eyeline="铁索船阵",focus="锁定端起的火把",stability="slight-shake",
h3="Anchored to Picture 11, a tracking shot bears straight on toward the iron-bound fleet, and in the last instant every torch aboard lifts, poised and blazing."),
]),
dict(sceneIndex=1,blocking="黄盖立于船尾踏舵，火船贴近铁索船阵，撞击前的一瞬，火把高举。",
soundscape="桨手喘息的号子，船身相靠的水声，黄盖暴喝的炸音。",
music="鼓点凝成一声，待巨响。",
h3_sound="Oarsmen grunt, hulls nudge close on the water, and the veteran's roar splits the moment before impact.",
h3_music="The drum condenses into a single held beat, waiting the crash.",
cuts=[
dict(beats=[12,12],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，黄盖立在船尾把舵一脚踏住，稳住船头直直对准目标，眉目沉凝。",
shot="固定中景，老将立在船尾一脚踏住舵，稳住船头对准目标，眉目沉凝稳如桩。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视侧面",composition="中心构图",eyeline="对准的船阵",focus="锁定稳舵的姿态",stability="stable",
h3="Anchored to Picture 12, a static medium shot shows the veteran planted at the stern, one foot braced on the rudder as he holds the bow dead on target, steady as a stake."),
dict(beats=[13,13],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，两船先是慢悠悠地靠上，待到贴近才听砰的一声闷响，船身一震铁链绷紧。",
shot="固定近景，两船缓缓靠上，直到贴近才砰地一声闷响，船身一震，相连的铁链猛地绷紧。",
lens="85mm 长焦，极浅景深",cameraPosition="船舷相贴+平视",composition="对角线",eyeline="相贴的船帮",focus="锁定绷紧的铁链",stability="slight-shake",
h3="Anchored to Picture 13, a static close-up sees the two hulls slide together slowly, then a dull, booming thud as they meet and the linking chain snaps taut."),
dict(beats=[14,14],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，黄盖看准时机一声暴喝，命人引燃船头的火种，火星在掌心里猛地窜起。",
shot="固定近景，老将看准时机一声暴喝，命人引燃船头火种，一点火星在掌上猛地窜高三尺。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="窜起的火星",focus="锁定暴喝的脸",stability="slight-shake",
h3="Anchored to Picture 14, a static close-up catches the veteran timing it to the instant, bellowing as a spark leaps high in his hand, flame kindling at the prow."),
]),
dict(sceneIndex=1,blocking="火船船头相撞铁索船阵，黄盖立于船头居中，油船在撞击刹那燃起。",
soundscape="船头相撞的闷响，轰然引火的闷轰，东风灌入火苗的呼啸。",
music="鼓声骤然炸开，火起。",
h3_sound="The bows collide, oil ignites with a deep whomp, and the east wind pours over the flame, feeding it into a roar.",
h3_music="The drum bursts open at the instant of fire.",
cuts=[
dict(beats=[15,15],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，船头相撞的刹那黄盖命人点火，油船轰然燃起，火光刹那吞没半船身。",
shot="固定中景，相撞的一瞬老将下令点火，油船轰地燃起，火光呼啸着吞没半个船身。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视",composition="三分法",eyeline="燃起的船头",focus="锁定窜起的火墙",stability="slight-shake",
h3="Anchored to Picture 15, a static medium shot sees the veteran give the order in the instant of the crash, the oil-boat roaring alight, flame eating half the hull at once."),
dict(beats=[16,16],seconds=3.0,size="wide",camera="Static Shot",chars=["C19"],
frame="全景，恰在此时一阵东风猛地灌来，把火苗引上整条船的油面，火势破空直上。",
shot="固定全景，一阵东风猛地灌来，火苗顺着油面爬满整条船，火势破空直冲向天。",
lens="35mm 广角，全景深",cameraPosition="船侧+平视",composition="对角线",eyeline="爬满火苗的甲板",focus="锁定腾起的火势",stability="slight-shake",
h3="Anchored to Picture 16, a static wide shot sees the east wind rush in and sweep the flame across the whole oiled deck, fire leaping and climbing straight into the air."),
dict(beats=[17,17],seconds=3.0,size="extreme-close",camera="Static Shot",chars=["C19"],
frame="大特写，火光冲天瞬间吞没船身，也把那火光带上了紧邻的铁索战船，火星如暴雨飞溅。",
shot="固定大特写，火光吞没船身又跃上相邻的铁索战船，火星像暴雨一样横扫着飞溅。",
lens="100mm 长焦，极浅景深",cameraPosition="燃船船帮+平视",composition="对角线",eyeline="跃上火船的火",focus="锁定飞溅的火星",stability="slight-shake",
h3="Anchored to Picture 17, a static extreme close-up watches the blaze swallow the hull and carry itself onto the chained neighbor, sparks hosing out like a storm."),
]),
dict(sceneIndex=1,blocking="画面转为整片铁索船阵受火，火船与艨艟相连成片，曹军在船间慌乱。",
soundscape="火势蔓延的轰响，兵卒惊呼逃窜，解索取水的杂乱喊声。",
music="火嗓与战鼓交杂，火势乐章。",
h3_sound="Flames spread with a roar, soldiers cry out and flee, and shouts for water and loosening chains tangle into chaos.",
h3_music="Cries and drums weave into a score of conflagration.",
cuts=[
dict(beats=[18,18],seconds=3.0,size="wide",camera="Pan Left",chars=["C19"],
frame="全景，火势一传十十传百，靠得最近的几艘艨艟几乎同时着了，火柱并排升腾。",
shot="镜头 Pan Left 扫过火海，火一传十、十传百，靠得最近的几艘艨艟几乎同时燃起，火柱并排升腾。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="并排升腾的火柱",focus="锁定相连的火带",stability="slight-shake",
h3="Anchored to Picture 18, the camera pans left over the blaze as it leaps boat to boat, the nearest warships taking flame together in a line of towers."),
dict(beats=[19,19],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=["C19"],
frame="大远景，火借东风风助火势，一霎间铁索连船尽被引燃，整片江面烧成一片通红。",
shot="固定大远景，火借东风、风助火势，铁索连船一圈圈尽被引燃，整片江面烧成通红一片。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="烧红的江面",focus="锁定整片火海",stability="stable",
h3="Anchored to Picture 19, a static extreme-wide shot sees fire riding the east wind until every chained craft is lit, the whole river turned to one sheet of red."),
dict(beats=[20,20],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，曹军惊呼四起，有人提桶取水有人慌着解索，却哪里还来得及，火已上船。",
shot="固定中景，船上兵卒惊呼四起，有人提桶、有人慌着解索，火却已经攀上船板，哪里还来得及。",
lens="50mm 标准，中浅景深",cameraPosition="曹军兵卒+平视",composition="三分法",eyeline="攀上船的火",focus="锁定慌乱取水的手",stability="handheld",
h3="Anchored to Picture 20, a static medium shot sees the crew shouting and scrambling, buckets raised and chains fumbled, but the flame is already on the deck, far too late."),
dict(beats=[21,21],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，铁索连船一艘牵动一片，火越烧越旺，竟连成一条绵延的火带横断面江。",
shot="固定大远景，铁索连船一艘牵动一片，火越烧越旺，连成一条绵延的火带横贯江面。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="横贯的火带",focus="锁定绵延的火带",stability="slight-shake",
h3="Anchored to Picture 21, a static extreme-wide shot reveals ship dragging ship through the chains, the fire swelling into a single unbroken band stretched across the river."),
]),
dict(sceneIndex=1,blocking="画面转入曹军奔逃，船沿兵卒跳滚入水，黄盖的船队自火边角掩杀。",
soundscape="兵卒跳水的噗通声，哭喊与铁甲碰撞，火海呼号。",
music="厮杀鼓点混入火声。",
h3_sound="Men leap and roll into the water with heavy splashes, cries and clashing mail mix with the howl of the blaze.",
h3_music="Combat drums cut through the roar of fire.",
cuts=[
dict(beats=[22,22],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，船上的兵卒跳的跳滚的滚，江面上挤满了拼命逃命的人，火光映着人形。",
shot="固定中景，船上的兵卒跳的跳、滚的滚，江面挤满拼死逃命的人影，火光把人形剪成黑色。",
lens="50mm 标准，中浅景深",cameraPosition="船舷+平视",composition="三分法",eyeline="挤满的江面",focus="锁定跳船的人影",stability="handheld",
h3="Anchored to Picture 22, a static medium shot sees soldiers leaping and tumbling, the river crammed with desperate swimmers, figures cut black against the flame."),
dict(beats=[23,23],seconds=3.0,size="wide",camera="Pan Right",chars=[],
frame="全景，曹军艨艟一艘连着一艘想逃逃不了，火从船首漫到船尾，浓烟冲天。",
shot="镜头 Pan Right 扫过一排燃着的艨艟，火从船首一路漫到船尾，浓烟裹着船身卷上天空。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="漫延的火焰",focus="锁定烧穿的艨艟",stability="slight-shake",
h3="Anchored to Picture 23, the camera pans right across the burning warships, flame running stem to stern, black smoke wreathed up into the sky."),
dict(beats=[24,24],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，黄盖一挥手，那队早已待命的小船便齐齐掩杀了过去，刀光映着火色。",
shot="固定中景，船头的老将一挥手，早已待命的小船便齐齐掩杀过去，刀光在火色里闪成一片。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视",composition="三分法",eyeline="掩杀的方向",focus="锁定挥下的手",stability="slight-shake",
h3="Anchored to Picture 24, a static medium shot sees the veteran sweep his arm and the waiting skiffs surge forward together, blades glinting in the firelight."),
]),
dict(sceneIndex=1,blocking="东吴小船沿火海边缘掩杀，曹军落水挣扎，火海翻滚吞没船身。",
soundscape="小船破浪的冲杀声，铁甲刀枪相接，热浪里人声嘶喊。",
music="水军厮杀鼓点爆裂。",
h3_sound="Skiffs crash through the waves in a charge, blade meets mail, and voices tear across the heat and glare.",
h3_music="Split-instant battle drums, cracking and fierce.",
cuts=[
dict(beats=[25,25],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，东吴兵卒沿着火光的边沿递上刀枪，专挑乱了阵脚的曹军下手，火在他们身后翻卷。",
shot="固定中景，东吴兵卒沿着火光边沿递出刀枪，专挑乱了阵脚的敌手，火在他们身后翻卷。",
lens="50mm 标准，中浅景深",cameraPosition="东吴兵卒+平视",composition="三分法",eyeline="乱阵的曹军",focus="锁定递出的刀枪",stability="slight-shake",
h3="Anchored to Picture 25, a static medium shot sees raiders work the edge of the fire, thrusting at the disordered crew while the flame rolls behind them."),
dict(beats=[26,26],seconds=3.0,size="close",camera="Static Shot",chars=[],
frame="特写，有曹将翻身落水想游走脱身，却被滚滚的热浪熏得失了方向，浪头吞没他。",
shot="固定近景，一名敌将翻身落水想游走，却被热浪熏得辨不清方向，一个浪头盖下来将他吞没。",
lens="85mm 长焦，极浅景深",cameraPosition="落水者+平视",composition="中心构图",eyeline="翻滚的热浪",focus="锁定沉下去的身影",stability="slight-shake",
h3="Anchored to Picture 26, a static close-up sees a fleeing officer hit the water to swim clear, but the scalding heat turns him around and the next wave closes over him."),
dict(beats=[27,27],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，火烧断了铁索，巨大的船身失了牵引，猛地朝一侧倾了过去，水柱冲天。",
shot="固定全景，火烧断铁索，失去牵引的巨大船身猛地朝一侧倾去，浪花被掀得冲天。",
lens="35mm 广角，全景深",cameraPosition="船舷+平视",composition="对角线",eyeline="倾倒的船身",focus="锁定断裂的铁索",stability="slight-shake",
h3="Anchored to Picture 27, a static wide shot sees the fire bite through the chain, the great hulk losing its anchor and heeling hard to one side, spray hurled skyward."),
]),
dict(sceneIndex=1,blocking="火海铺满江面，黄盖的船队撤向岸边，画面由惨烈转收束。",
soundscape="火海翻腾的连绵轰响，小船后撤的桨声，灰烬纷落。",
music="鼓声渐疏，收束。",
h3_sound="The conflagration rolls on unbroken, retreating oars dip, and ash sifts down through the scorched air.",
h3_music="The drums thin and draw to a close.",
cuts=[
dict(beats=[28,28],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，江水上下翻滚着火与烟，一眼望去竟分不出哪里是天哪里是水，天地尽染。",
shot="固定大远景，江水翻滚着火与烟，抬眼已分不清天与水，整片天地都被烧得模糊。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="烧红的天地",focus="锁定翻卷的烟与火",stability="stable",
h3="Anchored to Picture 28, a static extreme-wide shot shows river rolling with fire and smoke until sky and water are indistinguishable, the whole world scorched and blurred."),
dict(beats=[29,29],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，黄盖看那火势已然吞没了半片船阵，这才下令收拢小船缓缓后撤，眉目凝肃。",
shot="固定中景，老将看那火势已吞没半片船阵，才下令收拢小船缓缓后撤，眉目一片凝肃。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视侧面",composition="三分法",eyeline="撤船的方向",focus="锁定黄盖神态",stability="stable",
h3="Anchored to Picture 29, a static medium shot sees the veteran judge the fire has engulfed half the fleet, then order the skiffs gathered and drawn back, his face set and grave."),
dict(beats=[30,30],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，满天飞灰，喊声哭声铁甲相撞之声搅成一团，分不清谁是谁，人间炼狱。",
shot="固定全景，满天飞灰，喊声哭声与铁甲碰撞搅在一处，人人面目难辨，火光里一片混乱。",
lens="35mm 广角，全景深",cameraPosition="江面+俯视 20°",composition="三分法",eyeline="搅成一团的人群",focus="锁定飞舞的灰烬",stability="handheld",
h3="Anchored to Picture 30, a static wide shot sees ash flying and cries, wails and clashing mail all tangled until no face can be told from another in the inferno."),
]),
dict(sceneIndex=1,blocking="黄盖立于船头居前，火海在他身后铺成背景，小船舵梢他拄刀回望。",
soundscape="火海在身后的闷轰，江水拍板，黄盖拄刀落脚的一声。",
music="一记孤弦，满目苍凉。",
h3_sound="The blaze grumbles behind him, the river slaps the strake, and the veteran plants his halberd with a single heavy note.",
h3_music="One lone string, all the aftermath bleak.",
cuts=[
dict(beats=[31,31],seconds=3.0,size="close",camera="Push In",chars=["C19"],
frame="特写，黄盖立在船头望着那一片烧成火海的船阵，拄着刀久久没有说话，火光在他脸上跳动。",
shot="镜头 Push In 缓推向船头的老将，他望着那片烧成火海的船阵，拄着刀久久不语，火光在脸上跳动。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="火海船阵",focus="锁定黄盖双目",stability="stable",
h3="Anchored to Picture 31, a slow push in holds the veteran at the bow, leaning on his halberd as he gazes at the sunken fire-sea of ships, long silent, flame dancing on his face."),
]),
dict(sceneIndex=1,blocking="岸边热浪与火光作景，残军想从边角突围，东吴小船堵了回去。",
soundscape="残军突围的喊杀，小船划破水面的桨声，火烤木板的噼响。",
music="余火鼓点，欲尽时又起。",
h3_sound="Survivors shout and try to break clear, skiffs cut the water to block them, and wet oak hisses as the fire keeps hold.",
h3_music="A fading drum flares up once more before it ends.",
cuts=[
dict(beats=[32,32],seconds=3.0,size="wide",camera="Static Shot",chars=["C19"],
frame="全景，一队残存的曹军想从边角突围，被东吴的小船又堵了回去，火光隔开两方。",
shot="固定全景，一队残军想从火海边角突围，被东吴小船兜头堵回，火光在双方之间隔开一道墙。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="被堵回的残军",focus="锁定拦截的小船",stability="slight-shake",
h3="Anchored to Picture 32, a static wide shot sees a remnant try to break out at the corner only to be driven back by the raiders' skiffs, fire walling between the two sides."),
dict(beats=[33,33],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，火光映在满江水面上，随着水波一荡一荡，绵延到望不见头的远方，夜被烧穿。",
shot="固定大远景，火光映在满江水面上一荡一荡，顺水绵延到望不见的远方，夜色被烧穿一片。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="绵延的火光",focus="锁定一荡一荡的火影",stability="stable",
h3="Anchored to Picture 33, a static extreme-wide shot sees firelight ripple across the whole river in swelling bands, stretching to an unseeable far, the night burned through."),
]),
dict(sceneIndex=1,blocking="黄盖的船队掩杀至江心，火光染彻水面，杀声震天。",
soundscape="东吴小船掩杀的冲杀，刀光破空的嗖嗖，杀声与火声齐鸣。",
music="决战鼓点掀到顶点。",
h3_sound="Raiders' skiffs charge on, blades cut the air with a hiss, and the din of killing and fire crests together.",
h3_music="Battle drums surge to their very summit.",
cuts=[
dict(beats=[34,34],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，东吴的小船趁势掩杀过来，刀光映着火，杀声震天，黄盖立于船头望着战局。",
shot="固定中景，东吴小船趁势掩杀向前，刀光映着火色、杀声震天，船头的老将凝神观战。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+平视",composition="三分法",eyeline="掩杀的战团",focus="锁定映火的刀光",stability="slight-shake",
h3="Anchored to Picture 34, a static medium shot sees the small craft press the attack, blades flashing in the fire, shouts shaking the water, the veteran watching from the bow."),
dict(beats=[35,35],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，江面上烈焰翻涌浓烟蔽月，火光照得半条长江通红如血，天地一片橘红。",
shot="固定大远景，烈焰翻涌、浓烟蔽月，火光照得半条长江通红如血，人看不见，只剩天地橘红。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="烧红的半江",focus="锁定蔽月的浓烟",stability="stable",
h3="Anchored to Picture 35, a static extreme-wide shot sees flame roll and smoke blot the moon, half the Yangtze glowing blood-red, the world a single outreaching orange."),
]),
# ============ 场景2 帅船曹操 ============
dict(sceneIndex=2,blocking="帅船之上，曹操被烈焰逼到船尾居前，亲卫护于身侧，火舌自画面四周舔来。",
soundscape="烈焰轰燃的巨响，甲板碎裂，曹操急促喘息，慌乱脚步与甲叶。",
music="恐慌的低弦与鼓点错乱。",
h3_sound="The blaze roars, decking cracks, a rushed breath escapes the besieged lord, and footsteps and mail scatter in disorder.",
h3_music="Panicked low strings over a broken drum.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，帅船之上曹操被烈火烧得狼狈退到船尾，握剑的手都在抖，锦袍被烟熏黑。",
shot="固定中景，一名细眼长髯的枭雄被火逼到船尾，握着剑的手微微发颤，袍角已熏出黑斑。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="逼近的火舌",focus="锁定发颤的握剑手",stability="slight-shake",
h3="Anchored to Picture 1, a static medium shot sees the narrow-eyed warlord driven back to the stern by the blaze, sword hand trembling, his robe already sooty."),
dict(beats=[2,2],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，他左右早已乱作一团，亲卫护着他慌慌张张去寻那安稳的一方，火封锁前路。",
shot="固定全景，身侧早已乱作一团，亲卫护着枭雄仓皇去寻安稳的一旁，火却封住了前路。",
lens="35mm 广角，全景深",cameraPosition="曹操+俯视 20°",composition="三分法",eyeline="寻路的亲卫",focus="锁定被护住的枭雄",stability="handheld",
h3="Anchored to Picture 2, a static wide shot sees the guards swarm the lord to find the one clear side, but flame already seals the way ahead."),
dict(beats=[3,3],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，一座桅塔轰然栽进江里溅起大片水花，火舌飞快朝这边舔过来，火星纷飞。",
shot="固定全景，一座烧断的桅塔轰然栽进江里，溅起大片水花，火舌飞快朝这边舔来，火星四迸。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="对角线",eyeline="倾倒的桅塔",focus="锁定砸进水中的塔体",stability="slight-shake",
h3="Anchored to Picture 3, a static wide shot sees a burning mast-tower topple into the river with a great splash, the flame reaching fast this way, sparks bursting."),
]),
dict(sceneIndex=2,blocking="曹操被亲卫搀扶着跌撞于船身，火从四面包围，画面在踉跄与张望之间。",
soundscape="曹操跌撞的脚步，额汗滚落的无声，满江的轰燃与哭喊。",
music="鼓点错乱，加急。",
h3_sound="The lord staggers, sweat streaks his brow, and across the whole river the burning and the screaming swell to a din.",
h3_music="The broken drum quickens, frantic.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操脚下一趔趄，扶住船帮才算站稳，额上滚下豆大的汗珠，面皮抽紧。",
shot="固定近景，枭雄脚下趔趄，一把扶住船帮站稳，额上汗珠滚落，面皮绷得发紧。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="扶住的船帮",focus="锁定曹操发紧的面皮",stability="slight-shake",
h3="Anchored to Picture 4, a static close-up sees the warlord stumble, grab the gunwale to steady himself, sweat beading down his brow, his face drawing tight."),
dict(beats=[5,5],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，他抬头望见满江的火，又望见那头黑压压压过来的江东战船，心口一凉。",
shot="固定全景，枭雄抬头望见满江的火，又望见那头压过来的战船，心口一阵透凉。",
lens="35mm 广角，全景深",cameraPosition="曹操+平视",composition="对称",eyeline="压来的战船",focus="锁定曹操僵住的身形",stability="stable",
h3="Anchored to Picture 5, a static wide shot sees the warlord lift his eyes to a river of fire, then to the dark mass of enemy warships bearing down, a chill striking through him."),
dict(beats=[6,6],seconds=3.0,size="medium",camera="Tracking Shot",chars=["C04"],
frame="中景，亲卫拼死护着他抢上一条小舢板，拼命往北岸划，水花溅起老高。",
shot="跟拍镜头随亲卫护着枭雄抢上一条小舢板，桨手拼命朝北岸划，水花一次又一次溅起。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+侧随行",composition="三分法",eyeline="北岸方向",focus="锁定拼命的桨手",stability="slight-shake",
h3="Anchored to Picture 6, a tracking shot carries the guarded lord onto a small skiff as the oarsmen strain for the north bank, spray flying at every stroke."),
]),
dict(sceneIndex=2,blocking="小舢板居中，曹操伏于船头、亲卫分列，热浪从身后追上来。",
soundscape="桨声急促的划水，热浪扑背的隐隐轰鸣，曹操伏身的粗喘。",
music="低弦压沉，逃生节拍。",
h3_sound="Oars beat fast, heat presses at their backs with a low roar, and the crouched lord breathes hard and uneven.",
h3_music="Low sinking strings, the beat of an escape.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，舢板吃水很深，船上挤着七八个人，桨手拼命划，船身打得水花四溅。",
shot="固定全景，小舢板吃水很深、挤着七八个人，桨手拼命划动，船身一次次打得水花四溅。",
lens="35mm 广角，全景深",cameraPosition="曹操+平视",composition="三分法",eyeline="翻动的水花",focus="锁定吃水的舢板",stability="slight-shake",
h3="Anchored to Picture 7, a static wide shot shows the low-riding skiff crammed with near a dozen men, oars driven hard, water slapping over the thwarts."),
dict(beats=[8,8],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，身后的火船越烧越烈，热浪追着后背扑上来，烤得人半边脸发烫，黑烟窜高。",
shot="固定近景，身后的火越烧越烈，热浪扑上后背，把半张脸烤得发烫，黑烟从身后窜起。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+侧后",composition="中心构图",eyeline="身后火光",focus="锁定烤红的侧脸",stability="slight-shake",
h3="Anchored to Picture 8, a static close-up feels the pursuing heat scorch half a face as the burning ships blaze harder behind, black smoke climbing off the water."),
dict(beats=[9,9],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操伏在船头抓着一根缆绳，指节捏得泛白，一言不发望着前路。",
shot="固定中景，枭雄伏在船头攥住一根缆绳，指节捏得泛白，一句话也不说只盯着前路。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="前方水面",focus="锁定泛白的指节",stability="stable",
h3="Anchored to Picture 9, a static medium shot sees the warlord crouched at the bow, knuckles white around a rope, silent and fixed on the way ahead."),
]),
dict(sceneIndex=2,blocking="江面漂浮烧焦的木板军旗，曹操伏于船头，画面在翻江的火与沉默间。",
soundscape="焦木浮响，火海闷轰，曹操强咽的喉头声。",
music="弦乐沉默留白。",
h3_sound="Scorched planks knock together, the fire rolls on, and the lord swallows hard to hold back the surge in his throat.",
h3_music="Strings fall silent, leaving a gap.",
cuts=[
dict(beats=[10,10],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，水面上到处飘着烧焦的木板和军旗，整片江像一锅煮沸的火，舢板在其中穿行。",
shot="固定全景，水面漂满烧焦的木板和军旗，整片江像一锅煮沸的火，小舢板孤独地在其中穿行。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="漂满的焦木",focus="锁定穿行的舢板",stability="stable",
h3="Anchored to Picture 10, a static wide shot sees planks and torn standards drifting everywhere as the river boils like a cauldron, one small skiff threading through it all."),
dict(beats=[11,11],seconds=3.0,size="close",camera="Push In",chars=["C04"],
frame="特写，背后的火越来越大，曹操伏在船头一口鲜血险些喷出，生生咽了下去，喉结猛地一滚。",
shot="镜头 Push In 缓推向伏低的枭雄，他一口腥气冲到喉头又被生生咽回，喉结猛地一滚。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="船舷前方",focus="锁定咽下的喉结",stability="slight-shake",
h3="Anchored to Picture 11, a slow push in finds the lord at the bow as a rush of blood almost escapes him, then is swallowed, his throat working hard."),
dict(beats=[12,12],seconds=3.0,size="extreme-close",camera="Static Shot",chars=["C04"],
frame="大特写，他回望那一片烧成火海的船阵，眼底映着滔天的火光，久久没有说话。",
shot="固定大特写，一张沉暗的脸回望那片火海，眼底映着滔天的火光，沉默着久久不动。",
lens="100mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="火海船阵",focus="锁定映火的眼底",stability="stable",
h3="Anchored to Picture 12, a static extreme close-up holds the lord's face as he looks back at the fire-sea, the blaze mirrored in his eyes, silent for a long time."),
]),
dict(sceneIndex=2,blocking="船舷外，艨艟接连化作冲天火柱，曹操伏在船头，画面在灾难与前奔之间。",
soundscape="艨艟倒坍的轰响，火柱破空，曹操低咳与压抑的呼吸。",
music="哀弦低回，大势已去。",
h3_sound="Warships topple into columns of fire, and the lord's suppressed cough and ragged breath carry across the flames.",
h3_music="A mournful string turns low and slow, the tide against him.",
cuts=[
dict(beats=[13,13],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，那一艘艘他苦心经营的艨艟此刻尽化作冲天火柱，接连坍塌，火柱并排倒下。",
shot="固定全景，一艘艘苦心经营的艨艟尽化作冲天火柱，接连坍塌跌倒，火光如墙倒下。",
lens="35mm 广角，全景深",cameraPosition="江面+平视",composition="三分法",eyeline="坍塌的火柱",focus="锁定接连倒下的艨艟",stability="slight-shake",
h3="Anchored to Picture 13, a static wide shot sees the warships he had labored to build topple one after another into falling towers of flame."),
dict(beats=[14,14],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操闭了闭眼，再睁开时眼底已没了往日的从容，只剩一片暗沉，面容灰败。",
shot="固定近景，枭雄闭了闭眼，再睁开时往日的从容荡然无存，心里只剩一片暗沉的灰败。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="前方火海",focus="锁定曹操眼底暗沉",stability="stable",
h3="Anchored to Picture 14, a static close-up sees the warlord close his eyes and open them again, the old composure gone, only a deep and leaden darkness left behind."),
dict(beats=[15,15],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，他低低咳了两声，把喉间那股腥气硬生生咽了回去，指节扣着船舷。",
shot="固定中景，枭雄低低咳了两声，把喉间那股腥气硬咽回去，指节扣着船舷不放。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视侧面",composition="中心构图",eyeline="扣着的船舷",focus="锁定低咳的身影",stability="stable",
h3="Anchored to Picture 15, a static medium shot sees the lord cough low and swallow the acrid taste back down, fingers clawed onto the ship's rail."),
]),
dict(sceneIndex=2,blocking="曹操伏于船头，火光映面，画面独留他一句低语，舢板仍北行。",
soundscape="火海在身后的轰响，曹操一句低语被风扯散，江水拍板。",
music="一记重弦，不堪回首。",
h3_sound="The fire rolls behind, the lord's low line is torn by the wind, and the river slaps the strake.",
h3_music="One heavy string, too much to look back on.",
cuts=[
dict(beats=[16,16],seconds=3.1,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操回望那一片灰烬，低声自嘲，一句百万之众竟败在这一把火上，字字带着倦意。",
shot="固定近景，枭雄回望那片灰烬，低声吐出一句，百万之众败在一把火上，话里满是倦意。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="身后灰烬",focus="锁定曹操唇齿",stability="stable",
h3="Anchored to Picture 16, a static close-up holds the lord looking back at the ruination as he mutters with bone-deep weariness, <d>[Chinese] 百万之众，竟败在这一把火上。</d>"),
]),
dict(sceneIndex=2,blocking="舢板靠岸，曹操踉跄登岸，岸边残卒散布聚拢，画面由水上转入岸上的狼藉。",
soundscape="舢板靠岸的触底声，曹操踉跄的脚步，残卒低唤聚拢的杂声。",
music="弦音转为压抑的悲怆。",
h3_sound="The skiff grounds, the lord stumbles ashore, and scattered survivors call out and gather round him.",
h3_music="Strings turn to a pressing, grieving strain.",
cuts=[
dict(beats=[17,17],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，舢板靠岸，曹操踉跄登岸，回头望了一眼身后犹在燃烧的长江，火映着他。",
shot="固定全景，小舢板靠岸，枭雄踉跄登岸，回头望一眼身后仍燃烧的长江，火光映在他脸上。",
lens="35mm 广角，全景深",cameraPosition="曹操+平视",composition="三分法",eyeline="燃烧的长江",focus="锁定踉跄登岸的身影",stability="slight-shake",
h3="Anchored to Picture 17, a static wide shot sees the skiff reach the bank and the lord stumble up, turning once to the burning river still blazing behind him."),
dict(beats=[18,18],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，岸边只剩些零落溃散的兵卒，一见是他纷纷聚拢上来，衣甲残破。",
shot="固定中景，岸边只剩些零落溃兵，一见是他便纷纷聚拢过来，人人衣甲残破、垂头丧气。",
lens="50mm 标准，中浅景深",cameraPosition="残卒+平视",composition="三分法",eyeline="曹操方向",focus="锁定聚拢的残卒",stability="stable",
h3="Anchored to Picture 18, a static medium shot sees a few tattered survivors on the bank gather in at the sight of him, armor ragged, heads hanging."),
dict(beats=[19,19],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操环顾四周那一片残兵败将，心头一酸，几乎落下泪来，喉头微哽。",
shot="固定近景，枭雄环顾这一片残兵败将，心头一酸几乎落下泪来，喉头堵得发紧。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="环顾的残兵",focus="锁定曹操通红的眼眶",stability="stable",
h3="Anchored to Picture 19, a static close-up sees the warlord take in the broken remnants around him, a pang striking his heart so hard tears almost fall, throat tightening."),
]),
dict(sceneIndex=2,blocking="曹操立于岸上与残兵相对，身后火光染半天，画面由近景低语转入北行。",
soundscape="曹操低叹，残兵低泣，火光在身后的闷轰。",
music="弦音低徊，悲中生强。",
h3_sound="The lord lets out a soft sigh, men sniff back tears, and the blaze grumbles low beyond them.",
h3_music="Strings wander low, then gather strength from the grief.",
cuts=[
dict(beats=[20,20],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，他低低叹了一声，把那股酸意压回肚里，又挺了挺背，抹了一把脸。",
shot="固定近景，枭雄低叹一声把那阵酸意压回肚里，复又挺了挺背，抬手抹了把脸。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="前方方向",focus="锁定挺直的身形",stability="stable",
h3="Anchored to Picture 20, a static close-up sees the lord sigh low, drive the surge back down, straighten his back, and wipe a hand across his face."),
dict(beats=[21,21],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，回望身后火光仍染着半边天，连江水都映成一派通红，他背身而立。",
shot="固定全景，枭雄背身而立，身后的火光染着半边天，连江水都映成一派通红。",
lens="35mm 广角，全景深",cameraPosition="曹操+后侧",composition="对称",eyeline="脚下的路",focus="锁定背身的身影",stability="stable",
h3="Anchored to Picture 21, a static wide shot frames him with his back turned, the fire staining half the sky red and the river doubling it back at him."),
dict(beats=[22,22],seconds=3.0,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操攥紧缰绳，心底那阵翻江倒海终究化作了一声长长的叹息，眉眼松落。",
shot="镜头 Push In 缓推向枭雄，他攥紧缰绳，心口那阵翻江倒海终究化成一声长叹，眉眼松落。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="来时方向",focus="锁定攥紧缰绳的手",stability="stable",
h3="Anchored to Picture 22, a slow push in nears the lord as he grips the rein and lets the whole churning storm drain out in one long sigh, his brow easing at last."),
]),
dict(sceneIndex=2,blocking="岸边瘦马与曹操相对，残卒扶他上马，火光在身后，画面转向北方官道。",
soundscape="马蹄轻踏，曹操跨鞍的衣甲声，残卒扶持的低语，身后火声渐远。",
music="鼓音低促，向北开拔。",
h3_sound="Hooves scuff the ground, the lord swings into the saddle with a rustle of robe and mail, a guard's low word of support, and the fire gives way behind.",
h3_music="Low, pressing drums as they turn north.",
cuts=[
dict(beats=[23,23],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，他牵过一匹不知谁留下的瘦马，扶着鞍辔艰难地跨了上去，身形滞重。",
shot="固定中景，枭雄牵过一匹留下的瘦马，扶着鞍辔艰难地跨上去，身形显得滞重。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视侧面",composition="中心构图",eyeline="鞍辔方向",focus="锁定跨鞍的身影",stability="stable",
h3="Anchored to Picture 23, a static medium shot sees the lord take the thin horse left behind and haul himself wearily into the saddle, motion heavy and slow."),
dict(beats=[24,24],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，身后火光照见半边天，映着曹操那张灰败的脸色，一路向北，眉眼再无波澜。",
shot="固定近景，身后的火光照了半天边，把枭雄灰败的脸色映得发亮，他一路望向北方。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视侧面",composition="中心构图",eyeline="北方",focus="锁定灰败的脸色",stability="stable",
h3="Anchored to Picture 24, a static close-up sees the blaze light half the sky over the lord's sallow face as he turns for the north, his features flat and spent."),
dict(beats=[25,25],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，他摔开搀扶的手跌跌撞撞，朝那一片被烟熏黑的北岸官道走去，逆着余火。",
shot="固定全景，那人摔开搀扶的手，跌跌撞撞朝那片被烟熏黑的北岸官道走去，背对余火。",
lens="35mm 广角，全景深",cameraPosition="曹操+后侧",composition="三分法",eyeline="熏黑的官道",focus="锁定逆火而去的身影",stability="slight-shake",
h3="Anchored to Picture 25, a static wide shot sees him shake off the proffered hand and stagger toward the smoke-blackened north road, back to the dying fire."),
]),
dict(sceneIndex=2,blocking="身影背火光而行，亲卫仍在身侧，画面由近转远，火光渐小。",
soundscape="马蹄声渐密，残卒尾随的脚步，身后的火声一点点退远。",
music="鼓点定调整装，策骑向北。",
h3_sound="Hooves fall faster, stragglers follow on tired feet, and the fire behind fades by steady degrees.",
h3_music="The drums steady into a marching pace headed north.",
cuts=[
dict(beats=[26,26],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，身后的火光冲天浓烟滚滚，一路蔓延到他落脚之处，却不曾追上他的脚步。",
shot="固定中景，身后的火光冲天、浓烟滚滚一路蔓到他落脚之处，却始终追不上前行的马蹄。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="三分法",eyeline="逐渐拉远的火",focus="锁定前行的身影",stability="stable",
h3="Anchored to Picture 26, a static medium shot sees the towering fire and smoke reach right up to the spot he came from, yet never catch the steps ahead."),
dict(beats=[27,27],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=["C04"],
frame="大远景，亲卫牵过一匹瘦马，曹操翻身上马催着马往北就跑，身后空余一片焦土与废墟。",
shot="固定大远景，亲卫牵过瘦马，枭雄翻身上马往北疾驰，身后只余一片烧焦的废墟与焦土。",
lens="24mm 超广角，全景深",cameraPosition="曹操+平视远景",composition="对称",eyeline="北去的路",focus="锁定绝尘的身影",stability="stable",
h3="Anchored to Picture 27, a static extreme-wide shot sees the guard bring up a thin horse, the lord mount and ride hard for the north, leaving behind only scorched earth and ruin."),
]),
]