# -*- coding: utf-8 -*-
# ep47 苦肉计 + 铁索连环  场景1 beats1-28 C12,C19,C20 场景2 beats1-31 C20,C04
C12="the handsome young commander in silk battle robes and light armor"
C19="a burly grey-haired veteran in pitted iron armor"
C20="an ugly lean scholar in a plain taoist robe and bamboo crown"
C04="a heavy-build warlord with narrow eyes and a long beard in chancellor robes"
EP=47
SEG=[
dict(sceneIndex=1,blocking="帅帐内，周瑜居中坐于案后、黄盖立阶下居左，两旁将官跪满画面下部，烛火通明。",
soundscape="帅帐内争执声渐高，众将衣甲碰地的轻响，烛火爆花。",
music="低鼓压拍，弦乐含而不发。",
h3_sound="Argument rises across the war tent, armor creaks as officers kneel, and a lamp flame crackles in the tension.",
h3_music="Low drums keep the beat while a string line holds, coiled and unused.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Static Shot",chars=["C12","C19"],
frame="全景，帅帐议事，周瑜居中而坐，黄盖立在阶下一句顶一句，最后竟当众顶撞起来，烛火照满帐壁。",
shot="固定全景，一名披轻甲的青年端坐案后，一名灰甲老将立在阶下一句顶一句，僵持在满帐烛光里。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视",composition="对称",eyeline="阶下老将",focus="锁定二人对峙",stability="stable",
h3="Anchored to Picture 1, a static wide shot holds the young commander seated and the grey-haired veteran below trading sharp words, the whole tent lit and tense."),
dict(beats=[2,2],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，周瑜脸色一沉，一掌拍在案上，喝令将黄盖推出去斩了，茶盏应声弹起。",
shot="固定中景，披甲的青年脸色一沉，一掌拍在案上茶杯弹起，厉声喝令把顶撞的老将推出去。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="阶下方向",focus="锁定拍下的手掌",stability="slight-shake",
h3="Anchored to Picture 2, a static medium shot sees the young commander's face darken as he slams a palm onto the table and roars for the defiant veteran to be dragged out and beheaded."),
dict(beats=[3,3],seconds=3.0,size="wide",camera="Static Shot",chars=["C12","C19"],
frame="全景，满帐将官齐齐跪下求情，只有黄盖自己梗着脖子硬是不低头，众声恳求。",
shot="固定全景，满帐将官一齐跪倒求情，只有那名灰甲老将梗着脖子不低头，硬气地立在阶下。",
lens="35mm 广角，全景深",cameraPosition="周瑜+俯视 20°",composition="三分法",eyeline="跪倒众将",focus="锁定梗着脖子的黄盖",stability="stable",
h3="Anchored to Picture 3, a static wide shot shows the officers sinking to their knees in plea while the grey-haired veteran alone stands unbowed, neck stiff, refusing to submit."),
]),
dict(sceneIndex=1,blocking="周瑜居案后、黄盖立于阶下，二人怒目相向，四周跪满将官。",
soundscape="周瑜怒喝，众将哀求声不绝，烛火簌簌。",
music="鼓点骤紧，压抑。",
h3_sound="The commander's shout cuts through a chorus of officers begging while lamp flames tremble.",
h3_music="The drums press harder, oppressive and close.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜面色铁青，指着黄盖喝问他眼里可还剩下军令二字，眉宇怒火毕露。",
shot="镜头 Push In 缓推向铁青面孔的青年，他抬手直指阶下，怒喝一句军令二字，眉宇间火星迸裂。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="指处老将",focus="锁定周瑜怒目",stability="stable",
h3="Anchored to Picture 4, a slow push in tightens on the livid young commander as he jabs a finger at the man below and roars whether any room is left for discipline."),
dict(beats=[5,5],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，黄盖梗着脖子一声不吭，只把那双老眼直直迎上去，须髯花白血气未减。",
shot="固定近景，灰甲老将梗着脖子一声不吭，一双倔强的老眼直直迎上对面，须发花白。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="对面上方",focus="锁定黄盖老眼",stability="stable",
h3="Anchored to Picture 5, a static close-up rests on the grey-haired veteran whose thick neck stays stiff as he meets the gaze above with a steady, unbowed stare."),
dict(beats=[6,6],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，两旁将官只是不住地求，周瑜却越听越怒，一掌就要落下，案头震响。",
shot="固定中景，两旁将官不住地求，案后的青年却越听越怒，抬手一掌又要落下。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视正面",composition="三分法",eyeline="阶下众将",focus="锁定扬起的手掌",stability="slight-shake",
h3="Anchored to Picture 6, a static medium shot shows officers pleading ever louder while the commander's wrath grows and his hand rises to slam down again."),
]),
dict(sceneIndex=1,blocking="周瑜自案后立起、黄盖被按倒于阶下，画面以杖刑开场为核心。",
soundscape="周瑜一字一字挤出的怒声，兵卒上前拿人的脚步与甲叶声。",
music="鼓声骤止，弦乐悬一瞬。",
h3_sound="The commander's cold sentence lands word by word, then heavy boots and mail jingle as guards close in.",
h3_music="The drums cut short, strings hanging for an instant.",
cuts=[
dict(beats=[7,7],seconds=4.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜一字一字从牙缝里挤出来，改打脊杖五十，烛火映着他毫无回旋的眉眼。",
shot="固定近景，案后的青年一字一字从牙缝里挤出判词，改打脊杖五十，语气冷硬毫无回旋。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="阶下老将",focus="锁定周瑜唇齿",stability="stable",
h3="Anchored to Picture 7, a static close-up holds the commander as he grinds out the sentence word by word, <d>[Chinese] 看众将分上，饶你却死，改打脊杖五十！</d>"),
dict(beats=[8,8],seconds=3.0,size="medium",camera="Static Shot",chars=["C19","C12"],
frame="中景，兵卒上前把黄盖按倒在地，剥去衣甲，露出伤痕累累的旧背，阶下尘土扬起。",
shot="固定中景，几名兵卒把灰甲老将按倒在地，剥去甲叶，衣甲落地的闷响里露出一片旧背。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+俯视 20°",composition="三分法",eyeline="按下来的兵卒",focus="锁定剥落的衣甲",stability="slight-shake",
h3="Anchored to Picture 8, a static medium shot sees guards press the veteran to the ground and strip the armor, the clang of mail hitting dirt as an old scarred back is laid bare."),
]),
dict(sceneIndex=1,blocking="黄盖伏地居中，军棍起落，周瑜端坐案后入画一角，画面以杖刑与受刑人为主。",
soundscape="军棍落背的闷响，皮肉绽开的细声，黄盖忍痛不吭的粗喘。",
music="鼓声一下一下，沉重。",
h3_sound="The rod lands with a dull thud, flesh tears, and the old veteran forces out rough, silent breathing rather than a cry.",
h3_music="A drum measures each stroke, heavy and slow.",
cuts=[
dict(beats=[9,9],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，军棍一下一下打在背上，皮肉绽开，血顺着脊沟往下淌，背甲尽裂。",
shot="固定近景，军棍一下下落在背上，皮肉绽开，血顺着脊沟缓缓淌下，老将咬死不吭。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+俯视 20°",composition="对角线",eyeline="落下的军棍",focus="锁定淌血的旧背",stability="slight-shake",
h3="Anchored to Picture 9, a static close-up watches the rod fall again and again across the back, skin splitting and blood running along the spine while the man holds his silence."),
dict(beats=[10,10],seconds=3.0,size="medium",camera="Static Shot",chars=["C19"],
frame="中景，打到二十棍，黄盖背上已没一块好皮，额上豆大的汗珠滚落，指节抠进土里。",
shot="固定中景，打到一半背上已没一块好皮，豆大的汗珠滚落，老将仍咬着牙把指节抠进泥里。",
lens="50mm 标准，中浅景深",cameraPosition="黄盖+俯视 20°",composition="三分法",eyeline="地面",focus="锁定抠进土的手指",stability="slight-shake",
h3="Anchored to Picture 10, a static medium shot shows the welts mounting on the back, sweat beading on the brow, while fingers dig hard into the dirt and no sound escapes."),
dict(beats=[11,11],seconds=3.0,size="extreme-close",camera="Static Shot",chars=["C19"],
frame="大特写，他两手扣着地面，指节抠进土里，硬是没吭一声，青筋在手背绷起。",
shot="固定大特写，一双扣在地上的手，指节抵进泥里绷出青筋，痛到极致仍不发一声。",
lens="100mm 长焦，极浅景深",cameraPosition="黄盖之手+俯视",composition="对角线",eyeline="抠进的泥里",focus="锁定紧绷的指节",stability="stable",
h3="Anchored to Picture 11, a static extreme close-up rests on two hands clamped into the earth, knuckles white with strain, enduring to the limit without a single sound."),
]),
dict(sceneIndex=1,blocking="帐外兵卒看在眼里、周瑜端坐案后入画另角，画面在旁观与施刑间交替。",
soundscape="帐外兵卒的低声吸气与别过脸去的动静，军棍持续落背。",
music="鼓声持续，夹杂弦的闷音。",
h3_sound="Guards behind the tent edge draw quick breaths and turn away, while the rod keeps falling.",
h3_music="The drum drives on, a muted string under it.",
cuts=[
dict(beats=[12,12],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，帐外的兵卒看得直咽口水，有几个背过脸去不敢再看，烛影晃动。",
shot="固定中景，帐外几名兵卒看得直咽口水，有人背过脸去不敢再看，烛影在壁上乱晃。",
lens="50mm 标准，中浅景深",cameraPosition="兵卒+平视",composition="三分法",eyeline="帐内刑杖",focus="锁定别过脸的兵卒",stability="stable",
h3="Anchored to Picture 12, a static medium shot sees soldiers just outside the tent swallow hard and turn their faces away, unable to watch, shadows guttering on the canvas."),
dict(beats=[13,13],seconds=3.0,size="extreme-close",camera="Static Shot",chars=["C12"],
frame="大特写，周瑜端坐案后，握着茶盏的手却暗暗收紧，指节泛了白，面上不动。",
shot="固定大特写，一只端盏的手在案后暗暗收紧，指节一点点泛白，面上却一丝不动。",
lens="100mm 长焦，极浅景深",cameraPosition="周瑜之手+平视",composition="中心构图",eyeline="泛白的指节",focus="锁定握紧的茶盏",stability="stable",
h3="Anchored to Picture 13, a static extreme close-up rests on a hand gripping a cup behind the table, knuckles whitening while the face betrays nothing."),
dict(beats=[14,14],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，黄盖咬紧牙关，任由那棍子落，既不叫冤也不求饶，额角青筋暴起。",
shot="固定近景，老将咬紧牙关任由棍落，不叫冤不求饶，额角青筋暴起，双目睁着。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="前方地面",focus="锁定咬紧的牙关",stability="slight-shake",
h3="Anchored to Picture 14, a static close-up holds the veteran's clenched teeth as the rod falls, no plea and no cry, only veins standing on his forehead."),
]),
dict(sceneIndex=1,blocking="杖毕，兵卒拖着黄盖离场，场景转入帐内卧榻，画面由闹转静。",
soundscape="军棍止歇，兵卒拖拽的窸窣，老将伏榻的重喘，脚步声渐远。",
music="鼓声顿收，弦乐沉入极静。",
h3_sound="The rod stops, guards drag the veteran away, and the only sound left is his ragged breathing on the cot as footsteps retreat.",
h3_music="The drum stops dead and the strings sink into deep quiet.",
cuts=[
dict(beats=[15,15],seconds=3.0,size="wide",camera="Static Shot",chars=["C19","C12"],
frame="全景，五十棍打罢他已奄奄一息，被拖回帐里，背上一片血肉模糊，周瑜随行入内。",
shot="固定全景，五十棍后一名老将已被拖进帐中伏在榻上，背上一片血肉模糊，一名青年随后入内。",
lens="35mm 广角，全景深",cameraPosition="卧榻+平视",composition="三分法",eyeline="榻上的老将",focus="锁定榻上伤背",stability="stable",
h3="Anchored to Picture 15, a static wide shot sees the beaten veteran dragged to a cot inside, his back a raw ruin, the young commander stepping in behind."),
dict(beats=[16,16],seconds=3.0,size="close",camera="Push In",chars=["C19","C12"],
frame="特写，屏退旁人后黄盖伏在榻上挣扎抬眼，望向随后跟进来的周瑜，眼神发亮。",
shot="镜头 Push In 缓推向榻边，老将伏在榻上艰难抬眼，望见跟进来的青年，眼里仍亮着一道光。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视侧面",composition="三分法",eyeline="进帐的青年",focus="锁定黄盖抬眼",stability="stable",
h3="Anchored to Picture 16, a slow push in nears the cot as the wounded veteran raises his head with effort to meet the young commander, a light still burning in his eyes."),
]),
dict(sceneIndex=1,blocking="榻旁：周瑜蹲于榻边、黄盖伏榻，二人凑近低语，烛火偏暗。",
soundscape="周瑜拭汗的轻响，黄盖粗重的吸气，低语在帐内回绕。",
music="弦乐极轻，频于悲壮。",
h3_sound="A cloth dabs sweat, the veteran draws one labored breath, and their low voices turn in the dim tent.",
h3_music="A near-silent string line, freighted and somber.",
cuts=[
dict(beats=[17,17],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜在榻边蹲下，先替他把额上那层冷汗轻轻拭去，动作放得极轻，眉宇沉静。",
shot="固定近景，蹲在榻边的青年伸手把那层冷汗轻轻拭去，动作放得极轻，眉眼沉静。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="榻上伤者",focus="锁定拭汗的手",stability="stable",
h3="Anchored to Picture 17, a static close-up watches the young commander crouch by the cot and gently wipe the cold sweat from the old brow, his touch feather-light."),
dict(beats=[18,18],seconds=3.0,size="close",camera="Static Shot",chars=["C19","C12"],
frame="特写，黄盖喘着粗气，抓住周瑜的手腕，一双老眼却亮得惊人，指尖用力。",
shot="固定近景，伏榻的老将喘着粗气，一把抓住蹲着的青年手腕，一双老眼亮得惊人。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定抓住的手腕",stability="stable",
h3="Anchored to Picture 18, a static close-up shows the panting veteran seizing the young commander's wrist, his weathered eyes suddenly burning bright."),
dict(beats=[19,19],seconds=3.1,size="close",camera="Push In",chars=["C19"],
frame="特写，黄盖气若游丝地开口，眼里却亮着，一句苦肉计曹操会信么，屋内只余烛火映二人。",
shot="镜头 Push In 缓推向榻上的老将，他声音气若游丝，眼里却亮亮的，问出那一句。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+俯视 20°",composition="中心构图",eyeline="对方面部",focus="锁定黄盖双目",stability="stable",
h3="Anchored to Picture 19, a slow push in holds the veteran who asks in a frayed, whispered breath, eyes still bright, <d>[Chinese] 都督，这苦肉计，曹操会信么？</d>"),
]),
dict(sceneIndex=1,blocking="二人凑近卧榻，周瑜俯身、黄盖仰面，烛火在二人之间低烧。",
soundscape="周瑜压低声音的细语，黄盖的粗喘，帐内万籁俱静。",
music="弦乐更沉，一字一音。",
h3_sound="The commander leans in with a hushed voice, the veteran breathes raggedly, and the tent falls utterly still.",
h3_music="Still heavier strings, one note to a word.",
cuts=[
dict(beats=[20,20],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜俯身握住他搭在榻沿的手，压低声音，烛火在其眉眼间轻晃。",
shot="固定近景，俯身的青年轻轻握住榻沿那只手，压低声音说话，火光在眉眼间跳动。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="榻上老将",focus="锁定握住的手",stability="stable",
h3="Anchored to Picture 20, a static close-up sees the commander lean down to clasp the hand resting on the cot's edge as he lowers his voice, firelight flickering across his face."),
dict(beats=[21,21],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，周瑜只低声应他这份罪先记在账上等事成再好好将养，语气沉稳。",
shot="固定中景，蹲在榻边的青年低声应话，说这份罪先记下等事成再将养，语气沉稳笃定。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视侧面",composition="三分法",eyeline="榻上老将",focus="锁定周瑜侧脸",stability="stable",
h3="Anchored to Picture 21, a static medium shot has the young commander answering in a steady, low murmur that the debt of pain is recorded and will be repaid in good care once this is over."),
dict(beats=[22,22],seconds=3.1,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜一字一句说得极轻，你这一顿打不白挨自有它用，眼神笃定落向榻上。",
shot="镜头 Push In 缓推向俯身的青年，他一字一句说得极轻，眼神却笃定地落向榻上的人。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="榻上老将",focus="锁定周瑜双目",stability="stable",
h3="Anchored to Picture 22, a slow push in settles on the young commander as he murmurs in measured, quiet words, <d>[Chinese] 你这一顿打不白挨，自有它用。</d>"),
]),
dict(sceneIndex=1,blocking="黄盖伏榻居中，周瑜起身欲行，画面由榻边密语转向外送，烛火摇曳。",
soundscape="黄盖牵动伤口的倒吸冷气，衣甲起身的轻响，夜凉入帐。",
music="弦乐渐收，尾音萧索。",
h3_sound="The veteran winces as the smile tugs at his wounds, the commander rises with a rustle of mail, and a cool night air seeps into the tent.",
h3_music="The strings taper off, ending on a bleak note.",
cuts=[
dict(beats=[23,23],seconds=3.0,size="close",camera="Static Shot",chars=["C19"],
frame="特写，黄盖咧嘴扯出一丝笑，牵动背上的伤，眉头狠狠拧了一下，眼神却亮。",
shot="固定近景，伏榻的老将扯出一丝笑，立刻牵动背上伤处，眉头狠狠一拧，眼里却仍亮着。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定黄盖神情",stability="stable",
h3="Anchored to Picture 23, a static close-up catches the veteran drawing a thin smile, then flinching as it tugs at his wounds, though his eyes stay bright."),
dict(beats=[24,24],seconds=2.7,size="close",camera="Static Shot",chars=["C19"],
frame="特写，黄盖气力不足字字却沉，为江东为这口气值当，声若老钟余响。",
shot="固定近景，榻上的老将气力不足却字字沉实，一句为江东值当说得像老钟余响。",
lens="85mm 长焦，极浅景深",cameraPosition="黄盖+俯视 20°",composition="中心构图",eyeline="对方面部",focus="锁定黄盖唇齿",stability="stable",
h3="Anchored to Picture 24, a static close-up holds the ageing veteran as he voices the vow low and heavy with what little breath remains, <d>[Chinese] 为江东，为这口气，值当。</d>"),
dict(beats=[25,25],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，周瑜替他拉好被褥，又看了看那伤痕累累的旧背，这才起身走到帐口。",
shot="固定中景，蹲在榻边的青年替人拉好被褥，多看一眼那旧背，才起身走向帐口。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视侧面",composition="三分法",eyeline="伤痕旧背",focus="锁定拉被的手",stability="stable",
h3="Anchored to Picture 25, a static medium shot sees the young commander tuck the bedding over the wounded man, spare a look at the scarred old back, then rise and walk to the tent mouth."),
]),
dict(sceneIndex=1,blocking="周瑜走到帐口自画面一侧掀帘，黄盖伏榻远处入画，夜送降书紧接其后续接外景。",
soundscape="帘幕掀起的风声，周瑜离去的脚步，帐外夜风呜呜。",
music="弦乐转暗，留悬念。",
h3_sound="The tent flap rustles as it lifts, footsteps carry the commander away, and the night wind moans beyond.",
h3_music="The strings turn dark, leaving a lingering doubt.",
cuts=[
dict(beats=[26,26],seconds=3.0,size="wide",camera="Pull Out",chars=["C12"],
frame="全景，他回头望了一眼榻上的人，没有再说话，掀帘走了出去，衣角卷入夜风。",
shot="镜头 Pull Out 自帐口缓缓拉开，青年回头望一眼榻上的人，没有言语，掀帘而出。",
lens="35mm 广角，全景深",cameraPosition="周瑜+后侧",composition="三分法",eyeline="榻上方向",focus="锁定掀帘的身影",stability="stable",
h3="Anchored to Picture 26, a pull out draws back to the tent mouth as the young commander glances once at the cot, says nothing, and disappears through the flap."),
dict(beats=[27,27],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C12"],
frame="全景，当夜黄盖遣人秘密送出一封降书，言辞切切，只说周瑜不仁、愿投曹操，火把照亮信使。",
shot="跟拍镜头随潜行的信使穿过夜色，一封降书信在他怀里，火把明灭，直奔营门方向。",
lens="35mm 广角，全景深",cameraPosition="信使+侧随行",composition="三分法",eyeline="营门方向",focus="锁定怀中的信",stability="slight-shake",
h3="Anchored to Picture 27, a tracking shot follows a messenger stealing through the dark to the gate, a sealed surrender letter pressed against his chest, torchlight guttering."),
dict(beats=[28,28],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，中军帐外，一名将领远远望着一封密信送出营去，缓缓折回身影，烛影收拢。",
shot="固定中景，帐外一名披甲的青年远远望着密信送出营门，缓缓转身折回，身形隐进暗里。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+侧后",composition="三分法",eyeline="营门方向",focus="锁定折回的身影",stability="stable",
h3="Anchored to Picture 28, a static medium shot sees a cloaked figure at the camp's edge watching the letter carried out through the gate, then turning slowly back into the shadows."),
]),
# ============ 场景2 铁索连环 ============
dict(sceneIndex=2,blocking="曹营水寨船帮前，庞统居左敲着船帮、曹操居右探身追问，遥对江心船阵。",
soundscape="江涛拍打船身，晕船兵卒的低吟，庞统慢悠悠开口的衣声。",
music="弦乐沉缓，步步诱饵。",
h3_sound="The Yangtze slaps the hull, seasick soldiers groan low, and the lean scholar speaks with unhurried deliberation.",
h3_music="A slow, baiting string line.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C20"],
frame="全景，庞统借着引荐悄然渡江进了曹营水寨，他一身道袍，立于船桥打量四下。",
shot="跟拍镜头随一名道人登船入寨，一卷丈量着铁链与船板，举目打量这座水寨。",
lens="35mm 广角，全景深",cameraPosition="庞统+侧随行",composition="三分法",eyeline="船阵方向",focus="锁定打量船寨的道人",stability="slight-shake",
h3="Anchored to Picture 1, a tracking shot follows a lean tao-robed scholar as he slips aboard into the enemy camp, sweeping his gaze over the moored warships."),
dict(beats=[2,2],seconds=3.0,size="medium",camera="Static Shot",chars=["C20"],
frame="中景，他在寨中绕看一圈，见大江之上战船颠簸，军中不少将士晕船呕吐，眉头一挑。",
shot="固定中景，绕看船寨的道人瞧见船头颠簸、将士晕船，眉头轻挑，心里有了计较。",
lens="50mm 标准，中浅景深",cameraPosition="庞统+平视正面",composition="三分法",eyeline="晕船的兵卒",focus="锁定道人神色",stability="stable",
h3="Anchored to Picture 2, a static medium shot shows the scholar circling the camp, noting the tossing decks and seasick soldiers, a scheme stirring behind his odd face."),
dict(beats=[3,3],seconds=4.0,size="close",camera="Push In",chars=["C20"],
frame="特写，庞统敲着船帮慢悠悠开口，一句船行江上如履坦途，才不误丞相大计，眼神幽深。",
shot="镜头 Push In 缓推向敲着船帮的道人，他慢悠悠开口，一句如履坦途说得意味深长。",
lens="85mm 长焦，极浅景深",cameraPosition="庞统+平视正面",composition="中心构图",eyeline="对方身形",focus="锁定庞统眼神",stability="stable",
h3="Anchored to Picture 3, a slow push in closes on the scholar tapping the gunwale as he drawls, <d>[Chinese] 船行江上，如履坦途，才不误丞相大计。</d>"),
]),
dict(sceneIndex=2,blocking="曹操居右走到船帮边、庞统居左，二人隔一臂相谈，江面铁索为景。",
soundscape="江水拍板，铁链微响，曹操探身的衣甲声。",
music="弦乐低回，渐引入局。",
h3_sound="Water drums the strakes, an iron chain clinks, and the heavy warlord leans in with a rustle of robes.",
h3_music="Low, circling strings draw the trap shut.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操听他言语间似有破法，连忙探身追问，细眼里亮起一线精光。",
shot="固定中景，一名细眼长髯的枭雄听出话里有门道，连忙探身追问，眼里亮起精光。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定曹操眼神",stability="stable",
h3="Anchored to Picture 4, a static medium shot sees the narrow-eyed warlord catch the hint of a solution and stretch forward to press for it, a glint flicking through his gaze."),
dict(beats=[5,5],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，曹操起身走到船帮边，亲自拍了拍那粗大的铁链，回头等庞统细说，江风鼓满袍袖。",
shot="固定全景，枭雄起身行到船帮，抬手拍了拍那根粗铁链，又回身等那道人细说，袍袖被江风鼓起。",
lens="35mm 广角，全景深",cameraPosition="曹操+侧后",composition="三分法",eyeline="铁链再及道人",focus="锁定拍铁链的手",stability="stable",
h3="Anchored to Picture 5, a static wide shot shows the warlord stepping to the gunwale, patting a thick iron chain, and turning back to await the scholar's explanation."),
dict(beats=[6,6],seconds=3.6,size="close",camera="Push In",chars=["C20"],
frame="特写，庞统不紧不慢、话里有话，大江之上颠的是船稳的是人心，眼神莫测。",
shot="镜头 Push In 缓推向开口的道人，一句颠的是船稳的是人心，说得话里有话。",
lens="85mm 长焦，极浅景深",cameraPosition="庞统+平视正面",composition="中心构图",eyeline="对方身形",focus="锁定庞统神情",stability="stable",
h3="Anchored to Picture 6, a slow push in settles on the scholar who reasons with studied calm, <d>[Chinese] 大江之上，颠的是船，稳的是人心。</d>"),
]),
dict(sceneIndex=2,blocking="曹操居右、庞统居左，二人对立于船头，江心铁索船阵横在画面纵深。",
soundscape="江水滔滔，曹操压下的追问，铁索相击的脆响。",
music="弦乐渐紧，钩子落下。",
h3_sound="The river rushes, the warlord's question comes low and guarded, and iron links knock with a sharp ring.",
h3_music="The strings tighten as the hook drops.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="medium",camera="Static Shot",chars=["C04","C20"],
frame="中景，曹操听着眉头先是一喜随即又压下去，问这法子可有弊端，眉宇回转。",
shot="固定中景，枭雄听罢眉头先是一喜又立刻压下，追问这法子可有什么弊端。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="三分法",eyeline="对方面部",focus="锁定曹操眉头",stability="stable",
h3="Anchored to Picture 7, a static medium shot sees the warlord's brows lift in a spark of delight then sink again as he asks whether the plan carries any flaw."),
dict(beats=[8,8],seconds=4.2,size="close",camera="Push In",chars=["C20"],
frame="特写，庞统一副尽在掌握的样子，若能把船锁成一片风浪再大也稳如平地，眼神透着笃定。",
shot="镜头 Push In 缓推向道人，他端着尽在掌握的神气，一句锁船成片说得轻描淡写。",
lens="85mm 长焦，极浅景深",cameraPosition="庞统+平视正面",composition="中心构图",eyeline="对方身形",focus="锁定庞统眼神",stability="stable",
h3="Anchored to Picture 8, a slow push in holds the scholar with quiet mastery as he offers, <d>[Chinese] 若能把船锁成一片，风浪再大也稳如平地。</d>"),
dict(beats=[9,9],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操连说三声好，当即唤来水军将领，命连夜督造铁锁，袍袖一挥。",
shot="固定中景，枭雄连说三声好，抬手唤来水军将领，吩咐连夜督造铁锁，语气一转而决。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="召来将领",focus="锁定曹操手势",stability="stable",
h3="Anchored to Picture 9, a static medium shot watches the warlord pronounce three good, summon the naval officers, and order the chains forged through the night."),
]),
dict(sceneIndex=2,blocking="曹操居中坐于帅位、庞统立于一侧，二人一坐一立商议罩链，灯火通明。",
soundscape="曹操赞许的沉音，庞统拱手进言，灯花哔剥。",
music="鼓弦并肩，妙计将成。",
h3_sound="The warlord's approving reply rumbles, the scholar bows as he adds his counsel, and a lamp crackles overhead.",
h3_music="Drum and string stride together as the scheme nears its shape.",
cuts=[
dict(beats=[10,10],seconds=3.0,size="medium",camera="Static Shot",chars=["C20"],
frame="中景，庞统便顺势进言要曹操将战船首尾以铁索相连、铺上宽板稳如平地，拱手作请。",
shot="固定中景，立在一侧的道人顺势进言，拱手请以铁索连船、铺上宽板，说得滴水不漏。",
lens="50mm 标准，中浅景深",cameraPosition="庞统+平视正面",composition="三分法",eyeline="帅位方向",focus="锁定庞统拱手",stability="stable",
h3="Anchored to Picture 10, a static medium shot has the scholar pressing his counsel with a courteous bow, urging the warships linked stem to stem and decked over to lie steady as land."),
dict(beats=[11,11],seconds=3.1,size="close",camera="Static Shot",chars=["C20"],
frame="特写，庞统一拱手很笃定，铁索穷船风浪再大也不碍事，黑面短髯透着自得。",
shot="固定近景，道人一拱手显得笃定，一句铁索穷船不碍事，黑面短髯上透出几分自得。",
lens="85mm 长焦，极浅景深",cameraPosition="庞统+平视正面",composition="中心构图",eyeline="对方身形",focus="锁定庞统神情",stability="stable",
h3="Anchored to Picture 11, a static close-up shows the lean scholar folding his hands in certainty as he declares, <d>[Chinese] 铁索穷船，风浪再大也不碍事。</d>"),
dict(beats=[12,12],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，曹操听了大喜，当即下令连夜打造铁索连接战船，江面火把齐刷刷亮起。",
shot="固定全景，枭雄大喜扬声下令，水寨霎时亮起成排火把，连夜打造铁索。",
lens="35mm 广角，全景深",cameraPosition="曹操+俯视 20°",composition="三分法",eyeline="亮起火把的船阵",focus="锁定下令的身影",stability="stable",
h3="Anchored to Picture 12, a static wide shot sees the delighted warlord give the order at once, torchlight springing up in ranks across the camp to forge the chains through the night."),
]),
dict(sceneIndex=2,blocking="画面转船坞连夜赶工，铁索在地上一段段盘起，兵卒挥锤，火把照得雪亮。",
soundscape="锤击铁索的叮当声，火星四溅，兵卒此起彼伏的号子。",
music="打铁的节奏入鼓，略带杂音。",
h3_sound="Hammer rings on iron, sparks fly wide, and labourers call to one another through the racket.",
h3_music="The clash of ironwork settles into a rhythm over a steady drum.",
cuts=[
dict(beats=[13,13],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，曹军连夜赶工，锤声叮当，一直响到东方发白，火星横飞照亮铁链。",
shot="固定全景，连夜赶工的影子挥锤不停，铁花四溅，锤声一直响到天边泛白。",
lens="35mm 广角，全景深",cameraPosition="船坞+俯视 20°",composition="三分法",eyeline="挥锤的兵卒",focus="锁定飞溅的铁花",stability="slight-shake",
h3="Anchored to Picture 13, a static wide shot watches sparks fly from the hammers through the night until the east pales, ironwork ringing across the yard."),
dict(beats=[14,14],seconds=3.0,size="wide",camera="Pan Left",chars=[],
frame="全景，一艘接一艘的战船被铁索牵住，船字旗在风里挨得密不透风，江面织成一片。",
shot="镜头 Pan Left 扫过一排被铁索连住的战船，旗帜在风里挤得密不透风，船帮相连。",
lens="35mm 广角，全景深",cameraPosition="江面船阵+平视",composition="对称",eyeline="船阵纵深处",focus="锁定紧绷的铁索",stability="stable",
h3="Anchored to Picture 14, the camera pans left across warship after warship strung together by taut chains, their flags pressed close and unyielding in the wind."),
dict(beats=[15,15],seconds=3.0,size="medium",camera="Static Shot",chars=["C20"],
frame="中景，有降卒私下嘀咕说这般连起来只怕难以掉头，被身边人一把捂住了嘴，庞统远远看在眼里。",
shot="固定中景，一名降卒低声嘀咕难以掉头，立刻被人捂住嘴，立在远处的道人垂帘看入眼底。",
lens="50mm 标准，中浅景深",cameraPosition="降卒+平视",composition="三分法",eyeline="捂嘴的方向",focus="锁定被捂嘴的降卒",stability="stable",
h3="Anchored to Picture 15, a static medium shot catches a surrenderer whispering that linked ships cannot turn, only to be clamped silent by a comrade while the far scholar watches."),
]),
dict(sceneIndex=2,blocking="曹操立于船头居中，庞统隐于身侧，江面铁索船阵铺成画面主体。",
soundscape="江风和缓，铁索轻响，旗幡哗哗卷动。",
music="弦乐舒展，稳中藏险。",
h3_sound="The wind eases, chains rattle, and banners whip and settle against the sky.",
h3_music="Strings open out, calm carrying a hidden peril.",
cuts=[
dict(beats=[16,16],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操立在船头望着那片铁索船阵，只觉得心定了几分，细眼里有了底。",
shot="固定中景，立于船头的枭雄望着连成一片的铁索船阵，眼底添了几分定。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="三分法",eyeline="前方船阵",focus="锁定曹操神情",stability="stable",
h3="Anchored to Picture 16, a static medium shot shows the warlord at the prow surveying the iron-strung fleet, a measure of certainty settling into his narrow eyes."),
dict(beats=[17,17],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，江上战船一艘连着一艘，铁索横亘水面浩浩荡荡密如梳齿，望不见尽头。",
shot="固定大远景，江面战船一艘连一艘，铁索横亘其上，密如梳齿，铺陈到水天尽头。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="水天尽头",focus="锁定横亘的铁索",stability="stable",
h3="Anchored to Picture 17, a static extreme-wide shot reveals the whole river bound ship to ship, iron chains spanning the water like the teeth of a comb to the far horizon."),
dict(beats=[18,18],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操立在船头看罢连连颔首，说这般锁死水军便稳如磐石，袍袖猎猎。",
shot="固定中景，船头的枭雄连连颔首，一句锁死稳如磐石，袍袖被风扯得猎猎作响。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="三分法",eyeline="脚下船阵",focus="锁定曹操颔首",stability="stable",
h3="Anchored to Picture 18, a static medium shot sees the warlord nod twice and declare the tied fleet as firm as bedrock, his sleeves snapping in the wind."),
]),
dict(sceneIndex=2,blocking="曹操立船头、庞统侍立身侧，画面由明转微暗，庞统唇畔泛起笑意。",
soundscape="曹操吩咐备火器水具的沉音，江水轻响，庞统收住的笑。",
music="弦乐一转，暗藏锋芒。",
h3_sound="The warlord issues his order to stock fire and water, the river murmurs, and the scholar's hidden smile is swallowed at once.",
h3_music="Strings pivot, a blade hidden beneath.",
cuts=[
dict(beats=[19,19],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，他又吩咐下去命各船备足火器水具，以防夜里有人来袭，眉宇一沉。",
shot="固定中景，立在船头的枭雄又吩咐各船备足火器水具，防夜里有人来袭，眉头沉了沉。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="下方船队",focus="锁定曹操神态",stability="stable",
h3="Anchored to Picture 19, a static medium shot has the warlord further ordering every ship stocked with fire and water against a night raid, a shadow passing over his brow."),
dict(beats=[20,20],seconds=3.0,size="close",camera="Push In",chars=["C20"],
frame="特写，立在一侧的庞统听了，垂下眼帘嘴角不易察觉地泛起一丝笑意，眉眼隐没。",
shot="镜头 Push In 缓推向垂帘的道人，他闻言垂下眼帘，嘴角极淡地一勾又收住。",
lens="85mm 长焦，极浅景深",cameraPosition="庞统+平视侧面",composition="中心构图",eyeline="下方船队",focus="锁定庞统唇畔",stability="stable",
h3="Anchored to Picture 20, a slow push in finds the scholar lowering his lids as the barest smile edges his lips, then vanishes as if it never came."),
]),
dict(sceneIndex=2,blocking="曹操独坐帐案后，降书摊在案上，画面由船阵转入帐内灯火。",
soundscape="烛火哔剥，曹操翻开信纸的窸窣，指尖轻叩案面的声响。",
music="弦乐悬停，疑虑暗生。",
h3_sound="A lamp crackles, paper rustles as the letter is unfurled, and fingers tap the table's edge.",
h3_music="Strings hold suspended, doubt taking root.",
cuts=[
dict(beats=[21,21],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操接黄盖那封降书也已送到案前，他只看了三行，目光落在那字迹上。",
shot="固定近景，案后的枭雄摊开一封降书只看三行，目光沉定地落在那行字迹上。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="案上信纸",focus="锁定信中字迹",stability="stable",
h3="Anchored to Picture 21, a static close-up shows the warlord before the surrender letter, reading no more than three lines, gaze locked on the script."),
dict(beats=[22,22],seconds=3.0,size="close",camera="Tilt Up",chars=["C04"],
frame="特写，曹操把信放下又拿起，盯着字迹反复端详，眉心渐渐锁起来，烛火闪动。",
shot="镜头 Tilt Up 顺着案沿推上，枭雄把信放下又拿起，反复端详字迹，眉心一点一点锁紧。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="手中信纸",focus="锁定曹操眉心",stability="stable",
h3="Anchored to Picture 22, the camera tilts up past the lamplight as the warlord sets the letter down and picks it up again, rereading the lines, brow gathering."),
dict(beats=[23,23],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，他敲了敲案沿，忽然问左右黄盖这几日被打得可当真狠，眼睫微垂。",
shot="固定中景，案后的枭雄叩了叩案沿，忽然开口问那灰甲老将这几日挨的打可当真重，语气难测。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="左右亲卫",focus="锁定曹操叩案的手",stability="stable",
h3="Anchored to Picture 23, a static medium shot has the warlord drumming the table's edge as he asks the guards at hand whether the beating indeed cut deep."),
]),
dict(sceneIndex=2,blocking="曹操案后居右、亲卫立左，烛灯低照，降书搁在案角。",
soundscape="亲卫回话，曹操踱步的衣声，夜风从帐口钻入。",
music="弦乐低回，孰信孰诈难分。",
h3_sound="A guard answers, the warlord paces with a slide of robes, and night wind slips in through the canvas.",
h3_music="Low, circling strings leave trust and fraud unresolved.",
cuts=[
dict(beats=[24,24],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，亲卫回说脊杖五十打得皮开肉绽如今连坐都坐不住，曹操侧耳听定。",
shot="固定中景，一名亲卫回话道脊杖五十皮开肉绽，案后枭雄侧耳听定，灯火在中间隔开。",
lens="50mm 标准，中浅景深",cameraPosition="亲卫+平视",composition="三分法",eyeline="曹操方向",focus="锁定回话的亲卫",stability="stable",
h3="Anchored to Picture 24, a static medium shot hears the guard report the fifty strokes have left the man unable to sit, the warlord listening without moving."),
dict(beats=[25,25],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操听罢先是缓缓点头，目光却仍在那信角上徘徊不去，眼底深不见底。",
shot="固定近景，枭雄听罢缓缓点头，目光却仍黏在那封降书的信角上，来回徘徊。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="信角",focus="锁定曹操目光",stability="stable",
h3="Anchored to Picture 25, a static close-up sees the warlord nod slowly even as his gaze keeps returning to the corner of the letter, unreadable to the bottom."),
dict(beats=[26,26],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，他来回踱了几步，心底那杆秤终究还是偏向了来降那三分，烛影拖长。",
shot="固定全景，枭雄在案前来回踱步，烛影把他拉得忽长忽短，心里那杆秤终究偏了一分。",
lens="35mm 广角，全景深",cameraPosition="曹操+侧面",composition="三分法",eyeline="窗前烛火",focus="锁定踱步的身影",stability="stable",
h3="Anchored to Picture 26, a static wide shot follows the warlord pacing to and fro, his shadow stretching and shrinking, the scale inside him tipping at last toward surrender."),
]),
dict(sceneIndex=2,blocking="夜色帐内，曹操立于案后，铁索船影自窗外透入，降书在袖中掖。",
soundscape="夜风呜呜，江上艨艟静泊的水响，曹操低语自言自语。",
music="弦乐压暗，将信将疑。",
h3_sound="The night wind moans, moored warships creak on the water, and the warlord mutters half to himself.",
h3_music="Dark, guarded strings carry the doubt.",
cuts=[
dict(beats=[27,27],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，夜色里铁索连船的艨艟静泊江面，密如梳齿，望不见水，月色阴沉。",
shot="固定大远景，夜色里铁索连船的艨艟静泊江面，密如梳齿，压得连水都望不见。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="船阵尽头",focus="锁定静泊的铁索船",stability="stable",
h3="Anchored to Picture 27, a static extreme-wide shot shows the iron-bound fleet resting dead-flat under the moon, packed like a comb so close no water shows between."),
dict(beats=[28,28],seconds=2.2,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操自言自语指尖敲着案角，一句黄盖真降还是诈我，自喉间低低滑出。",
shot="固定近景，案后的枭雄指尖敲着案角，低低自语吐出一句，火光在他眼底晃动。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="案面",focus="锁定曹操唇齿",stability="stable",
h3="Anchored to Picture 28, a static close-up shows the warlord muttering to himself, fingers tapping the case, the half-question slipping out, <d>[Chinese] 黄盖真降，还是诈我？</d>"),
dict(beats=[29,29],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，他沉吟半晌，忽然唤过身旁亲信，低声吩咐一句，烛火压得更低。",
shot="固定中景，沉吟半晌的枭雄忽然唤过身旁亲信，低头低声吩咐一句，帐内瞬时更静。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="身边亲信",focus="锁定曹操侧首",stability="stable",
h3="Anchored to Picture 29, a static medium shot sees the warlord, after a long pause, summon a trusted aide and murmur a single low order, the tent at once quieter."),
]),
dict(sceneIndex=2,blocking="曹操立于案后、亲信俯首听命，画面在夜帐里收拢，铁索船影透窗。",
soundscape="曹操低声令下的气声，亲信领命退去的脚步，窗外的江风。",
music="弦乐终收，留余韵。",
h3_sound="The warlord's low order hangs in the air, the aide bows and retreats, and the river wind keeps on beyond the canvas.",
h3_music="The strings settle at last, a trailing edge left behind.",
cuts=[
dict(beats=[30,30],seconds=2.4,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操眼底深不见底，一句送信的人不留放回去，语气平得可怕。",
shot="固定近景，案后的枭雄眼底深不见底，一句吩咐放走送信的人，语气平得令人生寒。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="前方暗处",focus="锁定曹操双目",stability="stable",
h3="Anchored to Picture 30, a static close-up holds the warlord leveling an order in a voice flat enough to chill, <d>[Chinese] 送信的人不留，放回去。</d>"),
dict(beats=[31,31],seconds=3.0,size="medium",camera="Pull Out",chars=["C04"],
frame="中景，亲信领命而去，曹操这才把那封降书卷了起来慢慢搁进袖中，目光投向窗外铁索船影。",
shot="镜头 Pull Out 自窗口缓缓拉开，亲信领命而去，枭雄卷起降书放进袖中，望向窗外那片铁索船影。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+侧后",composition="三分法",eyeline="窗外船影",focus="锁定放进袖中的手",stability="stable",
h3="Anchored to Picture 31, a pull out draws back toward the window as the aide leaves and the warlord rolls the letter into his sleeve, gaze settling on the chained ships below."),
]),
]