# -*- coding: utf-8 -*-
# ep50 华容道义释  场景1 beats1-32 C04,C02  场景2 beats1-28 C02
C02="a tall crimson-robed general with phoenix eyes and a long black beard, gripping a green-dragon crescent blade"
C04="a stout warlord with narrow eyes and a long beard, in mud-stained chancellor robes"
EP=50
SEG=[
# ============ 场景1 华容道·曹操残军 ============
dict(sceneIndex=1,blocking="曹操牵马走在前居中，残军随后，山道狭窄仅容一骑，两旁山崖削立。",
soundscape="马蹄踩进湿泥的噗声，残军沉重的脚步声与粗喘，山风呜呜穿过谷道。",
music="压抑低弦与稀疏鼓点，气氛绷紧。",
h3_sound="Hooves squelch in the wet clay, tattered men drag heavy steps and ragged breaths, and a thin wind moans through the gorge.",
h3_music="Oppressive low strings over sparse drums, the air drawn tight.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Static Shot",chars=["C04"],
frame="全景，华容道山道泥泞逼仄，曹操一身锦袍早已被泥点溅满，牵马走在最前，身后残军垂头拖着脚步。",
shot="固定全景，泥泞的窄道只容一骑，一名细眼长髯、锦袍溅泥的枭雄牵马走在最前，残兵拖着疲步尾随。",
lens="28mm 广角，全景深",cameraPosition="曹操+平视",composition="三分法",eyeline="前方窄道",focus="锁定牵马前行的身影",stability="slight-shake",
h3="Anchored to Picture 1, a wide shot frames the narrow, muddy course as a mud-spattered warlord leads his horse at the front, tattered men dragging after him."),
dict(beats=[2,2],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操勒住马抬头，见前方山道被浓雾吞没、望不到头，心里没来由地发慌。",
shot="固定中景，枭雄勒马抬头，望入前面那道隐进浓雾的窄道，望不见尽头，眉间漫起一层隐隐不安。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="雾中窄道",focus="锁定曹操神情",stability="stable",
h3="Anchored to Picture 2, a medium shot holds the warlord reining in and looking up at the road swallowed by fog, an unaccountable unease stealing across his face."),
dict(beats=[3,3],seconds=3.0,size="close",camera="Static Shot",chars=[],
frame="特写，他身后的随从早没了气力，一个个拖着酸痛的双腿，走一步喘三步，神色灰败。",
shot="固定近景，几名残兵拖着酸痛的双腿紧跟马后，走一步喘三步，脸上尽是灰败的疲惫。",
lens="85mm 长焦，极浅景深",cameraPosition="随从+平视",composition="三分法",eyeline="前行的方向",focus="锁定拖步的腿",stability="slight-shake",
h3="Anchored to Picture 3, a close-up catches the men behind the horse, each dragging a sore leg and wheezing every few paces, faces ashen with fatigue."),
dict(beats=[4,4],seconds=3.0,size="wide",camera="Pan Left",chars=["C04"],
frame="全景，曹操回头望了一眼江那头冲天的火光，又厉声催促残军快走，莫再遇上埋伏。",
shot="镜头 Pan Left 随那枭雄回望再转向前路，他瞥一眼身后冲天的火光，厉声催促残军快走、莫再遇埋伏。",
lens="28mm 广角，全景深",cameraPosition="曹操+侧随行",composition="三分法",eyeline="江那头火光",focus="锁定催促的身形",stability="slight-shake",
h3="Anchored to Picture 4, the camera pans left as the warlord glances back at the towering fire across the river, then barks at the stragglers to hurry before more ambush."),
dict(beats=[5,5],seconds=3.0,size="close",camera="Static Shot",chars=[],
frame="特写，两旁山壁陡峭，头顶只余一线天光，投下的影子把这条道挤得越发幽暗。",
shot="固定近景，陡峭的山壁夹出一线天光，投下的影子把窄道压得愈发幽暗，逼得人透不过气。",
lens="85mm 长焦，极浅景深",cameraPosition="山壁下+仰视 20°",composition="对角线",eyeline="一线天光",focus="锁定逼仄的石壁",stability="stable",
h3="Anchored to Picture 5, a close-up sees the sheer walls close to a single thread of sky, their shadows pressing the roadway darker and nearer."),
]),
dict(sceneIndex=1,blocking="曹操居于画面中、催随从前行，道中乱石堆，山坳方向居画面左。",
soundscape="蹄声杂乱，急促呼吸，忽然一声孤立的马嘶穿出山坳，众人脚步一乱。",
music="一记不协和低音，骤生警兆。",
h3_sound="Hooves scatter over the stones, then a single horse-neigh splits out of the hollow, sending the column's steps into disorder.",
h3_music="One dissonant low note strikes, a sudden warning.",
cuts=[
dict(beats=[6,6],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，乱石堆里蹄声杂乱，一队残兵正仓皇地往前方岔口挤去，人人神色惊惶。",
shot="固定中景，乱石堆里蹄声纷乱，一队残兵仓皇地往岔口挤去，人人神色惊惶、脚步发软。",
lens="50mm 标准，中浅景深",cameraPosition="残兵+平视",composition="三分法",eyeline="前方岔口",focus="锁定挤行的队伍",stability="slight-shake",
h3="Anchored to Picture 6, a medium shot sees a straggling column press desperately toward the fork among the tumbled rocks, faces drawn with alarm."),
dict(beats=[7,7],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，曹操正催随从快走，山坳里忽然传出一声响亮的马嘶，他眉心骤然一跳。",
shot="固定近景，一段静默里，山坳忽然迸出一声马嘶，走在前的枭雄脚步骤然停住，眉心一跳。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视侧面",composition="中心构图",eyeline="山坳方向",focus="锁定骤然的眉心",stability="stable",
h3="Anchored to Picture 7, a close-up lingers on the warlord as he urges the men on, when a bright horse-neigh bursts from the hollow and his brow jumps."),
dict(beats=[8,8],seconds=3.0,size="wide",camera="Tilt Up",chars=[],
frame="全景，随即一面旗幡猎猎竖起，横拦住整条窄道，像一道剪断去路的门。",
shot="镜头 Tilt Up 自草丛摇上，一面旗幡猎猎竖起，横拦整条窄道，像一道关死的门拦在眼前。",
lens="28mm 广角，全景深",cameraPosition="旗幡+仰视 20°",composition="对称",eyeline="竖起的旗幡",focus="锁定猎猎的幡旗",stability="slight-shake",
h3="Anchored to Picture 8, the camera tilts up as a banner whips erect to block the whole narrow road, like a door slammed shut across the way."),
dict(beats=[9,9],seconds=3.0,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操勒住马，那一瞬只觉头皮一麻、心口咚咚直往下坠，握缰的手僵在半空。",
shot="镜头 Push In 缓推向勒马的枭雄，他头皮一麻、心口直坠，攥缰的手一时僵在半空。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="旗幡方向",focus="锁定僵住的手",stability="slight-shake",
h3="Anchored to Picture 9, a slow push in nears the warlord as a cold jolt runs up his scalp and his heart sinks, the rein-hand freezing mid-air."),
]),
dict(sceneIndex=1,blocking="前路被旗幡横拦，居中曹操勒马，关羽一马当先堵住道心，双方隔十余步。",
soundscape="败兵齐刷刷顿住的脚步声，马匹喷鼻，风声与剑出鞘的低响。",
music="鼓点骤收，剑拔弩张。",
h3_sound="The vanguard halts in a ragged shuffle, a horse snorts, wind and the low rasp of a blade clearing fill the pause.",
h3_music="The drums cut short, on a hair trigger.",
cuts=[
dict(beats=[10,10],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，前头的败兵被这突然竖起的旗一吓，登时齐刷刷顿住，进退不得，乱作一团。",
shot="固定中景，前头的败兵被骤然竖起的旗一吓，登时齐刷刷顿住，进也不是退也不是，挤作一团。",
lens="50mm 标准，中浅景深",cameraPosition="败兵+平视",composition="三分法",eyeline="竖起的旗",focus="锁定顿住的败兵",stability="slight-shake",
h3="Anchored to Picture 10, a medium shot sees the vanguard startle at the flag and freeze in place, trapped between advance and retreat, bunching into confusion."),
dict(beats=[11,11],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，关羽一马当先，横着青龙偃月刀勒住马头，威风凛凛堵在道心，丹凤眼扫视众人。",
shot="固定全景，一名绿袍长髯的将领一马当先，横着长刀勒马堵在道心，威风凛凛，岿然不动。",
lens="28mm 广角，全景深",cameraPosition="关羽+平视",composition="对称",eyeline="曹操方向",focus="锁定横刀的身影",stability="stable",
h3="Anchored to Picture 11, a wide shot shows a crimson-robed general at the fore, crescent blade held across, halting mid-road, imposing and unmoving."),
dict(beats=[12,12],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操身后一名亲将低喝一声就要催马，被曹操抬手稳稳拦下，眉头一沉。",
shot="固定中景，枭雄身后一名亲兵低喝欲催马强冲，被他一抬手稳稳拦下，眉头沉沉地一收。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视",composition="中心构图",eyeline="拦下的手",focus="锁定抬手的身影",stability="stable",
h3="Anchored to Picture 12, a medium shot sees a guardsman urge his mount forward until the warlord's steady hand pulls him up, brow drawing into a frown."),
dict(beats=[13,13],seconds=3.0,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操定睛细看，认出了那道身影，握着缰绳的手竟微微发颤，呼吸一窒。",
shot="镜头 Push In 缓推向枭雄，他定睛认出对面那道身影，攥缰的手微微发颤，呼吸骤然一停。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="对面身影",focus="锁定发颤的手",stability="slight-shake",
h3="Anchored to Picture 13, a slow push in finds the warlord recognizing the figure across the road, the hand on the rein trembling a little as his breath catches."),
]),
dict(sceneIndex=1,blocking="关羽居中堵道，曹操隔十步勒马与之相对，画面两侧山壁夹峙。",
soundscape="众人屏息的静默，风掠崖沿，曹操极轻的呼吸。",
music="弦乐压到最低，静得发紧。",
h3_sound="The men hold their breath, wind scrapes the cliff edge, and the warlord's breath comes shallow and tight.",
h3_music="Strings press down to a bare murmur, still and taut.",
cuts=[
dict(beats=[14,14],seconds=3.0,size="wide",camera="Static Shot",chars=["C04","C02"],
frame="全景，曹操勒住马，望见那道挺拔如松的身影，心口一沉，只觉天旋地转，走避无门。",
shot="固定全景，枭雄勒马，望见对面那道挺拔如松的绿袍身影，心口一沉，仿佛天地都在打转。",
lens="28mm 广角，全景深",cameraPosition="曹操+平视",composition="对称",eyeline="对面身影",focus="锁定沉下去的身形",stability="stable",
h3="Anchored to Picture 14, a wide shot sees the warlord rein in at the sight of the straight-backed figure, his heart sinking as the world seems to spin."),
dict(beats=[15,15],seconds=3.0,size="medium",camera="Static Shot",chars=["C04"],
frame="中景，曹操强自稳住声气，抬手让身后的随从都把脚步放轻些，别惊动对面。",
shot="固定中景，枭雄强捺住声气，抬手示意身后众人放轻脚步，别惊动对面那位。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="身后随从",focus="锁定示意的手",stability="stable",
h3="Anchored to Picture 15, a medium shot sees the warlord steady his voice and wave the men behind to soften their steps so as not to stir the one beyond."),
dict(beats=[16,16],seconds=3.0,size="close",camera="Static Shot",chars=["C04"],
frame="特写，他在心里飞快掂量，眼前这人欠他的那份情，够不够保下这一条命。",
shot="固定近景，枭雄在心底飞快掂量，眼前这份旧情究竟够不够保下一条命，目光微微闪动。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="前方方向",focus="锁定曹操眉眼",stability="stable",
h3="Anchored to Picture 16, a close-up sees the warlord turning over in his mind whether the kindness he once showed can buy back this one life, eyes flickering."),
]),
dict(sceneIndex=1,blocking="曹操驱马缓缓上前两步居左，关羽横刀堵于道心居右，两人逐渐拉近。",
soundscape="马蹄踏上湿泥的轻响，曹操深吸的一口气，风声放低。",
music="低弦收住一拍，言语将起。",
h3_sound="A horse steps softly through the mud, the warlord draws one long breath, and the wind falls low.",
h3_music="The strings hold one still beat as a voice is about to rise.",
cuts=[
dict(beats=[17,18],seconds=3.0,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操整了整被泥水浸透的衣袍，深吸一口气，驱马慢慢上前两步，先开口问安。",
shot="镜头 Push In 缓推向枭雄，他整了整浸透泥水的衣袍，深吸一口气，驱动坐骑缓缓上前两步，话音极低",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="对面身影",focus="锁定曹操唇齿",stability="slight-shake",
h3="Anchored to Picture 17, a slow push in nears the warlord as he smooths his mud-soaked robe, draws a breath, and rides two unhurried paces forward to greet his old acquaintance, <d>[Chinese] 云长，别来无恙。</d>"),
dict(beats=[19,19],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽端坐马上，丹凤眼微微一眯，却未答话，只把刀横得更稳了些，面沉如水。",
shot="固定近景，绿袍将领端坐马上，凤眼微微眯起却不接话，只把长刀横得更稳，面沉如水。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="曹操方向",focus="锁定关羽眉眼",stability="stable",
h3="Anchored to Picture 18, a close-up sees the general sitting calmly on his horse, phoenix eyes narrowing as he offers no reply, only holding the blade steadier."),
dict(beats=[20,20],seconds=3.0,size="wide",camera="Tilt Down",chars=["C04"],
frame="全景，曹操见他不动刀，心下一动，滚鞍下马，拢了拢沾泥的袍袖，神色恭谨。",
shot="镜头 Tilt Down 自马背摇下，枭雄见对方未动刀，心下一动便翻身下马，拢了拢沾泥的袍袖。",
lens="28mm 广角，全景深",cameraPosition="曹操+平视",composition="三分法",eyeline="拢袖的手",focus="锁定翻身下马的身影",stability="slight-shake",
h3="Anchored to Picture 19, the camera tilts down as the warlord, seeing the blade unmoved, swings off his horse and gathers his muddied sleeves, stance turning respectful."),
]),
dict(sceneIndex=1,blocking="曹操下马立于道中、深揖居左，关羽勒马居右，两人隔数步相对。",
soundscape="曹操深揖的衣甲低响，风掠过崖沿，满道屏息的静默。",
music="悲凉低弦，旧情翻涌。",
h3_sound="The warlord's bow stirs his sodden robe, wind slides along the cliff, and the whole road holds its breath.",
h3_music="A grief-laden low string, old debts rising.",
cuts=[
dict(beats=[21,21],seconds=3.0,size="medium",camera="Static Shot",chars=["C04","C02"],
frame="中景，他上前一步，拱手深深一揖，开言便提起当年在许都对关羽的那一番恩义。",
shot="固定中景，枭雄上前一步，拱手深揖，开口便提起当年许都对对面那位的一番恩义旧事。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视",composition="三分法",eyeline="对面身影",focus="锁定深揖的动作",stability="stable",
h3="Anchored to Picture 21, a medium shot sees the warlord step forward, bow deeply with folded hands, and begin to recall the favors he once did the general at Xudu."),
dict(beats=[22,22],seconds=5.0,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操一揖之后抬起身，望着对面的关羽，一字一句提起昔日的恩重礼厚，情真意切。",
shot="镜头 Push In 缓推向揖后的枭雄，他望着对面，一字一句提起当年待对方的多般照拂，情真意切",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="对面身影",focus="锁定曹操双眼",stability="stable",
h3="Anchored to Picture 22, a slow push in holds the warlord after his bow as he speaks of the kindness he once showed the general, earnest and unhurried, <d>[Chinese] 云长知恩重义，曹操一路待你如何，你心里有数。</d>"),
dict(beats=[23,23],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽握着刀柄的指节微微泛白，丹凤眼里掠过一抹难言的挣扎，喉结微动。",
shot="固定近景，绿袍将领握刀的手指节微微泛白，凤眼里掠过一抹难言的挣扎，喉头轻轻一滚。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="下方刀柄",focus="锁定泛白的指节",stability="stable",
h3="Anchored to Picture 23, a close-up sees the knot of the general's knuckles whiten around the haft, a hard-to-voice struggle passing through his phoenix eyes."),
dict(beats=[24,24],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，他身后的那辆车停在道旁，马车帐帘被掀起一线，两位嫂嫂的目光隐隐探出。",
shot="固定中景，一辆停在道旁的马车帐帘掀开一线，帘后人影默默张望，并不上前催促。",
lens="50mm 标准，中浅景深",cameraPosition="马车+平视",composition="三分法",eyeline="掀开的帐帘",focus="锁定帘后人影",stability="stable",
h3="Anchored to Picture 24, a medium shot rests on the carriage halted at the roadside, its curtain lifted a sliver, a silent gaze peering out without urging."),
]),
dict(sceneIndex=1,blocking="关羽居中勒马，身后随从与二嫂车驾，风掠崖沿吹动众人衣角。",
soundscape="风掠过崖沿的沙沙声，满道屏息的静默，残旗猎猎。",
music="低弦悬停，久等一个决断。",
h3_sound="Wind rustles along the cliff top, the whole road holds its breath, and tattered banners flap in the gusts.",
h3_music="One suspended low string, waiting long for a decision.",
cuts=[
dict(beats=[25,25],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽握着刀柄的指节松开又攥紧，丹凤眼里那抹挣扎越缠越深，迟迟不落刀。",
shot="固定近景，绿袍将领握刀的手指松开又攥紧，凤眼里那抹挣扎越缠越深，迟迟不肯落刀。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="下方刀柄",focus="锁定反复攥紧的指节",stability="stable",
h3="Anchored to Picture 25, a close-up sees the general's knuckles ease and tighten again as the struggle in his phoenix eyes deepens, still no blade falling."),
dict(beats=[26,26],seconds=3.0,size="medium",camera="Static Shot",chars=["C04","C02"],
frame="中景，曹操见那张脸半晌未动，又是深深一揖，几乎把腰弯到了膝盖，姿态放得极软。",
shot="固定中景，枭雄见对方半晌未动，又深深一揖，几乎把腰弯到膝头，姿态放得极软。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视",composition="三分法",eyeline="对面身影",focus="锁定弯下的身影",stability="stable",
h3="Anchored to Picture 26, a medium shot sees the warlord, met by a long still face, bow again so low his waist nears his knees, humbling himself outright."),
dict(beats=[27,27],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，风掠过矮崖沿，把两边人的衣角都吹得沙沙作响，气氛僵得能拧出水。",
shot="固定全景，风掠过矮崖，吹动两边人的衣角沙沙作响，道上一片凝固的僵持。",
lens="28mm 广角，全景深",cameraPosition="崖沿+平视",composition="三分法",eyeline="翻卷的衣角",focus="锁定凝固的僵持",stability="stable",
h3="Anchored to Picture 27, a wide shot sees the wind brush the low cliff and ruffle the hems on both sides, the whole road frozen in a tension that could snap."),
dict(beats=[28,28],seconds=3.0,size="medium",camera="Static Shot",chars=["C02","C04"],
frame="中景，满道静默，连马都不再刨蹄，像是在等一个人的决断。",
shot="固定中景，整条道静得能听见心跳，连马都不再刨蹄，所有人都在等对面那人的一句话。",
lens="50mm 标准，中浅景深",cameraPosition="道中+平视",composition="三分法",eyeline="对立的双方",focus="锁定静立的马匹",stability="stable",
h3="Anchored to Picture 28, a medium shot sees the whole road fall still, even the horses cease pawing the ground, as if everyone waits on a single verdict."),
dict(beats=[29,29],seconds=3.0,size="close",camera="Static Shot",chars=["C02","C04"],
frame="特写，身后那几面残破的旗在风里猎猎作响，众人屏住呼吸，只等关羽一句话。",
shot="固定近景，残旗在风里猎猎作响，满道的人屏着气，只等绿袍将领开口。",
lens="85mm 长焦，极浅景深",cameraPosition="残旗+平视",composition="三分法",eyeline="猎猎的残旗",focus="锁定屏息的人群",stability="slight-shake",
h3="Anchored to Picture 29, a close-up catches the torn banners snapping in the wind as everyone holds their breath, waiting for the general to speak."),
]),
dict(sceneIndex=1,blocking="关羽纵马侧身居右，曹操下马立于道中，两人对峙，气氛在沉默中缓缓松落一瞬。",
soundscape="关羽侧身带马的马蹄轻响，曹操趋步的声音，风声渐缓。",
music="低弦松开一格，仍是悬而未决。",
h3_sound="The general's horse takes a side step, the warlord moves closer a stride, and the wind begins to ease.",
h3_music="A low string slackens a notch, still unresolved.",
cuts=[
dict(beats=[30,30],seconds=3.0,size="wide",camera="Static Shot",chars=["C02","C04"],
frame="全景，关羽纵马侧身，避开曹操那一揖，半晌，却仍没落刀，刀尖悬在半空。",
shot="固定全景，绿袍将领纵马侧身，避开对面那一揖，长刀却仍悬在半空，迟迟不落。",
lens="28mm 广角，全景深",cameraPosition="关羽+平视",composition="三分法",eyeline="曹操方向",focus="锁定悬着的长刀",stability="stable",
h3="Anchored to Picture 30, a wide shot sees the general sidestep his horse to avoid the bow, yet the blade still hangs, never quite coming down."),
dict(beats=[31,31],seconds=3.0,size="medium",camera="Static Shot",chars=["C04","C02"],
frame="中景，曹操见关羽仍不落刀，又紧两步上前，把声音放得更软，几乎是央求。",
shot="固定中景，枭雄见对方仍不出刀，又紧上两步，声音放得更软，几乎成了恳求。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视",composition="中心构图",eyeline="对面身影",focus="锁定趋步的身影",stability="stable",
h3="Anchored to Picture 31, a medium shot sees the warlord step two paces closer when the blade still holds, softening his voice into something close to a plea."),
dict(beats=[32,32],seconds=4.8,size="close",camera="Push In",chars=["C04"],
frame="特写，曹操借着最后一丝底气，把话说得又低又慢，只求这支残兵能有一条生路走出山去。",
shot="镜头 Push In 缓推向枭雄，他压着一线底气，把话说得低而缓，只求放这群残兵一条生路",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="对面身影",focus="锁定曹操双目",stability="stable",
h3="Anchored to Picture 32, a slow push in nears the warlord as he speaks his last plea in a low, slow voice, asking only that his tattered men be granted a way through, <d>[Chinese] 将军杀我便杀，只求放我这几条残兵一条生路。</d>"),
]),
# ============ 场景2 关羽义释 ============
dict(sceneIndex=2,blocking="关羽居中勒马，刀尖缓缓垂落，曹操立于道对面的下马处，两人隔道相对。",
soundscape="刀尖擦过鞍革的低响，关羽极轻的一声长叹，风声渐收。",
music="一记低弦化开，决断既下。",
h3_sound="The blade rasps low across the saddle leather, the general lets out one faint sigh, and the wind draws back.",
h3_music="One low string melts away, the verdict given.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，关羽缓缓垂下刀尖，把头转向一旁，不看曹操，也不看身后，只望着道外。",
shot="固定中景，绿袍将领缓缓垂落刀尖，偏过头去不看对面，也不看身后，只望那道外。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视侧面",composition="三分法",eyeline="道外方向",focus="锁定垂刀的身影",stability="stable",
h3="Anchored to Picture 1, a medium shot sees the general lower the blade and turn his head away, looking neither at the warlord nor behind him, only past the road."),
dict(beats=[2,3],seconds=3.0,size="close",camera="Push In",chars=["C02"],
frame="特写，那柄青龙偃月刀的刀镡在掌心转了一圈，终是重重垂向地面，他低声吐出两个字。",
shot="镜头 Push In 缓推向持刀的将领，长刀的刀镡在掌中转了一圈，重重垂向地面，他低声开口放行",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="垂落的刀锋",focus="锁定垂刀的手",stability="stable",
h3="Anchored to Picture 2, a slow push in nears the general as the crescent blade turns once in his grip and sinks heavily toward the ground while he speaks low, <d>[Chinese] 罢了，你且去吧。</d>"),
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，曹操闻言大喜，也顾不得仪态，连作三个揖，翻身上马，脸上绽出喜色。",
shot="固定中景，枭雄闻言大喜，顾不得仪态连作三揖，随即翻身上马，眉眼都松了下来。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视",composition="三分法",eyeline="关羽方向",focus="锁定连揖的身影",stability="slight-shake",
h3="Anchored to Picture 3, a medium shot sees the warlord beam at the word, forgetting all dignity to bow three times and mount, relief washing over his face."),
]),
dict(sceneIndex=2,blocking="曹操翻身上马居左，关羽勒马居右，残军随曹操转出山坳，关羽回望。",
soundscape="马匹启程的蹄声渐起，残兵跟随的脚步，山道风声。",
music="低弦转疏，如释重负又怅然。",
h3_sound="Horses start into motion, tattered men fall in behind, and the wind combs through the mountain road.",
h3_music="Low strings thin out, relieved yet wistful.",
cuts=[
dict(beats=[5,5],seconds=3.0,size="wide",camera="Tracking Shot",chars=[],
frame="全景，他回望一眼关羽，见那道身影背对自己，再不多言，策马带着残兵疾奔而去。",
shot="跟拍镜头随枭雄策马转头疾奔，他回望一眼那道背身的身影，不再多言，领着残兵冲出。",
lens="28mm 广角，全景深",cameraPosition="曹操+侧随行",composition="三分法",eyeline="前方山道",focus="锁定疾奔的队伍",stability="slight-shake",
h3="Anchored to Picture 4, a tracking shot follows the warlord spurring hard, glancing once at the turned-back figure before charging off with the remnants."),
dict(beats=[6,6],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，曹操兵马转过山坳消失，好一阵，关羽才缓缓转回头来，眼底空落。",
shot="固定中景，马蹄与旗帜转过山坳消失，过了好一阵，绿袍将领才缓缓转回头，眼底一片空落。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视",composition="三分法",eyeline="空了的山坳",focus="锁定回转的身影",stability="stable",
h3="Anchored to Picture 5, a medium shot sees the warlord's column vanish past the hollow before the general slowly turns back, his eyes left hollow."),
dict(beats=[7,7],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，他望了一眼那条远去烟尘的路，眼底情绪翻涌，久久没能收回目光。",
shot="固定近景，绿袍将领望着那条扬起烟尘远去的路，眼底情绪翻涌，久久收不回目光。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="远去的烟尘",focus="锁定关羽双目",stability="stable",
h3="Anchored to Picture 6, a close-up sees the general gazing at the road trailing off in dust, a swell of feeling behind his eyes that he cannot soon look away from."),
dict(beats=[8,8],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，一名老卒上前，欲言又止，只悄悄把刀收了回去，不敢出声。",
shot="固定近景，一名老兵上前两步，欲言又止，只悄悄把刀收回去，未敢多言。",
lens="85mm 长焦，极浅景深",cameraPosition="老卒+平视",composition="三分法",eyeline="收起的刀",focus="锁定欲言的手",stability="stable",
h3="Anchored to Picture 7, a close-up sees an old soldier step forward, hesitate, then quietly sheath his blade and say nothing at all."),
]),
dict(sceneIndex=2,blocking="关羽居中抚刀，老卒立于其后，两人垂首相对，画面沉静。",
soundscape="刀柄被摩挲的低响，风声低鸣，同伴压抑的呼吸。",
music="低弦牵出旧忆，情绪渐沉。",
h3_sound="The haft is turned slowly under touch, wind hums low, and men's breaths stay carefully held.",
h3_music="A low string draws out an old memory, the mood sinking.",
cuts=[
dict(beats=[9,9],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽伸手抚了抚掌中的刀柄，那上头还留着握久了的一层温痕，迟迟没再动。",
shot="固定近景，绿袍将领伸手抚过掌中刀柄，上头还留着握久的一层温痕，迟迟没有动作。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="掌中刀柄",focus="锁定抚刀的手",stability="stable",
h3="Anchored to Picture 8, a close-up sees the general run a hand along the haft where the warmth of long holding still lingers, unmoving for a while."),
dict(beats=[10,10],seconds=3.0,size="close",camera="Push In",chars=["C02"],
frame="特写，他低头看着那把刀，忽然想起当年在许都相处的种种，心头一阵发紧。",
shot="镜头 Push In 缓推向垂首的将领，他望着掌中长刀，忆起当年许都共处的种种，心头一阵发紧。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="掌中长刀",focus="锁定关羽眉眼",stability="stable",
h3="Anchored to Picture 9, a slow push in holds the general as he looks down at the blade, the days at Xudu crowding back and a tightness closing around his chest."),
dict(beats=[11,11],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，关羽缓缓把刀横回胸前，像在掂量与旧恩相比，军令究竟要舍下哪一头。",
shot="固定中景，绿袍将领缓缓把长刀横回胸前，像在掂量与旧恩相比，这条军令该舍下哪一头。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视侧面",composition="中心构图",eyeline="横回胸前的刀",focus="锁定横刀的举动",stability="stable",
h3="Anchored to Picture 10, a medium shot sees the general ease the blade back across his chest, weighing old kindness against the order he would have to set aside."),
dict(beats=[12,12],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，他比谁都明白，这一刀放下去，回到营中要担的是怎样的军令之重。",
shot="固定近景，绿袍将领心里明白，这一刀放下去，回到营中要担起的是怎样一座军令的大山。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="前方方向",focus="锁定关羽神思",stability="stable",
h3="Anchored to Picture 11, a close-up sees how fully the general knows the weight of the order he would shoulder by letting the blade fall."),
]),
dict(sceneIndex=2,blocking="关羽居中垂目，身后士卒低声进言，他望一眼前方，画面居于道中。",
soundscape="士卒低声进言的细语，关羽一声极淡的吐息，风声缓缓。",
music="低弦一顿，接一句定音。",
h3_sound="A low counsel murmurs from the men behind, the general lets out one barely-there breath, and the wind eases.",
h3_music="The low string checks, then lands a single resolving note.",
cuts=[
dict(beats=[13,13],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽缓缓吐出一口长气，眼底那层挣扎反而褪尽，透出更亮的一分清明。",
shot="固定近景，绿袍将领缓缓吐出一口长气，眼底的挣扎反而褪尽，透出更清亮的一分决然。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="前方方向",focus="锁定关羽双目",stability="stable",
h3="Anchored to Picture 12, a close-up sees the general let out one long breath, the struggle slipping away to leave a clear, steady light in his eyes."),
dict(beats=[14,14],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，身后有士卒低声劝他，说曹操已乱，此刻追上去要捉他还来得及。",
shot="固定中景，几名士卒低声建言，说那人正乱，此刻追上去捉他还来得及，绿袍将领垂目未答。",
lens="50mm 标准，中浅景深",cameraPosition="士卒+平视",composition="三分法",eyeline="关羽方向",focus="锁定进言的士卒",stability="stable",
h3="Anchored to Picture 13, a medium shot sees soldiers urge him low that the warlord is in disarray and could still be taken now, the general offering no reply."),
dict(beats=[15,15],seconds=2.9,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽没有立刻答话，只回首望了望那道远去的尘烟，才淡淡开口。",
shot="固定近景，绿袍将领没有立刻接话，只望了望那道远去的尘烟，才淡淡开口",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="远去的尘烟",focus="锁定关羽眉目",stability="stable",
h3="Anchored to Picture 14, a close-up sees the general decline to answer at once, glancing toward the fading dust before stating his reasons plainly, <d>[Chinese] 我放他，自有我放他的道理。</d>"),
dict(beats=[16,16],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，他整了整铠甲，翻身上马，把青龙刀往肩上一横，策马朝营地方向行去。",
shot="固定全景，绿袍将领整了整铠甲，翻身上马，把长刀往肩上一横，策马朝营地方向行去。",
lens="28mm 广角，全景深",cameraPosition="关羽+平视",composition="三分法",eyeline="营地方向",focus="锁定返营的身影",stability="stable",
h3="Anchored to Picture 15, a wide shot sees the general straighten his armor, mount, set the blade back over his shoulder, and ride steadily toward camp."),
]),
dict(sceneIndex=2,blocking="关羽策马返营居中，转过石坳回首一望，老卒随行于其后。",
soundscape="马蹄轻踏山石，关羽回望时的缰绳低响，风声一片。",
music="低弦回环，情义两难。",
h3_sound="Hooves pick over the rocks, a rein creaks as the general glances back, and wind fills the whole gorge.",
h3_music="A low string winds and returns, caught between duty and debt.",
cuts=[
dict(beats=[17,17],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，转过一处石坳时，关羽还是勒马停了一停，回望了一眼空无一人的道口。",
shot="固定中景，转过一处石坳时，绿袍将领还是勒马停了一停，回望一眼空无一人的道口。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视侧面",composition="三分法",eyeline="空了的道口",focus="锁定勒马回望的身影",stability="stable",
h3="Anchored to Picture 16, a medium shot sees the general rein in past the rocks and glance back once at the now-empty mouth of the road."),
dict(beats=[18,18],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，有随行的老卒低声追问，将军既奉军令守山，为何又放了恩人过去。",
shot="固定近景，一名随行的老兵低声追问，既奉军令守山，为何又亲手放恩人过去，绿袍将领垂目未答。",
lens="85mm 长焦，极浅景深",cameraPosition="老卒+平视",composition="三分法",eyeline="关羽方向",focus="锁定追问的老卒",stability="stable",
h3="Anchored to Picture 17, a close-up sees a following old soldier ask low how the general, ordered to hold the pass, could have let his debtor go."),
dict(beats=[19,19],seconds=2.9,size="close",camera="Push In",chars=["C02"],
frame="特写，关羽没有正面答话，只望着前方暮色里的山道，声音压得又低又沉。",
shot="镜头 Push In 缓推向低语的将领，他望着暮色里的山道，把话说得又低又沉",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="暮色山道",focus="锁定关羽双目",stability="stable",
h3="Anchored to Picture 18, a slow push in nears the general as he keeps his eyes on the dimming road ahead and answers low and grave, <d>[Chinese] 曹操不该死在今日这座山下。</d>"),
dict(beats=[20,20],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，他说完这句便不再开口，只催马向前，把那一声叹息远远留在身后。",
shot="固定全景，绿袍将领说完这句便不再开口，只催马向前，把那一声叹息远远留在身后。",
lens="28mm 广角，全景深",cameraPosition="关羽+后侧",composition="三分法",eyeline="前方山道",focus="锁定催马的身影",stability="stable",
h3="Anchored to Picture 19, a wide shot sees the general speak no more, only urge his horse on and leave the trailing sigh behind him on the road."),
]),
dict(sceneIndex=2,blocking="关羽策马缓行居中，道尽尘烟散尽，画面由动转静。",
soundscape="马蹄踏过湿泥的轻响，风穿过空谷的呜咽，一声隐约的叹息。",
music="一记孤弦，满道怅然。",
h3_sound="Hooves press lightly through the wet clay, wind hums through the empty valley, and a faint, far-seeming sigh carries on the air.",
h3_music="One lone string, the whole road steeped in rue.",
cuts=[
dict(beats=[21,21],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，关羽没有答话，只把刀往肩上一抬，缓步向前，把刚才那话轻轻揭过。",
shot="固定中景，绿袍将领没有接话，只把长刀往肩上一抬，缓步向前，把方才那话轻轻揭过。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视",composition="三分法",eyeline="前方山道",focus="锁定抬刀的身影",stability="stable",
h3="Anchored to Picture 20, a medium shot sees the general answer nothing, only lift the blade to his shoulder and ride on, letting the matter drop."),
dict(beats=[22,22],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，山道尽头的尘烟散尽，华容道上只余马蹄踏过的湿泥，和风吹不散的一痕轻叹。",
shot="固定全景，山道尽头的尘烟散尽，华容道上只余马蹄踏过的湿泥，和一道被风吹不散的叹息。",
lens="28mm 广角，全景深",cameraPosition="山道+平视全景",composition="三分法",eyeline="散尽的烟尘",focus="锁定留痕的湿泥",stability="stable",
h3="Anchored to Picture 21, a wide shot sees the dust at the road's end settle, leaving only the mud hoofprints and a sigh the wind cannot blow away."),
dict(beats=[23,23],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，关羽一路行去，转过矮山头时忽然勒马顿了一顿，回头望那空了的道口又看了一眼。",
shot="固定近景，绿袍将领行过矮山头时忽然勒马一顿，回头冲那道口的空处又看了一眼。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视侧面",composition="中心构图",eyeline="空了的道口",focus="锁定回望的神情",stability="stable",
h3="Anchored to Picture 22, a close-up sees the general, past the low spur, check his horse and turn once more toward the emptied road."),
dict(beats=[24,24],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，他握着缰绳的手微微收拢，像是把那句到了嘴边的话又咽了回去。",
shot="固定近景，绿袍将领攥缰的手微微收拢，像把一句到嘴边的话又咽了回去。",
lens="85mm 长焦，极浅景深",cameraPosition="关羽+平视正面",composition="中心构图",eyeline="回落的目光",focus="锁定收拢的手",stability="stable",
h3="Anchored to Picture 23, a close-up sees the general's rein-hand tighten gently, as if swallowing back a word that had risen to his lips."),
]),
dict(sceneIndex=2,blocking="关羽策马行于道中，身后老卒随行，暮色渐合。",
soundscape="马蹄声渐远，风掠过空谷的呜咽，老卒压抑的呼吸。",
music="低弦收束，渐归于夜。",
h3_sound="Hoofbeats recede, wind moans through the empty valley, and the old soldier keeps his breath low.",
h3_music="Low strings draw in and settle toward the night.",
cuts=[
dict(beats=[25,25],seconds=3.0,size="medium",camera="Static Shot",chars=["C02"],
frame="中景，他抬眼望了望暮色里那条空荡荡的山道，良久，才缓缓收回目光。",
shot="固定中景，绿袍将领抬眼望了望暮色里那条空荡的山道，良久，才缓缓收回目光。",
lens="50mm 标准，中浅景深",cameraPosition="关羽+平视侧面",composition="三分法",eyeline="暮色山道",focus="锁定抬眼的身影",stability="stable",
h3="Anchored to Picture 24, a medium shot sees the general lift his eyes over the empty road in the dusk, holding the look a long while before turning away."),
dict(beats=[26,26],seconds=3.0,size="close",camera="Static Shot",chars=["C02"],
frame="特写，身后的老卒都望着他，等他说句什么，他却终究没有开口。",
shot="固定近景，身后的老兵们都望着他，等他一句交代，他却终究没有开口。",
lens="85mm 长焦，极浅景深",cameraPosition="老卒+平视",composition="中心构图",eyeline="关羽背影",focus="锁定等候的目光",stability="stable",
h3="Anchored to Picture 25, a close-up sees the old soldiers watching him, waiting for a word that never finally comes."),
dict(beats=[27,27],seconds=3.0,size="wide",camera="Static Shot",chars=["C02"],
frame="全景，风吹过那道空谷，呜呜作响，像替他长长地叹了一口气。",
shot="固定全景，风穿过那道空谷呜呜作响，像替他长长地叹了一口气，卷向远处。",
lens="28mm 广角，全景深",cameraPosition="空谷+平视",composition="三分法",eyeline="穿谷的风",focus="锁定空荡的谷道",stability="stable",
h3="Anchored to Picture 26, a wide shot sees the wind sweep the empty valley and moan on and on, as though to sigh out a long breath in his stead."),
dict(beats=[28,28],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=["C02"],
frame="大远景，他这才收回头，纵马直行，渐行渐远，身后那道山影笼进沉沉暮色里。",
shot="固定大远景，绿袍将领这才收回目光，纵马直行、渐行渐远，身后那道山影笼进沉沉暮色。",
lens="24mm 超广角，全景深",cameraPosition="山道+平视远景",composition="对称",eyeline="远去的背影",focus="锁定渐远的身影",stability="stable",
h3="Anchored to Picture 27, an extreme wide shot sees the general finally look away and ride on, growing small in the distance as the mountain shadow folds into the dusk."),
]),
]