# -*- coding: utf-8 -*-
# ep46 草船借箭  场景1 beats 1-38 C05,C13 ; 场景2 beats 1-21 C05,C13,C12
# chars: C05 孔明 C13 鲁肃 C12 周瑜
C05="a refined scholar in a feathered white cloak holding a feather fan"
C13="a plain-faced advisor with a stubble beard in a scholar robe"
C12="a handsome young commander in silk battle robes and light armor"

EP=46
SEG=[
dict(sceneIndex=1,blocking="帅帐内，鲁肃立于画面右侧、孔明居左，二人相距半臂、面朝相对，暖烛自一侧打在脸上。",
soundscape="夜风掠过帐幔，帐外江水隐约拍岸，偶有士卒低语。",
music="古筝柔板低诉。",
h3_sound="A night wind rattles the canvas drapes, the Yangtze laps faintly at the bank outside, and low murmurs drift from distant guards.",
h3_music="A quiet guzheng in slow, sparse arpeggios, restrained and unhurried.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，孔明面如冠玉、头戴纶巾身披鹤氅，帅帐暖烛光里拱手一笑，眉目清朗，夜雾从帐口漫入。",
shot="固定特写，一名握羽扇的清俊儒生拱手颔首，自端坐微微前倾，笑意在烛光下漫开。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定孔明面部",stability="stable",
h3="Anchored to Picture 1, a static close-up holds a refined scholar in a feathered cloak who slowly folds his hands in a salute and lets a calm smile spread, warm lamp-light steady on his brow."),
dict(beats=[2,2],seconds=2.5,size="medium",camera="Static Shot",chars=["C13"],
frame="中景，颔下蓄须、眉目宽和的鲁肃一把拽住孔明手臂探身前倾，眉头紧锁，暖烛照见满眼急切。",
shot="固定中景，一名蓄须士人拽住同伴的手臂往前倾身，从并肩凑成耳语，眉眼间满是焦急。",
lens="50mm 标准，中浅景深",cameraPosition="鲁肃+平视正面",composition="三分法",eyeline="对方脸庞",focus="锁定鲁肃上半身",stability="stable",
h3="Anchored to Picture 2, a static medium shot frames the plain-faced advisor gripping his companion's sleeve and leaning in to whisper, urgent worry new to his brow."),
dict(beats=[3,3],seconds=4.2,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃压低声急问，眉目宽和却满眼焦急，烛火在脸上轻轻晃动，帐影沉沉。",
shot="固定近景，一名蓄须士人压低嗓门急切开口，眉头越皱越紧，语速急促。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定鲁肃唇与目",stability="stable",
h3="Anchored to Picture 3, a static close-up shows the worried advisor demanding in a breathless, hunted tone, <d>[Chinese] 你这一口气吹出来，三日怎么造十万支箭？</d>, the words tumbling quickly from him."),
]),
dict(sceneIndex=1,blocking="鲁肃居右、孔明居左，本段开场以孔明抬手的动作为重心，二人在岸畔并列，面向江岸草船。",
soundscape="江风渐起，岸上兵卒抬草把的脚步声与低喊，草把堆叠的窸窣。",
music="筚篥长音一段，转弱。",
h3_sound="The river wind picks up, dockside soldiers heave straw bundles onto the boats with grunts, and wet thatch rasps as it is stacked.",
h3_music="A reedy xiao flute draws one long note that softens into the hush of the river.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明不慌，抬手轻拍鲁肃肩头，鹤氅在江风里微扬，天边晨光初透。",
shot="固定中景，一名执扇儒生不慌不忙抬起手，轻轻落在同伴肩头，袍角被江风掀起一角。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视正面",composition="三分法",eyeline="对方肩头",focus="锁定落下的手",stability="stable",
h3="Anchored to Picture 4, a static medium shot follows the calm scholar lifting a hand to rest it on his companion's shoulder, one sleeve stirred by the wind."),
dict(beats=[5,5],seconds=3.8,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明含笑开口，江风拂动纶巾，眼底掠过一丝笃定的光，晨雾在背后浮沉。",
shot="镜头 Push In 缓推向开口的儒生脸庞，说话时眉目舒展、语速平平却字字笃定。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="前方江面",focus="锁定孔明面部",stability="stable",
h3="Anchored to Picture 5, a slow push in tightens on the scholar as he answers in an unhurried, assured voice, <d>[Chinese] 公瑾借的是箭，我借的是天时与王孙。</d>, his gaze drifting to the river."),
dict(beats=[6,6],seconds=3.0,size="wide",camera="Pan Left",chars=["C05"],
frame="全景，次日清晨，孔明立于船头命人打起草把，二十只空船沿江一字排开，草把立在船身两侧。",
shot="镜头 Pan Left 摇过江岸，一名挥扇的儒生立于船头下令，兵卒在两侧打起一捆捆草把，船队顺着滩岸铺开。",
lens="35mm 广角，全景深",cameraPosition="孔明+俯视 20°",composition="三分法",eyeline="前方船队",focus="锁定船身草把排",stability="slight-shake",
h3="Anchored to Picture 6, the camera pans left across the row of empty boats as the scholar on the lead bow directs soldiers to lash thick straw bales along the hulls, the long line of craft stretching along the bank."),
]),
dict(sceneIndex=1,blocking="船上：鲁肃居右、孔明居左，二人隔一臂对坐船身一侧，鲁肃面朝孔明、孔明面带浅笑指点草把。",
soundscape="木桨轻轻点水，草把窸窣，鲁肃急切絮语与孔明平静应答。",
music="扬琴脆音数记，作问答节拍。",
h3_sound="Oars dip softly into the water, straw rustles, and the advisor frets while the scholar answers evenly.",
h3_music="A crisp yangqin strikes a few bright notes, pacing the back-and-forth.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C13"],
frame="全景，鲁肃被孔明拉上船，一个劲儿劝，孔明只让他坐好看着，船身轻晃离岸。",
shot="跟拍镜头随上船的士人落座，一名执扇儒生一边把他按坐在船板一边摆手示意莫急，船身轻轻晃着离岸。",
lens="35mm 广角，全景深",cameraPosition="鲁肃+平视侧面",composition="三分法",eyeline="对方面部",focus="锁定鲁肃落座",stability="slight-shake",
h3="Anchored to Picture 7, a tracking shot steadies on the advisor being seated on the deck while the scholar waves off his protests, the hull easing out into the current."),
dict(beats=[8,8],seconds=3.0,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃闻言一噎，又替他急，说船这般空凭什么让曹军放箭，脸上写满不解。",
shot="固定近景，一名蓄须士人满心不解，话堵在嗓子又急切追上，眼巴巴望着空荡荡的船身。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+平视正面",composition="中心构图",eyeline="对方脸庞",focus="锁定鲁肃神情",stability="stable",
h3="Anchored to Picture 8, a static close-up holds the puzzled advisor who swallows his words, then blurts with fresh worry while eyeing the bare hull of the boat."),
dict(beats=[9,9],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明只笑了笑，抬手指向船侧那一排齐齐整整的草把，晨雾在身后漫涌。",
shot="固定中景，执扇的儒生只微微一笑，抬手指向船侧整整齐齐一排草把，神色自若。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视正面",composition="三分法",eyeline="草把方向",focus="锁定指尖所指",stability="stable",
h3="Anchored to Picture 9, in a static medium shot the calm scholar answers with only a small smile, lifting a hand to point at the even row of straw bales along the hull."),
dict(beats=[10,10],seconds=3.8,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明一面捻动草把边缘一面不急不慢开口，晨光在指间镀上薄金。",
shot="镜头 Push In 缓推向捻着草把指节的一张脸，开口时从容不迫，语速平缓。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="手中草把",focus="锁定孔明面部",stability="stable",
h3="Anchored to Picture 10, a slow push in nears the scholar as he twirls a straw edge and states unhurriedly, <d>[Chinese] 箭要往哪儿落，我早给它备好了靶子。</d>, dawn glinting on his fingers."),
]),
dict(sceneIndex=1,blocking="孔明立于船头居左、鲁肃攀住船舷居右，雾从江面卷来，二人面向前方水面。",
soundscape="船身破水的哗哗声，鲁肃探身时衣袖摩擦，雾里远处水面空寂。",
music="低音弦乐铺底，渐起。",
h3_sound="The hull hisses through water, fabric rustles as the advisor leans out, and beyond hangs the empty hush of fog.",
h3_music="Low strings swell beneath, rising slowly with the mist.",
cuts=[
dict(beats=[11,11],seconds=3.0,size="medium",camera="Pan Right",chars=["C13"],
frame="中景，鲁肃将信将疑，抱着船板探身朝雾里张望，白茫茫一片什么也看不见。",
shot="镜头 Pan Right 随探身的士人移向雾里，他攀着船舷努力朝前望，浓雾却吞尽视线。",
lens="50mm 标准，中浅景深",cameraPosition="鲁肃+侧后 30°",composition="三分法",eyeline="前方雾中",focus="锁定鲁肃侧脸",stability="slight-shake",
h3="Anchored to Picture 11, the camera pans right with the advisor leaning over the gunwale into the fog, peering ahead where only pale murk meets his eye."),
dict(beats=[12,12],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明立在船头，侧耳听那水声由缓转急，羽扇轻握，了然于心。",
shot="固定中景，一名执扇儒生立于船头，微微眯眼去听水面，从凝神到轻轻颔首。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视侧面",composition="三分法",eyeline="前方水面",focus="锁定孔明神态",stability="stable",
h3="Anchored to Picture 12, a static medium shot shows the fan-holding scholar standing at the prow, eyes narrowing as he listens to the quickening water, then nodding to himself."),
dict(beats=[13,13],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，江上渐起大雾，天光尽掩，几丈之外便看不清船影，二十条船隐没白茫之中。",
shot="固定大远景，浓雾自江面漫开，天色尽掩，船影在白茫里若隐若现。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="纵深江面",focus="锁定雾中船影",stability="stable",
h3="Anchored to Picture 13, a static extreme-wide shot watches dense fog roll over the river until day is swallowed and the boats dissolve halfway into the white."),
dict(beats=[14,14],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C05"],
frame="全景，孔明命众船绳索相连、一字排开，缓缓摇向曹营水寨方向，雾中一片肃然。",
shot="跟拍镜头沿船头一线滑过，执扇的儒生命人排开绳索，船队缓缓转向雾中的水寨方向。",
lens="35mm 广角，全景深",cameraPosition="孔明+俯视 20°",composition="三分法",eyeline="摇往方向",focus="锁定船头转向",stability="slight-shake",
h3="Anchored to Picture 14, a tracking shot glides along the prow line as the scholar orders the boats lashed into a single row and swung slowly toward the misty enemy encampment."),
dict(beats=[15,15],seconds=3.0,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃拉住孔明衣角，说这要是被曹军看破一条船也回不去，声音发紧。",
shot="固定近景，一名士人悄悄拽住同伴衣角，压低嗓门担忧，眉眼绷得紧紧的。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+平视正面",composition="中心构图",eyeline="对方脸庞",focus="锁定鲁肃眉眼",stability="stable",
h3="Anchored to Picture 15, a static close-up frames the advisor nervously tugging his companion's sleeve and warning in a tight voice that if the enemy sees through them not one boat will turn back."),
]),
dict(sceneIndex=1,blocking="孔明居左立于船头、鲁肃居右扶着船舷，二人面向夜幕江面，大雾围拢。",
soundscape="江涛声渐涌，鲁肃低声絮问，孔明平静应答，木桨节奏安稳。",
music="洞箫长音一段，渺远。",
h3_sound="The river swell rises, the advisor murmurs low questions, and the scholar answers with quiet composure over steady oars.",
h3_music="A distant xiao weaves one long, far-off phrase above the water.",
cuts=[
dict(beats=[16,16],seconds=4.2,size="close",camera="Static Shot",chars=["C05"],
frame="特写，孔明负手望向雾里，沉声说得笃定，面色平静，雾从他肩侧流过。",
shot="固定近景，执扇的儒生负手望向雾里，答得分外笃定，面上不见半分犹疑。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="前方雾中",focus="锁定孔明双目",stability="stable",
h3="Anchored to Picture 16, a static close-up holds the scholar gazing into the fog as he states with absolute certainty, <d>[Chinese] 雾这么大，曹军分不清虚实，只会乱放箭。</d>"),
dict(beats=[17,17],seconds=3.0,size="medium",camera="Static Shot",chars=["C13"],
frame="中景，鲁肃这才稍稍定心，又低声问这雾究竟是借来的还是等来的，微一探身。",
shot="固定中景，一名士人刚放下心事又低声问起雾的来处，稍稍探身好奇相询。",
lens="50mm 标准，中浅景深",cameraPosition="鲁肃+平视正面",composition="三分法",eyeline="对方脸庞",focus="锁定鲁肃面部",stability="stable",
h3="Anchored to Picture 17, a static medium shot shows the advisor slumping with relief, then leaning in to ask in a low voice whether this fog was borrowed or merely awaited."),
dict(beats=[18,18],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，孔明没有正面答，只微微一笑说等一个天时便可知晓，眼中藏着谜底。",
shot="固定近景，执扇的儒生避而不答，只牵起一丝微笑，说等一个天时便见分晓。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="前方江面",focus="锁定孔明笑意",stability="stable",
h3="Anchored to Picture 18, a static close-up catches the scholar sidestepping the question with a faint smile, murmuring that they need only wait for a certain hour."),
dict(beats=[19,19],seconds=2.2,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明立于船头负手而立，短句沉稳，前方夜幕里已现岸影。",
shot="固定中景，负手而立的儒生立在船头，短短一句稳住身边人，目光落向前方夜色。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视侧面",composition="三分法",eyeline="前方夜幕",focus="锁定孔明侧影",stability="stable",
h3="Anchored to Picture 19, in a static medium shot the standing scholar gives a short, steadying command, <d>[Chinese] 坐稳，前方便是曹营。</d>, eyes fixed on the dark ahead."),
]),
# -------- 曹营鼓声线（无对白，%多环境）--------
dict(sceneIndex=1,blocking="空船入夜推进，画面以鼓声与桨影为主，孔明立于船头为画面重心。",
soundscape="战鼓连擂震响，木桨齐齐破水，呐喊声自船队腾起。",
music="战鼓与众声齐发，节奏渐紧。",
h3_sound="War drums pound in unison, oars splash in a tight rhythm, and shouts rise from the fleet into the night.",
h3_music="Battle drums and rising horns lock into a quickening march.",
cuts=[
dict(beats=[20,20],seconds=3.0,size="wide",camera="Pan Left",chars=["C05"],
frame="全景，夜色渐深雾愈浓，孔明让各船擂起战鼓、齐声呐喊，火烛在船头跳跃。",
shot="镜头 Pan Left 扫过整列船队，执扇的儒生抬手令下，鼓手挥臂擂鼓，呐喊声浪在雾里铺开。",
lens="35mm 广角，全景深",cameraPosition="孔明+俯视 20°",composition="三分法",eyeline="船队方向",focus="锁定鼓手动作",stability="slight-shake",
h3="Anchored to Picture 20, the camera pans left down the line of boats as the scholar signals and drummers swing into a heavy beat, war shouts spreading through the mist."),
dict(beats=[21,21],seconds=3.0,size="wide",camera="Tracking Shot",chars=["C05"],
frame="全景，战鼓擂得震天响，木桨齐齐划开水面，二十条船跟着鼓点缓缓推进。",
shot="跟拍镜头在船队侧面随行，鼓声震响，成排的木桨整齐破水，船队踏着节拍推向前方。",
lens="35mm 广角，全景深",cameraPosition="孔明+侧随行",composition="三分法",eyeline="推进方向",focus="锁定整齐桨列",stability="slight-shake",
h3="Anchored to Picture 21, a tracking shot keeps pace off the flank as the drums thunder, a ranked sweep of oars cutting the water, the twenty craft advancing on the beat."),
dict(beats=[22,22],seconds=3.0,size="extreme-wide",camera="Static Shot",chars=[],
frame="大远景，雾里分不清虚实，那鼓声在雾里荡开，听在耳里倒像有千军万马掩杀过来。",
shot="固定大远景，浓雾裹住整片江面，鼓声在雾里回荡，仿佛千军正从白茫中压来。",
lens="24mm 超广角，全景深",cameraPosition="江面+平视远景",composition="对称",eyeline="雾中纵深",focus="锁定雾与鼓声起处",stability="stable",
h3="Anchored to Picture 22, a static extreme-wide shot lets the fog swallow the river while drumbeats echo through the murk as though a whole army were bearing down."),
]),
# ------- 对岸曹营反应线 -------
dict(sceneIndex=1,blocking="画面转对岸曹营水寨，空镜为主，偶见灯火，人物少入画。",
soundscape="鼓声喊声渡江而来，岗哨惊动、甲胄细响，营内压低的议论。",
music="鼓声隔江减弱，弦乐悬而未落。",
h3_sound="Drumbeats and war cries drift across the water, a sentry rustles awake, and armored men shift uneasily behind the camp fires.",
h3_music="The drumbeat fades across the river while a tense string line hangs unresolved.",
cuts=[
dict(beats=[23,23],seconds=3.0,size="wide",camera="Static Shot",chars=[],
frame="全景，鼓声喊声顺着江面传过去，对岸曹营的岗哨被惊动，火把在雾里摇晃。",
shot="固定全景，对岸水寨的灯火在雾里探头，守卒慌乱举火张望，鼓声自江上涌来。",
lens="35mm 广角，全景深",cameraPosition="岸寨+平视远景",composition="三分法",eyeline="江面鼓声来处",focus="锁定晃动的火把",stability="stable",
h3="Anchored to Picture 23, a static wide shot of the distant enemy camp shows torches swaying as sentries start awake, the drumbeat rolling across the water toward them."),
dict(beats=[24,24],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，曹营水寨不明虚实，哪里敢亮灯出战，只报说黑夜浓雾不敢擅动。",
shot="固定中景，营寨帐口一名守将抬手喝止灯火，冲着雾里只报不敢出战，夜色浓重。",
lens="50mm 标准，中浅景深",cameraPosition="营寨帐口+平视",composition="三分法",eyeline="雾中江面",focus="锁定守将手势",stability="stable",
h3="Anchored to Picture 24, a static medium shot sees an enemy officer waving the camp back from the lamps, refusing to sally through the black fog and its hidden sounds."),
dict(beats=[25,25],seconds=3.0,size="close",camera="Static Shot",chars=[],
frame="特写，曹营内灯火未动，却隐隐传出整队甲胄的响动，一双攥枪的手在暗里收紧。",
shot="固定近景，暗里一排兵卒静静按枪而立，甲叶在紧张里细响，火光未动。",
lens="85mm 长焦，极浅景深",cameraPosition="兵卒队列+平视",composition="中心构图",eyeline="前方雾中",focus="锁定攥枪的手",stability="stable",
h3="Anchored to Picture 25, a static close-up rests on a rank of unmoving spearmen in the dark, mail faintly clinking, the lamps held dead, tension coiling in the hush."),
dict(beats=[26,26],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，有人献策以火船试探，被曹操一句雾重难辨回绝了下去，灯火下的身影。",
shot="固定中景，艳烛帐内一名上将抬手压下献策的人，只一句雾重难辨，众人退下。",
lens="50mm 标准，中浅景深",cameraPosition="中军帐+平视",composition="三分法",eyeline="献策之人",focus="锁定摆手的身影",stability="stable",
h3="Anchored to Picture 26, a static medium shot shows the camp's lord waving off a proposal to probe with fire-boats, dismissing it with a curt word about the heavy fog."),
]),
# ------- 放箭 -------
dict(sceneIndex=1,blocking="曹操身形虚化于暗处，以弓弩与雾中箭雨为画面主体，孔明线在船头穿插。",
soundscape="弓弦张紧的吱呀声，乱箭破空的嗖嗖声，箭钉草把时的笃笃声。",
music="鼓声骤紧，进入放箭的高潮。",
h3_sound="Bowstrings creak as they are drawn, arrows hiss through the air in volleys, and shafts thud home into the straw.",
h3_music="The drums tighten sharply, driving into the climax of the volley.",
cuts=[
dict(beats=[27,27],seconds=3.0,size="medium",camera="Static Shot",chars=[],
frame="中景，曹操在中军坐下，咬着牙摆下话来传令各营听号放箭，灯火映着他阴沉侧脸。",
shot="固定中景，端坐上位的枭雄咬着牙兜底令下，各营听号放箭，火把把他半边脸映得阴沉。",
lens="50mm 标准，中浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="下方将官",focus="锁定曹操侧脸",stability="stable",
h3="Anchored to Picture 27, a static medium shot shows the grim lord seated in command as he grits out the order to loose arrows on signal, lamplight sharp on his hard profile."),
dict(beats=[28,28],seconds=3.0,size="wide",camera="Pan Right",chars=[],
frame="全景，话音一落曹营弓弩便齐齐对准那片雾气翻涌的江面，一排弓手满弓待发。",
shot="镜头 Pan Right 扫过一排满弓待发的弓手，箭簇齐指雾里，弦音响成一片。",
lens="35mm 广角，全景深",cameraPosition="弓手队列+平视",composition="三分法",eyeline="雾中江面",focus="锁定拉满的弓弦",stability="slight-shake",
h3="Anchored to Picture 28, the camera pans right along a ranked line of archers drawing their bows to full, every shaft leveled into the churning fog."),
dict(beats=[29,29],seconds=3.0,size="close",camera="Static Shot",chars=[],
frame="特写，曹操沉吟片刻命众军乱箭齐射，射向雾中鼓声响动之处，手指向前方。",
shot="固定近景，枭雄沉声示意，抬手点向雾里鼓声起处，众军应令。",
lens="85mm 长焦，极浅景深",cameraPosition="曹操+平视正面",composition="中心构图",eyeline="手指方向",focus="锁定曹操手势",stability="stable",
h3="Anchored to Picture 29, a static close-up catches the lord's cold command as his hand points into the fog where the drums sound, a single word loosing the storm."),
]),
# ------- 箭雨 -------
dict(sceneIndex=1,blocking="孔明立于船头居中，鲁肃在舱板下，箭雨自画面上方砸向船舷草把。",
soundscape="箭雨破空的密集嗖响，箭簇钉进草把的笃笃声，船身受震。",
music="鼓与弦交织，节奏密而不乱。",
h3_sound="A thick volley of arrows hisses down, shafts thudding into the straw bales, the hull shuddering under the onslaught.",
h3_music="Drums and strings interweave, dense but steady.",
cuts=[
dict(beats=[30,30],seconds=3.0,size="wide",camera="Static Shot",chars=["C05"],
frame="全景，弓弦一响，铺天盖地的箭雨朝草船攒射而下，笃笃钉进草把，箭羽翻飞。",
shot="固定全景，漫天箭雨迎着船头泼来，一支支笃笃钉进船舷草把，箭羽在雾里翻飞。",
lens="35mm 广角，全景深",cameraPosition="孔明+俯视 20°",composition="三分法",eyeline="箭雨方向",focus="锁定钉入草把的箭",stability="slight-shake",
h3="Anchored to Picture 30, a static wide shot sees cascades of arrows pour down on the straw boats, shafts biting into the thatch in thick, rattling bursts."),
dict(beats=[31,31],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，一支箭擦着孔明的发冠掠过，他纹丝不动，只把目光落在草把的方向上。",
shot="固定近景，一支箭贴着一名儒生的发冠飞过，他眼都不眨，目光稳稳落向船舷草把。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="草把方向",focus="锁定孔明双目",stability="stable",
h3="Anchored to Picture 31, a static close-up lets an arrow streak past the scholar's cap as he stands utterly still, gaze resting on the straw where the shafts are landing."),
dict(beats=[32,32],seconds=3.0,size="extreme-close",camera="Static Shot",chars=[],
frame="大特写，草把上的箭越插越密，船侧木板笃笃作响，像落了一场急雨，金属磨过草梗。",
shot="固定大特写，一支支箭钉进湿草把，弓干轻颤，草梗上密密扶着颤动的箭杆。",
lens="100mm 长焦，极浅景深",cameraPosition="草把+平视",composition="对角线",eyeline="逐渐密布的箭",focus="锁定新钉入的箭尖",stability="stable",
h3="Anchored to Picture 32, a static extreme close-up shows arrows bristling ever thicker into the wet straw, quarterstaves quivering, the wood thrumming like hard rain."),
]),
# ------- 继续受箭 -------
dict(sceneIndex=1,blocking="孔明在船头、鲁肃在舱下，箭雨持续，画面以受箭的船与二人反应交替。",
soundscape="箭雨持续钉落的声响，鲁肃压低的惊呼与喘息。",
music="鼓声低且在密处收住，留喘息。",
h3_sound="Arrows keep thudding into the hull, the hidden advisor breathes hard, and the drums hold low to leave a gap for breath.",
h3_music="The drums drop low and pause at the peak, leaving only the hush of the volley.",
cuts=[
dict(beats=[33,33],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明回头对擂鼓的兵卒吩咐，说鼓擂得再响些别叫曹军听出破绽，侧过脸说话。",
shot="固定中景，执扇的儒生侧过头朝鼓手吩咐再擂响些，别让对岸听出破绽，神情从容。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+侧后 30°",composition="三分法",eyeline="鼓手方向",focus="锁定孔明侧脸",stability="stable",
h3="Anchored to Picture 33, a static medium shot has the scholar turning his head to tell the drummer to beat louder so the enemy hears no hesitation, his calm unbroken."),
dict(beats=[34,34],seconds=3.0,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃在舱板下缩着，一边数着箭响一边替孔明捏着把汗，脸颊紧张得发紧。",
shot="固定近景，蜷在舱下的士人一边数着一声声箭响一边咬紧牙关，替他这同伴捏一把冷汗。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+俯视 20°",composition="中心构图",eyeline="上方的船舷",focus="锁定鲁肃眉眼",stability="slight-shake",
h3="Anchored to Picture 34, a static close-up finds the advisor hunched under the deck, counting each shaft and clenching his jaw in shared dread."),
dict(beats=[35,35],seconds=3.0,size="wide",camera="Tilt Up",chars=[],
frame="全景，夜色里曹营的箭雨一轮接一轮，直把雾中的草船射成一片刺猬，箭羽竖起如林。",
shot="镜头 Tilt Up 自船身摇向桅顶，箭雨一轮接一轮钉落，整条草船已密密插成一只刺猬。",
lens="35mm 广角，全景深",cameraPosition="船身+仰视 15°",composition="三分法",eyeline="桅顶箭雨",focus="锁定密集的箭",stability="slight-shake",
h3="Anchored to Picture 35, the camera tilts up the hull to the mast as wave after wave of arrows sinks in, the straw boat bristling into a porcupine of shafts."),
dict(beats=[36,36],seconds=3.0,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明立于船头，任那一声声箭响在耳畔炸开，面上半分不改，雾绕着他。",
shot="镜头 Push In 缓推向船头那张洞明而平静的脸，箭声在耳畔炸响，他却纹丝不动。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="前方雾中",focus="锁定孔明双目",stability="stable",
h3="Anchored to Picture 36, a slow push in nears the scholar standing calm at the prow, arrows bursting around him in the fog while his face shows nothing at all."),
]),
# ------- 谢箭 -------
dict(sceneIndex=1,blocking="孔明在船头、鲁肃缩于舱下，箭雨渐歇，画面归静。",
soundscape="箭雨收住，江水再一次涌上船舷，鲁肃闷在舱下的喘息。",
music="鼓弦俱歇，只余一记余音。",
h3_sound="The arrows fall still, the river laps once more at the hull, and a weary breath escapes the man beneath the deck.",
h3_music="Drums and strings fall silent, leaving a single fading note.",
cuts=[
dict(beats=[37,37],seconds=2.7,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明遥对雾那头一揖，开口道谢，鹤氅在风里轻扬，神态从容。",
shot="固定中景，执扇的儒生朝雾那头遥遥一揖，从容开口，语气里带着几分从容的客气。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="雾那头的方向",focus="锁定孔明拱手",stability="stable",
h3="Anchored to Picture 37, a static medium shot shows the scholar bowing toward the mist in parting courtesy as he says, <d>[Chinese] 多谢丞相赠箭，他日再还。</d>"),
dict(beats=[38,38],seconds=3.0,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃躲在舱板下，听得整个人都缩成一团，大气不敢出。",
shot="固定近景，蜷在舱下的士人听见那句道谢，整个身子又缩紧一分，几乎不敢喘气。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+俯视 20°",composition="中心构图",eyeline="头顶舱板",focus="锁定鲁肃神情",stability="slight-shake",
h3="Anchored to Picture 38, a static close-up sees the advisor shrinking further into the hold at those words, scarcely daring to draw breath."),
]),
# ================= 场景2 =================
dict(sceneIndex=2,blocking="晨雾江岸，孔明立于船头、鲁肃自舱板下钻出居后，兵卒在船侧拔箭。",
soundscape="天破晓的水声，兵卒拔箭触碰草把，箭枝落地堆叠。",
music="晨起弦乐一段，清朗。",
h3_sound="Daunt water laps at the hull, soldiers pull shafts from the straw with a rasp, and arrows clink onto a growing pile.",
h3_music="A clear morning string passage, light and bright.",
cuts=[
dict(beats=[1,1],seconds=3.0,size="wide",camera="Pan Left",chars=["C05"],
frame="全景，天将破晓，孔明下令众船掉头，借着顺风满载而归，船队逐一亮出侧影。",
shot="镜头 Pan Left 随船头转向，执扇的儒生挥手下令，二十条船借着顺风一齐掉头回程。",
lens="35mm 广角，全景深",cameraPosition="孔明+俯视 20°",composition="三分法",eyeline="来时的岸",focus="锁定船头转向",stability="slight-shake",
h3="Anchored to Picture 1, the camera pans left as daylight breaks, the scholar signaling the fleet to swing about and run home on the favoring wind, loaded deep."),
dict(beats=[2,2],seconds=3.0,size="close",camera="Static Shot",chars=["C05"],
frame="特写，孔明命人将船头船尾的草把一一收拢，箭头密密麻麻几乎插成一只刺猬，晨光照亮箭杆。",
shot="固定近景，执扇的儒生扫过船舷那只插满箭的草把，抬手示意收拢，晨光亮在箭杆上。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="草把上的箭",focus="锁定密集的箭尾",stability="stable",
h3="Anchored to Picture 2, a static close-up shows the scholar surveying the bristling bales along the hull and signaling them gathered, morning glinting on the shafts."),
dict(beats=[3,3],seconds=3.0,size="extreme-close",camera="Static Shot",chars=[],
frame="大特写，兵卒拔箭时手都发颤，一支一支往地上堆，很快堆成一片小小的箭山。",
shot="固定大特写，一双发颤的手一支支拔出箭杆，码到地上，堆成一小片箭簇的小山。",
lens="100mm 长焦，极浅景深",cameraPosition="兵卒之手+平视",composition="对角线",eyeline="越堆越高",focus="锁定发颤的手",stability="slight-shake",
h3="Anchored to Picture 3, a static extreme close-up watches a trembling hand draw shaft after shaft and stack them until a small hill of arrows rises on the deck."),
]),
dict(sceneIndex=2,blocking="孔明居左走过船边、鲁肃自舱板下钻出居右，晨雾笼罩滩岸。",
soundscape="踱步声，鲁肃拍打身上木屑的轻响，长长舒气，船身轻碰岸。",
music="弦乐转沉稳。",
h3_sound="Footsteps pace along the deck, the advisor brushes wood shavings from his robe and lets out one long sigh as the hull nudges the bank.",
h3_music="The strings turn sonorous and grave.",
cuts=[
dict(beats=[4,4],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明踱到船边看了看箭头，又看了看天色，只说了声收兵靠岸，晨雾散淡。",
shot="固定中景，执扇的儒生踱到船舷看了一眼箭、又抬眼望天，简短吩咐收兵靠岸。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视侧面",composition="三分法",eyeline="天色方向",focus="锁定孔明神态",stability="stable",
h3="Anchored to Picture 4, a static medium shot watches the scholar pace to the gunwale, glance at the arrows then at the sky, and give a quiet order to make for shore."),
dict(beats=[5,5],seconds=3.0,size="close",camera="Static Shot",chars=["C13"],
frame="特写，鲁肃这才从舱板下钻出来，拍着身上的木屑，长长舒了口气，劫后余生。",
shot="固定近景，一名士人从舱板下探出头爬出，拍着衣上木屑长长舒气，满脸余悸。",
lens="85mm 长焦，极浅景深",cameraPosition="鲁肃+平视正面",composition="中心构图",eyeline="前方岸滩",focus="锁定鲁肃神情",stability="stable",
h3="Anchored to Picture 5, a static close-up catches the advisor crawling out from the hold, brushing off shavings and sighing with the relief of one who survived the night."),
dict(beats=[6,6],seconds=3.0,size="wide",camera="Push In",chars=["C12","C05"],
frame="全景，周瑜闻讯赶来，望着二十条草船上累累的雕翎，眉头几不可察地一拧，孔明在侧。",
shot="镜头 Push In 推向船首，一名披轻甲的俊朗青年立在岸边，望着满船雕翎，眉头极轻地一拧。",
lens="35mm 广角，全景深",cameraPosition="周瑜+平视正面",composition="三分法",eyeline="满船箭翎",focus="锁定周瑜眉头",stability="stable",
h3="Anchored to Picture 6, a push in nears the handsome young commander standing on the bank, taking in the arrow-heavy boats with a faint, almost hidden crease of his brow."),
]),
dict(sceneIndex=2,blocking="兵卒报数居中、周瑜立于岸、孔明立于船头，三人三角站位，晨光镀岸。",
soundscape="兵卒如实报数，箭枝轻响，岸上低声咋舌。",
music="配乐极简，留白。",
h3_sound="A soldier counts out the tally, arrows clink, and a murmur of disbelief moves along the shore.",
h3_music="The score thins to near silence, leaving room.",
cuts=[
dict(beats=[7,7],seconds=3.0,size="medium",camera="Static Shot",chars=["C12","C05"],
frame="中景，兵卒实数半晌禀报恰好满十万之数，周瑜只淡淡嗯一声，孔明负手而立。",
shot="固定中景，一名兵卒数罢朗声报出十万之数，披甲的青年只淡淡应了一声，另一名儒生负手静立。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+平视正面",composition="三分法",eyeline="报数兵卒",focus="锁定周瑜神情",stability="stable",
h3="Anchored to Picture 7, a static medium shot hears the soldier count aloud to a clean one hundred thousand while the young commander answers with a flat, measured note."),
dict(beats=[8,8],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜又亲自走到一条草船前，拔下箭在指间转了转，看着箭头做工，眉眼不动。",
shot="固定近景，披轻甲的青年走到草船前拔下一支箭，在指间缓缓转了一圈细看箭头，神情难测。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="手中箭头",focus="锁定指间转动的箭",stability="stable",
h3="Anchored to Picture 8, a static close-up shows the commander pulling one arrow free, turning it slowly in his fingers to study the head, his expression unreadable."),
dict(beats=[9,9],seconds=3.1,size="close",camera="Push In",chars=["C12"],
frame="特写，周瑜开口，语气听不出喜怒，目光在箭与孔明之间掠过，晨光落上眉眼。",
shot="镜头 Push In 缓推向开口的青年，语气听不出喜怒，话里带着客气的凉意。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定周瑜双目",stability="stable",
h3="Anchored to Picture 9, a slow push in holds the commander as he remarks in a tone drained of joy or anger, <d>[Chinese] 三日之限，先生倒是一分不差。</d>"),
]),
dict(sceneIndex=2,blocking="周瑜居左、孔明居右，兵卒在岸边成景，二人隔数步相对，互相拱手。",
soundscape="岸上兵卒的低声咋舌，江水轻拍，晨光渐亮。",
music="弦乐轻摇，暗藏分寸。",
h3_sound="Low astonishment runs among the soldiers on the shore, the river laps gently, and the morning brightens.",
h3_music="Strings sway lightly, a hint of guardedness beneath.",
cuts=[
dict(beats=[10,10],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明神色如常，只说托了江东这方水土与诸将的福，拱手间滴水不漏。",
shot="固定中景，执扇的儒生神色如常，拱手客套，一句托诸将之福说得滴水不漏。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视正面",composition="三分法",eyeline="对方脸庞",focus="锁定孔明拱手",stability="stable",
h3="Anchored to Picture 10, a static medium shot shows the scholar answering with perfect composure, crediting the river and its officers in a voice that gives nothing away."),
dict(beats=[11,11],seconds=3.0,size="medium",camera="Static Shot",chars=["C13"],
frame="中景，岸上有兵卒低声咋舌，说凭空便多出十万支箭来真真神了，交头接耳。",
shot="固定中景，岸边几名兵卒低声咋舌，凑在一处惊叹这支凭空多出来的箭，语气里满是服气。",
lens="50mm 标准，中浅景深",cameraPosition="兵卒+平视",composition="三分法",eyeline="船队方向",focus="锁定咋舌的兵卒",stability="stable",
h3="Anchored to Picture 11, a static medium shot sees a knot of soldiers whispering in awe at the fleet that conjured a hundred thousand arrows from thin air."),
dict(beats=[12,12],seconds=3.0,size="extreme-close",camera="Static Shot",chars=["C12"],
frame="大特写，周瑜听在耳里面上没动，袖中的指尖却又收拢了几分，指节隐现青筋。",
shot="固定大特写，一只藏在袖中的手缓缓收拢，指节一点点攥紧，面上却不露分毫。",
lens="100mm 长焦，极浅景深",cameraPosition="周瑜之手+平视",composition="中心构图",eyeline="攥紧的指节",focus="锁定收拢的指尖",stability="stable",
h3="Anchored to Picture 12, a static extreme close-up rests on a hand hidden in a sleeve tightening finger by finger into a fist, the face betraying nothing."),
]),
dict(sceneIndex=2,blocking="周瑜与孔明相对而立，兵卒退远，晨雾里二人影深，互相拱手推让。",
soundscape="江水轻响，二人客套来去的气声，远处兵卒搬草把的窸窣。",
music="弦乐转收，带一丝凉。",
h3_sound="The river murmurs, courteous words pass between the two men, and beyond them soldiers haul straw with a soft rasp.",
h3_music="The strings close in with a touch of cool reserve.",
cuts=[
dict(beats=[13,13],seconds=2.7,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜话里带了几分客气，眼底却沉了沉，晨光落在他眉眼上。",
shot="固定近景，披轻甲的青年话里客气、眼底却沉了下去，笑意只停在表面。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="对方面部",focus="锁定周瑜眼底",stability="stable",
h3="Anchored to Picture 13, a static close-up holds the commander speaking with measured courtesy while something cools behind his eyes, <d>[Chinese] 孔明用计，果然出神入化。</d>"),
dict(beats=[14,14],seconds=3.0,size="medium",camera="Static Shot",chars=["C05"],
frame="中景，孔明拱手还礼，笑着推了回去，神气从容，看不出半点居功。",
shot="固定中景，执扇的儒生拱手一笑，把话轻轻推了回去，从容里不带半分居功。",
lens="50mm 标准，中浅景深",cameraPosition="孔明+平视正面",composition="三分法",eyeline="对方脸庞",focus="锁定孔明笑意",stability="stable",
h3="Anchored to Picture 14, a static medium shot sees the scholar return the courtesy with a light bow and an easy smile, waving the praise back."),
dict(beats=[15,15],seconds=3.1,size="close",camera="Push In",chars=["C05"],
frame="特写，孔明笑着推了回去，全赖公瑾与江东将士的船罢了，滴水不漏，晨雾在身后。",
shot="镜头 Push In 缓推向开口的儒生，一句全赖都督与将士的船，答得滴水不漏。",
lens="85mm 长焦，极浅景深",cameraPosition="孔明+平视正面",composition="中心构图",eyeline="对方脸庞",focus="锁定孔明双目",stability="stable",
h3="Anchored to Picture 15, a slow push in settles on the scholar as he demurs with a smile, <d>[Chinese] 全赖公瑾与江东将士的船罢了。</d>, each word measured and smooth."),
]),
dict(sceneIndex=2,blocking="周瑜背身居前、孔明与之拉开距离，晨雾里船队靠岸，兵卒搬草把。",
soundscape="周瑜离去的衣袍声响，江水轻拍，兵卒抬草把上仓的低喊。",
music="弦乐沉缓，藏妒意。",
h3_sound="The commander turns away with a rush of robes, the river laps, and soldiers heave the straw bales toward the storehouse amid low calls.",
h3_music="A slow, heavy string line, jealousy coiled beneath.",
cuts=[
dict(beats=[16,16],seconds=3.0,size="medium",camera="Pull Out",chars=["C12"],
frame="中景，周瑜背过身去，脸上的笑一点一点收干净，袖中的指节缓缓攥紧，晨雾笼身。",
shot="镜头 Pull Out 自那青年的背影缓缓拉开，他脸上的笑一点一点收净，袖中指尖悄悄攥紧。",
lens="50mm 标准，中浅景深",cameraPosition="周瑜+后侧",composition="中心构图",eyeline="前方江面",focus="锁定攥紧的袖中手",stability="stable",
h3="Anchored to Picture 16, a pull out draws back from the commander's back as his smile fades entirely and his hidden hand curls slowly into a fist."),
dict(beats=[17,17],seconds=3.0,size="wide",camera="Pan Left",chars=["C05"],
frame="全景，晨雾里孔明的船队正一一靠岸，染着露水的草把被兵卒连夜搬到仓去。",
shot="镜头 Pan Left 扫过晨雾里的滩岸，船队依次靠岸，兵卒抬着带露的草把往仓边走。",
lens="35mm 广角，全景深",cameraPosition="滩岸+俯视 20°",composition="三分法",eyeline="仓房方向",focus="锁定搬草把的兵卒",stability="slight-shake",
h3="Anchored to Picture 17, the camera pans left over the dewy bank as the boats come ashore one by one and soldiers haul the dew-laden bales to the storehouse."),
dict(beats=[18,18],seconds=3.0,size="medium",camera="Static Shot",chars=["C12"],
frame="中景，一名军需官上前报数，说除去损耗实数只多不少，周瑜背身听完。",
shot="固定中景，一名军需官上前报出实数只多不少，背身而立的青年凝神听完，没有回头。",
lens="50mm 标准，中浅景深",cameraPosition="军需官+平视",composition="三分法",eyeline="周瑜背影",focus="锁定报数的军需官",stability="stable",
h3="Anchored to Picture 18, a static medium shot watches a quartermaster step up to report the tally is only over the quota, the commander listening without turning."),
]),
dict(sceneIndex=2,blocking="周瑜立于岸边，孔明背影在晨雾里远去，周瑜面向江面，众人止步。",
soundscape="江水轻涌，晨风拂过袍角，众人屏息不敢作声。",
music="弦乐淡出，尾音怅然。",
h3_sound="The river swells quietly, wind brushes the robe hems, and everyone holds still, afraid to speak.",
h3_music="The strings fade out on a wistful, unspent note.",
cuts=[
dict(beats=[19,19],seconds=3.0,size="close",camera="Static Shot",chars=["C12"],
frame="特写，周瑜抬手止住话头，半晌才缓缓道了声知道了，眉眼沉沉的。",
shot="固定近景，披轻甲的青年抬手止住旁人话头，半晌才放下一句知道了，语气压得极平。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视正面",composition="中心构图",eyeline="前方江面",focus="锁定周瑜神情",stability="stable",
h3="Anchored to Picture 19, a static close-up sees the commander raise a hand to stop the talk and, after a long pause, let out a flat, quiet word of acknowledgment."),
dict(beats=[20,20],seconds=3.0,size="wide",camera="Static Shot",chars=["C12"],
frame="全景，他回身望着那道渐渐被晨光镀金的江面，眼底沉沉的，再没半分笑意。",
shot="固定全景，披甲的青年回身望着被晨光镀金的江面，眼底沉成一潭，再无半分笑意。",
lens="35mm 广角，全景深",cameraPosition="周瑜+后侧",composition="三分法",eyeline="镀金的江面",focus="锁定周瑜侧影",stability="stable",
h3="Anchored to Picture 20, a static wide shot frames the commander turned toward the gold-gilt river, his eyes growing heavy, every trace of a smile gone."),
dict(beats=[21,21],seconds=3.0,size="close",camera="Push In",chars=["C12"],
frame="特写，他抬头望了一眼晨雾里班师归来的孔明背影，又低下头半晌没有说话，喉头微咽。",
shot="镜头 Push In 缓推向低头不语的青年，他望过雾里远去的背影，终是低下了头。",
lens="85mm 长焦，极浅景深",cameraPosition="周瑜+平视侧面",composition="中心构图",eyeline="雾中远去的背影",focus="锁定周瑜沉默的侧脸",stability="stable",
h3="Anchored to Picture 21, a slow push in settles on the young commander as he glances once toward the retreating figure, then bows his head, silent for a long moment."),
]),
]