// ep11 原始分段（每段：sceneIndex, cuts[], blocking, soundscape, music?, h3sound, h3music）
export default [
// 场1 朝会·白日 C04 C10 (beats 1-19)
{
 sceneIndex:1, blocking:'曹操在画面左侧丹陛高台、居中背对群臣而立；袁绍在右首班列内抬眸打量，二人相距约十余步，面朝同一方向（曹操朝天子御座，袁绍朝曹操）',
 cuts:[
  {beats:[1,1],seconds:2.5,size:'wide',camera:'Tracking Shot',characters:['C04'],props:[],eng:'The tracking shot follows at moderate speed as a tall figure in dark court robes ascends the sunlit stone steps of the grand hall, cradling a yellow imperial edict; the sword-tassel sways with each step.',
   frame:'全景，白日朝会大殿石阶，曹操着一身玄色朝服手捧黄缎圣旨大步踏上丹陛，晨光洒在其身上',shot:'镜头平缓跟拍一名玄袍朝服的高大男子手捧黄缎圣旨大步踏上丹陛，袍角翻动、步伐沉稳',
   lens:'35mm 广角，中景深',cameraPosition:'曹操 + 侧面平视跟随',composition:'引导线构图',eyeline:'前方御座高台',focus:'锁定曹操上阶的身形',stability:'stable'},
  {beats:[2,2],seconds:2.5,size:'medium',camera:'Pan Right',characters:['C04','C10'],props:[],eng:'A pan right glides across the kneeling ministers and settles on a blue-robed high-crowned aristocrat in the ranks, who lifts his eyes to coolly appraise the man on the dais.',
   frame:'中景，满殿群臣伏首屏息，班列中袁绍一身蓝袍锦绶抬眸冷冷打量高台上的曹操',shot:'镜头右摇扫过俯首的群臣，停在班列一名蓝袍高冠的老者身上，他抬眸冷冷望着台上',
   lens:'50mm 标准，中景深',cameraPosition:'袁绍 + 平视',composition:'三分法',eyeline:'高台上的曹操',focus:'锁定袁绍的面部',stability:'stable'},
  {beats:[3,3],seconds:4.5,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the stern face of the man in dark robes as he loudly proclaims in a resonant voice, {t0}',
   frame:'特写，曹操立于御座前双手展开圣旨，目光扫过满殿群臣，神情威重',shot:'固定近景，台上的玄袍男子双手展旨，朗声宣诏，声震满堂',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'满殿群臣',focus:'锁定曹操面部',stability:'stable'},
 ],
 soundscape:'大殿回响，群臣衣袍摩擦的低语，圣旨布帛展开的窸窣',
 h3sound:'The great hall echoes with the rustle of ministers\' robes and the ripple of the imperial edict unfurling.',
 h3music:'Low solemn court strings at a slow tempo.',
},
{
 sceneIndex:1, blocking:'同前场：曹操居左侧丹陛，袁绍居右首班列，二人隔殿相望',
 cuts:[
  {beats:[4,4],seconds:3.8,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the cold face of the blue-robed aristocrat as he jabs back with restrained displeasure, {t0}',
   frame:'特写，袁绍立在班列微微抬眸，慢悠悠地冷笑质问，神情轻蔑而不悦',shot:'固定近景，班列中的蓝袍老者压着不快，慢悠悠地开口质问',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'高台上的曹操',focus:'锁定袁绍面部',stability:'stable'},
  {beats:[5,5],seconds:2.5,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot shows the man on the dais smile slightly and give the edict a small flick in his hand, unbothered.',
   frame:'中景，曹操微微一笑，把圣旨在手上展了展，胸有成竹',shot:'固定中景，台上的玄袍男子微微一笑，把圣旨在手中展了展',
   lens:'50mm 标准，中景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'袁绍方向',focus:'锁定曹操上半身',stability:'stable'},
  {beats:[6,6],seconds:3.6,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man on the dais as he answers firmly, {t0}',
   frame:'中景，曹操持圣旨朗声而答，神情笃定',shot:'固定中景，台上的玄袍男子执旨朗声作答，字字笃定',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'袁绍方向',focus:'锁定曹操面部',stability:'stable'},
 ],
 soundscape:'袁绍冷声质问在殿中回响',
 h3sound:'The aristocrat\'s cold question rings through the hall.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'同前场：一问一答成对峙，曹操居台侧、袁绍居班列',
 cuts:[
  {beats:[7,7],seconds:3.3,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the hard face of the aristocrat as he states flatly, {t0}',
   frame:'特写，袁绍沉声而答，态度冷硬，目光带着轻蔑',shot:'固定近景，蓝袍老者沉声回话，语气冷硬',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'高台',focus:'锁定袁绍眼部',stability:'stable'},
  {beats:[8,8],seconds:3.6,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man with the edict as he answers with rising sharpness, {t0}',
   frame:'中景，曹操举诏而答，笑意里透出锐利',shot:'固定中景，台上的玄袍男子举诏回应，语气转利',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'袁绍',focus:'锁定曹操面部',stability:'stable'},
  {beats:[9,9],seconds:4.5,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he retorts hard, barely holding his temper, {t0}',
   frame:'特写，袁绍强硬回话，面上已带不豫',shot:'固定近景，蓝袍老者强硬回绝，强自按捺怒气',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'中心构图',eyeline:'高台',focus:'锁定袁绍面部',stability:'stable'},
 ],
 soundscape:'袁绍动怒却强自按捺，殿中气压渐低',
 h3sound:'Tension thickens in the hall as the aristocrat holds back his temper.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'袁绍在右首班列欲转身离去，曹操从台侧迎上抬臂拦阻，两人相对',
 cuts:[
  {beats:[10,11],seconds:5,size:'medium',camera:'Truck Left',characters:['C04','C10'],props:[],eng:'A truck left follows the two men as the aristocrat turns to leave and the dark-robed man steps in, arm raised to block, then draws close and lowers his voice.',
   frame:'中景，袁绍拂袖转身要走，曹操抬臂虚虚一拦，缓步踱到他面前压低声音',shot:'镜头左移跟拍，蓝袍老者拂袖欲走，玄袍男子抬臂轻拦，缓步趋近压低声音',
   lens:'50mm 标准，中景深',cameraPosition:'双人 + 平视侧面',composition:'三分法',eyeline:'袁绍看向曹操抬起的手臂',focus:'锁定两人对峙的上半身',stability:'stable'},
  {beats:[12,12],seconds:3.5,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he lowers his voice in a placating tone, {t0}',
   frame:'特写，曹操贴近袁绍，压低声音，笑意和缓',shot:'固定近景，玄袍男子贴近老者，压低声音缓声道',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正侧面',composition:'三分法',eyeline:'袁绍面部',focus:'锁定曹操面部',stability:'stable'},
  {beats:[13,13],seconds:4.5,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he presses back without yielding, eyes sharp, {t0}',
   frame:'特写，袁绍寸步不让，直言逼问，目光锐利',shot:'固定近景，蓝袍老者寸步不让，冷声逼问',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正侧面',composition:'三分法',eyeline:'曹操面部',focus:'锁定袁绍面部',stability:'stable'},
 ],
 soundscape:'袁绍拂袖声，曹操压低的耳语',
 h3sound:'The swish of the sleeve and the man\'s low word spoken close.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'两人僵在殿中相对而立，曹操忽而一笑退开半步，群臣伏首',
 cuts:[
  {beats:[14,15],seconds:5,size:'wide',camera:'Static Shot',characters:['C04','C10'],props:[],eng:'A static wide shot holds the two men frozen mid-hall while the ministers bow low; then the dark-robed man laughs aloud and steps back to clear the way.',
   frame:'全景，两人僵在原地殿中落针可闻，群臣俯首不敢抬；曹操忽地哈哈一笑先退一步让开去路',shot:'固定全景，两人相对僵立，群臣俯首；玄袍男子忽地大笑，先退一步让开去路',
   lens:'35mm 广角，深景深',cameraPosition:'双人 + 平视侧面',composition:'对称构图',eyeline:'袁绍看曹操',focus:'锁定对峙的两人',stability:'stable'},
  {beats:[16,16],seconds:3.8,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man as he smooths things over with a knowing smile, {t0}',
   frame:'中景，曹操就势圆场，笑意里藏着话',shot:'固定中景，台上的玄袍男子就势圆场，笑意里带着深意',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'袁绍',focus:'锁定曹操面部',stability:'stable'},
  {beats:[17,17],seconds:2.8,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he answers coldly and curtly, {t0}',
   frame:'特写，袁绍冷硬回绝，不愿多言',shot:'固定近景，蓝袍老者冷硬一句，不再多言',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'别过头去',focus:'锁定袁绍面部',stability:'stable'},
 ],
 soundscape:'殿中一片死寂，随即曹操一声笑',
 h3sound:'The hall falls dead silent, broken by the man\'s sudden laugh.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'袁绍转身大步出殿朝画面深处走，曹操立于原地目送',
 cuts:[
  {beats:[18,19],seconds:5,size:'wide',camera:'Static Shot',characters:['C04','C10'],props:[],eng:'A static wide shot holds as the aristocrat stares a moment, turns and strides out with robe hem flying; the dark-robed man watches his receding back, the smile fading from his face.',
   frame:'全景，袁绍冷眼盯了曹操片刻转身大步出殿袍角翻飞，曹操望着他的背影脸上的笑意一点点收干净',shot:'固定全景，蓝袍老者盯了对方片刻回身大步出殿，袍角翻飞；玄袍男子目送其背影，笑意一点点收净',
   lens:'35mm 广角，深景深',cameraPosition:'双人 + 平视侧面',composition:'引导线构图',eyeline:'袁绍走向殿外，曹操目送',focus:'锁定袁绍背影与曹操神色',stability:'stable'},
 ],
 soundscape:'袁绍的脚步声远去，大殿复归空寂',
 h3sound:'The aristocrat\'s footsteps recede and the grand hall falls still.',
 h3music:'N/A',
},
// 场2 烛影·夜政 C04 (beats 1-15)
{
 sceneIndex:2, blocking:'夜政内景，曹操独坐画面中央案后，面前一盏烛灯，案上摊开诏书',
 cuts:[
  {beats:[1,1],seconds:2.5,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot at night shows the dark-robed man sitting alone beneath a green plum tree, an imperial edict spread on the desk before him in the wavering candlelight.',
   frame:'全景，夜深，曹操独坐青梅树下案上摊开一卷诏书，烛光摇动',shot:'固定全景，深夜里一名玄袍男子独坐树下案前，案上摊开诏书，烛光晃动',
   lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视侧面',composition:'三分法',eyeline:'案上诏书',focus:'锁定独坐的曹操',stability:'stable'},
  {beats:[2,2],seconds:4.5,size:'close',camera:'Push In',characters:['C04'],props:[],eng:'A slow push in tightens on the man\'s brooding face as he speaks his own inner voice aloud, {t0}',
   frame:'特写，曹操凝视诏书，神情深沉，眼里映着烛火',shot:'镜头小幅缓推，玄袍男子凝视案上诏书，眼底映着跳动的烛光',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'案上诏书',focus:'锁定曹操面部',stability:'stable'},
  {beats:[3,3],seconds:2.5,size:'extreme-close',camera:'Static Shot',characters:['C04'],props:[],eng:'An extreme close-up holds static as the man takes up a green fruit and slowly turns it between his fingers.',
   frame:'大特写，曹操捻起案上一枚青果，在指间慢慢转动',shot:'固定大特写，玄袍男子捻起案上一枚青果，在指间缓缓转动',
   lens:'100mm 微距，极浅景深',cameraPosition:'曹操的手 + 平视',composition:'中心构图',eyeline:'手中青果',focus:'锁定转动的指尖',stability:'stable'},
 ],
 soundscape:'更深人静的夜，烛火噼啪，青果在指间滚动',
 h3sound:'A deep night hush with the soft crackle of candle flame and the fruit rolling between fingers.',
 h3music:'Low nocturnal strings at a very slow tempo.',
},
{
 sceneIndex:2, blocking:'曹操独坐案前，檐下铜灯透进摇曳的烛影',
 cuts:[
  {beats:[4,4],seconds:3.6,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he speaks low, part to himself, part to the night, {t0}',
   frame:'特写，曹操低语自信，似讲与自己也讲与夜色',shot:'固定近景，玄袍男子低语，字句沉稳',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'幽暗处',focus:'锁定曹操面部',stability:'stable'},
  {beats:[5,5],seconds:2.5,size:'wide',camera:'Tilt Up',characters:['C04'],props:[],eng:'A slow tilt up takes in the bronze lamp under the eave as its candle shadow wavers across a vermilion pillar.',
   frame:'全景，檐下铜灯烛影摇动，在朱红柱上投下晃人的影',shot:'镜头缓缓仰摇，檐下铜灯的烛影在朱红柱上晃动摇曳',
   lens:'35mm 广角，深景深',cameraPosition:'檐下 + 平视仰摇',composition:'引导线构图',eyeline:'烛影柱面',focus:'锁定摇动的烛影',stability:'stable'},
  {beats:[6,6],seconds:3.3,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he states firmly, {t0}',
   frame:'特写，曹操直视烛火断言，神情笃定',shot:'固定近景，玄袍男子直视烛火断言，语气沉稳',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'烛火',focus:'锁定曹操双目',stability:'stable'},
 ],
 soundscape:'烛影摇动，夜色深透，远处隐约的虫鸣',
 h3sound:'Candlelight flickers across the night, distant insects barely audible.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'曹操独坐案前，提笔蘸墨于诏书空白处',
 cuts:[
  {beats:[7,7],seconds:3.3,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man\'s knitted brow as he voices a worry, {t0}',
   frame:'特写，曹操眉峰微聚，点出对袁绍的忧患',shot:'固定近景，玄袍男子眉峰微聚，压低声音自语',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'诏书',focus:'锁定曹操面部',stability:'stable'},
  {beats:[8,8],seconds:2.5,size:'extreme-close',camera:'Static Shot',characters:['C04'],props:[],eng:'An extreme close-up frames the brush as the man dips it in ink and writes a short line in the edict\'s blank margin.',
   frame:'大特写，曹操提笔蘸墨，在诏书空白处落下一行小字',shot:'固定大特写，玄袍男子提笔蘸墨，在诏书空白处落下小字',
   lens:'100mm 微距，极浅景深',cameraPosition:'笔尖纸面 + 俯视 30°',composition:'中心构图',eyeline:'笔尖',focus:'锁定落笔的笔尖',stability:'stable'},
  {beats:[9,9],seconds:3.8,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he sets down the brush and speaks gravely, {t0}',
   frame:'特写，曹操收笔，低语喟叹，神情深远',shot:'固定近景，玄袍男子搁下笔，低沉地道出了一句',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'书卷',focus:'锁定曹操眼部',stability:'stable'},
 ],
 soundscape:'笔毫落纸的沙沙声，烛火轻微的噼啪',
 h3sound:'The scratch of brush on paper over the faint crackle of candle flame.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'曹操独坐案前，烛光为台，门外透进夜色',
 cuts:[
  {beats:[10,10],seconds:4.5,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he makes his resolve clear, {t0}',
   frame:'特写，曹操缓声许下宏愿，目光沉凝',shot:'固定近景，玄袍男子缓声许愿，字字坚定',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'烛火深处',focus:'锁定曹操面部',stability:'stable'},
  {beats:[11,11],seconds:3.1,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man as he narrows his eyes and speaks, {t0}',
   frame:'中景，曹操微眯眼，低声自语点醒自己',shot:'固定中景，玄袍男子微眯起眼，低声自语',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'案前幽暗',focus:'锁定曹操上半身',stability:'stable'},
  {beats:[12,12],seconds:2.5,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot holds as the man sets down the brush and the candlelight dances in his eyes.',
   frame:'全景，曹操搁下笔，烛光在他眼底跳了跳',shot:'固定全景，玄袍男子搁下笔，烛光在他眼底跳动',
   lens:'35mm 广角，中景深',cameraPosition:'曹操 + 平视侧面',composition:'三分法',eyeline:'案面',focus:'锁定搁笔的手',stability:'stable'},
 ],
 soundscape:'烛火跳动，夜色深处传来隐约的操练声',
 h3sound:'The candle flame leaps as faint drilling drifts in from afar.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'曹操独坐案前，侧耳倾听远处兵马动静，朝门外方向下令',
 cuts:[
  {beats:[13,13],seconds:2.5,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot holds as the man cocks his ear toward the door and faint drilling echoes from the distant streets.',
   frame:'全景，曹操侧耳，远处街上传来自家兵马操练的动静',shot:'固定全景，玄袍男子侧耳倾听，远处传来隐约的操练声',
   lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视侧面',composition:'三分法',eyeline:'门外',focus:'锁定曹操侧耳的神态',stability:'stable'},
  {beats:[14,14],seconds:4,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man as he gives the order clearly, {t0}',
   frame:'中景，曹操沉声传令，气度凛然',shot:'固定中景，玄袍男子朗声下令，字字清晰',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'门外方向',focus:'锁定曹操面部',stability:'stable'},
  {beats:[15,15],seconds:2.5,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot holds a guard outside the frame answering in acknowledgment, his footsteps quickly vanishing into the dark.',
   frame:'全景，门外一名亲兵在外应诺，脚步声很快消失在夜色里',shot:'固定全景，门外一名亲兵应诺转身，脚步声没入夜色',
   lens:'35mm 广角，深景深',cameraPosition:'门内 + 平视',composition:'三分法',eyeline:'门外夜色',focus:'锁定门外离去的影',stability:'stable'},
 ],
 soundscape:'亲兵应诺声，脚步声迅速远去，远处操练声渐拢',
 h3sound:'A guard answers, his steps fade, and the distant drilling draws nearer.',
 h3music:'N/A',
},
// 场3 朝会·白日 C04 C10 (beats 1-23)
{
 sceneIndex:3, blocking:'朝堂重列，曹操居台上首，袁绍居右首班列，满殿群臣俯首',
 cuts:[
  {beats:[1,1],seconds:2.5,size:'wide',camera:'Static Shot',characters:['C04','C10'],props:[],eng:'A static wide shot shows the court reconvened three days later, the blue-robed aristocrat in his place in the ranks, daylight flooding the hall.',
   frame:'全景，三日之后朝堂重列，袁绍亦在其位，日光照进大殿',shot:'固定全景，三日之后朝堂重列，蓝袍高冠者亦立于班列，日光洒入',
   lens:'35mm 广角，深景深',cameraPosition:'朝堂 + 平视正面',composition:'对称构图',eyeline:'御座方向',focus:'锁定朝班全景',stability:'stable'},
  {beats:[2,2],seconds:4,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man in the lead as he declares, {t0}',
   frame:'中景，曹操朗声宣令，示意四方皆归许都调度',shot:'固定中景，上首玄袍男子朗声宣令，气度沉稳',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'满殿群臣',focus:'锁定曹操面部',stability:'stable'},
  {beats:[3,3],seconds:2.9,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he answers coldly, {t0}',
   frame:'特写，袁绍沉声，寸步不让',shot:'固定近景，蓝袍老者沉声回话，态度冷硬',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'上首曹操',focus:'锁定袁绍面部',stability:'stable'},
  {beats:[4,4],seconds:3.1,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man in the lead as he returns sharply, {t0}',
   frame:'中景，曹操回敬一句，话锋带刺',shot:'固定中景，上首玄袍男子回敬一句，话锋锐利',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'袁绍',focus:'锁定曹操面部',stability:'stable'},
 ],
 soundscape:'朝会威严，群臣整齐的低语',
 h3sound:'The solemn court murmur as ministers file into neat ranks.',
 h3music:'Low court strings at a slow pace.',
},
{
 sceneIndex:3, blocking:'曹操居上首、袁绍居右首对视，传令官从阶下碎步呈上黄封木盒',
 cuts:[
  {beats:[5,6],seconds:5,size:'medium',camera:'Pan Left',characters:['C04','C10'],props:[],eng:'A pan left follows the stare between the two men, then swings to a messenger stepping up the dais to present a sealed yellow box before the man in the lead.',
   frame:'中景，袁绍与曹操四目相接谁也不让；阶下传令官捧一盒黄封恭谨呈到曹操面前',shot:'固定机位随镜头左移，两人对视不让，随即传令官捧黄封木盒呈上',
   lens:'50mm 标准，中景深',cameraPosition:'双人 + 平视侧面',composition:'三分法',eyeline:'对视后看木盒',focus:'锁定对视的两人',stability:'stable'},
  {beats:[7,7],seconds:3.1,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man as he takes the box and proclaims, {t0}',
   frame:'特写，曹操接过黄封，朗声宣示',shot:'固定近景，上首玄袍男子接过黄封，朗声宣示',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'手中黄封',focus:'锁定曹操持封的手',stability:'stable'},
  {beats:[8,8],seconds:3.8,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he presses coldly, {t0}',
   frame:'特写，袁绍冷声发难，意有所指',shot:'固定近景，蓝袍老者冷声发难，话里带刺',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'上首',focus:'锁定袁绍面部',stability:'stable'},
 ],
 soundscape:'传令官碎步上前的衣声，黄封盒盖轻落',
 h3sound:'The messenger\'s quick steps and the light click of the sealed box.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'曹操居上首朗声宣诏，袁绍在班列按剑而立',
 cuts:[
  {beats:[9,9],seconds:3.8,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he presses on without letting up, {t0}',
   frame:'特写，袁绍接着话头，毫不退让',shot:'固定近景，蓝袍老者接过话头，不给台阶',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'上首',focus:'锁定袁绍面部',stability:'stable'},
  {beats:[10,11],seconds:5,size:'wide',camera:'Static Shot',characters:['C04','C10'],props:[],eng:'A static wide shot shows the man in the lead declaring to the hall as the ministers bow together, only the blue-robed aristocrat standing, fingers tightening on his sword hilt.',
   frame:'全景，曹操朗声宣诏声震满殿群臣齐齐俯首，唯袁绍静立班列手抚剑柄指节收紧',shot:'固定全景，上首玄袍男子朗声宣诏，群臣齐俯首，唯蓝袍老者独立班列抚剑而立',
   lens:'35mm 广角，深景深',cameraPosition:'朝堂 + 平视正面',composition:'对称构图',eyeline:'俯首的群臣与按剑的袁绍',focus:'锁定俯首群臣中挺立的袁绍',stability:'stable'},
 ],
 soundscape:'宣诏声震满殿，群臣齐齐俯首的衣声',
 h3sound:'The proclamation rings through the hall as ministers bow low together.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'袁绍班列按剑，曹操踞上首',
 cuts:[
  {beats:[12,12],seconds:4,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as a bitter inner thought crosses his face, {t0}',
   frame:'特写，袁绍垂眸，神情带着不平与怒意',shot:'固定近景，蓝袍老者垂眸，眼底压着不平的怒意',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'中心构图',eyeline:'剑柄',focus:'锁定袁绍面部',stability:'stable'},
  {beats:[13,13],seconds:3.8,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the man in the lead as he advises gently, {t0}',
   frame:'中景，曹操和声相劝，笑意和缓',shot:'固定中景，上首玄袍男子和声相劝',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'袁绍',focus:'锁定曹操面部',stability:'stable'},
  {beats:[14,14],seconds:4.2,size:'close',camera:'Static Shot',characters:['C10'],props:[],eng:'A static close-up holds the aristocrat as he retorts with a mocking smile, {t0}',
   frame:'特写，袁绍讽笑回敬，锋芒毕露',shot:'固定近景，蓝袍老者讽笑回敬，锋芒毕露',
   lens:'85mm 长焦，浅景深',cameraPosition:'袁绍 + 平视正面',composition:'三分法',eyeline:'上首',focus:'锁定袁绍面部',stability:'stable'},
 ],
 soundscape:'袁绍压抑的怒意，曹操和缓的调笑',
 h3sound:'The aristocrat\'s held-back anger against the man\'s easy, disarming amusement.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'曹操下阶趋前拍袁绍肩头，袁绍甩袖下阶朝殿外走',
 cuts:[
  {beats:[15,16],seconds:5.4,size:'medium',camera:'Push In',characters:['C04','C10'],props:[],eng:'A gentle push in holds as the man in the lead pats the aristocrat\'s shoulder and speaks with an invitation, {t0}',
   frame:'中景，曹操先拍了拍袁绍的肩头缓声道，约他改日一叙',shot:'镜头小幅缓推，上首玄袍男子趋前拍拍老者肩头，缓声相约',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视侧面',composition:'三分法',eyeline:'袁绍回看曹操',focus:'锁定拍肩的手与两人神情',stability:'stable'},
  {beats:[17,18],seconds:6.5,size:'wide',camera:'Static Shot',characters:['C04','C10'],props:[],eng:'A static wide shot holds as the aristocrat flings his sleeve, turns and strides down the dais, calling back, {t0}; the man in the lead watches his back.',
   frame:'全景，袁绍重重甩袍袖转身大步走下丹陛扬声吩咐，曹操望着他的背影',shot:'固定全景，蓝袍老者重重甩袖回身大步下阶，扬声吩咐，上首玄袍男子目送',
   lens:'35mm 广角，深景深',cameraPosition:'双人 + 平视侧面',composition:'引导线构图',eyeline:'袁绍走向殿外',focus:'锁定下阶的袁绍',stability:'stable'},
 ],
 soundscape:'曹操缓语，袁绍甩袖下阶的脚步声',
 h3sound:'The man\'s soft words, then the sharp swish and heavy steps of the aristocrat leaving.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'袁绍出殿，曹操于阶上目送，旋即招一名亲兵附耳',
 cuts:[
  {beats:[19,20],seconds:4.7,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the man watching the receding back, his smile dying as he murmurs, {t0}',
   frame:'特写，曹操望着袁绍下阶的背影，眼底笑意彻底褪尽低声断言',shot:'固定近景，上首玄袍男子目送背影，笑意彻底收净低声自语',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'袁绍离去的方向',focus:'锁定曹操眼底神色',stability:'stable'},
  {beats:[21,22],seconds:5.4,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds as the man turns and beckons a guard to whisper orders, {t0}',
   frame:'中景，曹操回过身招来一名亲兵附耳低语数句',shot:'固定中景，上首玄袍男子回身招来一名亲兵，附耳低声嘱咐',
   lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 平视侧面',composition:'三分法',eyeline:'亲兵侧耳',focus:'锁定两人低语',stability:'stable'},
 ],
 soundscape:'曹操低声的断语，附耳低语的耳语',
 h3sound:'The man\'s low verdict, then the soft hush of whispered orders.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'曹操独立殿上望向深殿外的天色',
 cuts:[
  {beats:[23,23],seconds:2.5,size:'wide',camera:'Pull Out',characters:['C04'],props:[],eng:'A slow pull out widens over the empty hall as the man stands alone watching the darkening sky beyond the doors, saying nothing.',
   frame:'全景，亲兵应诺退下，曹操独望殿外渐暗的天色久久不语',shot:'镜头缓缓拉远，亲兵退下，玄袍男子独望殿外渐暗的天色，久久不语',
   lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视远眺',composition:'中心构图',eyeline:'殿外渐暗的天色',focus:'锁定曹操剪影',stability:'stable'},
 ],
 soundscape:'大殿空寂，暮色渐合的风声',
 h3sound:'The great hall falls empty and still as dusk closes in.',
 h3music:'Low lonely strings at a slow tempo, fading.',
},
];