// ep12 原始分段
export default [
// 场1 S05 城下晨光 C01 C02 C03 (beats 1-15)
{
 sceneIndex:1, blocking:'刘备自陶府石阶独出于画面中央，双手捧让书于胸前，府门外晨光清薄、少人。张飞随后于右手侧一把夺书，关羽在张飞身侧按下其手腕。',
 cuts:[
  {beats:[1,2],seconds:5,size:'wide',camera:'Tracking Shot',characters:['C01'],props:[],eng:'A tracking shot follows a benevolent lord in plain linen robes as he steps out from a mansion hall, both hands cradling a scroll bearing a grand official seal; he pauses at the top of the stone steps, gaze fixed on the gleaming seal in a long, uncertain stillness.',
   frame:'全景，城下晨光，刘备自陶府步出双手捧一卷盖了州印的让书，立在石阶前望着印半晌没动',shot:'镜头平缓跟拍一名素衣仁德之主双手捧一卷州印让书走出府门，在石阶上停步，望着封印久久不动',
   lens:'35mm 广角，深景深',cameraPosition:'刘备 + 侧面平视跟随',composition:'引导线构图',eyeline:'手中卷册',focus:'锁定刘备与让书',stability:'stable'},
  {beats:[3,3],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord as he speaks with genuine reluctance, {t0}',
   frame:'特写，刘备望着手中让书，满眼迟疑，低声说自己接不起这重担',shot:'固定近景，素衣男子凝视手中让书，低声道出心事',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'手中让书',focus:'锁定刘备面部',stability:'stable'},
 ],
 soundscape:'晨风疏朗，府门外隐隐鸟鸣',
 h3sound:'A morning breeze and faint birdsong from outside the mansion gate.',
 h3music:'Soft warm strings at a slow tempo.',
},
{
 sceneIndex:1, blocking:'三人聚在阶前：刘备居中捧书，张飞在其右手侧劈手夺过，关羽在张飞身侧按住其手腕压言。',
 cuts:[
  {beats:[4,4],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static medium shot frames a boisterous fierce warrior snatching the scroll from the lord\'s hands in one brisk grab.',
   frame:'中景，张飞在旁一把将让书从刘备手中夺过来，眉梢带急',shot:'固定中景，一名豹头环眼的黑脸猛将劈手夺过让书',
   lens:'50mm 标准，中景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'被夺的让书',focus:'锁定夺书的手',stability:'stable'},
  {beats:[5,5],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior as he barks out, {t0}',
   frame:'特写，张飞扬着让书扬声催劝，语气急切',shot:'固定近景，黑脸猛将扬着让书大声催促',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
  {beats:[6,7],seconds:6,size:'medium',camera:'Static Shot',characters:['C02','C03'],props:[],eng:'A static medium shot holds a tall red-faced general gently pressing the fierce warrior\'s wrist to calm him, then the red-faced general offers a prudent word, {t0}',
   frame:'中景，关羽伸手按住张飞的手腕示意他别抢话，随即缓声劝解',shot:'固定中景，一名红脸长髯的稳重大将按住黑脸猛将手腕，缓声开口',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'张飞',focus:'锁定按腕的手',stability:'stable'},
 ],
 soundscape:'袖袖摩挲，三人压低的话音',
 h3sound:'The rustle of sleeves and low exchanged words.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'刘备居中卷书而立，张飞于右拍胸豪言，关羽于左正色相劝，三人于阶前成势。',
 cuts:[
  {beats:[8,9],seconds:6,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot holds the lord slowly rolling up the scroll and shaking his head as he speaks with self-deprecation, {t0}',
   frame:'中景，刘备摇了摇头缓缓把让书卷起来，自谦说自己何德何能',shot:'固定中景，素衣男子摇头卷起让书，谦辞自贬',
   lens:'50mm 标准，中浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'手中让书',focus:'锁定刘备面部',stability:'stable'},
  {beats:[10,10],seconds:4.5,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot holds the fierce warrior beaming as he urges in a loud, proud voice, {t0}',
   frame:'中景，张飞咧嘴一笑，豪声说这徐州就是咱们的谁也别想抢',shot:'固定中景，黑脸猛将咧嘴一笑，声若洪钟地豪言',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
  {beats:[11,11],seconds:4.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general speaking with cool respect, {t0}',
   frame:'特写，关羽正色相劝陶公让贤是敬大哥的名声莫要负了他',shot:'固定近景，红脸大将正色相劝，语气郑重',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
 ],
 soundscape:'张飞的豪言，关羽低沉的话音',
 h3sound:'The warrior\'s bold laughter, then the general\'s calm counsel.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'张飞声震使檐角尘土簌簌落下，刘备居前苦笑推书，关羽于侧欲言又止。',
 cuts:[
  {beats:[12,13],seconds:5.5,size:'wide',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static wide shot holds the fierce warrior\'s voice rattling the dust from the eaves, then the lord gives a bitter smile at the clouds rolling in and pushes the scroll aside.',
   frame:'全景，张飞嗓门震得檐角尘土簌簌往下落，刘备苦笑着望向天边压过来的云，把让书推到一旁',shot:'固定全景，殿前檐角尘土因一声怒吼簌簌落下，素衣男子苦笑着望天，把让书推在一旁',
   lens:'35mm 广角，深景深',cameraPosition:'双人 + 平视侧面',composition:'三分法',eyeline:'刘备望天边云、张飞望刘备',focus:'锁定刘备神态与让书',stability:'stable'},
  {beats:[14,14],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord gently reassuring, {t0}',
   frame:'特写，刘备缓声安抚，让陶使君先安心养病',shot:'固定近景，素衣男子温声相劝，神色平和',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'关羽方向',focus:'锁定刘备面部',stability:'stable'},
  {beats:[15,15],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot shows the red-faced general about to probe further but, catching the lord\'s look, holding back his words.',
   frame:'中景，关羽还想再劝，见兄长神色，终究没把话说出口',shot:'固定中景，红脸大将欲言又止，见兄长神色便收住了话',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'刘备',focus:'锁定关羽收话的神态',stability:'stable'},
 ],
 soundscape:'檐角尘落，风声，话音渐歇',
 h3sound:'A passing breeze as the voices fall quiet.',
 h3music:'N/A',
},
// 场2 S05 烈日校场 C01 C02 C03 (beats 1-15)
{
 sceneIndex:2, blocking:'校场正中高台，刘备居中登台欲接印，关羽立于其侧，台下文武分列两侧、百姓翘首。',
 cuts:[
  {beats:[1,1],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot shows the drilling field under blazing sun, the assembled civil and military officials of the province waiting in ranks as a lord in plain robes steps up to receive the seal.',
   frame:'全景，烈日校场，徐州文武尽数列位，刘备登台准备接印',shot:'固定全景，烈日下校场列满文武，素衣男子登台欲接印',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视正面',composition:'对称构图',eyeline:'台下',focus:'锁定登台的刘备',stability:'stable'},
  {beats:[2,2],seconds:4.5,size:'medium',camera:'Static Shot',characters:['C02'],props:[],eng:'A static medium shot holds the red-faced general urging gently, {t0}',
   frame:'中景，关羽低声相劝，陶公以全城相托再辞便负了人心',shot:'固定中景，红脸大将低声相劝，语带恳切',
   lens:'50mm 标准，中浅景深',cameraPosition:'关羽 + 平视正面',composition:'三分法',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
  {beats:[3,3],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot holds the lord looking out over the sea of expectant faces below, standing in a long, silent hesitation.',
   frame:'全景，刘备望着台下黑压压翘首的百姓，默默站了一会儿',shot:'固定全景，素衣男子望着台下翘首的百姓，默默伫立',
   lens:'35mm 广角，深景深',cameraPosition:'刘备 + 平视侧面',composition:'引导线构图',eyeline:'台下百姓',focus:'锁定刘备侧影',stability:'stable'},
 ],
 soundscape:'校场风声，台下百姓压抑的低声',
 h3sound:'Wind over the drilling field and the hush of the waiting crowd.',
 h3music:'Low solemn drums at a slow pace.',
},
{
 sceneIndex:2, blocking:'刘备居中，张飞于左抢印塞入其手，关羽于右相劝，三人围立于高台之上。',
 cuts:[
  {beats:[4,4],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord voicing his self-doubt, {t0}',
   frame:'特写，刘备低声自愧，觉得自己德不配位',shot:'固定近景，素衣男子低声道出自觉德不配位的心事',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'台下',focus:'锁定刘备眼部',stability:'stable'},
  {beats:[5,5],seconds:3.5,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot holds the fierce warrior declaring boldly, {t0}',
   frame:'中景，张飞扬声高呼，你不配天下还有谁配',shot:'固定中景，黑脸猛将扬声高呼，气势炽盛',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
  {beats:[6,6],seconds:3,size:'close',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A close-up holds the fierce warrior snatching the seal from the tray and shoving it into the lord\'s hands.',
   frame:'特写，张飞一把抢过托盘里的州印直往刘备手里塞',shot:'固定特写，黑脸猛将抢过州印直塞进素衣男子掌中',
   lens:'85mm 长焦，浅景深',cameraPosition:'双人 + 平视',composition:'中心构图',eyeline:'手上州印',focus:'锁定夺印的手',stability:'stable'},
  {beats:[7,7],seconds:4.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general persuading, {t0}',
   frame:'特写，关羽正色相劝，百姓翘首以盼大哥再推反冷了众人的心',shot:'固定近景，红脸大将正色相劝，语气郑重',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
 ],
 soundscape:'张飞的喊声，关羽沉稳的劝',
 h3sound:'The warrior\'s loud shout, then the general\'s steady counsel.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'刘备立于台沿，捧印高举过头，台下百姓跪伏一片，关羽于侧再劝。',
 cuts:[
  {beats:[8,8],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot shows the crowd below kneeling in unison, voices rising in a great cheer.',
   frame:'全景，台下百姓齐声山呼，呼啦啦跪倒一片',shot:'固定全景，台下百姓齐声山呼跪倒一片',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视正面',composition:'对称构图',eyeline:'台下',focus:'锁定跪倒的百姓',stability:'stable'},
  {beats:[9,9],seconds:3.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general repeating his counsel, {t0}',
   frame:'特写，关羽又劝一句，名正则言顺大哥莫要再推辞',shot:'固定近景，红脸大将又补一句相劝',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
  {beats:[10,10],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot holds the lord weighing the seal in his palm, then slowly raising it above his head.',
   frame:'中景，刘备接过州印在掌心里掂了掂，缓缓举过头顶',shot:'固定中景，素衣男子接过州印在掌心掂了掂，缓缓高举过头',
   lens:'50mm 标准，中浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'手中州印',focus:'锁定举印的手',stability:'stable'},
  {beats:[11,11],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord making his vow, {t0}',
   frame:'特写，刘备朗声许诺，既领此土必与徐州百姓同安危',shot:'固定近景，素衣男子朗声许诺，字字坚定',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'台下百姓',focus:'锁定刘备面部',stability:'stable'},
 ],
 soundscape:'山呼雷动，随即一静',
 h3sound:'A thunderous cheer, then a hush as the vow is spoken.',
 h3music:'Rising, resolute strings.',
},
{
 sceneIndex:2, blocking:'校场欢腾三碗，刘备居中迎风而立，张飞关羽分列左右。',
 cuts:[
  {beats:[12,12],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot shows the field erupting in cheers as the lord\'s eyes grow faintly red.',
   frame:'全景，校场上下欢声雷动，刘备眼圈不由得微微泛红',shot:'固定全景，校场欢声雷动，素衣男子眼圈微红',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视侧面',composition:'引导线构图',eyeline:'台下欢腾的景象',focus:'锁定刘备神态',stability:'stable'},
  {beats:[13,13],seconds:3.5,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot holds the fierce warrior beaming as he calls out, {t0}',
   frame:'中景，张飞咧嘴笑道，咱也有自己的家了',shot:'固定中景，黑脸猛将咧嘴笑着，意气风发',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'关羽',focus:'锁定张飞面部',stability:'stable'},
  {beats:[14,14],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot holds the red-faced general, rarely smiling, offering the lord a deep formal bow.',
   frame:'中景，关羽难得弯了弯嘴角，正色向刘备长长一揖',shot:'固定中景，红脸大将难得露出笑意，郑重向素衣男子深揖',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'刘备',focus:'锁定作揖的关羽',stability:'stable'},
  {beats:[15,15],seconds:5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord pledging, {t0}',
   frame:'特写，刘备郑重许下日后政当宽厚兵当俭用莫令徐州再受刀兵的诺言',shot:'固定近景，素衣男子郑重许诺，神情凝重',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'台下',focus:'锁定刘备面部',stability:'stable'},
 ],
 soundscape:'欢声渐息，郑重的话音',
 h3sound:'The revelry settles as the solemn vow is spoken.',
 h3music:'Solemn low brass fading.',
},
// 场3 S05 夜凉古城 C01 C02 C03 (beats 1-23)
{
 sceneIndex:3, blocking:'夜府内，刘备独坐案后居中，案上摊开徐州图册，一盏明灯，烛影摇动。',
 cuts:[
  {beats:[1,1],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot at night shows the lord sitting alone in the mansion, a map of the province spread across the desk before him.',
   frame:'全景，夜深，刘备独坐府中案上摊着一幅徐州四境图册',shot:'固定全景，深夜里素衣男子独坐案前，案上摊着徐州图册',
   lens:'35mm 广角，中景深',cameraPosition:'刘备 + 平视侧面',composition:'三分法',eyeline:'案上图册',focus:'锁定独坐的刘备',stability:'stable'},
  {beats:[2,2],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord murmuring his worry, {t0}',
   frame:'特写，刘备低声感叹，徐州虽得，四面却皆是虎狼',shot:'固定近景，素衣男子低语絮念，眉间忧色',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'图册',focus:'锁定刘备面部',stability:'stable'},
  {beats:[3,3],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord as his inner voice continues in an off-screen voiceover while his lips remain closed, {t0}',
   frame:'特写，刘备眼底映着烛火，画外响起自己的心声',shot:'固定近景，素衣男子神色沉凝，画外轻诉心中忧虑，双唇不动',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'窗外夜色',focus:'锁定刘备眼底',stability:'stable'},
 ],
 soundscape:'夜风，烛火噼啪',
 h3sound:'A night breeze and the soft crackle of candle flame.',
 h3music:'Low nocturnal strings at a very slow tempo.',
},
{
 sceneIndex:3, blocking:'关羽提灯自门而入，将一盏温茶轻置案边；张飞随后抱酒坛跨过门槛，哐当放落，三人于灯下聚齐。',
 cuts:[
  {beats:[4,4],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot shows a tall red-faced general entering with a lamp, gently setting a warm cup of tea by the lord\'s table.',
   frame:'中景，关羽提着灯走进来，把一盏温茶轻轻放在刘备案边',shot:'固定中景，红脸大将提灯而入，将一盏温茶轻放案边',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'放下的茶盏',focus:'锁定放茶的手',stability:'stable'},
  {beats:[5,5],seconds:3.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general pledging, {t0}',
   frame:'特写，关羽正色相劝，大哥既坐此位，兄弟自当同守',shot:'固定近景，红脸大将正色进言，语带坚定',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
  {beats:[6,6],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static medium shot shows a boisterous fierce warrior lugging a jar of wine through the threshold and setting it down with a thud.',
   frame:'中景，张飞抱着一坛酒挤过门槛，咚地放在地上',shot:'固定中景，黑脸猛将抱着一坛酒跨过门槛，砰地放落',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'放下的酒坛',focus:'锁定放坛的动作',stability:'stable'},
  {beats:[7,7],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior growling possessively, {t0}',
   frame:'特写，张飞扬声威吓，谁要打徐州，先问过我手里的蛇矛',shot:'固定近景，黑脸猛将扬声威吓，气势摄人',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'门外',focus:'锁定张飞面部',stability:'stable'},
 ],
 soundscape:'酒坛落地声，张飞粗豪的话音',
 h3sound:'The heavy thud of the wine jar and the warrior\'s gruff roar.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'三人围灯而坐，刘备居上图前指点四方，关羽张飞分坐两侧。',
 cuts:[
  {beats:[8,8],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord speaking gently, {t0}',
   frame:'特写，刘备缓声点醒，守土还得靠民心',shot:'固定近景，素衣男子温声讲理，语气平和',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定刘备面部',stability:'stable'},
  {beats:[9,9],seconds:4.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior grumbling impatiently, {t0}',
   frame:'特写，张飞嘟囔着说民心民心听我听着头疼',shot:'固定近景，黑脸猛将一脸不耐地嘟囔',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'一旁',focus:'锁定张飞面部',stability:'stable'},
  {beats:[10,10],seconds:3,size:'wide',camera:'Static Shot',characters:['C01','C02','C03'],props:[],eng:'A static wide shot shows the three men settling around the lamp as the lord points across the map in the four directions.',
   frame:'全景，三人围着灯坐下，刘备伸手在图上指点四方',shot:'固定全景，灯火下三人围坐，素衣男子伸手在图上指点四方',
   lens:'35mm 广角，中景深',cameraPosition:'三人 + 平视侧面',composition:'对称构图',eyeline:'图册',focus:'锁定指图的手',stability:'stable'},
 ],
 soundscape:'夜里的低语，酒碗轻碰',
 h3sound:'Low voices and the clink of a wine bowl in the night.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'灯下三人相商，刘备居中沉色，关羽照旧持重，张飞灌酒应承。',
 cuts:[
  {beats:[11,11],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord weighing their weak foundations, {t0}',
   frame:'特写，刘备低声说道，根基还是太薄',shot:'固定近景，素衣男子低声道出处境，忧色深重',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'图册',focus:'锁定刘备面部',stability:'stable'},
  {beats:[12,12],seconds:4,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general counseling patience, {t0}',
   frame:'特写，关羽沉声劝道，先安定内政广积粮草再慢慢坐大',shot:'固定近景，红脸大将沉声进言，老成持重',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
  {beats:[13,13],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the fierce warrior drinking a long gulp of wine and answering in a low rumble.',
   frame:'中景，张飞灌了一大口酒，瓮声瓮气地应下',shot:'固定中景，黑脸猛将咕咚灌下一大口酒，瓮声应承',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'手中酒碗',focus:'锁定灌酒的动作',stability:'stable'},
 ],
 soundscape:'吞咽声，三人的低语',
 h3sound:'The gulping of wine and mumbling assent in the lamplight.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'刘备居中研图再三，关羽张飞分守左右，商议既定，刘备合上图册望向窗。',
 cuts:[
  {beats:[14,14],seconds:3.5,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot holds the fierce warrior pledging his loyalty, {t0}',
   frame:'中景，张飞拍着胸膛说大哥你说怎么打我就怎么打',shot:'固定中景，黑脸猛将拍胸立誓，气焰十足',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
  {beats:[15,15],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord slowly closing the map, gaze drifting to the dark window.',
   frame:'特写，刘备把图册缓缓合上，望向窗外沉沉的夜色',shot:'固定近景，素衣男子缓缓合上图册，目光投向窗外夜色',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'窗外夜色',focus:'锁定刘备神色',stability:'stable'},
  {beats:[16,16],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord voicing his unease, {t0}',
   frame:'特写，刘备低声道，这徐州能不能长久，心里还是没底',shot:'固定近景，素衣男子低语，眉间忧惧',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'窗外夜色',focus:'锁定刘备面部',stability:'stable'},
  {beats:[17,17],seconds:4,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general reassuring him, {t0}',
   frame:'特写，关羽宽慰，兵来将挡水来土掩，大哥且放宽心',shot:'固定近景，红脸大将温言宽慰，神色从容',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
 ],
 soundscape:'夜沉，话音低回',
 h3sound:'The deep night and low, reassuring voices.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'门首忽响急促拍门声，一名满身尘土的传令兵扑滚着闯进来，双手捧上一封火漆急报；刘备居中接手就着烛火展信。',
 cuts:[
  {beats:[18,19],seconds:5,size:'medium',camera:'Static Shot',characters:['C01','C02','C03'],props:[],eng:'A static medium shot holds the three men as sudden urgent knocking pounds at the door and a messenger caked in dust bursts through.',
   frame:'中景，门外忽传来急促拍门声，一名满身尘土的传令兵扑滚着闯进门来',shot:'固定中景，三人闻声抬眼，一名尘仆传令兵踉跄扑入',
   lens:'50mm 标准，中景深',cameraPosition:'三人 + 平视',composition:'三分法',eyeline:'门口',focus:'锁定闯入的传令兵',stability:'slight-shake'},
  {beats:[20,20],seconds:2,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord demanding, {t0}',
   frame:'特写，刘备沉声问道，何事如此慌张',shot:'固定近景，素衣男子沉声发问',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'传令兵',focus:'锁定刘备面部',stability:'stable'},
  {beats:[21,21],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot shows the panting messenger holding out a wax-sealed urgent dispatch in both hands.',
   frame:'中景，传令兵急喘着，双手捧上一封火漆急报',shot:'固定中景，传令兵急喘着双手捧出一封火漆急报',
   lens:'50mm 标准，中浅景深',cameraPosition:'传令兵 + 平视',composition:'三分法',eyeline:'手中急报',focus:'锁定捧报的双手',stability:'stable'},
  {beats:[22,22],seconds:2,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the red-faced general asking, {t0}',
   frame:'特写，关羽蹙眉问道，是北边来的信吗',shot:'固定近景，红脸大将蹙眉发问',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'急报',focus:'锁定关羽面部',stability:'stable'},
  {beats:[23,23],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord unfolding the letter by the candle, his face sinking little by little as he reads.',
   frame:'特写，刘备展信就着烛火一看，脸色一点一点沉了下来',shot:'固定近景，素衣男子就着烛火展信，脸色一点点沉下',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'信纸',focus:'锁定刘备沉下去的面色',stability:'stable'},
 ],
 soundscape:'拍门声，急促的喘息，烛火噼啪',
 h3sound:'Urgent knocking, ragged breathing, and the crackle of candle flame.',
 h3music:'Tense low strings rising.',
},
];