// ep13 原始分段
export default [
// 场1 S05 夜凉古城 C03 (beats 1-11)
{
 sceneIndex:1, blocking:'夜宴厅内，张飞独坐在长案后主位上，抱着酒坛喝得面红耳赤；醉兵上菜于台前踉跄，张飞劈手掼碗；校尉在侧曲身圆场。',
 cuts:[
  {beats:[1,2],seconds:5,size:'wide',camera:'Static Shot',characters:['C03'],props:[],eng:'A static wide shot at night shows a boisterous fierce warrior slumped over a long table mid-feast, face flushed red, clutching a wine jar and drinking greedily as a soldier staggers forward with dishes.',
   frame:'全景，夜宴厅内，张飞抱着酒坛喝得面红耳赤，一名醉兵上菜踉跄',shot:'固定全景，夜里宴厅中，一名黑脸猛将座椅前抱坛痛饮，一名士卒端菜踉跄上前',
   lens:'35mm 广角，中景深',cameraPosition:'张飞 + 平视侧面',composition:'三分法',eyeline:'酒坛/醉兵',focus:'锁定坛边痛饮的张飞',stability:'stable'},
  {beats:[3,3],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior as he slams the wine bowl down and flares up, {t0}',
   frame:'特写，张飞劈手把酒碗掼在案上，怒声下令重责醉兵',shot:'固定近景，黑脸猛将一把掼下酒碗，怒声喝斥',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'台下醉兵',focus:'锁定张飞面部',stability:'stable'},
 ],
 soundscape:'夜宴喧哗，酒碗迸碎的脆响',
 h3sound:'The clamor of the night feast cut by a wine bowl smashing.',
 h3music:'Booming low drums at a steady pace.',
},
{
 sceneIndex:1, blocking:'醉兵跪伏堂下连连叩头，校尉在侧按住他陪笑圆场，张飞踞坐主位扬眉喝断。',
 cuts:[
  {beats:[4,5],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the drunk soldier kneeling and kowtowing in terror while a junior officer beside him presses the man down and plays peacemaker.',
   frame:'中景，醉兵吓得跪倒连连叩头，旁边一名校尉急忙上前按住他，陪着笑打圆场',shot:'固定中景，一名醉卒跪地叩头，一名校尉上前按住他陪笑',
   lens:'50mm 标准，中景深',cameraPosition:'台前 + 平视',composition:'三分法',eyeline:'主位的张飞',focus:'锁定跪地的醉兵与圆场的校尉',stability:'stable'},
  {beats:[6,6],seconds:3.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior growling decisively, {t0}',
   frame:'特写，张飞扬声喝断，本将军说打就打哪个敢求情',shot:'固定近景，黑脸猛将扬声喝断，神态不容置疑',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'台下',focus:'锁定张飞面部',stability:'stable'},
  {beats:[7,7],seconds:3.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior declaring gruffly, {t0}',
   frame:'特写，张飞沉声自许，大哥不在这徐州就得我立规矩',shot:'固定近景，黑脸猛将沉声自许，气焰张扬',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'台下诸卒',focus:'锁定张飞面部',stability:'stable'},
  {beats:[8,8],seconds:3,size:'wide',camera:'Static Shot',characters:['C03'],props:[],eng:'A static wide shot shows two guards dragging the bound soldier out as his cries gradually recede.',
   frame:'全景，两名亲兵提着棍子把醉兵拖了出去，哭声渐渐远了',shot:'固定全景，两名亲兵将醉卒拖出堂外，哭喊声渐远',
   lens:'35mm 广角，深景深',cameraPosition:'堂内 + 平视',composition:'引导线构图',eyeline:'人被拖远的方向',focus:'锁定被拖走的醉兵',stability:'stable'},
 ],
 soundscape:'叩头求饶声，喝断声，被拖远渐息的哭声',
 h3sound:'Pleading kowtows, a decisive roar, and cries fading as the man is dragged away.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'张飞踞坐主位抓起酒坛仰头灌下，扬声招呼满堂士卒，众卒面面相觑各怀怨气。',
 cuts:[
  {beats:[9,9],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the fierce warrior grabbing the wine jar and tilting his head back for a long gulp.',
   frame:'中景，张飞又抓起酒坛仰头咕咚灌了一大口',shot:'固定中景，黑脸猛将抓起酒坛仰头猛灌一大口',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'三分法',eyeline:'手中酒坛',focus:'锁定灌酒的动作',stability:'stable'},
  {beats:[10,10],seconds:3,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior bellowing, {t0}',
   frame:'特写，张飞扬声招呼满堂，都别愣着喝',shot:'固定近景，黑脸猛将扬声催促，声若洪钟',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'满堂士卒',focus:'锁定张飞面部',stability:'stable'},
  {beats:[11,11],seconds:3,size:'wide',camera:'Static Shot',characters:['C03'],props:[],eng:'A static wide shot holds the ranks of soldiers exchanging uneasy glances, each nursing a bellyful of grievance beneath the wine haze.',
   frame:'全景，满堂士卒面面相觑，酒意里各怀着一肚子怨气',shot:'固定全景，满堂士卒面面相觑，面上各有忍色',
   lens:'35mm 广角，深景深',cameraPosition:'堂内 + 平视',composition:'对称构图',eyeline:'四散相觑',focus:'锁定士卒们隐忍的神色',stability:'stable'},
 ],
 soundscape:'吞咽声，张飞的催促，殿卒压抑的低语',
 h3sound:'The gulping of wine, the warrior\'s urging, and subdued muttering among the soldiers.',
 h3music:'N/A',
},
// 场2 S05 夜凉古城 C03 C06 props P03 (beats 1-16)
{
 sceneIndex:2, blocking:'夜凉后半夜，张飞歪倒案头酣睡；门外忽起马蹄火把如潮水般涌向城门，喊杀声与浓烟卷上城头。',
 cuts:[
  {beats:[1,1],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the fierce warrior slumped over the table, snoring heavily in a deep sleep as the night feast winds down.',
   frame:'中景，后半夜酒宴散尽，张飞歪在案头呼呼酣睡过去',shot:'固定中景，夜半宴散，黑脸猛将歪倒案头沉沉睡去',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视侧面',composition:'三分法',eyeline:'紧闭的眼',focus:'锁定酣睡的张飞',stability:'stable'},
  {beats:[2,2],seconds:3,size:'wide',camera:'Static Shot',characters:[],props:[],eng:'A static wide shot at night shows a surge of hoofbeats from outside the city wall as a tide of torches swells toward the gate.',
   frame:'全景，城外忽起一片马蹄声，火把如潮水般涌向城门',shot:'固定全景，夜城之外马蹄骤起，火把如潮涌向城门',
   lens:'35mm 广角，深景深',cameraPosition:'城头外 + 俯视远眺',composition:'引导线构图',eyeline:'涌向城门的火把',focus:'锁定奔涌的火把洪流',stability:'slight-shake'},
  {beats:[3,4],seconds:5.5,size:'medium',camera:'Static Shot',characters:[],props:[],eng:'A static medium shot holds a gate officer rushing in with a panicked report, cut short as someone forces him aside with a blade while war cries erupt and smoke rolls up onto the battlements.',
   frame:'中景，城门校尉仓皇来报话没说完就被人一刀逼开，喊杀声陡起浓烟卷上城头',shot:'固定中景，一名城门校尉仓皇闯入急报，话未说完被人一刀逼开，喊杀四起',
   lens:'50mm 标准，中景深',cameraPosition:'城门内 + 平视',composition:'三分法',eyeline:'门外喊杀',focus:'锁定被逼开的校尉与窜起的浓烟',stability:'slight-shake'},
 ],
 soundscape:'马蹄如雷，火把噼啪，喊杀声四起',
 h3sound:'Thundering hooves, crackling torches, and war cries erupting across the night city.',
 h3music:'Rumbling low drums, rising tension.',
},
{
 sceneIndex:2, blocking:'张飞被巨响惊醒踉跄起身，骂声未落，门外一名满身是血的亲兵扑进来抱着他的腰嘶喊，张飞圆睁虎目提矛欲冲。',
 cuts:[
  {beats:[5,5],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the fierce warrior jolted awake by the blast, stumbling and nearly dropping the spear in his hand.',
   frame:'中景，张飞被巨响惊醒一个踉跄，手里的蛇矛差点脱手',shot:'固定中景，黑脸猛将被响动惊醒，踉跄间手里长矛几欲脱手',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'门口',focus:'锁定张飞惊醒的身形',stability:'slight-shake'},
  {beats:[6,6],seconds:3.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior roaring in fury, {t0}',
   frame:'特写，张飞怒声喝问哪个龟孙敢到衙门口闹事',shot:'固定近景，黑脸猛将怒目圆睁，吼声如雷',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'门外',focus:'锁定张飞怒吼的面容',stability:'slight-shake'},
  {beats:[7,7],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows a blood-soaked guard bursting through the door and throwing his arms around the warrior\'s waist.',
   frame:'中景，门外一名亲兵扑进来满身是血一把抱住张飞的腰',shot:'固定中景，一名浑身是血的亲兵扑入，一把抱住黑脸猛将的腰',
   lens:'50mm 标准，中景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'张飞',focus:'锁定抱腰的亲兵',stability:'slight-shake'},
  {beats:[8,8],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior as the guard cries out, {t0}',
   frame:'特写，亲兵嘶声急报，吕布夺了城头快随末将走',shot:'固定近景，亲兵满脸血污嘶声急报',
   lens:'85mm 长焦，浅景深',cameraPosition:'亲兵 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定亲兵惶急的面容',stability:'slight-shake'},
 ],
 soundscape:'巨响，张飞的怒吼，亲兵嘶哑的急报',
 h3sound:'A great boom, the warrior\'s roar, and the guard\'s hoarse urgent cry.',
 h3music:'Driving war drums, fast and sharp.',
},
{
 sceneIndex:2, blocking:'张飞酒醒一半虎目圆睁提矛要冲，几名亲兵死死箍住他的臂膀硬拖往侧门；他连声呼喝叫骂。',
 cuts:[
  {beats:[9,9],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:[],eng:'A static medium shot shows the fierce warrior snapping fully alert, eyes blazing, hoisting his spear and charging for the door.',
   frame:'中景，张飞酒醒了一半虎目圆睁提矛便要往外冲',shot:'固定中景，黑脸猛将酒醒大半，圆睁虎目提矛欲冲',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'门外',focus:'锁定张飞提矛的身形',stability:'slight-shake'},
  {beats:[10,10],seconds:2,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior shouting to fight, {t0}',
   frame:'特写，张飞嘶声叫嚷，老子去跟他拼了',shot:'固定近景，黑脸猛将嘶声高呼，状若拼命',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'门外',focus:'锁定张飞怒面',stability:'handheld'},
  {beats:[11,11],seconds:3,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior bellowing for his spear, {t0}',
   frame:'特写，张飞连声喝问我的矛呢都给我闪开',shot:'固定近景，黑脸猛将连声喝问长矛，急躁暴怒',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'身前',focus:'锁定张飞面部',stability:'handheld'},
  {beats:[12,12],seconds:3,size:'wide',camera:'Static Shot',characters:['C03'],props:[],eng:'A static wide shot shows several guards locking their arms around the warrior and dragging him bodily toward the side gate.',
   frame:'全景，几名亲兵死死箍住张飞的臂膀，硬拖着他往侧门走',shot:'固定全景，数名亲兵箍住黑脸猛将臂膀，连拖带拽向侧门',
   lens:'35mm 广角，中景深',cameraPosition:'厅堂 + 平视侧面',composition:'引导线构图',eyeline:'侧门',focus:'锁定被拖拽的张飞',stability:'slight-shake'},
 ],
 soundscape:'挣扎呼喝，金属与衣甲的碰撞，门外喊杀愈近',
 h3sound:'Struggling shouts, clashing harnesses, and the war cries drawing closer.',
 h3music:'Rapid war drums, relentless.',
},
{
 sceneIndex:2, blocking:'吕布已踏血立上城头，仗着方天画戟傲然俯视；张飞被亲卫护着翻墙逃出，回望满城已是火海。',
 cuts:[
  {beats:[13,13],seconds:3,size:'wide',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static wide shot shows a proud warrior standing bloodstained atop the battlement, leaning on a long ornate halberd as he gazes down with contempt.',
   frame:'全景，吕布已踏血立上城头，仗着方天画戟傲然俯视',shot:'固定全景，一名甲胄悍将踏血立于城头，手拄方天画戟傲然俯视',
   lens:'35mm 广角，深景深',cameraPosition:'吕布 + 低角度仰视',composition:'低角度构图',eyeline:'城下败将',focus:'锁定仗戟傲立的吕布',stability:'stable'},
  {beats:[14,14],seconds:4,size:'close',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static close-up holds the proud warrior taunting with a drawl, {t0}',
   frame:'特写，吕布眯眼轻蔑地扬声冷嘲',shot:'固定近景，甲胄悍将眯眼扬语，神态倨傲',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'城下',focus:'锁定吕布倨傲的面容',stability:'stable'},
  {beats:[15,16],seconds:5.5,size:'wide',camera:'Static Shot',characters:['C03','C06'],props:['P03'],eng:'A static wide shot shows the proud warrior sweeping a hand forward as a tide of torches floods the mansion gate, while the fierce warrior is hauled over the wall in escape, glancing back to see the whole city engulfed in flames.',
   frame:'全景，吕布一挥手火把如潮水般灌进府门，张飞被亲卫护着翻墙逃出回头一望满城已是火海',shot:'固定全景，城头悍将挥手，火把洪流灌入府门；黑脸猛将被亲卫护着翻墙而出，回望满城火海',
   lens:'35mm 广角，深景深',cameraPosition:'空中俯瞰 + 平视',composition:'大远景构图',eyeline:'回望火海的张飞',focus:'锁定翻墙逃出的张飞与满城火海',stability:'stable'},
 ],
 soundscape:'火把噼啪如潮，甲叶与画戟的金属声，火势的闷响',
 h3sound:'The whoosh of torches, clinking armor, and the low roar of spreading flames.',
 h3music:'Solemn low brass over rumbling fire.',
},
// 场3 S05 城下晨光 C01 C02 (beats 1-15)
{
 sceneIndex:3, blocking:'天色微明的小沛城下，一骑快马连夜闯入；刘备披衣出府接报，伸出的手在半空僵住，关羽披甲赶到结伴随后。',
 cuts:[
  {beats:[1,2],seconds:5,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot at first light shows a lone rider galloping hard into the small town beneath the walls; the lord steps out in his robe, reaches for the dispatch, and his hand freezes mid-air.',
   frame:'全景，天色微明小沛城下一骑快马连夜闯入，刘备披衣出府接过军报伸出的手在半空僵住',shot:'固定全景，晨光里一骑快马闯入小沛城下，素衣男子披衣出府接报，伸出的手在空中僵住',
   lens:'35mm 广角，深景深',cameraPosition:'刘备 + 平视侧面',composition:'引导线构图',eyeline:'手中军报',focus:'锁定僵在半空的手',stability:'stable'},
  {beats:[3,3],seconds:2.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord asking faintly, {t0}',
   frame:'特写，刘备低声失神地问，徐州当真失守了',shot:'固定近景，素衣男子低声发问，神色恍惚',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'军报',focus:'锁定刘备失神的面色',stability:'stable'},
 ],
 soundscape:'马蹄渐歇，晨风，人声低沉',
 h3sound:'Hooves slowing, the morning wind, and a low hush.',
 h3music:'Low melancholic strings at a slow tempo.',
},
{
 sceneIndex:3, blocking:'小沛府外，刘备居前手捧军报，关羽披甲赶到立于其侧，二人望着城门方向。',
 cuts:[
  {beats:[4,5],seconds:5,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot shows a tall armored general hurrying over with brows knotted tight; his lord spreads the dispatch open, fingertips trembling faintly.',
   frame:'中景，关羽披甲赶到眉头拧成死结，刘备展开军报指尖微微发颤',shot:'固定中景，一名披甲大将急步赶到眉结难展，素衣男子展开军报指尖轻颤',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'手中军报',focus:'锁定发颤的指尖',stability:'stable'},
  {beats:[6,6],seconds:4.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the armored general voicing the dread, {t0}',
   frame:'特写，关羽沉声道二弟在城三弟在泗水恐已被乱军冲散',shot:'固定近景，披甲大将沉声说出最坏的担忧',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽神色',stability:'stable'},
  {beats:[7,7],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord letting out a keen regret, {t0}',
   frame:'特写，刘备咬牙道吕布好快的刀我道他还在城外安营',shot:'固定近景，素衣男子咬牙低叹，眼底又惊又恨',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'城门',focus:'锁定刘备面部',stability:'stable'},
 ],
 soundscape:'衣甲细响，晨风里压低的交谈',
 h3sound:'The rustle of armor and hushed, urgent talk in the morning breeze.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'刘备望了望城头那面旗深吸一口气，扬声传令收拢残部；城门外尘土又起，一名哨探滚鞍下马急报。',
 cuts:[
  {beats:[8,9],seconds:5,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot holds the lord drawing a deep breath as he gazes at the banner over the town, then giving the order, {t0} to rally the scattered troops.',
   frame:'中景，刘备望着小沛城头那面旗深吸一口气，扬声下令各自收拢残部约到小沛会合',shot:'固定中景，素衣男子望旗深吸，随即扬声传令收拢残部',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'城头旗帜',focus:'锁定下令的刘备',stability:'stable'},
  {beats:[10,10],seconds:3,size:'wide',camera:'Static Shot',characters:['C02'],props:[],eng:'A static wide shot shows dust rising beyond the town gate as a scout reels from his horse.',
   frame:'全景，城外尘土又起，一名哨探滚鞍下马',shot:'固定全景，城门外尘土扬起，一名哨探翻身落马',
   lens:'35mm 广角，深景深',cameraPosition:'城门 + 平视',composition:'引导线构图',eyeline:'滚鞍下马的哨探',focus:'锁定落马的哨探',stability:'stable'},
  {beats:[11,11],seconds:4.5,size:'close',camera:'Static Shot',characters:['C02'],props:[],eng:'A static close-up holds the armored general relaying the scout\'s warning, {t0}',
   frame:'特写，关羽回禀西面有追兵看成色像是吕布的人马',shot:'固定近景，披甲大将沉声转告哨探急报',
   lens:'85mm 长焦，浅景深',cameraPosition:'关羽 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定关羽面部',stability:'stable'},
 ],
 soundscape:'尘土与马蹄，紧张的报讯，晨风',
 h3sound:'Rising dust, hurried hoofbeats, and tense reports carried on the morning wind.',
 h3music:'N/A',
},
{
 sceneIndex:3, blocking:'刘备立时定住神色回府收好大印，与关羽翻身上马踏着晨雾疾驰而去；身后小沛城门缓缓合拢，吊桥拉起。',
 cuts:[
  {beats:[12,13],seconds:5.5,size:'medium',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static medium shot holds the lord steadying his face, turning back into the house to secure the great seal, then speaking with grim resolve, {t0}',
   frame:'中景，刘备立时定住神色转身回府收好大印，随即沉声道留得命在徐州终究能夺回来',shot:'固定中景，素衣男子收敛神色回府收好大印，再出门时已沉稳下来',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'前方',focus:'锁定刘备定住的神情',stability:'stable'},
  {beats:[14,15],seconds:5.5,size:'wide',camera:'Static Shot',characters:['C01','C02'],props:[],eng:'A static wide shot shows the two men mounting and riding hard off through the morning mist and trailing dust, while behind them the town gate slowly closes and the drawbridge hauls up with a groan.',
   frame:'全景，二人翻身上马踏着晨雾与烟尘疾驰而去，身后小沛城门缓缓合拢吊桥吱呀一声拉起',shot:'固定全景，两人翻身上马踏雾疾驰远去，身后城门缓合、吊桥拉起',
   lens:'35mm 广角，深景深',cameraPosition:'远处 + 平视远眺',composition:'引导线构图',eyeline:'策马远去的二人',focus:'锁定渐远的双骑与合拢的城门',stability:'stable'},
 ],
 soundscape:'马蹄疾驰，吊桥绞索的吱呀声，晨雾渐合',
 h3sound:'Galloping hooves, the groan of the drawbridge rope, and the closing of the gate.',
 h3music:'Solemn low strings, resolute.',
},
// 场4 S05 城下晨光 C01 C06 (beats 1-14)
{
 sceneIndex:4, blocking:'数日后徐州城下，吕布高坐赤兔马上志得意满居中，刘备单骑立于阵前拱手相商，两军隔沙场相望。',
 cuts:[
  {beats:[1,1],seconds:3,size:'wide',camera:'Static Shot',characters:['C06'],props:[],eng:'A static wide shot shows a proud warrior seated high on his crimson steed before the city, flushed with complacency, banners newly changed behind him.',
   frame:'全景，数日后徐州城下，吕布高坐赤兔马上志得意满',shot:'固定全景，一名甲胄悍将高踞赤兔马上立于徐州城下，意气风发',
   lens:'35mm 广角，深景深',cameraPosition:'吕布 + 平视',composition:'对称构图',eyeline:'阵前',focus:'锁定踞马而立的吕布',stability:'stable'},
  {beats:[2,2],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot shows the lord, alone on horseback, offering the proud warrior a respectful clasped salute before the two lines of troops.',
   frame:'中景，刘备单骑立于阵前，朝吕布拱了拱手',shot:'固定中景，素衣男子单骑立于阵前，向城下悍将拱手行礼',
   lens:'50mm 标准，中浅景深',cameraPosition:'刘备 + 平视正面',composition:'三分法',eyeline:'吕布',focus:'锁定拱手行礼的刘备',stability:'stable'},
  {beats:[3,3],seconds:5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord requesting refuge in a low, measured tone, {t0}',
   frame:'特写，刘备拱手陈词，容我与二位贤弟借小沛暂栖',shot:'固定近景，素衣男子低姿态拱手陈词',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定刘备恳请的神情',stability:'stable'},
 ],
 soundscape:'沙场风沙，旌旗猎猎，马蹄轻踏',
 h3sound:'Desert wind, snapping banners, and horses shifting restlessly.',
 h3music:'Low court drums, cautious.',
},
{
 sceneIndex:4, blocking:'吕布眯眼打量眼前败军之将，扬声应下；刘备低头又深深一拜。',
 cuts:[
  {beats:[4,4],seconds:3,size:'medium',camera:'Static Shot',characters:['C06'],props:[],eng:'A static medium shot holds the proud warrior narrowing his eyes, sizing up the defeated general before him.',
   frame:'中景，吕布眯起眼，打量眼前这个败军之将',shot:'固定中景，城下悍将眯起眼来回打量败将',
   lens:'50mm 标准，中浅景深',cameraPosition:'吕布 + 平视正面',composition:'三分法',eyeline:'刘备',focus:'锁定吕布打量的目光',stability:'stable'},
  {beats:[5,5],seconds:4,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior answering with feigned magnanimity, {t0}',
   frame:'特写，吕布笑道玄德兄素以仁德闻名我岂能不容',shot:'固定近景，城下悍将从容回话，语气敷衍大度',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定吕布面部',stability:'stable'},
  {beats:[6,6],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up shows the lord lowering his head and bowing deeply once more.',
   frame:'特写，刘备低下头，又深深拜了一拜',shot:'固定近景，素衣男子低头深拜，姿态谦卑',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视侧面',composition:'中心构图',eyeline:'马前的土地',focus:'锁定深拜下去的刘备',stability:'stable'},
  {beats:[7,7],seconds:2,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord murmuring his thanks, {t0}',
   frame:'特写，刘备低声道谢，多谢布兄美意',shot:'固定近景，素衣男子低声道谢，声气低沉',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定刘备面部',stability:'stable'},
 ],
 soundscape:'沙场低风，叩谢的低声，马蹄轻响',
 h3sound:'A low desert wind, murmured thanks, and soft hoofbeats.',
 h3music:'N/A',
},
{
 sceneIndex:4, blocking:'吕布扬鞭大笑一夹马腹扬尘疾驰回城；刘备独自立在当场，望着城楼新换的旗号，缓缓攥紧了手掌。',
 cuts:[
  {beats:[8,8],seconds:4.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior issuing a veiled warning, {t0}',
   frame:'特写，吕布居高临下地劝道，这人吃人的世道处处得小心些',shot:'固定近景，城下悍将随口劝诫，语带深意',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定吕布面部',stability:'stable'},
  {beats:[9,9],seconds:3,size:'wide',camera:'Static Shot',characters:['C06'],props:[],eng:'A static wide shot shows the proud warrior cracking his whip with a great laugh and galloping back into the city in a cloud of dust.',
   frame:'全景，吕布扬鞭大笑，一夹马腹扬尘疾驰回城',shot:'固定全景，城下悍将扬鞭大笑，策马扬尘冲回城内',
   lens:'35mm 广角，深景深',cameraPosition:'侧面 + 平视',composition:'引导线构图',eyeline:'扬尘回城的吕布',focus:'锁定策马回城的背影',stability:'stable'},
  {beats:[10,10],seconds:3,size:'medium',camera:'Push In',characters:['C01'],props:[],eng:'A slow push in tightens on the lord standing alone where he stood, staring at the newly changed banner over the gate as his hand slowly clenches.',
   frame:'中景，刘备独自立在当场望着城楼新换的旗号，攥紧了手掌',shot:'镜头小幅缓推，素衣男子独自立于原地，望城头新旗，缓缓攥紧手掌',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'城楼新旗',focus:'锁定刘备攥紧的手掌',stability:'stable'},
 ],
 soundscape:'马蹄疾去，旗幡作响，风沙骤起',
 h3sound:'Hooves receding, banners snapping, and gusts of desert wind.',
 h3music:'Thin, uneasy strings.',
},
{
 sceneIndex:4, blocking:'刘备仍立于城下，接连低声吐出两句心声，末了画外自语；城头哨探又将一封密信悄悄递到他手上。',
 cuts:[
  {beats:[11,11],seconds:3.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord murmuring his fixed resolve, {t0}',
   frame:'特写，刘备垂眸低语，借得住小沛借不住一颗杀心',shot:'固定近景，素衣男子垂眸低语，眉间阴沉',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'城楼',focus:'锁定刘备阴沉的眉眼',stability:'stable'},
  {beats:[12,12],seconds:2.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord vowing quietly, {t0}',
   frame:'特写，刘备低声记下今日之辱，我记下了',shot:'固定近景，素衣男子低声立誓，神色冷硬',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'城楼',focus:'锁定刘备面部',stability:'stable'},
  {beats:[13,13],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord as his inner voice speaks in an off-screen voiceover while his lips remain closed, {t0}',
   frame:'特写，刘备凝望城头，画外响起自己的心声',shot:'固定近景，素衣男子凝望城头，双唇紧抿，画外轻诉心志',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'城楼新旗',focus:'锁定刘备沉凝的眼底',stability:'stable'},
  {beats:[14,14],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot shows a sentry stepping down to quietly slip a sealed letter into the lord\'s hand.',
   frame:'中景，城门哨探又悄悄将一封密信递到刘备手上',shot:'固定中景，一名哨探从城头下来，将一封密信悄递进素衣男子手中',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'手中密信',focus:'锁定递信的双手',stability:'stable'},
 ],
 soundscape:'风沙卷衣，低声的心声渐渐淡去，衣甲轻响',
 h3sound:'Wind churning robes, fading murmured thoughts, and the rustle of armor.',
 h3music:'Low, ominous strings fading.',
},
];