// ep14 原始分段
export default [
// 场1 S05 烈日校场 C01 C03 C06 props P03 (beats 1-35)
{
 sceneIndex:1, blocking:'烈日校场，袁刘两军隔沙场列阵对峙，吕布一骑当先纵马立于正中，刘备在刘阵一侧按住躁动的部曲。',
 cuts:[
  {beats:[1,2],seconds:5,size:'wide',camera:'Static Shot',characters:['C01','C06'],props:[],eng:'A static wide shot under blazing sun shows two armies arrayed across the drilling field, and a proud warrior on a crimson steed spurring to the middle of the field, raising a hand to hold the standoff.',
   frame:'全景，烈日校场袁刘两军隔沙场列阵对峙，吕布一骑当先纵马立于两阵正中抬手压住局面',shot:'固定全景，烈日下两军隔场对峙，一名甲胄悍将独骑立于阵中抬手压住局面',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视正面',composition:'对称构图',eyeline:'两阵',focus:'锁定阵中的吕布',stability:'stable'},
  {beats:[3,3],seconds:5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior commanding the field, {t0}',
   frame:'特写，吕布扬声道，都给某家住手今日这仗两家谁也打不得',shot:'固定近景，甲胄悍将扬声喝止，气盖全场',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'两阵军将',focus:'锁定吕布面部',stability:'stable'},
 ],
 soundscape:'烈日风沙，战马嘶鸣，两军甲叶轻响',
 h3sound:'Blazing wind, horses snorting, and the faint clink of harnesses across the field.',
 h3music:'Low war drums held at a simmer.',
},
{
 sceneIndex:1, blocking:'阵中，刘备在刘军阵前按部曲；袁军主将怒目，张飞在侧扬声质问，吕布据画戟应答。',
 cuts:[
  {beats:[4,4],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot shows an enemy general glaring furiously from the opposing ranks while the lord beside keeps his restless troops pinned in check.',
   frame:'中景，袁军主将纪灵在阵中怒目而视，刘备在一旁按住躁动的部曲',shot:'固定中景，对面阵中一员敌将怒目，素衣男子在己方阵前按住躁动部曲',
   lens:'50mm 标准，中景深',cameraPosition:'刘阵 + 平视侧面',composition:'三分法',eyeline:'敌阵',focus:'锁定按兵不动的刘备与怒目敌将',stability:'stable'},
  {beats:[5,5],seconds:3,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior demanding to know, {t0}',
   frame:'特写，张飞扬声质问，你凭什么拦我们两家',shot:'固定近景，黑脸猛将扬声质问，气势逼人',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定张飞面部',stability:'stable'},
  {beats:[6,6],seconds:3,size:'close',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static close-up holds the proud warrior answering with a flick of his halberd, {t0}',
   frame:'特写，吕布扬了扬掌中的方天画戟，轻描淡写地应答',shot:'固定近景，甲胄悍将轻扬掌中画戟，漫不经心地回话',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'画戟刃锋',focus:'锁定吕布与画戟',stability:'stable'},
 ],
 soundscape:'敌阵怒喝，张飞的质问，画戟刃锋轻鸣',
 h3sound:'A growl from the enemy, the warrior\'s challenge, and the ring of the halberd blade.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'刘备在阵前扬声陈情，吕布据赤兔马漫然回应，二人隔沙场对答。',
 cuts:[
  {beats:[7,7],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord pleading in a measured voice, {t0}',
   frame:'特写，刘备拱手陈情，袁术兵犯我境还请布兄主持公道',shot:'固定近景，素衣男子拱手陈情，语带恳请',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定刘备面部',stability:'stable'},
  {beats:[8,8],seconds:3.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior replying with cool self-assurance, {t0}',
   frame:'特写，吕布漫声回应，公道不公道某家自有道理',shot:'固定近景，甲胄悍将漫声回话，胸有成竹',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定吕布面部',stability:'stable'},
 ],
 soundscape:'沙场风沙，马蹄轻踏，对答的低语',
 h3sound:'Desert wind, shifting hooves, and a pair of unhurried exchanges.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'吕布翻身下马，命军士在校场中央立起一杆大画戟，随即弯弓搭箭遥遥指向戟尖小枝。',
 cuts:[
  {beats:[9,10],seconds:6,size:'medium',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static medium shot shows the proud warrior dismounting, ordering a soldier to plant a tall halberd upright at the center of the field, then proposing a wager, {t0}',
   frame:'中景，吕布翻身下马命军士在校场中央立起一杆大画戟，扬声要与二位立个赌约给大家消消火',shot:'固定中景，甲胄悍将翻下马，命军士在中央立起一杆画戟，扬声立约',
   lens:'50mm 标准，中景深',cameraPosition:'吕布 + 平视侧面',composition:'三分法',eyeline:'中央大戟',focus:'锁定立起的画戟与吕布',stability:'stable'},
  {beats:[11,11],seconds:3,size:'close',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static close-up holds the proud warrior drawing his bow, aligning the arrow with the small branch at the halberd tip in the distance.',
   frame:'特写，吕布弯弓搭箭，遥遥指向远处那戟尖的一截小枝',shot:'固定特写，甲胄悍将弯弓搭箭，箭尖遥遥对准远处戟尖小枝',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视侧面',composition:'中心构图',eyeline:'远处戟尖',focus:'锁定搭上弦的箭',stability:'stable'},
 ],
 soundscape:'军士的脚步声，弓弦拉开的轻响，满场渐静',
 h3sound:'Soldiers moving, a bowstring creaking, and the field falling hush.',
 h3music:'Low percussion, sharp and expectant.',
},
{
 sceneIndex:1, blocking:'吕布扬声立下赌约，满场军将屏息，目光齐齐落在那根大戟上。',
 cuts:[
  {beats:[12,12],seconds:4.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior laying down the wager, {t0}',
   frame:'特写，吕布扬声说明赌约，我一箭射中那戟尖折枝两家就此各退',shot:'固定近景，甲胄悍将扬声立下赌约',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'远处大戟',focus:'锁定吕布面部',stability:'stable'},
  {beats:[13,13],seconds:5,size:'wide',camera:'Static Shot',characters:['C01','C03','C06'],props:['P03'],eng:'A static wide shot holds the field of soldiers holding their breath, every gaze fixed on the halberd standing at the center.',
   frame:'全景，满场军将屏住呼吸，目光齐齐落在那根立着的画戟上',shot:'固定全景，满场军将屏息，目光齐齐落在中央那杆画戟上',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视正面',composition:'对称构图',eyeline:'中央画戟',focus:'锁定屏息的众军与中央大戟',stability:'stable'},
 ],
 soundscape:'满场屏息，风沙掠过画戟的轻响',
 h3sound:'The whole field holds its breath as the wind passes over the halberd.',
 h3music:'A single tense drumbeat.',
},
{
 sceneIndex:1, blocking:'张飞扬声讥刺，吕布连激两句，张飞七窍生烟几欲发作被刘备低声止住。',
 cuts:[
  {beats:[14,14],seconds:3.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior taunting with scorn, {t0}',
   frame:'特写，张飞不屑道，就凭你一箭也敢拿我们做注',shot:'固定近景，黑脸猛将扬声讥刺，满脸不屑',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定张飞面部',stability:'stable'},
  {beats:[15,15],seconds:3.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior baiting him, {t0}',
   frame:'特写，吕布慢声道，你要怕输大可领着兵先走',shot:'固定近景，甲胄悍将慢条斯理地激将',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定吕布面部',stability:'stable'},
  {beats:[16,16],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static medium shot shows the fierce warrior blazing with fury and about to erupt, only for the lord to hold him back with a low word.',
   frame:'中景，张飞气得七窍生烟瞪圆了眼就要发作，被刘备低声止住',shot:'固定中景，黑脸猛将怒目欲发，素衣男子在旁低声按住他',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'张飞怒目/刘备按住',focus:'锁定要发作的张飞',stability:'stable'},
 ],
 soundscape:'张飞的怒哼，吕布的激将，兵甲骚动',
 h3sound:'The warrior\'s angry grunt, the proud man\'s taunt, and a stir of harnesses.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'吕布朗声大笑策马兜了个圈重新立于沙场正中，勒住赤兔缓缓张弓，把箭稳稳搭上弦，扬声喝令。',
 cuts:[
  {beats:[17,18],seconds:5.5,size:'medium',camera:'Tracking Shot',characters:['C06'],props:['P03'],eng:'A tracking shot follows the proud warrior wheeling his crimson steed in a wide loop back to the center, reining in and slowly drawing the bow, fitting the arrow to the string.',
   frame:'中景，吕布朗声大笑策马兜了个圈重新立在沙场正中，勒住赤兔缓缓张弓把箭稳稳搭上弦',shot:'镜头跟随甲胄悍将策马绕场一圈回正，勒马、缓缓张弓搭上弦',
   lens:'50mm 标准，中景深',cameraPosition:'吕布 + 侧面平视跟随',composition:'引导线构图',eyeline:'远处戟尖',focus:'锁定搭上弦的箭与箭尖',stability:'slight-shake'},
  {beats:[19,19],seconds:4,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior bracing the bow as he speaks, {t0}',
   frame:'特写，吕布稳稳拉满弓，扬声喝道看好了这一箭定我两家去留',shot:'固定近景，甲胄悍将拉满长弓，眼神锁定远处',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'远处戟尖',focus:'锁定吕布凝注的眼神',stability:'stable'},
  {beats:[20,20],seconds:3,size:'close',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'An extreme lunging detail holds as the arrow splits the air and strikes the small branch at the tip of the halberd, snapping it cleanly.',
   frame:'特写，利箭破空而去正中戟尖小枝，应声而折',shot:'固定特写，一支利箭破空正中戟尖小枝，小枝应声折断',
   lens:'100mm 微距，极浅景深',cameraPosition:'箭与戟尖 + 平视',composition:'中心构图',eyeline:'折断的小枝',focus:'锁定中箭折断的戟尖',stability:'slight-shake'},
 ],
 soundscape:'马蹄绕场，弓弦绷紧，利箭破空的锐响，小枝折断声',
 h3sound:'Hooves circling, a bowstring drawn taut, the sharp hiss of the arrow, and the crack of the snapped branch.',
 h3music:'A sharp sting of drums.',
},
{
 sceneIndex:1, blocking:'全场先是一瞬死寂，随即轰然爆出一片叫好，张飞也扬声喝彩；袁军主将面如死灰勒马停在原地。',
 cuts:[
  {beats:[21,22],seconds:5,size:'wide',camera:'Static Shot',characters:['C06'],props:[],eng:'A static wide shot shows the field frozen in one instant of dead silence, then erupting into a thunderous roar of applause, {t0}',
   frame:'全景，全场先是死一般寂静，随即轰然爆出一片叫好，张飞的喝声也在其中',shot:'固定全景，全场一瞬死寂随即轰然叫好，人声如潮',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视正面',composition:'对称构图',eyeline:'翻涌的人潮',focus:'锁定爆发出叫好的人潮',stability:'stable'},
  {beats:[23,23],seconds:3,size:'medium',camera:'Static Shot',characters:[],props:[],eng:'A static medium shot shows the enemy general, his face drained of color, reining his horse to a standstill where he is.',
   frame:'中景，袁军主将纪灵面如死灰，一甩马缰勒马停在原地',shot:'固定中景，对面阵中一员敌将面色灰败，勒马停在原地',
   lens:'50mm 标准，中浅景深',cameraPosition:'敌阵 + 平视',composition:'三分法',eyeline:'中央断枝',focus:'锁定灰败勒马的敌将',stability:'stable'},
 ],
 soundscape:'死寂一瞬，随即轰然的人声与叫好',
 h3sound:'A single dead silence, then a thunderous swell of cheers.',
 h3music:'Triumphant low brass.',
},
{
 sceneIndex:1, blocking:'吕布扬声问服，袁军主将咬牙未发；刘备拱手道谢，袁军依约缓缓退去。',
 cuts:[
  {beats:[24,24],seconds:4,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior asking for submission, {t0}',
   frame:'特写，吕布扬声问道，天命如此纪将军你可服气',shot:'固定近景，甲胄悍将扬声逼问',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'敌阵',focus:'锁定吕布面部',stability:'stable'},
  {beats:[25,25],seconds:3,size:'medium',camera:'Static Shot',characters:[],props:[],eng:'A static medium shot shows the enemy general clenching his jaw at the broken branch, yet making no outburst.',
   frame:'中景，袁军主将纪灵咬牙看着那截断枝，终究没有发作',shot:'固定中景，敌将看着断枝重重咬牙，终究没有发作',
   lens:'50mm 标准，中浅景深',cameraPosition:'敌阵 + 平视',composition:'三分法',eyeline:'眼前的断枝',focus:'锁定咬牙按捺的敌将',stability:'stable'},
  {beats:[26,26],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord giving thanks, {t0}',
   frame:'特写，刘备拱手道谢，有劳布兄鼎力两家化干戈为玉帛',shot:'固定近景，素衣男子拱手道谢，语带敬意',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定刘备面部',stability:'stable'},
 {beats:[27,27],seconds:3,size:'wide',camera:'Static Shot',characters:['C01'],props:[],eng:'A static wide shot shows the enemy troops withdrawing slowly as agreed while the lord has his forces reorganized, quietly letting out the breath held in him.',
   frame:'全景，袁军依约缓缓退去，刘备命人收拢军阵暗暗松了口气',shot:'固定全景，敌阵依约缓缓退去，素衣男子命人收拢军阵，暗暗松了口气',
   lens:'35mm 广角，深景深',cameraPosition:'校场 + 平视侧面',composition:'引导线构图',eyeline:'退去的袁军',focus:'锁定退军与松口气的刘备',stability:'stable'},
 ],
 soundscape:'袁军退去的马蹄与脚步，兵甲渐远，刘备松气的声音',
 h3sound:'Horses and footfalls as the enemy withdraws, and the lord\'s long, quiet exhale.',
 h3music:'Solemn, settling strings.',
},
{
 sceneIndex:1, blocking:'袁军退尽，刘备望着吕布背影低语一句，末了又补一句冷话；张飞在侧跺矛欲上被亲兵拉住。',
 cuts:[
  {beats:[28,29],seconds:6,size:'medium',camera:'Static Shot',characters:['C01','C06'],props:[],eng:'A static medium shot holds the lord murmuring that the arrow has undone the siege for them, {t0}, then lifts his eyes toward that figure with no gratitude at all in them.',
   frame:'中景，刘备低声说吕布这一箭倒替我们解了大围，随即抬眸望向那人，眼底却没有半分感激之色',shot:'固定中景，素衣男子低声道谢意，抬眼望去眼底却无半分感激',
   lens:'50mm 标准，中浅景深',cameraPosition:'刘备 + 平视',composition:'三分法',eyeline:'望远的吕布背影',focus:'锁定刘备冷淡的眼底',stability:'stable'},
  {beats:[30,30],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord speaking his true thought, {t0}',
   frame:'特写，刘备低声自语，这一箭的恩终究是要拿血来还的',shot:'固定近景，素衣男子低语，眼底阴沉',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'远处',focus:'锁定刘备面部',stability:'stable'},
  {beats:[31,31],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static medium shot shows the fierce warrior stamping his foot into the dirt and starting forward, held back by the guards.',
   frame:'中景，张飞把脚往地上一跺，几步正要上前被亲兵拉住',shot:'固定中景，黑脸猛将把脚往地上一跺，迈步欲上被亲兵拉住',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视',composition:'三分法',eyeline:'吕布方向',focus:'锁定一脚跺地要上的张飞',stability:'stable'},
 ],
 soundscape:'刘备低语，一脚跺地的闷响，亲兵低声劝阻',
 h3sound:'The lord\'s low words, the dull thud of a foot stamping, and guards muttering restraint.',
 h3music:'Low, uneasy strings.',
},
{
 sceneIndex:1, blocking:'张飞扬声要跟吕布说明白记下徐州之仇，刘备按住他手臂缓缓摇头示意不可莽撞。',
 cuts:[
  {beats:[32,32],seconds:5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior vowing the score, {t0}',
   frame:'特写，张飞扬声道，容我跟他说明白这徐州之仇记下了',shot:'固定近景，黑脸猛将扬声立誓，满腔怒火',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'吕布方向',focus:'锁定张飞怒气未平的面容',stability:'stable'},
  {beats:[33,33],seconds:3,size:'medium',camera:'Static Shot',characters:['C01','C03'],props:[],eng:'A static medium shot shows the lord pressing the fierce warrior\'s arm and shaking his head slowly, urging caution.',
   frame:'中景，刘备按住张飞的手臂，缓缓摇了摇头示意不可莽撞',shot:'固定中景，素衣男子伸手按住猛将手臂，缓缓摇头',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'张飞',focus:'锁定按臂摇头的刘备',stability:'stable'},
 ],
 soundscape:'张飞粗重的喘息，刘备低声的劝止',
 h3sound:'The warrior\'s heavy breathing and the lord\'s low, calming word.',
 h3music:'N/A',
},
{
 sceneIndex:1, blocking:'刘备按着张飞沉声剖析利害，张飞愤愤不平地回一句。',
 cuts:[
  {beats:[34,34],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord counseling patience, {t0}',
   frame:'特写，刘备沉声劝道，三弟稍安眼下他握着袁刘两家的命脉',shot:'固定近景，素衣男子沉声剖析，神色凝重',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定刘备面部',stability:'stable'},
  {beats:[35,35],seconds:3.5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior answering with resentful pride, {t0}',
   frame:'特写，张飞愤声道，那也不能让他给你我脸色看',shot:'固定近景，黑脸猛将愤愤回嘴，满脸不服',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
 ],
 soundscape:'两军收兵的声响，张飞压抑的愤声',
 h3sound:'Troops reforming in the distance and a stifled word of resentment.',
 h3music:'N/A',
},
// 场2 S05 烈日校场 C01 C03 C06 props P03 P06 (beats 1-16)
{
 sceneIndex:2, blocking:'众人散去，吕布握着那截断枝缓缓行到张飞面前，张飞按着丈八蛇矛虎目相对。',
 cuts:[
  {beats:[1,1],seconds:3,size:'medium',camera:'Static Shot',characters:['C06'],props:[],eng:'A static medium shot shows, as the crowd disperses, the proud warrior carrying the broken branch slowly walking up to the fierce warrior.',
   frame:'中景，众人散去，吕布握着那截断枝缓缓行到张飞面前',shot:'固定中景，众人散去，甲胄悍将握着断枝缓步来到黑脸猛将面前',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'张飞',focus:'锁定拄枝走近的吕布',stability:'stable'},
  {beats:[2,2],seconds:4.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior speaking with a quiet edge, {t0}',
   frame:'特写，吕布低头把玩断枝，缓声道今日这一箭替你大哥保下了性命',shot:'固定近景，甲胄悍将垂眸把玩断枝，语带傲意',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'手中断枝',focus:'锁定吕布与断枝',stability:'stable'},
  {beats:[3,3],seconds:3,size:'medium',camera:'Static Shot',characters:['C03'],props:['P06'],eng:'A static medium shot shows the fierce warrior staring wide-eyed, hand resting on his serpent spear, giving no answer.',
   frame:'中景，张飞虎目圆睁按着蛇矛，没有应声',shot:'固定中景，黑脸猛将圆睁虎目手按蛇矛，沉默不应',
   lens:'50mm 标准，中浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定按矛沉默的张飞',stability:'stable'},
 ],
 soundscape:'沙场将散的脚步，人声远去，断枝摩挲声',
 h3sound:'Scattered footsteps fading, and the rubbing of the broken branch in hand.',
 h3music:'Lean, uneasy strings.',
},
{
 sceneIndex:2, blocking:'吕布与张飞隔着断枝相对，一个傲然逼话，一个按矛硬顶。',
 cuts:[
  {beats:[4,4],seconds:4.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior pressing the claim, {t0}',
   frame:'特写，吕布缓声道，你记好这份情我迟早要你刘备来还',shot:'固定近景，甲胄悍将逼近一步，语带威胁',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定吕布面部',stability:'stable'},
  {beats:[5,5],seconds:5,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior answering hard, {t0}',
   frame:'特写，张飞冷声回敬，一箭之惠是一箭之惠夺城之仇是夺城之仇',shot:'固定近景，黑脸猛将冷声回敬，毫不相让',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'吕布',focus:'锁定张飞面部',stability:'stable'},
 ],
 soundscape:'两人针锋相对的低话，沙场风沙',
 h3sound:'Two bristling voices, close, over the desert wind.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'吕布不恼反笑翻身上马，居高临下撂下一句话，随之一夹马腹扬长而去卷起一路黄尘。',
 cuts:[
  {beats:[6,6],seconds:3,size:'medium',camera:'Static Shot',characters:['C06'],props:['P03'],eng:'A static medium shot shows the proud warrior laughing, unruffled, vaulting onto his horse with halberd in hand and looking down from the saddle.',
   frame:'中景，吕布不恼反笑翻身提戟上马，居高临下望着张飞',shot:'固定中景，甲胄悍将不恼反笑翻身提戟上马，居高临下',
   lens:'50mm 标准，中浅景深',cameraPosition:'吕布 + 低角度仰视',composition:'低角度构图',eyeline:'马下的张飞',focus:'锁定踞马而笑的吕布',stability:'stable'},
  {beats:[7,7],seconds:4.5,size:'close',camera:'Static Shot',characters:['C06'],props:[],eng:'A static close-up holds the proud warrior imparting his last word, {t0}',
   frame:'特写，吕布垂眼道，聪明这世上最经不起的就是欠账',shot:'固定近景，甲胄悍将垂眼撂话，语带深意',
   lens:'85mm 长焦，浅景深',cameraPosition:'吕布 + 平视正面',composition:'中心构图',eyeline:'张飞',focus:'锁定吕布神情',stability:'stable'},
  {beats:[8,8],seconds:3,size:'wide',camera:'Static Shot',characters:['C06'],props:[],eng:'A static wide shot shows the proud warrior spurring his horse and riding off, trailing a long plume of yellow dust.',
   frame:'全景，吕布一夹马腹扬长而去，卷起一路黄尘',shot:'固定全景，甲胄悍将夹马扬鞭绝尘而去，身后黄尘漫卷',
   lens:'35mm 广角，深景深',cameraPosition:'远处 + 平视',composition:'引导线构图',eyeline:'扬尘远去的马影',focus:'锁定远去的黄尘马影',stability:'stable'},
 ],
 soundscape:'马蹄踏尘，吕布去远的笑声，黄尘卷起',
 h3sound:'Hooves upon the dust, a fading laugh, and the swirl of rolling dust.',
 h3music:'Thin, wry strings.',
},
{
 sceneIndex:2, blocking:'刘备案前望着那道背影眉间未舒，随即向张飞低声点出袁术未必死心，张飞愤愤表示吕布两头讨巧。',
 cuts:[
  {beats:[9,9],seconds:3,size:'medium',camera:'Static Shot',characters:['C01'],props:[],eng:'A static medium shot shows the lord watching that receding figure, his brow never once easing.',
   frame:'中景，刘备案前望着那道背影，眉间却并未舒开半分',shot:'固定中景，素衣男子望着远去背影，眉间拧紧未展',
   lens:'50mm 标准，中浅景深',cameraPosition:'刘备 + 平视侧面',composition:'三分法',eyeline:'远去的背影',focus:'锁定刘备未展的眉头',stability:'stable'},
  {beats:[10,10],seconds:4,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord voicing his wariness, {t0}',
   frame:'特写，刘备低声说道，纪灵退是退了袁术未必就死心',shot:'固定近景，素衣男子低声点出隐患',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'前方',focus:'锁定刘备面部',stability:'stable'},
  {beats:[11,11],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior gesturing with exasperation, {t0}',
   frame:'特写，张飞愤声道，那吕布明摆着是两头讨巧',shot:'固定近景，黑脸猛将一脸不忿地点破',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
 ],
 soundscape:'沙场余音，两人压低的交谈',
 h3sound:'The fading dioramas of the field and low, wary talk between the two.',
 h3music:'N/A',
},
{
 sceneIndex:2, blocking:'刘备立在案前缓缓点出这场局难善了，末了画外轻叹一身强敌环伺。',
 cuts:[
  {beats:[12,12],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord shaping the tangled situation, {t0}',
   frame:'特写，刘备低声道，他越是居中取利这场局便越难善了',shot:'固定近景，素衣男子低语点破，眉峰凝重',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'案前',focus:'锁定刘备面部',stability:'stable'},
  {beats:[13,13],seconds:4.5,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord as his inner voice adds in an off-screen voiceover while his lips remain closed, {t0}',
   frame:'特写，刘备凝眸，画外响起自己的心声',shot:'固定近景，素衣男子神色沉凝，双唇紧闭画外轻叹',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'远空',focus:'锁定刘备沉凝的眼底',stability:'stable'},
 ],
 soundscape:'沙场渐静，风声低回，画外轻叹',
 h3sound:'The field grows quiet, wind eddies low, and a faint inner sigh lingers.',
 h3music:'Low, melancholic strings.',
},
{
 sceneIndex:2, blocking:'刘备垂眼望向自己摊开的掌心久久不收，张飞在侧扬声表态要质疑，刘备抬眼眸中沉沉未应声。',
 cuts:[
  {beats:[14,14],seconds:3,size:'medium',camera:'Push In',characters:['C01'],props:[],eng:'A slow push in tightens on the lord lowering his eyes to his own spread palm, never closing it for a long while.',
   frame:'中景，刘备垂眼望向自己摊开的掌心，久久没有收拢',shot:'镜头小幅缓推，素衣男子垂眸看自己摊开的掌心，久久不动',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'摊开的掌心',focus:'锁定刘备摊开的掌',stability:'stable'},
  {beats:[15,15],seconds:4,size:'close',camera:'Static Shot',characters:['C03'],props:[],eng:'A static close-up holds the fierce warrior by his side, {t0}',
   frame:'特写，张飞补了一句，这恩咱们迟早要他也还回来',shot:'固定近景，黑脸猛将在侧扬声表态',
   lens:'85mm 长焦，浅景深',cameraPosition:'张飞 + 平视正面',composition:'中心构图',eyeline:'刘备',focus:'锁定张飞面部',stability:'stable'},
  {beats:[16,16],seconds:3,size:'close',camera:'Static Shot',characters:['C01'],props:[],eng:'A static close-up holds the lord raising his eyes, heavy and unvoiced.',
   frame:'特写，刘备抬眼望去，眸中沉沉，没有应声',shot:'固定近景，素衣男子抬眼，眸色沉沉的未作回应',
   lens:'85mm 长焦，浅景深',cameraPosition:'刘备 + 平视正面',composition:'中心构图',eyeline:'前方远处',focus:'锁定刘备深沉的眸光',stability:'stable'},
 ],
 soundscape:'沙场余风，张飞粗豪的话音，随后一片静',
 h3sound:'A last gust over the field, the warrior\'s gruff word, and then a heavy stillness.',
 h3music:'Low, unresolved strings.',
},
];