// ep15 原始分段
export default [
// 场1 S05 烈日校场 C23 C04 (beats 1-28)
{
 sceneIndex:1, blocking:'平原校场两军列阵鏖战，弓矢如雨喊杀震天；夏侯惇挺枪一马当先，杀透数阵直往吕布军前冲。',
 cuts:[
  {beats:[1,1],seconds:4,size:'wide',camera:'Static Shot',characters:['C23'],props:[],eng:'A static wide shot shows two armies locked in battle across the plain under a blazing sun, arrows falling like rain and war cries shaking the sky.',
   frame:'全景，平原上两军列阵鏖战，弓矢如雨喊杀震天',shot:'固定全景，烈日平原两军混战，箭矢如雨喊杀震天',
   lens:'35mm 广角，深景深',cameraPosition:'战场 + 平视远眺',composition:'引导线构图',eyeline:'混战的两军',focus:'锁定纷飞的箭矢与厮杀的军阵',stability:'handheld'},
  {beats:[2,2],seconds:4,size:'medium',camera:'Tracking Shot',characters:['C23'],props:[],eng:'A tracking shot follows a fierce one-eyed general on horseback, spear couched, piercing through several formations and charging straight toward the enemy vanguard.',
   frame:'中景，夏侯惇挺枪杀透数阵，径直往吕布军前冲',shot:'镜头跟随一名独眼悍将挺枪策马杀透数阵，直冲敌前',
   lens:'50mm 标准，中景深',cameraPosition:'夏侯惇 + 侧面平视跟随',composition:'引导线构图',eyeline:'敌阵',focus:'锁定杀透重围的夏侯惇',stability:'slight-shake'},
  {beats:[3,3],seconds:3.5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general bellowing a challenge, {t0}',
   frame:'特写，夏侯惇扬声呼喝，谁敢跟我去取那匹赤兔马的命',shot:'固定近景，独眼悍将扬声呼喝，声震四野',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'敌阵深处',focus:'锁定夏侯惇面部',stability:'slight-shake'},
 ],
 soundscape:'金戈交鸣，喊杀震天，箭矢破空',
 h3sound:'Clashing weaponry, war cries that shake the heavens, and arrows shearing the air.',
 h3music:'Driving war drums, fierce and fast.',
},
{
 sceneIndex:1, blocking:'夏侯惇扬声放话，正要冲锋时一根冷箭擦着他耳畔掠过，他抬手抹血反而咧开嘴笑了。',
 cuts:[
  {beats:[4,4],seconds:4.5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general declaring his intent, {t0}',
   frame:'特写，夏侯惇扬声放话，今日定要撕开这道阵',shot:'固定近景，独眼悍将扬声立誓，气势如虹',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'前方敌阵',focus:'锁定夏侯惇面部',stability:'slight-shake'},
  {beats:[5,5],seconds:4,size:'medium',camera:'Static Shot',characters:['C23'],props:[],eng:'A static medium shot shows a stray arrow whistle in; the fierce general tilts his head and it grazes just past his ear.',
   frame:'中景，一根冷箭射来，夏侯惇侧头，利箭擦着他耳畔掠过',shot:'固定中景，一根冷箭破空而来，独眼悍将侧头避过，箭擦耳掠过',
   lens:'50mm 标准，中景深',cameraPosition:'夏侯惇 + 平视侧面',composition:'三分法',eyeline:'擦耳的箭',focus:'锁定擦耳掠过的箭与避箭的侧脸',stability:'slight-shake'},
  {beats:[6,6],seconds:4,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A close-up holds the fierce general wiping blood from his face and breaking instead into a grin.',
   frame:'特写，夏侯惇抬手抹了一把脸上的血，反而咧开嘴笑了',shot:'固定特写，独眼悍将抬手抹去面上血迹，咧嘴一笑',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'前方',focus:'锁定抹血后咧嘴的笑',stability:'slight-shake'},
 ],
 soundscape:'箭矢呼啸，马蹄踏地，夏侯惇粗豪的呼喝',
 h3sound:'An arrow whistling, hooves thudding, and the wild brave shout of the fierce general.',
 h3music:'Driving war drums, relentless.',
},
{
 sceneIndex:1, blocking:'夏侯惇扬声叫阵，话音未落一支冷箭自斜刺里破空而来，直贯他的左眼。',
 cuts:[
  {beats:[7,7],seconds:4.5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general taunting, {t0}',
   frame:'特写，夏侯惇扬声叫阵，暗箭伤我不怕我取你性命只管来',shot:'固定近景，独眼悍将扬声叫阵，战意炽盛',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'前方',focus:'锁定夏侯惇面部',stability:'slight-shake'},
  {beats:[8,9],seconds:6,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A close-up holds a cold arrow streak in from an angle and strike the fierce general square in the left eye, a spurt of blood bursting forth.',
   frame:'特写，话音未落一支冷箭自斜刺里破空而来，利箭直贯夏侯惇的左眼，血珠猛地迸溅出来',shot:'固定特写，一支冷箭自斜刺破空，直贯独眼悍将左眼，血珠迸溅',
   lens:'100mm 微距，极浅景深',cameraPosition:'箭落处 + 平视',composition:'中心构图',eyeline:'中箭的左眼',focus:'锁定中箭迸血的瞬间',stability:'handheld'},
 ],
 soundscape:'叫阵余音，箭矢破空极速，闷响与血溅声',
 h3sound:'The taunt hangs, an arrow hisses, then the dull impact as it strikes and blood bursts.',
 h3music:'A sharp stinger, then silence.',
},
{
 sceneIndex:1, blocking:'夏侯惇身子一晃，连忙用枪杆撑住稳住马身，随即扬声喝骂。',
 cuts:[
  {beats:[10,11],seconds:6,size:'medium',camera:'Static Shot',characters:['C23'],props:[],eng:'A static medium shot shows the fierce general lurching, bracing himself with his spear shaft to steady his horse, then snapping out, {t0}',
   frame:'中景，夏侯惇身子一晃连忙用枪杆撑住稳住马身，扬声喝骂雕虫小技也敢暗箭伤人',shot:'固定中景，独眼悍将身子一晃以枪杆撑稳马身，扬声喝骂',
   lens:'50mm 标准，中景深',cameraPosition:'夏侯惇 + 平视侧面',composition:'三分法',eyeline:'前方',focus:'锁定撑枪稳马的动作',stability:'slight-shake'},
  {beats:[12,12],seconds:4,size:'extreme-close',camera:'Static Shot',characters:['C23'],props:[],eng:'An extreme close-up holds the fierce general grabbing the arrow-shaft and yanking it clean out, blood smearing across his whole face.',
   frame:'大特写，夏侯惇一把扯住箭杆猛地往外一带，血水溅了满脸',shot:'固定大特写，独眼悍将一把扯住箭杆猛地拽出，血水溅上满脸',
   lens:'100mm 微距，极浅景深',cameraPosition:'面部 + 平视',composition:'中心构图',eyeline:'拽出的箭杆',focus:'锁定拔箭见骨的一瞬',stability:'handheld'},
 ],
 soundscape:'马蹄踉跄，拔箭的闷响，血水四溅',
 h3sound:'A horse stumbling, the wet sound of the arrow being torn out, and blood splattering.',
 h3music:'Low, ominous war drums.',
},
{
 sceneIndex:1, blocking:'夏侯惇扬声让亲兵把箭抵稳，亲兵上前架住他的手臂；他沉声点出中箭伤的是父精母血。',
 cuts:[
  {beats:[13,13],seconds:4,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general steadying against the pain as he orders, {t0}',
   frame:'特写，夏侯惇咬牙扬声，底替我把箭抵稳了莫要晃',shot:'固定近景，独眼悍将咬牙出声，强自稳住',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'身前',focus:'锁定夏侯惇咬牙的面容',stability:'slight-shake'},
  {beats:[14,15],seconds:6,size:'medium',camera:'Static Shot',characters:['C23'],props:[],eng:'A static medium shot shows a guard stepping close to steady his arm; the fierce general then speaks gravely, {t0}',
   frame:'中景，身边亲兵上前稳稳架住他的手，夏侯惇沉声道中箭的是我伤的是我父精母血',shot:'固定中景，一名亲兵上前架上独眼悍将的手臂，呼号悍将沉声开口',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'身前',focus:'锁定架臂的亲兵与沉声的夏侯惇',stability:'slight-shake'},
 ],
 soundscape:'战场喊杀隐约，夏侯惇压抑的沉声，兵甲轻响',
 h3sound:'Muffled battle cries, the general\'s restrained voice, and the stir of harness.',
 h3music:'Low war drums holding.',
},
{
 sceneIndex:1, blocking:'夏侯惇把血淋淋的眼珠托在掌中看了一眼，扬声叹句父精母血；旁人已吓得掩面欲逃。',
 cuts:[
  {beats:[16,16],seconds:3,size:'wide',camera:'Static Shot',characters:['C23'],props:[],eng:'A static wide shot shows those around the fierce general shielding their faces in horror, a few turning to flee.',
   frame:'全景，旁人已吓得掩面，有人低呼转身欲逃',shot:'固定全景，周遭兵卒吓得掩面，有人低呼欲逃',
   lens:'35mm 广角，深景深',cameraPosition:'众人 + 平视',composition:'对称构图',eyeline:'掩面欲逃的兵卒',focus:'锁定惊骇掩面的众卒',stability:'handheld'},
  {beats:[17,18],seconds:6,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general holding the blood-soaked eye in his palm, glancing at it once as he speaks, {t0}',
   frame:'特写，夏侯惇把血淋淋的眼珠托在掌中看了一眼，扬声说父所给我的安能轻易舍弃',shot:'固定近景，独眼悍将把血淋淋的眼珠托在掌中看了一眼，扬声开口',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'掌中的眼珠',focus:'锁定掌中眼珠与沉静的神情',stability:'slight-shake'},
 ],
 soundscape:'四周惊恐的低呼，风声，夏侯惇沉声的话音',
 h3sound:'Horrified gasps around, the wind, and the general\'s low words.',
 h3music:'Deep, solemn drums.',
},
{
 sceneIndex:1, blocking:'夏侯惇仰天厉啸，张弓搭箭回手一箭射落放箭之人，曹军将士尽皆血脉贲张。',
 cuts:[
  {beats:[19,19],seconds:5,size:'wide',camera:'Static Shot',characters:['C23'],props:[],eng:'A wide shot shows the fierce general lifting his head in a piercing cry, drawing his bow and loosing a single return arrow to strike down the hidden archer.',
   frame:'全景，夏侯惇仰天一声厉啸，张弓搭箭回手一箭射落放箭之人',shot:'固定全景，独眼悍将仰天厉啸，张弓回射一箭，射落暗放冷箭之人',
   lens:'35mm 广角，深景深',cameraPosition:'战场 + 平视',composition:'引导线构图',eyeline:'远处放箭之处',focus:'锁定扬弓回射的夏侯惇',stability:'handheld'},
  {beats:[20,20],seconds:4,size:'wide',camera:'Static Shot',characters:['C23'],props:[],eng:'A static wide shot shows the lord\'s soldiers, fired by the spectacle, surging with blood up across the ranks.',
   frame:'全景，曹军将士见夏侯惇如此刚烈，尽皆血脉贲张',shot:'固定全景，曹军将士见悍将如此刚烈，尽皆血脉贲张',
   lens:'35mm 广角，深景深',cameraPosition:'军阵 + 平视',composition:'对称构图',eyeline:'热血翻涌的曹军',focus:'锁定血脉贲张的曹军阵列',stability:'handheld'},
 ],
 soundscape:'一声厉啸，弓弦弹响，箭矢破空，随即三军鼓噪',
 h3sound:'A piercing cry, a bowstring snapping, an arrow tearing air, then the roar of the army.',
 h3music:'War drums surging to a boil.',
},
{
 sceneIndex:1, blocking:'夏侯惇扬声喝令众军睁眼莫让一箭枉费，军中怒吼如潮，铁流反压过去。',
 cuts:[
  {beats:[21,21],seconds:4,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general shouting the war cry, {t0}',
   frame:'特写，夏侯惇扬声喝道，都将眼睛睁大了莫让这一箭枉费',shot:'固定近景，独眼悍将扬声呼喝，声振三军',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'敌阵',focus:'锁定夏侯惇面部',stability:'slight-shake'},
  {beats:[22,22],seconds:4,size:'wide',camera:'Static Shot',characters:['C23'],props:[],eng:'A static wide shot shows the army let out a single roar and surge forward like iron tide rolling over the enemy.',
   frame:'全景，军中一片怒吼，铁流如潮水般反压过去',shot:'固定全景，曹军齐声怒吼，铁流如潮反压而来',
   lens:'35mm 广角，深景深',cameraPosition:'军阵 + 平视',composition:'对称构图',eyeline:'反压过去的铁流',focus:'锁定卷入敌阵的铁流',stability:'handheld'},
 ],
 soundscape:'三军怒吼，铁流席卷，马蹄踏地如雷',
 h3sound:'A single great roar, the iron tide surging, and hoofbeats rolling like thunder.',
 h3music:'Rapid, triumphant war drums.',
},
{
 sceneIndex:1, blocking:'夏侯惇一马当先冲阵，吕布军被这狠劲冲得连连后退，他扬声再逼一句。',
 cuts:[
  {beats:[23,23],seconds:4,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general leading the charge, {t0}',
   frame:'特写，夏侯惇扬声呼冲，弟兄们跟我冲杀败眼前这阵',shot:'固定近景，独眼悍将扬声呼喝，一马当先',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'敌阵',focus:'锁定夏侯惇面部',stability:'slight-shake'},
  {beats:[24,24],seconds:4,size:'wide',camera:'Tracking Shot',characters:['C23'],props:[],eng:'A tracking shot follows the fierce general charging at the very front as the enemy ranks give way before this ferocity, reeling back.',
   frame:'全景，夏侯惇一马当先，吕布军竟被这狠劲冲得连连后退',shot:'镜头跟随一马当先的独眼悍将，敌阵被这股狠劲冲得连连后退',
   lens:'35mm 广角，深景深',cameraPosition:'夏侯惇 + 侧面平视跟随',composition:'引导线构图',eyeline:'节节后退的敌阵',focus:'锁定冲垮敌阵的独眼悍将',stability:'handheld'},
  {beats:[25,25],seconds:4.5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general pressing the kill, {t0}',
   frame:'特写，夏侯惇扬声喝道，再冲一刀叫那吕布知道什么叫疼',shot:'固定近景，独眼悍将扬声喝令，战意愈炽',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'敌阵',focus:'锁定夏侯惇面部',stability:'slight-shake'},
 ],
 soundscape:'马蹄如雷，敌阵溃退的杂沓，夏侯惇的连声呼喝',
 h3sound:'Thunderous hooves, the scramble of the retreating enemy, and the general\'s relentless shouts.',
 h3music:'Triumphant drums, driving onward.',
},
{
 sceneIndex:1, blocking:'夏侯惇把枪在地上一顿，扬声一声断喝，随即振枪跃马直杀入敌阵深处。',
 cuts:[
  {beats:[26,27],seconds:6,size:'medium',camera:'Static Shot',characters:['C23'],props:[],eng:'A static medium shot shows the fierce general, eyes unswerving, planting his spear into the ground with a thud as he declares, {t0}',
   frame:'中景，夏侯惇目不旁顾把枪在地上一顿，扬声说道我这双眼丢在你吕布阵前你有胆便来取',shot:'固定中景，独眼悍将目不旁顾把枪往地上一顿，扬声断喝',
   lens:'50mm 标准，中浅景深',cameraPosition:'夏侯惇 + 平视侧面',composition:'中心构图',eyeline:'敌阵',focus:'锁定顿枪而立的夏侯惇',stability:'slight-shake'},
  {beats:[28,28],seconds:4,size:'wide',camera:'Tracking Shot',characters:['C23'],props:[],eng:'A tracking shot follows the fierce general, spear raised, spurring his horse and plunging once more into the depths of the enemy formation.',
   frame:'全景，夏侯惇说毕振枪跃马，竟又向敌阵深处杀去',shot:'镜头跟随独眼悍将振枪跃马，只身又杀入敌阵深处',
   lens:'35mm 广角，中景深',cameraPosition:'夏侯惇 + 侧面平视跟随',composition:'引导线构图',eyeline:'敌阵深处',focus:'锁定杀入敌阵尽头的独眼悍将',stability:'handheld'},
 ],
 soundscape:'枪杆顿地的闷响，一声断喝，马蹄奔雷',
 h3sound:'The thud of the planted spear, a single sharp cry, and hooves like rolling thunder.',
 h3music:'Solemn, swelling war drums.',
},
// 场2 S05 城下晨光 C23 C04 (beats 1-16)
{
 sceneIndex:2, blocking:'战罢，曹操在中军帐前相迎，看着自己这员悍将；夏侯惇翻身下马，血迹已干在脸上，人却站得笔直。',
 cuts:[
  {beats:[1,1],seconds:3,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot shows the lord standing before the central war tent, waiting to receive his fierce general in the light of a new morning.',
   frame:'全景，战罢晨光，曹操在中军帐前相迎，看着自己这员悍将',shot:'固定全景，晨光里一名玄衣主帅在中军帐前相迎，等候爱将回营',
   lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视正面',composition:'对称构图',eyeline:'帐前大道',focus:'锁定候营的曹操',stability:'stable'},
  {beats:[2,2],seconds:3,size:'medium',camera:'Static Shot',characters:['C23'],props:[],eng:'A static medium shot shows the fierce general dismounting, the blood long dried on his face yet his frame standing utterly straight.',
   frame:'中景，夏侯惇翻身下马，血迹已干在脸上，人却站得笔直',shot:'固定中景，独眼悍将翻身下马，面上血迹已干，身形却站得笔直',
   lens:'50mm 标准，中景深',cameraPosition:'夏侯惇 + 平视',composition:'中心构图',eyeline:'曹操',focus:'锁定下马而立的夏侯惇',stability:'stable'},
  {beats:[3,3],seconds:4,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the lord speaking in a low, broken voice, {t0}',
   frame:'特写，曹操望着他低声道，元让你这双眼是我对不起你',shot:'固定近景，玄衣主帅望着爱将低声道痛，声气发涩',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'夏侯惇',focus:'锁定曹操沉痛的面容',stability:'stable'},
 ],
 soundscape:'营帐晨风，战马轻嘶，曹操涩然的话音',
 h3sound:'Morning wind about the tent, a horse snorting, and the lord\'s rough, restrained voice.',
 h3music:'Solemn low strings, grief-colored.',
},
{
 sceneIndex:2, blocking:'夏侯惇坦然回话身家，曹操握住他的手半晌说不出话，夏侯惇反手拍了拍他的背。',
 cuts:[
  {beats:[4,4],seconds:5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general answering plainly, {t0}',
   frame:'特写，夏侯惇朗声回话，主公何出此言将军马革裹尸理应如此',shot:'固定近景，独眼悍将坦然回话，神色无怨',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇面部',stability:'stable'},
  {beats:[5,6],seconds:6,size:'medium',camera:'Static Shot',characters:['C04','C23'],props:[],eng:'A static medium shot shows the lord clasping the fierce general\'s hand, words failing him for a long while, until the general reaches over and pats his back.',
   frame:'中景，曹操握着他的手半晌说不出话来，夏侯惇却反手拍了拍曹操的背',shot:'固定中景，玄衣主帅握着爱将的手很久无语，悍将反手轻拍其背',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'两人交握的手',focus:'锁定两手相握与拍背的动作',stability:'stable'},
 ],
 soundscape:'晨风，曹操哽住的话音，衣甲轻响',
 h3sound:'The morning wind, the lord\'s voice catching, and the soft rustle of armor.',
 h3music:'Warm, low strings softening.',
},
{
 sceneIndex:2, blocking:'夏侯惇沉声说一只眼换三军胆气，曹操望着他那只空了的眼眶，眼底深不见底。',
 cuts:[
  {beats:[7,7],seconds:4,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general speaking with a wry ease, {t0}',
   frame:'特写，夏侯惇淡声道，一只眼睛换三军胆气值了',shot:'固定近景，独眼悍将轻描淡写地应了一句，眼底无憾',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇面部',stability:'stable'},
  {beats:[8,8],seconds:4,size:'close',camera:'Push In',characters:['C04'],props:[],eng:'A slow push in tightens on the lord gazing at the fierce general\'s empty eye socket, his own gaze bottomless and dark.',
   frame:'特写，曹操望着他那只空了的眼眶，眼底深不见底',shot:'镜头小幅缓推，玄衣主帅望着爱将空了的眼眶，眼底深不见底',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'空了的眼眶',focus:'锁定曹操深不见底的眼底',stability:'stable'},
 ],
 soundscape:'营中晨息，两人相对的沉默',
 h3sound:'The stillness of the morning camp and a heavy silence between the two.',
 h3music:'Low, reverent strings.',
},
{
 sceneIndex:2, blocking:'曹操握拳许下从吕布手里讨回兖州的志，夏侯惇慨然答命愿替他去拼。',
 cuts:[
  {beats:[9,9],seconds:4.5,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the lord voicing his resolve, {t0}',
   frame:'特写，曹操沉声道，兖州这仗我迟早要从吕布手里讨回来',shot:'固定近景，玄衣主帅沉声立誓，语意决然',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'夏侯惇',focus:'锁定曹操面部',stability:'stable'},
  {beats:[10,10],seconds:5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general pledging his life, {t0}',
   frame:'特写，夏侯惇抱拳慨然道，主公既有此心末将这条命留着替你去拼',shot:'固定近景，独眼悍将抱拳慨然应命，气概凛然',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇面部',stability:'stable'},
 ],
 soundscape:'晨风吹帐，两人交心的低语',
 h3sound:'The morning wind stirring the tent and two men voicing their pact in low tones.',
 h3music:'Resolute low brass over strings.',
},
{
 sceneIndex:2, blocking:'夏侯惇抱拳领命转身大步而去步伐虎虎生风，曹操立在原处望着那道背影久久没有动。',
 cuts:[
  {beats:[11,11],seconds:3.5,size:'medium',camera:'Tracking Shot',characters:['C23'],props:[],eng:'A tracking shot follows the fierce general, fists folded in salute, turning and striding off with brisk, forceful steps.',
   frame:'中景，夏侯惇抱拳领命转身大步而去，步伐仍旧虎虎生风',shot:'镜头平稳跟随独眼悍将抱拳领命，转身大步而去，步履生风',
   lens:'50mm 标准，中景深',cameraPosition:'夏侯惇 + 侧面平视跟随',composition:'三分法',eyeline:'前路',focus:'锁定大步离去的夏侯惇',stability:'stable'},
  {beats:[12,12],seconds:3.5,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot shows the lord standing where he was, watching that receding figure, long unmoving.',
   frame:'全景，曹操立在原处望着那道背影，久久没有动',shot:'固定全景，玄衣主帅立在原处望着远去的背影，久久不动',
   lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视侧面',composition:'引导线构图',eyeline:'远去的背影',focus:'锁定曹操凝望的背影',stability:'stable'},
 ],
 soundscape:'营中脚步渐远，晨风，马蹄轻踏',
 h3sound:'Footsteps receding through the camp, the morning wind, and the soft tread of horses.',
 h3music:'Quiet, weighty strings.',
},
{
 sceneIndex:2, blocking:'曹操凝望残营，画外响起心声感叹吕布骁勇与己方损伤；夏侯惇回过身扬声请命要替他守兖州。',
 cuts:[
  {beats:[13,13],seconds:5,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the lord as his inner voice speaks in an off-screen voiceover while his lips remain closed, {t0}',
   frame:'特写，曹操凝眸望向远营，画外响起自己的心声',shot:'固定近景，玄衣主帅凝眸远望，双唇紧抿画外轻叹',
   lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'远营',focus:'锁定曹操沉凝的眼底',stability:'stable'},
  {beats:[14,14],seconds:4.5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general turning back to pledge, {t0}',
   frame:'特写，夏侯惇回过身扬声请命，主公安心这兖州城我来替你守',shot:'固定近景，独眼悍将转身扬声请命，声气坚定',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇请命的面容',stability:'stable'},
 ],
 soundscape:'晨风低回，画外心声，随即悍将的请命',
 h3sound:'A low morning wind, a faint inner voice, then the general\'s firm pledge.',
 h3music:'Low strings gaining warmth and resolve.',
},
{
 sceneIndex:2, blocking:'夏侯惇扬声再表要替主公夺回几座城，话音未落一名校尉忽地策马而来递上一封加急军报。',
 cuts:[
  {beats:[15,15],seconds:5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general speaking his open promise, {t0}',
   frame:'特写，夏侯惇扬声说出末将不才也定要替主公夺回这几座城',shot:'固定近景，独眼悍将扬声明志，慷慨激昂',
   lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇面部',stability:'stable'},
  {beats:[16,16],seconds:3.5,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot shows a young officer suddenly galloping up to hand the lord a sealed urgent dispatch.',
   frame:'中景，一名校尉忽地策马而来，递上一封加急军报',shot:'固定中景，一名校尉骤马而至，将一封加急军报递到玄衣主帅手中',
   lens:'50mm 标准，中浅景深',cameraPosition:'双人 + 平视',composition:'三分法',eyeline:'手中军报',focus:'锁定递上的加急军报',stability:'stable'},
 ],
 soundscape:'马蹄骤至，悍将话音未落，军报递来的衣甲声',
 h3sound:'Hooves drawing up suddenly, the general\'s voice cut short, and the rustle of the sealed dispatch changing hands.',
 h3music:'Low, suspenseful strings.',
},
{
   sceneIndex:2, blocking:'曹操就着晨光展开军报，眉头一点点攒紧；夏侯惇在旁扬声安抚，曹操回身入帐，烛火映着他愈加深沉的脸。',
   cuts:[
    {beats:[17,17],seconds:3,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the lord unfolding the urgent dispatch in the pale morning light, his brow knitting tighter with every line.',
     frame:'特写，曹操就着晨光展开加急军报，眉头一点一点攒紧',shot:'固定近景，玄衣主帅就着晨光展开军报，眉峰越皱越紧',
     lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'手中军报',focus:'锁定曹操攒紧的眉头',stability:'stable'},
    {beats:[18,18],seconds:4,size:'medium',camera:'Static Shot',characters:['C04'],props:[],eng:'A static medium shot holds the lord reporting the grim news in a low, hard voice, {t0}',
     frame:'中景，曹操沉声道兖州诸城又有三座易帜，神情冷峻',shot:'固定中景，玄衣主帅沉声报出军情，神色冷峻',
     lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'三分法',eyeline:'军报',focus:'锁定曹操沉凝的眼神',stability:'stable'},
    {beats:[19,19],seconds:4,size:'close',camera:'Static Shot',characters:['C04'],props:[],eng:'A static close-up holds the lord as his inner voice surfaces while his lips stay shut, {t0}',
     frame:'特写，画外响起曹操心声，兖州若失我这根基便塌了半边天',shot:'固定近景，玄衣主帅双唇紧抿，画外心声低沉',
     lens:'85mm 长焦，浅景深',cameraPosition:'曹操 + 平视正面',composition:'中心构图',eyeline:'军报',focus:'锁定曹操沉郁的眼底',stability:'stable'},
   ],
   soundscape:'晨风卷着军报，加急马蹄渐歇',
   h3sound:'The morning wind rustling the dispatch and receding hooves.',
   h3music:'Low, weighty strings.',
  },
{
   sceneIndex:2, blocking:'夏侯惇扬声安抚，曹操回身入帐，烛火映着他愈加深沉的脸。',
   cuts:[
    {beats:[20,20],seconds:5,size:'close',camera:'Static Shot',characters:['C23'],props:[],eng:'A static close-up holds the fierce general stepping forward to speak with fierce reassurance, {t0}',
     frame:'特写，夏侯惇扬声安抚，主公莫忧兖州是咱们的家丢了我去夺回来',shot:'固定近景，独眼悍将扬声安抚，气概不减',
     lens:'85mm 长焦，浅景深',cameraPosition:'夏侯惇 + 平视正面',composition:'中心构图',eyeline:'曹操',focus:'锁定夏侯惇请战的面容',stability:'stable'},
    {beats:[21,22],seconds:6,size:'medium',camera:'Push In',characters:['C04'],props:[],eng:'A slow push in follows the lord turning and walking back into the tent, candlelight playing across a face growing ever heavier as he gives the order, {t0}',
     frame:'中景，曹操回身入帐烛火映着愈加沉重的脸，沉声下令今夜不动明日再与吕布分个高下',shot:'镜头缓推，玄衣主帅回身入帐，烛火摇曳，沉沉传令',
     lens:'50mm 标准，中浅景深',cameraPosition:'曹操 + 侧面平视跟随',composition:'引导线构图',eyeline:'帐内',focus:'锁定入帐的曹操与摇曳的烛火',stability:'stable'},
    {beats:[23,23],seconds:4,size:'wide',camera:'Static Shot',characters:['C04'],props:[],eng:'A static wide shot holds the lord silhouetted inside the tent as his inner voice closes on a bitter resolve, {t0}',
     frame:'全景，曹操立于帐内烛火中，画外心声缓缓道出终将一并讨回',shot:'固定全景，玄衣主帅立于帐中烛影里，神情深沉',
     lens:'35mm 广角，深景深',cameraPosition:'曹操 + 平视侧面',composition:'对称构图',eyeline:'帐外夜色',focus:'锁定帐内曹操的剪影',stability:'stable'},
   ],
   soundscape:'帐内烛火噼啪',
   h3sound:'The crackle of tent candlelight.',
   h3music:'Low, weighty strings that harden into resolve.',
  },
];