# -*- coding: utf-8 -*-
"""EP10 segments (each segment <=15s, one dict per segment).
cut tuple: (seconds, beats, size, camera, chars, props, frame, shot, lens, camPos, comp, eye, focus, stab, en)
beats per-scene 1-based. All EP10 scenes props None -> cut props=[]. Names only inside <d>; en/shot use descriptors."""

# =============== scene 1 : 董卓身死诸军生乱 长安倾覆 (beats 1-19) C06/C07/C08 ===============
E10_1A = dict(scene=1,
 overall='Behind the west gate of Chang\u2019an two western armies break the gates at night, torches blazing, and pour into the burning, hunted streets.',
 music_en='A rolling, ominous war-drum gets heavier as flames rise over the roofs.',
 blocking='西凉军（额外兵卒）举火破城而入；长安城内大乱，百姓四散；吕布（C06）纵马迎战。',
 soundscape='夜风裹着马嘶与关木崩断的巨响，火把与惊呼交错，满城脚步杂乱',
 music='一阵渐沉的战鼓滚成浑雷，火光在屋瓦间蔓延开来',
 cuts=[
  (2.5,[1,1],'wide','Tracking Shot',['C06'],[],
   '全景，夜，长安西门被轰然撞开，成队举着火把的军士涌入城门，火光把门楼照得通红',
   '镜头跟随涌入的火把队伍，西凉兵卒破门长驱而下，火光迎面汹涌而至',
   '35mm 广角，中景深','城门 + 平视远眺','引导线构图','洞开的城门','锁定涌入的兵潮','slight-shake'),
  (2.5,[2,2],'wide','Pan Right',['C06'],[],
   '全景，西凉铁骑沿着长街冲杀，见屋就烧见人就追，长安城内顿时大乱，百姓惊叫着四散奔逃',
   '镜头向右摇过错乱的街市，铁骑一路烧杀，逃难的人群挤作一团，浓烟滚滚',
   '35mm 广角，深景深','长街 + 平视远眺','引导线构图','四散奔逃的人群','锁定翻起的烟火','slight-shake'),
  (2.5,[3,3],'medium','Shake Slightly',['C06'],[],
   '中景，一名头戴雉尾紫金冠的猛将纵马迎上，横着画戟左右扫荡，却架不住四面一齐压下的箭雨',
   '轻微晃动的手持镜头，这名猛将抡戟格挡四面八方射来的利箭，马步被逼得连连后退',
   '50mm 标准，中浅景深','猛将 + 侧前平视','三分法','压来的箭雨','锁定格挡画戟','handheld'),
 ])
E10_1B = dict(scene=2,
 overall='He calls to the young woman to gather the few valuables and ride out with him while he fights a rearguard under a rain of arrows.',
 music_en='Hot, urgent strings under the clash; the woman\u2019s gasp is swallowed by the roar.',
 blocking='吕布（C06）护住貂蝉（C07）且战且退，扬声让她随他出城。',
 soundscape='兵刃与箭矢杂响不断，猛将高喊的话语被火光与嘶鸣搅得忽隐忽现',
 music='炽热而急切的弦音垫在厮杀声下，杂以女子被呼声吞没的惊呼',
 cuts=[
  (2.9,[4,4],'medium','Tracking Shot',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将一戟扫退逼近的敌骑，纵马自火事中冲出来，扬声朝身后高喊',
   '镜头平稳跟拍猛将且战且走，他边挥戟开路边回头高喊，火光把他的侧脸照得明灭不定',
   '50mm 标准，中浅景深','猛将 + 侧后平视跟随','三分法','身后的女子','锁定猛将回头喊话','slight-shake',
   'A tracking medium shot follows the crowned warrior as he hacks his way clear and calls back to the young woman: <d>[Chinese] 貂蝉，收拾细软，随我出城！</d>'),
  (2.5,[5,5],'medium','Truck Right',['C06'],[],
   '中景，他且战且退，臂上中了一箭，一咬牙，拽起后方那名华服的年轻女子拨马便走',
   '镜头随猛将右移，他臂上中箭仍不死心，狠一咬牙把女子拽上坐骑拨马疾走',
   '50mm 标准，中浅景深','二人 + 侧后平视跟随','对角线构图','拨马的方向','锁定被拽上马的女子','slight-shake'),
 ])
E10_1C = dict(scene=2,
 overall='Ducking the arrows, he sweeps back two riders, a bloodstain seeping through his sleeve, while she is borne along before him, too shaken even to wipe the tears.',
 music_en='The drums press closer; a muffled wail threads through the iron.',
 blocking='吕布（C06）一戟扫退两骑，臂上血痕浸透半截袖甲，把貂蝉（C07）护在身前。',
 soundscape='画戟扫开两骑的闷响，袖甲被血浸透的黏腻小音，怀里女子呜咽却顾不上抹泪',
 music='战鼓越发逼近，一道闷在金属里的低泣混在铁器声之间',
 cuts=[
  (2.5,[6,6],'medium','Static Shot',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将闷哼一声，一戟扫退扑上来的两骑，臂上那道血痕正如墨般浸透半截袖甲',
   '固定镜头，猛将咬牙一戟扫开两骑，左臂的袖甲已被血染透，他却半步也没有停',
   '50mm 标准，中浅景深','猛将 + 平视侧面','三分法','扫开的敌骑','锁定浸血的袖甲','slight-shake'),
  (2.5,[7,7],'close','Static Shot',['C07'],[],
   '特写，被护在身前的华服年轻女子一路跌撞，眼泪也顾不上抹一把，只紧紧抓着猛将的衣甲低声喘',
   '固定镜头，这名华服的年轻女子紧抓着猛将衣甲，一路颠簸，泪痕仓皇，却不敢松手',
   '85mm 长焦，浅景深','女子 + 侧面平视','中心构图','猛将的衣甲','锁定女子慌乱的侧脸','slight-shake'),
 ])
E10_1D = dict(scene=2,
 overall='She notices his wound and he brushes it off, telling her to hold fast; ahead the gate guard collapses and a long spear cuts the banner down.',
 music_en='A sharp, interrupted exchange; then a deeper war-roll as the gate gives way.',
 blocking='貂蝉（C07）察觉猛将伤势；吕布（C06）回话；城门守军败退，长枪挑落将旗。',
 soundscape='女子一句压低的惊呼，猛将一句快的再正常不过的回话，随后城门口守军败退、旗杆断裂',
 music='一段被切断的短促对答，继而是城门失守时更沉的一阵战鼓',
 cuts=[
  (2.0,[8,8],'close','Static Shot',['C07'],[],
   '特写，被护在身前的华服年轻女子瞥见猛将臂上的伤口，神色一紧，失声追问一句',
   '固定镜头，这名华服的年轻女子瞥见伤口，惊得声音都变了，直直望着那片血痕',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','猛将的伤口','锁定女子骤变的神色','stable',
   'A static close-up holds the young woman as she catches sight of the wound and cries out in alarm: <d>[Chinese] 奉先，你的伤……</d>'),
  (2.2,[9,9],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将连看也不看那伤，只沉声回了句皮肉小伤，让她把他抱紧',
   '固定镜头，这名猛将眉头都不蹙一下，边策马边沉声回话，让她顾好自己便罢',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','身前的女子','锁定猛将沉稳的面容','stable',
   'A static close-up holds the warrior as he ignores the wound and speaks over his shoulder, steady: <d>[Chinese] 一点皮外伤，抱住我！</d>'),
  (2.5,[10,10],'wide','Tracking Shot',['C06'],[],
   '全景，城门口守军节节败退，一名西凉将领一杆长枪挑落城头的将旗，纵马直入长街',
   '镜头远远跟随那枝被挑落的大纛，西凉兵如潮水般漫过城门，直向城中央涌来',
   '35mm 广角，中景深','城门 + 平视远眺','引导线构图','坠落的将旗','锁定翻倒的大纛','slight-shake'),
 ])
E10_1E = dict(scene=2,
 overall='She cries that her foster father is still on the walls, and he answers that amid the rout one life at a time, hers must come first.',
 music_en='A desperate plea over the din, met by a resolve that leaves no room for debate.',
 blocking='貂蝉（C07）提醒城上还有义父；吕布（C06）回答乱军之中先保她的性命。',
 soundscape='混乱中女子一声急唤，随后猛将一句不容再议的话，马蹄声密密踏过街石',
 music='一声慌乱的求救穿过喧嚣，随即被一道不容商量的沉声压定',
 cuts=[
  (2.2,[11,11],'close','Static Shot',['C07'],[],
   '特写，这名华服的年轻女子猛然回首望向城头方向，声音急切地提醒一句，似是不忍就这么丢下老父',
   '固定镜头，这名女子回头望向城头，声音里带着急，那点挂念在慌乱里格外的突兀',
   '85mm 长焦，浅景深','女子 + 平视正侧面','三分法','城头方向','锁定女子回望城头的眼','slight-shake',
   'A static close-up holds the young woman as she looks back toward the walls and calls in urgent alarm: <d>[Chinese] 奉先，城上还有义父！</d>'),
  (3.8,[12,12],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将目光不变，声音又冷又稳，只说乱军之中顾不得那许多，先保她的性命',
   '固定镜头，这名猛将沉声作答，目光始终锁着前方的去路，语气不容置喙',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','前方的乱军','锁定猛将冷定的眼','stable',
   'A static close-up holds the warrior as he answers without glancing back, his tone brooking no argument: <d>[Chinese] 乱军之中顾不得那许多，先保你性命！</d>'),
 ])
E10_1F = dict(scene=2,
 overall='On the city wall the grey-haired minister is cornered; he straightens his robes, curses the bandits, and takes his own life before the flames swallow his shadow.',
 music_en='A lone, dignified note beneath the chaos; then a devastating silence.',
 blocking='城头，王允（C08）被乱军围困，整衣怒斥群寇后自刎，身影掩在火光里。',
 soundscape='城头一声老臣的怒喝，紧着一道极轻的闷响与倒下，火光在其后张大',
 music='一缕孤高尊严的音在乱局低落处奏起，随后坠入一段几近崩裂的寂静',
 cuts=[
  (2.5,[13,13],'close','Push In',['C08'],[],
   '特写，城头之上，一名须发花白的老臣被围在乱军之中，他振衣一整，怒视身前刀剑，开口痛斥',
   '镜头朝这名须发花白的老臣缓缓推近，他坦然整理衣冠，面对满目刀光，神色凛然不屈',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','逼来的乱军','锁定老臣凛然的目光','stable'),
  (3.1,[14,14],'close','Static Shot',['C08'],[],
   '特写，这名须发花白的老臣一字一句骂尽群寇，声音虽苍老却毫不打抖，目光定定不避',
   '固定镜头，这名老臣直面群寇高声痛斥，字字铿锵，把一身傲骨立在城头',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','群寇','锁定老臣怒极的眼','stable',
   'A static close-up holds the grey-haired minister as he defiantly curses the bandits to their faces: <d>[Chinese] 贼人休要张狂，我宁死也不降！</d>'),
  (2.5,[15,15],'extreme-wide','Static Shot',['C08'],[],
   '大远景，这名须发花白的老臣自刎于城楼之上，倒下的身影，正掩在那片未熄的火光里',
   '固定大远景，城头那点身影缓缓倒进火光里，群寇围拢又散开，只剩未熄的火舌舔着垛口',
   '24mm 广角，深景深','城头 + 平视远眺','中心构图','火光中的城楼','锁定倒下没入火光的影','stable'),
 ])
E10_1G = dict(scene=2,
 overall='A thread of dawn leaks through the south gate over the ravaged city as the western force plants a banner and the streets echo with wailing.',
 music_en='Grim light; the cries carry low and hollow across the ruin.',
 blocking='南门豁口漏进晨光，长街一片狼藉；西凉军挑起旗，长安城中哭成一片。',
 soundscape='一缕晨曦落在焦土上，旗帜张扬的猎猎声里混杂此起彼伏的哭声',
 music='苍凉的晨光乐句，哭声低低空空，滚过满目疮痍的街市',
 cuts=[
  (2.5,[16,16],'extreme-wide','Static Shot',['C06'],[],
   '大远景，南门豁口处一缕晨光漏进城来，把满城未熄的烟火和烧黑的屋脊照得分外苍凉',
   '固定大远景，一缕晨光斜斜穿过南门缺口，洒在焦黑的街市与残烟之上',
   '24mm 广角，深景深','南门 + 平视远眺','中心构图','晨光下的废墟','锁定那片苍凉的晨曦','stable'),
  (2.5,[17,17],'wide','Pan Right',['C06'],[],
   '全景，西凉军夺下城池，矛尖挑起一面反字大旗，长安城中一片狼藉，哭声四起',
   '镜头向右摇过长街，铁矛挑起的旗帜在狼藉的街市上张扬，四下里哭喊不绝',
   '35mm 广角，中景深','长街 + 平视远眺','引导线构图','张扬的旗帜','锁定满目狼藉','slight-shake'),
 ])
E10_1H = dict(scene=2,
 overall='Two western commanders rein in face to face at the middle of the street, neither willing to yield a step to the other.',
 music_en='A cold standoff; a held chord of mutual distrust.',
 blocking='李傕、郭汜（不在框内）在长街正中勒马对望，各不相让。',
 soundscape='两军对峙、缰绳绷紧的马嘶声，满街肃静的刀剑出鞘声',
 music='一段冷凝的乐段，一句彼此戒备的和弦悬在长街上空',
 cuts=[
  (2.5,[18,18],'wide','Static Shot',['C06'],[],
   '全景，长街正中，两名西凉将领各自勒马对望，谁也不肯先让半步，中间的空地针落可闻',
   '固定镜头，两骑马头相对峙立在街头，将领们隔街对视，僵持的空气近乎凝固',
   '35mm 广角，深景深','长街 + 平视远眺','对称构图','对立的双骑','锁定对峙的两人','stable'),
 ])
E10_1I = dict(scene=2,
 overall='Shielding the young woman, the warrior breaks through the south gate as it slams shut, cutting off the cries of the burning city behind them.',
 music_en='The drums fall away; wind whoops past as the gate closes.',
 blocking='吕布（C06）护着貂蝉（C07）冲出南门，身后城门骤然合拢。',
 soundscape='画戟扫开最后几人的脆响，马蹄踩过碎石出城，身后城门沉重的合拢声隔绝满城哭喊',
 music='战鼓渐远，风声在耳边呼啸而过，随之城门闭合的闷响封住一切',
 cuts=[
  (2.5,[19,19],'wide','Tracking Shot',['C06','C07'],[],
   '全景，这名头戴雉尾紫金冠的猛将护着华服的年轻女子，奋力冲出南门，身后两扇城门轰然合拢，隔断了满城哭喊',
   '镜头平稳跟拍冲出城门的骑影，猛将把女子护在身前冲出缺口，沉重的门扇在身后重重合拢',
   '35mm 广角，中景深','城门 + 侧后平视跟随','引导线构图','洞开的南门','锁定冲出城门的二人','stable'),
 ])

# =============== scene 2 : 别散重逢蓟北 (beats 1-14) C01/C02/C03 ===============
E10_2A = dict(scene=2,
 overall='Across the same troubled age the coalition has long dispersed; three brothers lead their horses along the highway, and the black-armoured one looks back at the vanished campsite.',
 music_en='An open, slightly rueful air; the plains roll on before them.',
 blocking='刘、关、张三兄弟（C01/C02/C03）牵着马并肩走在官道上；张飞回头望营地。',
 soundscape='官道上马蹄轻响与衣甲摩擦，旷野的风声，黑甲猛汉回望时的一声轻哼',
 music='一段开阔而略带怅惘的乐句，旷野横展在三人面前',
 cuts=[
  (2.5,[1,1],'wide','Tracking Shot',['C01','C02','C03'],[],
   '全景，同一片乱世里，联军早已散去，三名武将牵着各自的马，并肩走在官道之上',
   '镜头平稳跟随三匹牵着走的马，三名武将在旷野官道上并肩而行，神色各有沉静',
   '35mm 广角，中景深','三人 + 侧后平视跟随','引导线构图','前方的官道','锁定并肩而行的三人','stable'),
  (2.5,[2,2],'medium','Static Shot',['C03'],[],
   '中景，一名黑甲猛汉回头望一眼渐渐消失的营地，大步追上前面的大哥，神色里带着不满',
   '固定镜头，这名黑甲猛汉回头瞥了眼已淡去的营地，撇撇嘴，紧走几步跟上大哥',
   '50mm 标准，中浅景深','黑甲猛汉 + 侧面平视','三分法','渐远的前方','锁定猛汉不满的神色','stable'),
 ])
E10_2B = dict(scene=2,
 overall='The black-armoured one mutters that the coalition was no friend of fellowship, and the white-robed lord answers that so long as the brothers stand together, they stand anywhere.',
 music_en='A plainspoken exchange; steady, unhurried chords underneath.',
 blocking='张飞（C03）抱怨联军不讲义气；刘备（C01）答兄弟同心便处处站得住。',
 soundscape='黑甲猛汉一声压着不满的抱怨，白衣头领一句宽厚笃定的回话，风从草原上经过',
 music='一段直来直去的对答乐，以稳定不急的和弦垫底',
 cuts=[
  (3.8,[3,3],'close','Static Shot',['C03'],[],
   '特写，这名黑甲猛汉瓮声瓮气地开口抱怨，说那联军也不讲义气、说散就散，语气里带着嫌恶',
   '固定镜头，这名黑甲猛汉粗声抱怨，眉宇间满是对那联军的不屑',
   '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','前方的大哥','锁定猛汉不满的眼神','stable',
   'A static close-up holds the black-armoured warrior as he grumbles about the feckless league: <d>[Chinese] 大哥，那联军也不讲义气，说散就散。</d>'),
  (6.2,[4,4],'close','Static Shot',['C01'],[],
   '特写，白衣头领神色平和，朗声回话，说聚也罢散也罢都不打紧，兄弟三人同心到哪儿都站得住',
   '固定镜头，这名白衣头领语气宽厚笃定，一番话说得人心安定',
   '85mm 长焦，浅景深','头领 + 平视正面','中心构图','身后的兄弟','锁定头领从容的目光','stable',
   'A static close-up holds the white-robed lord as he answers with steady warmth: <d>[Chinese] 聚也好散也罢，都不打紧。我兄弟三人同心，到哪儿都站得住。</d>'),
 ])
E10_2C = dict(scene=2,
 overall='The green-robed general agrees that where the brothers are not welcomed they will carve out a place to stand of their own.',
 music_en='A quiet, assured assent threading the wind.',
 blocking='关羽（C02）接话，说此处不留自有安身立命之所。',
 soundscape='绿袍将领一句不高的附话，风把马蹄与衣角一起吹着',
 music='一记平静笃定的应和音，顺着旷野的风低低流过',
 cuts=[
  (4.7,[5,5],'close','Static Shot',['C02'],[],
   '特写，一名绿袍长髯的将领缓声接话，说此处不留人、自有安身立命之所在，神色沉静',
   '固定镜头，这名绿袍长髯的将领平和地附和，话语沉稳，不疾不徐',
   '85mm 长焦，浅景深','将领 + 平视正面','中心构图','大哥','锁定将领沉稳的眉眼','stable',
   'A static close-up holds the long-bearded general in green as he adds a quiet, assured word: <d>[Chinese] 大哥说得是。此处不留，自有安身立命之所在。</d>'),
  (2.5,[6,6],'wide','Static Shot',['C01','C02','C03'],[],
   '全景，三人正行间，迎面一队溃散的败卒远远看见一面绣字旗号，纷纷跪倒在地',
   '固定镜头，官道迎面行来一队丢盔弃甲的败卒，夕阳下望见那面旗号，一个接一个跪了下去',
   '35mm 广角，深景深','官道 + 平视远眺','引导线构图','跪倒的败卒','锁定纷纷跪倒的人群','stable'),
 ])
E10_2D = dict(scene=2,
 overall='The white-robed lord dismounts to help a wounded soldier up and has water brought for him, telling the troops they are welcome as brothers and shall not go thirsty.',
 music_en='A tender, rallying phrase; kindness carried in a few chords.',
 blocking='刘备（C01）急忙下马扶起伤卒，命人取来清水；败卒应声聚拢。',
 soundscape='头领下马的衣袍声，扶起伤卒时的一声闷哼，随即一句宽厚的言语与取水声',
 music='一句温厚且提振的乐句，几个和弦间带出关怀与热忱',
 cuts=[
  (2.5,[7,7],'medium','Static Shot',['C01'],[],
   '中景，这名白衣头领看得心急，一把翻身下马，快步上前扶起为首的一名伤卒，又吩咐人去取水',
   '固定镜头，白衣头领下马疾步扶起伤卒，动作干脆，眉目间满是关切',
   '50mm 标准，中浅景深','头领 + 侧面平视','三分法','倒地的伤卒','锁定扶人的头领','stable'),
  (5.6,[8,8],'close','Static Shot',['C01'],[],
   '特写，白衣头领握着伤卒的手，声音朗然而和缓，说愿意跟随的便如同自家兄弟，有他一碗水便不让众人渴着',
   '固定镜头，这名白衣头领温言相告，一番话朴实而恳切，直说到众人心坎里',
   '85mm 长焦，浅景深','头领 + 平视正面','中心构图','跪地的败卒','锁定头领恳切的目光','stable',
   'A static close-up holds the white-robed lord as he speaks with plain sincerity to the kneeling troops: <d>[Chinese] 尔等愿随，便如我兄弟。有我一碗水，就不让你们渴着。</d>'),
 ])
E10_2E = dict(scene=2,
 overall='The black-armoured warrior grins and gathers the scattered spears, and in the talk the ranks swell until they raise their fists to his call.',
 music_en='A warming, growing pulse as the company gathers; a swell of shouts.',
 blocking='张飞（C03）咧嘴一笑拾起散落的长矛归拢；众卒（额外）应和举拳。',
 soundscape='黑甲猛汉咧嘴笑着拾拾捡捡的甲叶声，一句招呼，随即应和的齐声举拳与低吼',
 music='一段渐渐聚拢、升温的乐句，随这队伍的气劲一路高涨',
 cuts=[
  (2.5,[9,9],'close','Static Shot',['C03'],[],
   '特写，这名黑甲猛汉在旁咧嘴一笑，弯下腰把散落一地的长矛一把一把拾起来归拢到一处',
   '固定镜头，这名黑甲猛汉咧着嘴拾起散矛归拢，动作麻利，眼底透着高兴',
   '85mm 长焦，浅景深','黑甲猛汉 + 侧前平视','三分法','散落的长矛','锁定捡矛归拢的手','stable'),
  (3.1,[10,10],'close','Static Shot',['C03'],[],
   '特写，黑甲猛汉捧着归拢好的长矛直起身，眉开眼笑地朝前头喊了一句，说这队伍是越走越壮实了',
   '固定镜头，这名黑甲猛汉直起身来扬声笑喊，嗓门洪亮，满是欢喜',
   '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','前方的大哥','锁定猛汉畅快的眉眼','stable',
   'A static close-up holds the black-armoured warrior as he straightens up beaming and calls ahead: <d>[Chinese] 跟着大哥，这队伍越走越壮实！</d>'),
  (2.5,[11,11],'wide','Static Shot',['C01','C02','C03'],[],
   '全景，说话间又聚拢数百败卒，齐齐举拳应和三人的号令，尘土在脚下扬起的队伍愈发壮大',
   '固定镜头，越来越多的败卒围拢过来，齐刷刷举拳应和，三人在人潮中央显得愈发稳当',
   '35mm 广角，深景深','旷野 + 平视远眺','引导线构图','举拳的人群','锁定应和的群卒','slight-shake'),
 ])
E10_2F = dict(scene=2,
 overall='The three mount and ride on flank by flank, raising an endless stream of men behind them as they head for the far north.',
 music_en='A steady, swelling march as the column stretches behind.',
 blocking='刘、关、张（C01/C02/C03）翻身上马并辔而行，身后拖着望不见尾的人流。',
 soundscape='众人翻身上马的衣甲响、马蹄声渐齐，身后无数脚步声汇成一股向蓟北压去',
 music='一段稳定而愈壮的进行曲，队伍在人流身后不断拉长',
 cuts=[
  (2.5,[12,12],'wide','Tracking Shot',['C01','C02','C03'],[],
   '全景，三人翻身上马，并辔而行，身后跟着望不见尾的人流，沿着旷野朝蓟北方向浩浩开去',
   '镜头平稳跟随并辔的三骑，身后那条蜿蜒的队伍望不见尽头，一路向北方推进',
   '35mm 广角，中景深','三骑 + 侧后平视跟随','引导线构图','延伸的官道','锁定浩荡的队伍','stable'),
  (2.5,[13,13],'extreme-wide','Static Shot',['C01','C02','C03'],[],
   '大远景，马蹄扬尘，三骑渐行渐远，隐入莽莽旷野的尽头，身后的队伍再不见边际',
   '固定大远景，三匹战马在飞扬的尘烟中慢慢变小，融入旷野尽头，惟余一线旅尘',
   '24mm 广角，深景深','旷野 + 平视远眺','中心构图','远去的三骑','锁定渐远的骑影','stable'),
 ])
E10_2G = dict(scene=2,
 overall='They look back once at the column of smoke over the central plains, and without a word each grips the reins a little tighter.',
 music_en='A quiet, resolute pause over a long, far horizon.',
 blocking='三人回望中原冲天的烟火，谁也没言语，只把缰绳又攥紧了些。',
 soundscape='三骑勒马回望的缰绳声轻动，旷野风声里远处烟火隐约的嘶响，旋又归于寂静',
 music='一段静而坚毅的休止，遥遥铺向那道绵长的地平线',
 cuts=[
  (2.5,[14,14],'extreme-wide','Static Shot',['C01','C02','C03'],[],
   '大远景，三人回望一眼中原那团冲天的烟火，谁也没言语，只把缰绳又攥紧了些，随即策马没入天际',
   '固定大远景，三骑在极远处勒马回望，背后那点烟火在天边隐约飘着，随即缓缓转首向前',
   '24mm 广角，深景深','旷野 + 平视远眺','对称构图','远方的烟火','锁定回望又转首的剪影','stable'),
 ])

# =============== scene 3 : 各方雄主并起 (beats 1-19) C04/C10/C24 ===============
E10_3A = dict(scene=3,
 overall='At Chenliu the narrow-eyed lord stands on the mustering platform, unrolls an edict, and declares he will raise an army to build a great enterprise together with all of them.',
 music_en='A rising, swaggering fanfare under the proclamation.',
 blocking='曹操（C04）立于陈留点将台，抖开诏书向众军宣读起兵共图大业。',
 soundscape='点将台下攒动的人头与衣甲声，诏书抖开的布帛响，随后一句高亢的宣言与应和的声浪',
 music='一段上扬而张扬的号角垫在宣言之下，群卒随之轰然应和',
 cuts=[
  (2.5,[1,1],'wide','Static Shot',['C04'],[],
   '全景，陈留城头，一名细眼长髯的贵介立于高处点将台上，把一封诏书扬在空中向台下众军宣读',
   '固定镜头，这名细眼长髯的贵介高立于点将台上扬诏宣示，台下甲士黑压压一片翘首以望',
   '35mm 广角，深景深','城头 + 平视远眺','引导线构图','台下的众军','锁定扬诏的贵介','stable'),
  (2.5,[2,2],'close','Push In',['C04'],[],
   '特写，这名细眼长髯的贵介抖开诏书，目光扫过台下攒动的人头，声音陡然拔高，气势十足',
   '镜头朝这名贵介缓缓推近，他抖开诏书，目光居高临下扫过人群，语调一节比一节高',
   '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','台下众军','锁定贵介发亮的眼','stable'),
  (5.8,[3,3],'close','Static Shot',['C04'],[],
   '特写，这名细眼长髯的贵介一字一句朗声宣告，说要在这纷乱天下里与诸君共图大业，声震四方',
   '固定镜头，这名贵介慷慨陈词，话语铿锵有力，字字都像敲在众军心坎上',
   '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','台下众军','锁定贵介慷慨的眉目','stable',
   'A static close-up holds the narrow-eyed lord as he proclaims in a ringing voice his resolve to raise an army: <d>[Chinese] 董卓虽诛，天下纷争未定。我陈留起兵，与诸君共图大业！</d>'),
 ])
E10_3B = dict(scene=3,
 overall='The ranks below raise spears and swords in thunderous reply; he ascends the altar and, taking a cup of pledge-wine, sprinkles it on the ground before heaven and earth.',
 music_en='A huge swell of shouts; a solemn gesture as the wine scatters.',
 blocking='曹操（C04）登坛三拜，接过誓酒扬手泼洒祭过天地；台下众军举刀枪应和。',
 soundscape='台下轰然举起的刀枪与万口一声的应和，誓酒泼洒在地的轻响，风声掠过祭坛',
 music='一道山呼海啸般的应和声浪，随后誓酒洒地时一段郑重肃穆的乐句',
 cuts=[
  (2.5,[4,4],'wide','Pan Right',['C04'],[],
   '全景，台下军士举起刀枪应和，声浪一阵高过一阵，旌旗猎猎翻卷',
   '镜头向右摇过台下的军阵，无数刀枪高高举起，呼喝声连成一片震彻城头',
   '35mm 广角，中景深','台下的军阵 + 平视远眺','引导线构图','翻卷的旌旗','锁定高举的刀枪','slight-shake'),
  (2.5,[5,5],'medium','Static Shot',['C04'],[],
   '中景，这名细眼长髯的贵介于坛上郑重三拜，接过一碗誓酒，扬手泼洒在地，祭过天地',
   '固定镜头，贵介登坛三拜后接过誓酒，抬手一洒，酒液落地，姿态庄重',
   '50mm 标准，中浅景深','贵介 + 平视正面','中心构图','洒落的誓酒','锁定泼洒的酒','stable'),
  (6.2,[6,6],'close','Static Shot',['C04'],[],
   '特写，这名细眼长髯的贵介抬眼望着台下，一字一字说出那句乱世等不得靠山、只有握得住刀的才配称王的话',
   '固定镜头，这名贵介目光冷而亮，话语里满是狼性与野心，直直敲在每一个字上',
   '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','台下众军','锁定贵介野心的目光','stable',
   'A static close-up holds the narrow-eyed lord as he lays out his cold creed for the age: <d>[Chinese] 这乱世，等不得靠山，也等不得天命。能握住刀的，才配称王。</d>'),
 ])
E10_3C = dict(scene=3,
 overall='Meanwhile in the Hebei camp of the proud noble, the master sits in state over a roster and registers the officers who have come over to him.',
 music_en='A proud, swaggering phrase, formal and self-regarding.',
 blocking='袁绍（C10）高踞主座，捧着一卷名册，把投奔的部曲一一录下。',
 soundscape='主座上一阵从容的翻册声，投奔者报名的杂沓声，贵胄清点部众的自持低语',
 music='一段骄矜而端正的乐句，透着十足的自我看重',
 cuts=[
  (2.5,[7,7],'wide','Static Shot',['C10'],[],
   '全景，另一边，河北袁氏营帐里，一名华服高冠的倨傲贵胄高踞主座，捧着名册号令投部排序',
   '固定镜头，这名倨傲贵胄端坐主位，身前摊着一卷名册，堂下投奔者络绎而入',
   '35mm 广角，中景深','帅帐 + 平视远眺','对称构图','堂下投奔者','锁定高踞的贵胄','stable'),
  (4.9,[8,8],'close','Static Shot',['C10'],[],
   '特写，这名倨傲贵胄端着名册，慢悠悠地开口，说四世三公的名望之下，河北之地岂能拱手让人',
   '固定镜头，这名倨傲贵胄语气倨傲自得，一句话里满是家世的门第与底气',
   '85mm 长焦，浅景深','贵胄 + 平视正面','中心构图','手中的名册','锁定贵胄倨傲的眉眼','stable',
   'A static close-up holds the haughty noble as he speaks with aristocratic pride: <d>[Chinese] 我袁氏一门四世三公，河北之地，岂能拱手让人。</d>'),
 ])
E10_3D = dict(scene=3,
 overall='He slams the roster down, resolved to take his own place in the age, and orders from beyond the tent a call for talent far and wide.',
 music_en='A heavy, decisive thud; a herald\u2019s flourish beyond the flap.',
 blocking='袁绍（C10）把名册往案上一墩；营外有人张贴招贤榜文，应募者络绎于道。',
 soundscape='名册顿落案上的一声重响，帐外传来贴榜文与吆喝的动静',
 music='一句沉重决断的落音，继而是帐外穿梭的号筒与应募声',
 cuts=[
  (2.5,[9,9],'medium','Static Shot',['C10'],[],
   '中景，这名倨傲贵胄把名册往案上重重一墩，铁了心要在这乱世里占住一席之地',
   '固定镜头，贵胄将名册重重墩在案上，神色笃定，下定的决心毫不含糊',
   '50mm 标准，中浅景深','贵胄 + 平视正面','三分法','案上的名册','锁定顿落的册子','stable'),
  (2.5,[10,10],'wide','Pan Right',['C10'],[],
   '全景，名册一合，营外早有人把招贤的榜文贴上了河北的城门口，应募者携家络绎于道上',
   '镜头向右摇过城门口的榜文，背着行李前来的应募者排成长龙，络绎不绝',
   '35mm 广角，中景深','城门口 + 平视远眺','引导线构图','贴好的榜文','锁定应募的长队','stable'),
  (3.3,[11,11],'close','Static Shot',['C10'],[],
   '特写，这名倨傲贵胄抬眼吩咐下去，只说广招贤才多多益善，语气从容而笃定',
   '固定镜头，这名倨傲贵胄吩咐属僚，话语平缓却满含雄心，显然拿定了主意',
   '85mm 长焦，浅景深','贵胄 + 平视正面','中心构图','账下的属僚','锁定贵胄从容的神色','stable',
   'A static close-up holds the haughty noble as he gives a measured order: <d>[Chinese] 传令下去，广招贤才，多多益善。</d>'),
 ])
E10_3E = dict(scene=3,
 overall='In Jiangdong the iron general reins in at the ford, glances back at the central plains, and presses the imperial seal of the Han he carries in his saddle with his hand.',
 music_en='A rolling of river waves; a low, decisive chord.',
 blocking='孙坚（C24）勒马于渡口，回望中原，把那方玉玺又按了按。',
 soundscape='江涛拍岸的轰响与马鸣，铁甲将领回望时一声几不可闻的轻叹',
 music='江水翻滚的声响其下，一句低沉决断的和弦稳稳敲定',
 cuts=[
  (2.5,[12,12],'wide','Static Shot',['C24'],[],
   '全景，江东，一名银甲红巾的雄武将领勒马立于渡口，回头望一眼中原方向，神色深沉',
   '固定镜头，这名银甲将领勒马回望，江风掀动他的红巾与披风，目光投向中原',
   '35mm 广角，中景深','渡口 + 平视远眺','引导线构图','中原方向','锁定回望的将领','stable'),
  (4.0,[13,13],'close','Static Shot',['C24'],[],
   '特写，这名银甲将领垂眼望了望手中一方玉玺，沉声开口，说中原将乱，要先据江东养精蓄锐',
   '固定镜头，这名银甲将领低语盘算，目光沉稳，一番话为自己的立足定下步调',
   '85mm 长焦，浅景深','将领 + 平视正面','中心构图','掌中的玉玺','锁定将领沉定的眼','stable',
   'A static close-up holds the iron general as he weighs his course: <d>[Chinese] 中原将乱，我孙氏先据江东，养精蓄锐。</d>'),
 ])
E10_3F = dict(scene=3,
 overall='He spurs ahead toward Jiangdong and, after crossing, spreads a half-unrolled map whose fingertip hovers along the river line without lifting.',
 music_en='River roll and a long, appraising pause over the map.',
 blocking='孙坚（C24）扬鞭催马渡江，之后摊开半卷地图，指尖停在沿江一线。',
 soundscape='扬鞭催马的马蹄声，渡江的浪声，随军摊开地图、指尖轻抚纸面的沙响',
 music='江涛与马蹄之后，一段审视地图的绵长沉吟',
 cuts=[
  (2.5,[14,14],'wide','Tracking Shot',['C24'],[],
   '全景，他扬鞭催马，身后江涛拍岸，一行雄兵跟着这名银甲将领朝江东开去',
   '镜头平稳跟随策马的将领，他纵马扬鞭渡向江东，身后兵卒列队相随',
   '35mm 广角，中景深','渡口 + 侧后平视跟随','引导线构图','过江的方向','锁定催马的将领','stable'),
  (2.5,[15,15],'close','Static Shot',['C24'],[],
   '特写，渡江之后，这名银甲将领摊开半卷地图，指尖停在沿江一线，久久没有移开',
   '固定镜头，银甲将领垂首俯看地图，指尖沿着江线缓缓游走，目光久久凝在上面',
   '85mm 长焦，浅景深','将领 + 俯视正侧面','中心构图','摊开的地图','锁定按在江线的指尖','stable'),
 ])
E10_3G = dict(scene=3,
 overall='On the western frontier the remnant soldiers of the tyrant\u2019s force still hold a few broken passes, their blades glinting cold in the last light.',
 music_en='A thin, somber air over a lonely wall in the dying sun.',
 blocking='关西残部（额外兵卒）仍戍着几座破关。',
 soundscape='残阳里刀枪掠过鞘口的寒响，破关冷风卷动旗残的猎猎声',
 music='一阕清淡萧瑟的乐音，罩着残阳下那座孤关',
 cuts=[
  (2.5,[16,16],'extreme-wide','Static Shot',[],[],
   '大远景，关西方向，残存的西凉旧部仍戍着那几座破关，刀枪在残阳里泛着一层寒光',
   '固定大远景，几座破败的关城横在残阳下，戍卒倚墙而立，刀尖的光冷冷地亮着',
   '24mm 广角，深景深','破关 + 平视远眺','中心构图','残阳里的关墙','锁定泛着寒光的兵刃','stable'),
  (2.5,[17,17],'extreme-wide','Static Shot',[],[],
   '大远景，各地方圆百里，县令衙役早已散尽，只余几面枭雄的旗帜在城头孤独地悬着',
   '固定大远景，空荡荡的州城不见人烟，惟有城头那面旗帜被风吹着孤悬在暮色里',
   '24mm 广角，深景深','空城 + 平视远眺','中心构图','孤悬的旗帜','锁定冷清的空城','stable'),
 ])
E10_3H = dict(scene=3,
 overall='Four winds rise and banners hide the sun as beacons are lit one after another across the land and no man can longer hold them back.',
 music_en='A broad, swelling surge as every region kindles to war.',
 blocking='陆上各地方圆百里烽火一处接一处点燃，旌旗蔽日。',
 soundscape='狂风猎猎吹卷漫天旌旗，远方一处接一处的烽烟腾起，锣鼓此起彼伏',
 music='一段阔大而愈壮的声浪，随各地烽火一盏盏点亮席卷四野',
 cuts=[
  (2.5,[18,18],'extreme-wide','Static Shot',[],[],
   '大远景，四野风起，旌旗蔽日，天下各地的烽火一处接一处点燃，再无人能挡',
   '固定大远景，猎猎旌旗遮住半边天，四方的烽火烟柱接二连三地腾起',
   '24mm 广角，深景深','四野 + 平视远眺','中心构图','蔽日的旌旗','锁定连成片的烽火','slight-shake'),
  (2.5,[19,19],'extreme-wide','Static Shot',[],[],
   '大远景，极目之处一杆杆帅旗各自竖起，乱世的棋盘就此铺开，枭雄争霸，恐难止歇',
   '固定大远景，天地尽头众多帅旗逐杆立起，那道长到望不见头的棋盘缓缓铺满人间',
   '24mm 广角，深景深','四野 + 平视远眺','对称构图','林立的帅旗','锁定莽莽铺开的争霸','slight-shake'),
 ])

EP10_SC1 = [E10_1A, E10_1B, E10_1C, E10_1D, E10_1E, E10_1F, E10_1G, E10_1H, E10_1I]
EP10_SC2 = [E10_2A, E10_2B, E10_2C, E10_2D, E10_2E, E10_2F, E10_2G]
EP10_SC3 = [E10_3A, E10_3B, E10_3C, E10_3D, E10_3E, E10_3F, E10_3G, E10_3H]
for seg in EP10_SC1: seg['sceneIndex'] = 1
for seg in EP10_SC2: seg['sceneIndex'] = 2
for seg in EP10_SC3: seg['sceneIndex'] = 3
EP10 = EP10_SC1 + EP10_SC2 + EP10_SC3