# -*- coding: utf-8 -*-
"""EP9 segments (each segment <=15s, one dict per segment).
cut tuple: (seconds, beats, size, camera, chars, props, frame, shot, lens, camPos, comp, eye, focus, stab, en)
beats per-scene 1-based. Names only inside <d>; en/shot use descriptors."""

# =============== scene 1 : 密室定计 (beats 1-18) C06/C08 ===============
E9_1A = dict(scene=1,
 overall='In a secret chamber at night a grey-bearded minister pours a cup of wine and pushes it to a haggard, crowned warrior.',
 music_en='A low, hushed string tremolo over the still room.',
 blocking='王允（C08）亲手斟一碗酒推到吕布（C06）面前，良久不语；吕布攥着酒盏不动。',
 soundscape='夜深水静，酒入盏的细响，两人相对无言，只剩窗纸被风压得轻响',
 music='一段低而屏息的弦颤笼着满室沉静',
 cuts=[
  (2.5,[1,1],'medium','Static Shot',['C08'],[],
   '中景，夜，密室里一名须发花白的老臣亲手斟了一盏酒，缓缓推到桌前一名头戴雉尾紫金冠、略显颓色的猛将面前，良久不语',
   '固定镜头，这名须发花白的老臣斟酒推盏，抬眼望向对面的猛将，欲言又止',
   '50mm 标准，中浅景深','老臣 + 平视正面','中心构图','推出去的酒盏','锁定老臣凝重的神色','stable'),
  (2.5,[2,2],'close','Push In',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将双手攥着酒盏一动不动，一双眼睛红红的，像是一整夜没合眼',
   '镜头朝这名猛将缓缓推近，他握着酒盏不动，眼眶泛红、形容憔悴，满腹心事压着',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','手中的酒盏','锁定猛将泛红的眼','stable'),
  (4.7,[3,3],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣终于开口，声音压得又低又沉，把那桩倒悬的祸事一句挑明',
   '固定镜头，这名须发花白的老臣低声开口，字字郑重，把利害关系和盘托出',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣低沉的眉眼','stable',
   'A static close-up holds the grey-bearded minister as he finally speaks in a low, weighty voice: <d>[Chinese] 奉先，董卓若一日不倒，貂蝉便一日不得安宁。</d>'),
 ])
E9_1B = dict(scene=1,
 overall='The warrior lifts his eyes and drops them again, knuckles whitened, and answers that he is no man\u2019s fish to knead.',
 music_en='A taut, coiled string beneath his reluctant reply.',
 blocking='吕布（C06）猛地抬眼又垂下，指节攥得发白，低声答话。',
 soundscape='猛将一声压抑的低语，指节在盏沿上勒出的脆响，烛火微微一跳',
 music='一段绷紧的弦垫在话语底下，随时可能崩断',
 cuts=[
  (2.5,[4,4],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将猛地抬眼，又很快垂下，紧攥酒盏的指节根根泛白',
   '固定镜头，这名猛将抬眼又迅速垂下，眼里的光一闪而过，指节在盏沿勒得发白',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','酒盏','锁定猛将攥盏的手','stable'),
  (4.4,[5,5],'close','Static Shot',['C06'],[],
   '特写，这名猛将垂着眼，声音不高却带着一股硬劲，说出那句他也不是任人揉捏的软柿子',
   '固定镜头，这名猛将低声回话，语气里有挣扎也有火气，把自己那点不肯服软的性子剖了出来',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将垂而又抬的眼','stable',
   'A static close-up holds the crowned warrior as he answers low, a stubborn fire in his voice: <d>[Chinese] 他是我义父。可我也不是任人揉捏的软柿子。</d>'),
 ])
E9_1C = dict(scene=1,
 overall='The minister presses that the realm hates him and the land would be saved, while the warrior worries how the world will judge an adopted son.',
 music_en='A rising appeal answered by a troubled, guarded line.',
 blocking='王允（C08）陈以大义；吕布（C06）道出弑义父的顾虑。',
 soundscape='老臣一句铿锵的大义，随后猛将一句迟疑的自问，烛火在两人之间忽明忽暗',
 music='一段上扬的恳切随之化作一句心事重重的低弦回应',
 cuts=[
  (6.4,[6,6],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣一字一句陈明这暴虐无道、天下皆恨的罪状，再说除他汉室有救、万民称快',
   '固定镜头，这名须发花白的老臣神色凛然，把这话说得铿锵有力，字字掷地有声',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣慷慨的面容','stable',
   'A static close-up holds the minister as he presses the weight of it all: <d>[Chinese] 他暴虐无道，令天下恨之入骨。你若除他，汉室有救，万民称快。</d>'),
  (4.4,[7,7],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将低声说出那句弑义父天下人会怎样看我的顾虑，眉间满是挣扎',
   '固定镜头，这名猛将迟疑着说出顾虑，声音越来越轻，眉头拧成一个结',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将纠结的眉','stable',
   'A static close-up holds the warrior as he voices his deepest misgiving: <d>[Chinese] 我若动手，便是弑义父，天下人会怎样看我。</d>'),
 ])
E9_1D = dict(scene=1,
 overall='The minister draws close and, in a whisper, says he would slay a traitor to the state, a deed all men would praise.',
 music_en='A hushed, conspiratorial line, low and persuasive.',
 blocking='王允（C08）推了推酒盏凑近一步，压低声音劝解。',
 soundscape='老臣凑近低语，声音压得极低，满室只剩这窃窃一句',
 music='一句极轻的、充满蛊惑的低弦，贴着耳根滑过',
 cuts=[
  (2.5,[8,8],'close','Push In',['C08'],[],
   '特写，这名须发花白的老臣推了推酒盏，向对面的猛将凑近一步，声音压得极低欲言又止',
   '镜头朝这名老臣缓缓推近，他倾身凑近，压低的嗓音里带着笃定与急切',
   '85mm 长焦，浅景深','老臣 + 平视正侧面','中心构图','逼近的猛将','锁定老臣低语的唇','stable'),
  (4.9,[9,9],'close','Static Shot',['C08'],[],
   '特写，老臣盯着猛将的眼睛，一字一字低语，把除国贼、天下会念你的好记你的功的话说尽',
   '固定镜头，这名须发花白的老臣压低声音一句句劝说，眼神笃定，(言語里像锚定了什么)',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','猛将的眼','锁定老臣坚定的目光','stable',
   'A static close-up holds the minister as he whispers, eye to eye with the warrior: <d>[Chinese] 你除的是国贼。天下人只会念你的好，记你的功。</d>'),
 ])
E9_1E = dict(scene=1,
 overall='The minister brightens the candle and brings out a yellowed decree of revolt, and the warrior sees there is no turning back once it is raised.',
 music_en='A solemn, fateful note as the old edict is unrolled.',
 blocking='王允（C08）拨亮烛芯，从案下取出旧诏摊开；吕布（C06）搭眼一扫，眉头微皱。',
 soundscape='烛芯被拨亮的一声轻响，旧诏展开时布帛沙响，随后猛将一声低沉的轻叹',
 music='一句庄重而宿命的音随旧诏展开落定，压住一室沉寂',
 cuts=[
  (2.5,[10,10],'medium','Static Shot',['C08'],[],
   '中景，这名须发花白的老臣伸手拨亮烛芯，又从案下取出一卷泛黄的旧诏，轻轻摊在猛将面前',
   '固定镜头，老臣拨亮烛火，取出旧诏展开，动作郑重，像揭出一桩尘封的旧事',
   '50mm 标准，中浅景深','老臣 + 平视侧面','三分法','摊开的旧诏','锁定展开的诏书','stable'),
  (2.5,[11,11],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将搭眼一扫，见是讨逆的檄文，眉头几不可察地微微一皱',
   '固定镜头，这名猛将低头扫过檄文，神色沉了一瞬，眉头轻轻蹙起',
   '85mm 长焦，浅景深','猛将 + 俯视正面','中心构图','案上檄文','锁定猛将蹙起的眉','stable'),
  (4.2,[12,12],'close','Static Shot',['C06'],[],
   '特写，这名猛将指腹按在檄文上，低声说出那句檄文一揭便再无回头余地的话，目光沉郁',
   '固定镜头，这名猛将低声道岔点,目光定定落在檄文上，声音里带着辨认得清的重量',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','案上檄文','锁定猛将沉郁的脸','stable',
   'A static close-up holds the warrior as he weighs the parchment in his hands and speaks of the point of no return: <d>[Chinese] 这檄文一揭，天下就再无我回头的余地了。</d>'),
 ])
E9_1F = dict(scene=1,
 overall='The minister tells him plainly he is already cornered, for the tyrant prizes yet distrusts him; the warrior reaches out and folds the edict away into his sleeve.',
 music_en='A low warning, then the faint rustle of cloth as the deed is accepted.',
 blocking='王允（C08）点破他已无退路；吕布（C06）沉默半晌，终把那卷檄文收入袖中。',
 soundscape='老臣一句冷静的点破，随后猛将顿了一拍，捧起檄文缓缓收入袖中的衣料声',
 music='一句低警告响起，继而是布料窸窣一声，仿佛某件大事就此敲定',
 cuts=[
  (4.9,[13,13],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣冷静地一点一点地拆穿他已无退路的处境，声音不带半分感情',
   '固定镜头，这名老臣压着声线一句句点破，目光冷淡而笃定，像早已看穿一切',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣冷静的眼','stable',
   'A static close-up holds the minister as he lays out the cold arithmetic plainly: <d>[Chinese] 你本已无退路。董卓贪你爱将，其实已疑你久矣。</d>'),
  (2.5,[14,14],'medium','Static Shot',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将沉默良久，终是伸手，轻轻把那卷檄文收进袖中',
   '固定镜头，这名猛将静默片刻，抬手将檄文缓缓收入袖中，动作虽轻，分量却重',
   '50mm 标准，中浅景深','猛将 + 平视侧面','三分法','袖中的檄文','锁定收卷入袖的手','stable'),
 ])
E9_1G = dict(scene=1,
 overall='The warrior drains the wine in one go, slams the cup down so the flame jumps, and vows to rid the state of the scourge at dawn.',
 music_en='A sudden resolve; a sharp percussion as the cup strikes the table.',
 blocking='吕布（C06）端起酒一仰而尽，重重把盏拍在案上，扬声立誓。',
 soundscape='酒入喉的咕咚一声，酒杯顿落的闷响撞得烛火一晃，随后一句有力的立誓',
 music='一段骤起的决意，杯落案上的一记短促打击随之而来',
 cuts=[
  (2.5,[15,15],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将端起那盏酒，手在半空停了一瞬，还是一仰头一饮而尽',
   '固定镜头，这名猛将端盏在手微一停顿，随即仰头一饮而尽，喉结一滚',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','仰起的酒盏','锁定猛将仰头饮酒','stable'),
  (2.5,[16,16],'medium','Static Shot',['C06'],[],
   '中景，这名猛将重重把酒盏拍在案上，撞得案上烛火猛地一晃',
   '固定镜头，猛将一挥手把盏重重顿在案上，力道之大让烛火连跳好几下',
   '50mm 标准，中浅景深','猛将 + 平视侧面','三分法','案上酒盏','锁定顿落的酒盏','slight-shake'),
  (4.7,[17,17],'close','Static Shot',['C06'],[],
   '特写，这名猛将抬眼定住，声音不高却字字如铁，立下明早大殿除贼的誓言',
   '固定镜头，这名猛将抬眼开口，目光沉定，一诺如山',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将决然的眼','stable',
   'A static close-up holds the warrior as he lifts his gaze and swears it like iron: <d>[Chinese] 好。明早大殿之上，我便替天下除了这个祸害。</d>'),
 ])
E9_1H = dict(scene=1,
 overall='Night wind stirs the flame; the two men hold each other\u2019s gaze as a killing stroke settles between them.',
 music_en='A held, fateful chord; the whole chamber suspended.',
 blocking='夜风卷动烛火，王允（C08）与吕布（C06）对视，一场杀局就此落定。',
 soundscape='夜风卷过窗纸，烛火晃动，两人隔着那一跳一跳的火光沉默对视',
 music='一句悬置不落的宿命和弦，把一室杀机拢得密不透风',
 cuts=[
  (2.5,[18,18],'extreme-wide','Static Shot',['C08','C06'],[],
   '大远景，夜风卷动烛火，密室里须发花白的老臣与头戴雉尾紫金冠的猛将隔着案相对，目光定定相接，一场杀局就此落定',
   '固定大远景，两人隔案对视，烛火在中间摇曳，满室杀机沉默地压着',
   '24mm 广角，深景深','密室全景 + 平视远眺','对称构图','对视的两人','锁定隔案相望的二人剪影','stable'),
 ])

# =============== scene 2 : 殿前诛董 (beats 1-17) C06/C08/C09 props=['P03'] ===============
E9_2A = dict(scene=2,
 overall='At dawn the bloated tyrant rides his carriage up to the palace steps and, alighting, feels a dull heat in his gut and a stirring of unease.',
 music_en='A heavy, pompous procession cutting into a thread of foreboding.',
 blocking='董卓（C09）乘车驾直驶殿前台阶，下车后腹中发热、心口一紧感出蹊跷。',
 soundscape='晨光里铜车碾过石阶的辘辘声，一阵沉重车驾辎重，随后权臣心口一紧的闷响',
 music='一段厚重而骄横的队列乐，渐渐钻入一缕不祥的预示音',
 cuts=[
  (2.5,[1,1],'wide','Tracking Shot',['C09'],[],
   '全景，晨光铺满丹陛，一名体躯臃肿的凶戾权臣大摇大摆地乘着华丽车驾，直驶向殿前台阶',
   '镜头平稳跟随一辆华丽车驾驶过丹陛，车中那名体躯臃肿的权臣趾高气扬',
   '35mm 广角，中景深','权臣车驾 + 侧后平视跟随','引导线构图','前方殿陛','锁定驶向殿阶的车驾','stable'),
  (2.5,[2,2],'close','Push In',['C09'],[],
   '特写，这名凶戾权臣在阶前下车，腹中隐隐发热，心口忽地一紧，神色里掠过一丝几不可察的警觉',
   '镜头朝这名权臣缓缓推近，他落地时身形一顿，眉头微动，仿佛觉出几分蹊跷',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','前方殿门','锁定权臣一闪的警觉','stable'),
  (2.9,[3,3],'close','Static Shot',['C09'],[],
   '特写，这名凶戾权臣站定，皱眉扫了一眼空荡的内庭，低声说出那句今日怎这般冷清的话',
   '固定镜头，这名凶戾权臣环顾空庭，眉头越皱越紧，压着声音问了一句',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','空荡的内庭','锁定权臣骤然警觉的眼','stable',
   'A static close-up holds the tyrant as he frowns at the oddly empty courtyard and mutters to himself: <d>[Chinese] 今日这内庭，怎的这般冷清？</d>'),
 ])
E9_2B = dict(scene=2,
 overall='There is a rush from a side gate, a halberd flicks the carriage curtain up with a cry of treason, and the tyrant screams for his guards.',
 music_en='A sharp, jagged stab of strings; confusion and shouts.',
 blocking='李肃（不在框内）自侧门冲出，一戟挑开车帘；董卓（C09）惊怒大喊。',
 soundscape='侧门被猛地撞开，一杆画戟挑帘的裂响，紧着权臣又惊又怒的嘶喊',
 music='一声尖利断续的弦击划破晨光，继而是嘈杂的呼喝声浪',
 cuts=[
  (2.5,[4,4],'medium','Truck Right',['C09'],[],
   '中景，侧门猛然撞开，一道黑影冲出，一杆画戟挑下车帘，一声捉贼的高喊破空而起',
   '镜头随侧门急向右移，一道持戟身影扑出，挑帘高喝，晨光里寒光一冽',
   '50mm 标准，中浅景深','车驾 + 平视侧面','对角线构图','挑开的车帘','锁定冲出的持戟身影','slight-shake'),
  (2.9,[5,5],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣又惊又怒，指着扑来的身影嘶喊，声音里已带上一丝慌乱',
   '固定镜头，这名凶戾权臣惊怒嘶喊，指节微微发抖，退了一步又强自站住',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','扑来的身影','锁定权臣惊怒的面容','slight-shake',
   'A static close-up holds the tyrant as he screams in rage and alarm: <d>[Chinese] 李肃！你竟敢反我！来人啊！</d>'),
 ])
E9_2C = dict(scene=2,
 overall='His guards scatter and he flees toward the hall only to find the crowned warrior barring the way with halberd drawn; father begs and adopted son renounces.',
 music_en='A hunted scramble, then a cold declarative blade of music.',
 blocking='董卓（C09）推开护卫欲逃，却见吕布（C06）持戟立在阶前受其求救与绝情回应。',
 soundscape='权臣狼狈推搡护卫的闷响，随即猛将手持画戟横在阶前的铮鸣，两声对话一急一冷',
 music='一段慌乱的追击乐,随即一句冷锐的断言乐压住全场',
 cuts=[
  (2.5,[6,6],'medium','Tracking Shot',['C09'],[],
   '中景，凶戾权臣狼狈地推开护卫，拔腿就要往殿内逃，同刻抬头望见阶前立着一道持戟的身影',
   '镜头跟随狼狈奔逃的权臣，他抬眼时神色骤变，阶前那道身影已是拦路的铁壁',
   '50mm 标准，中浅景深','权臣 + 侧后平视跟随','引导线构图','阶前的猛将','锁定权臣骤然煞白的脸','slight-shake'),
  (2.2,[7,7],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣见了那身影立时改口哀求，声音里又惊又惧，只叫他快来救父',
   '固定镜头，这名权臣慌乱中改口求救，声音发抖，哪还有半分往日的跋扈',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','阶前的猛将','锁定权臣哀求的眼','slight-shake',
   'A static close-up holds the tyrant as he turns to pleading, dread cracking his voice: <d>[Chinese] 吾儿奉先，快来救父！</d>'),
  (3.8,[8,8],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将举戟指向逃来的权臣，声音又冷又硬，一字一字断绝了那父子相称',
   '固定镜头，这名猛将横戟而指，神色凛然，一句话说得毫无转圜余地',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','逃来的权臣','锁定猛将冷硬的目光','stable',
   'A static close-up holds the warrior as he levels the halberd and cuts off all kinship, cold and hard: <d>[Chinese] 反贼到此，还想父子相称，求免一死！</d>'),
 ])
E9_2D = dict(scene=2,
 overall='He springs up and drives the halberd through the tyrant\u2019s chest; the tyrant stands a frozen instant, then topples onto the steps as blood spreads.',
 music_en='A single, stark stab of brass, then a dull, heavy silence.',
 blocking='吕布（C06）纵身上前，一戟贯穿董卓（C09）前胸；满朝文武惊颤后爆出压抑的欢呼。',
 soundscape='猛将纵身跃起、一声闷响，画戟贯穿的钝响，随后满殿压抑许久的一声欢呼炸开',
 music='一记单一而尖刻的铜管声，继而坠入一霎肃穆的沉重死寂',
 cuts=[
  (2.5,[9,9],'medium','Tracking Shot',['C06'],[],
   '中景，这只头戴雉尾紫金冠的猛将纵身上前，手中画戟一引，正正贯穿那名权臣的前胸',
   '镜头平稳跟拍猛将纵身前扑的身形，画戟一送到底，寒光没入胸前的衣袍',
   '50mm 标准，中浅景深','猛将 + 侧前平视跟随','对角线构图','贯穿的一戟','锁定贯穿的瞬间','slight-shake'),
  (2.5,[10,10],'wide','Static Shot',['C09'],[],
   '全景，凶戾权臣瞪大双眼僵立一瞬，随即轰然倒在丹陛之上，血污自伤处缓缓漫开，晨光铺在其上',
   '固定镜头，权臣僵立一瞬后轰然倒地，丹陛上血污漫开，晨光照得一地刺目',
   '35mm 广角，深景深','丹陛 + 俯视远眺','中心构图','倒地的权臣','锁定倒下的身形与漫开的血','stable'),
  (2.5,[11,11],'wide','Pan Right',['C06'],[],
   '全景，殿内满朝文武先是一瞬僵住，随即爆出一阵压抑许久的欢呼，各色朝服攒动',
   '镜头向右缓缓摇过群臣，众人神色由惊转喜，一阵低而畅的快意鼓起掌声',
   '35mm 广角，中景深','群臣 + 平视远眺','引导线构图','殿前的猛将','锁定欢腾的群臣','slight-shake'),
 ])
E9_2E = dict(scene=2,
 overall='Amid the acclaim a cry rises that the troublemaker is dead and the Han low-hung phase is saved, while the warrior stands over the body, his gaze briefly darkening.',
 music_en='A swelling release of tension, then a private, inward beat.',
 blocking='朝臣（C08）高呼汉室有救；吕布（C06）驻戟立于晨光中，眸色却微微一沉。',
 soundscape='群臣一声高过一声的欢呼，猛将驻戟时甲叶作响，晨光里那片刻的静默',
 music='一道豁然开朗的释然乐句，随即转入一记私稳的心跳节拍',
 cuts=[
  (2.4,[12,12],'close','Static Shot',['C08'],[],
   '特写，一名须发花白的老臣振臂高呼，声音里有压抑后的痛快，喊出那句汉室得救的话',
   '固定镜头，这名须发花白的老臣振臂高呼，神采飞扬，把满腔郁气一并喊出',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','殿前猛将','锁定老臣放光的眼','stable',
   'A static close-up holds a grey-bearded minister as he cries out with long-suppressed relief: <d>[Chinese] 董贼已诛，汉室有救了！</d>'),
  (2.5,[13,13],'medium','Static Shot',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将驻戟而立，迎着晨光，尘埃落定之时，眸色却沉了沉',
   '固定镜头，猛将迎着晨光驻戟而立，待尘埃落定，那双眼睛里却飞快掠过一丝沉色',
   '50mm 标准，中浅景深','猛将 + 平视正面','中心构图','倒地的权臣','锁定猛将沉了一瞬的眸','stable'),
 ])
E9_2F = dict(scene=2,
 overall='He draws the halberd out and lets his gaze sweep the crowd of calculating eyes before he sets it down and takes charge of the capital.',
 music_en='A low, possessive resolve as he reasserts control.',
 blocking='吕布（C06）一根一根拔出画戟，扫视阶下众人，然后扬声放话镇守长安。',
 soundscape='画戟缓缓抽出的刃响，猛将目光扫过满阶时衣甲轻响，随即一句沉声话语落定',
 music='一句低沉而充斥掌控欲的乐句，随他重新握住局面缓缓摆平',
 cuts=[
  (2.5,[14,14],'close','Push In',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将一手一根一根拔出画戟，目光缓缓扫过阶下那一双双眼，眼底冷的没有温度',
   '镜头朝这名猛将缓缓推近，他抽戟的动作又慢又稳，眉眼间是对满场目光的了然与戒备',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','门外的丹陛','锁定猛将拔戟垂下的眼','stable'),
  (4.2,[15,15],'close','Static Shot',['C06'],[],
   '特写，这名猛将放下画戟，扬声说出了那句今后长安由他看护的话，声音里满是当仁不让的冷硬',
   '固定镜头，这名猛将开口放话，一句一字都带着掌控的姿态，不容置疑',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','满殿群臣','锁定猛将主掌的面容','stable',
   'A static close-up holds the warrior as he announces his grip on the capital with quiet finality: <d>[Chinese] 董贼已除。今后这长安，自有我吕布看护。</d>'),
 ])
E9_2G = dict(scene=2,
 overall='Word spreads to the common people surging at the palace walls, while the minister bows repeatedly and casts one uneasy look toward the west gate.',
 music_en='A swelling murmur of the crowd; an undertone of unease under the old minister.',
 blocking='百姓（不在框内）涌入皇城外围欢呼；王允（C08）在阶前作揖，抬眼望了望城西方向。',
 soundscape='皇城外一片欢腾的人声，老臣作揖的衣袍声，随后一声几不可闻的、望向城西的轻叹',
 music='人群的嗡鸣渐起，其下压着一缕老臣眉头染上的淡淡的隐忧',
 cuts=[
  (2.5,[16,16],'wide','Static Shot',['C08'],[],
   '全景，皇城外围涌来无数百姓，人声鼎沸，欢呼声一浪高过一浪；阶前须发花白的老臣不住向四方作揖',
   '固定镜头，人群涌在围墙外交相欢呼，老臣在阶前连连作揖，神色却不算全然轻松',
   '35mm 广角，中景深','皇城前 + 平视远眺','引导线构图','欢腾的人群','锁定作揖的老臣','slight-shake'),
  (2.5,[17,17],'close','Push In',['C08'],[],
   '特写，这名须发花白的老臣在满堂欢喜中，独独抬眼望了望城西方向，眉头几不可察地一沉',
   '镜头朝这名老臣缓缓推近，他抬眼望向远方，笑意一点点收住，眉头轻轻压下一层心事',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','城西地平线','锁定老臣沉下的目光','stable'),
 ])

# =============== scene 3 : 斩草除根之争 (beats 1-15) C06/C08 ===============
E9_3A = dict(scene=2,
 overall='After the victory feast disperses the minister keeps the warrior behind to raise the danger of the tyrant\u2019s scattered western forces.',
 music_en='A spare, worried line under a late-night hall.',
 blocking='庆功宴散，王允（C08）独留吕布（C06）在偏殿议事，开口点出西凉旧部隐患。',
 soundscape='宴散后殿宇重归空寂，杯盏撤去的细响，老臣压着声的一句警告',
 music='一句淡而忧心忡忡的弦音，罩着午夜偏殿的冷清',
 cuts=[
  (2.5,[1,1],'medium','Static Shot',['C08','C06'],[],
   '中景，夜，庆功酒宴已散，偏殿里须发花白的老臣独独留下那名头戴雉尾紫金冠的猛将，屏退了余人',
   '固定镜头，宴已散去，老臣独留猛将于偏殿，殿门合拢，烛光下两人相对而坐',
   '50mm 标准，中浅景深','二人 + 平视侧面','对称构图','对坐的两人','锁定被独留的猛将','stable'),
  (4.9,[2,2],'close','Static Shot',['C08'],[],
   '特写，这名须发花白的老臣指尖按着案角，低声把那西凉旧部拥重兵在外的隐患一句道破',
   '固定镜头，这名老臣压低声音道出隐忧，神色凝重，视线始终不离开对坐的猛将',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣忧虑的眉眼','stable',
   'A static close-up holds the minister as he voices the lingering danger: <d>[Chinese] 董卓虽除，其西凉旧部李傕、郭汜尚拥重兵在外。</d>'),
 ])
E9_3B = dict(scene=2,
 overall='The warrior scoffs at a pack of beaten dogs, but the minister insists the grass must be pulled out by the roots lest it grow again.',
 music_en='A dismissive pluck answered by a stern, insistent line.',
 blocking='吕布（C06）不屑摆手；王允（C08）坚持斩草须除根。',
 soundscape='猛将一声轻蔑的笑与摆手，随后老臣坚定地提出通令各关严加堵截',
 music='一句轻蔑的拨弦随即换成一段严肃而执拗的乐句',
 cuts=[
  (3.8,[3,3],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将不以为然地哂笑一声，摆摆手，只说那是一群闻风便跑的丧家之犬',
   '固定镜头，这名猛将轻蔑一笑，连话里都带着不放在眼里的傲气',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将轻蔑的笑','stable',
   'A static close-up holds the warrior as he snorts in contempt, brushing the warning aside: <d>[Chinese] 一群丧家之犬，闻风便跑，何足挂齿。</d>'),
  (6.0,[4,4],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣神色一正，说出斩草须除根的话，提出要通令各关严加堵截、不容卷土重来',
   '固定镜头，这名老臣正色相告，语气坚定，把这桩必须了断的后患说得斩钉截铁',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣坚定的神色','stable',
   'A static close-up holds the minister as he insists with hard finality: <d>[Chinese] 斩草须除根。我意通令各关，严加堵截，不使他们卷土重来。</d>'),
 ])
E9_3C = dict(scene=2,
 overall='The warrior furrows his brow and urges restraint, warning that driving them hard will only create more trouble.',
 music_en='A cautious, reasoning line against the hard edge of the earlier vow.',
 blocking='吕布（C06）皱眉摆手，劝老臣此刻正宜安抚；王允（C08）静听不答。',
 soundscape='猛将皱眉劝诫的低语，一句逼急了反而生变的提醒，殿外夜风穿廊而过',
 music='一段谨慎而思量的乐句，压在对立的那道硬话之上',
 cuts=[
  (2.5,[5,5],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将皱眉，不以为然地摆了摆手，神色里觉得这是小题大做',
   '固定镜头，这名猛将皱眉摆手，动作随意，把对方的话当成多虑',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将摆动的眉梢','stable'),
  (4.4,[6,6],'close','Static Shot',['C06'],[],
   '特写，这名猛将放缓声音劝诫，说此刻正宜安抚，逼急了反而要生变，眉宇竟透出少见的沉稳',
   '固定镜头，这名猛将语重心长地劝,神色少有地显得沉稳',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','老臣','锁定猛将示警的眼','stable',
   'A static close-up holds the warrior as he counsels patience with rare sobriety: <d>[Chinese] 义父慎思，此刻正宜安抚，逼急了反而生变。</d>'),
 ])
E9_3D = dict(scene=2,
 overall='The minister overrides him and says leaving the tiger in the hills will bring endless trouble; the warrior, seeing no room, bows and withdraws from the hall.',
 music_en='A firm refusal, then a muted retreat of footsteps.',
 blocking='王允（C08）强势定论由他办；吕布（C06）欲言又止，终究拱手退出偏殿。',
 soundscape='老臣一句不容置喙的定论，随后猛将一句欲言又止的犹豫，衣袍与脚步渐渐退远的声响',
 music='一句坚决的拒斥乐，随后脚步闷响着渐行渐远',
 cuts=[
  (5.3,[7,7],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣一句话定死，说放虎归山后患无穷、这事便由他来办，不给半分商量的余地',
   '固定镜头，这名老臣态度强硬，话里没有丝毫转圜，一锤定音',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的猛将','锁定老臣不容争辩的目光','stable',
   'A static close-up holds the minister as he rules with finality: <d>[Chinese] 放虎归山，后患无穷。这事便由我来办，你勿再多言。</d>'),
  (2.5,[8,8],'medium','Truck Left',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将欲言又止，僵了一瞬，终究拱了拱手，转身一步步退出偏殿',
   '镜头随猛将左移，他欲言又止后拱手一礼，转身离去，脚步透着一丝无可奈何',
   '50mm 标准，中浅景深','猛将 + 侧后平视跟随','引导线构图','殿门','锁定猛将退去的背影','stable'),
 ])
E9_3E = dict(scene=3,
 overall='Left alone the minister writes warrants to every pass, muttering to himself that the root must be pulled or it will feed on him come later.',
 music_en='A solitary scratch of the brush, a low self-foreboding mutter.',
 blocking='王允（C08）独坐偏殿执笔写通缉文书，自语那句斩草须除根的话。',
 soundscape='毛笔在纸上沙沙的走动声，老臣一句压得极低的自语，窗外风声渐起',
 music='独奏的笔尖沙声衬着一句低沉的自我警醒',
 cuts=[
  (2.5,[9,9],'medium','Static Shot',['C08'],[],
   '中景，宴散人走，须发花白的老臣独自留在殿中，执笔写下一道道发往各关的通缉文书',
   '固定镜头，老臣一人独坐执笔，案上摊开一叠文书，笔尖起落不停',
   '50mm 标准，中浅景深','老臣 + 俯视侧面','三分法','案上文书','锁定执笔的老臣','stable'),
  (5.3,[10,10],'close','Static Shot',['C08'],[],
   '特写，这名须发花白的老臣边写边低声自语，把那句斩草须除根、这一步再不能软了的话，说给自己听',
   '固定镜头，这名老臣落笔间低声喃喃，目光沉在纸上，像对自己立誓',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','案上文书','锁定老臣低语的面容','stable',
   'A static close-up holds the minister as he writes on, muttering a private resolve to himself: <d>[Chinese] 斩草若不除根，来日必为所噬。这一步，再不能软了。</d>'),
 ])
E9_3F = dict(scene=3,
 overall='The candle draws a vast dark shadow across the window paper, and the minister looks up to see figures moving in the moonlight.',
 music_en='A thin, creeping dissonance; the room grows close.',
 blocking='窗外忽然一暗，王允（C08）透过窗棂见月色里人影幢幢。',
 soundscape='烛火噼啪一声，窗纸外骤然一暗，紧着是压得极低的人影移动的窸窣',
 music='一缕细而蔓生的不协和音爬上来，把室内逼得发紧',
 cuts=[
  (2.5,[11,11],'medium','Push In',['C08'],[],
   '中景，笔尖落处墨迹未干，窗纸外忽然一暗，像是有大片黑影压了过来，遮住月光',
   '镜头朝窗缓缓推近，窗外光线骤然敛去，一道沉重黑影贴上了窗纸',
   '50mm 标准，中浅景深','窗纸 + 平视正面','中心构图','窗外的黑影','锁定骤然压暗的窗','slight-shake'),
  (2.5,[12,12],'extreme-close','Static Shot',['C08'],[],
   '大特写，这名须发花白的老臣手一抖猛地抬头，隔着窗棂只见月色里人影幢幢，如鬼魅行走',
   '固定镜头，老臣骤然抬头，眼底映出窗外纷乱游移的身影，呼吸都为之一屏',
   '100mm 微距，极浅景深','老臣的眼 + 平视','中心构图','窗外的身影','锁定老臣骤凝的视线','stable'),
 ])
E9_3G = dict(scene=3,
 overall='He sets down the brush and steps into the corridor but finds the night guards have melted away; cold wind cuts through and he bolts the doors shut.',
 music_en='An eerie, emptied quiet; a quick, frightened bolt.',
 blocking='王允（C08）搁笔行至廊下发现守编退尽，冷风穿堂，回身闩紧殿门。',
 soundscape='老臣搁笔起身的声响，廊下空寂得反常，冷风穿堂而过，随即殿门被急促闩上的闷响',
 music='一段空寂诡异的静，紧接着一记慌张的门闩声响',
 cuts=[
  (2.5,[13,13],'wide','Static Shot',['C08'],[],
   '全景，这名须发花白的老臣搁下笔，几步走到廊下，却见原本守夜的卫士已退得干干净净，空无一人',
   '固定镜头，老臣环顾廊下，只见空荡荡不见半个人影，反常得叫人心里发毛',
   '35mm 广角，深景深','空廊 + 平视远眺','引导线构图','空无一人的回廊','锁定一片空寂的长廊','stable'),
  (2.5,[14,14],'medium','Truck Right',['C08'],[],
   '中景，冷风穿堂而过，这名须发花白的老臣神色一凛，把文书一把按进袖中，回身快步闩紧了殿门',
   '镜头随老臣右移，他神色紧张地收好文书、快步回身闩门，动作又急又紧',
   '50mm 标准，中浅景深','老臣 + 侧后平视跟随','三分法','殿门','锁定闩门的动作','slight-shake'),
 ])
E9_3H = dict(scene=4,
 overall='The candle flame is battered by the wind and beyond the window a rush of hoofbeats circles toward the west gate.',
 music_en='A final, whipping turbulence over a fast-approaching roll of hooves.',
 blocking='烛火东倒西歪，王允（C08）立于殿内，窗外马蹄声由远及近直扑城西。',
 soundscape='烛火被风卷得噼啪乱晃，忽地一阵密集的马蹄声由远及近，往城西方向疾驰而去',
 music='一句激烈的狂风乐席卷而过，马蹄声在其下越滚越近，直奔城西',
 cuts=[
  (2.5,[15,15],'medium','Pan Left',['C08'],[],
   '中景，烛火被风卷得东倒西歪，这名须发花白的老臣立在殿中央，窗外忽然传来一阵急促的马蹄声，由远及近，直扑城西',
   '镜头向左缓缓摇过，烛影东倒西晃，老臣侧耳凝神，窗外蹄声如骤雨般滚向城西',
   '50mm 标准，中浅景深','殿内 + 平视侧面','三分法','窗外的夜色','锁定老臣凝神的侧影','stable'),
 ])

EP9_SC1 = [E9_1A, E9_1B, E9_1C, E9_1D, E9_1E, E9_1F, E9_1G, E9_1H]
EP9_SC2 = [E9_2A, E9_2B, E9_2C, E9_2D, E9_2E, E9_2F, E9_2G]
EP9_SC3 = [E9_3A, E9_3B, E9_3C, E9_3D, E9_3E, E9_3F, E9_3G, E9_3H]
for seg in EP9_SC1: seg['sceneIndex'] = 1
for seg in EP9_SC2: seg['sceneIndex'] = 2
for seg in EP9_SC3: seg['sceneIndex'] = 3
EP9 = EP9_SC1 + EP9_SC2 + EP9_SC3