# -*- coding: utf-8 -*-
"""EP7 segments (each segment <=15s, one dict per segment).
cut tuple: (seconds, beats, size, camera, chars, props, frame, shot, lens, camPos, comp, eye, focus, stab, en)
beats per-scene 1-based. All EP7 scenes props None -> cut props=[]. Names only inside <d>; en/shot use descriptors."""

# =============== scene 1 : 洛阳焚城 (beats 1-22) C06/C08/C09 ===============
E7_1A = dict(scene=1,
 overall='On the burning rampart of Luoyang a tyrant watches his soldiers put the city to the torch.',
 music_en='A grim, low drone with crackling embers and a lone horn that keeps its single note hanging.',
 blocking='董卓（C09）拄剑立于城头正中俯瞰；城下百姓哭喊奔逃。',
 soundscape='城头火光冲天、噼啪作响，浓烟滚滚，城下百姓哭喊奔逃的声浪',
 music='低沉的慢板垫底，夹着木柴燃爆的噼啪，一杆号保持着同一个音悬着不落',
 cuts=[
  (2.5,[1,1],'wide','Pan Right',['C09'],[],
   '全景，洛阳城头，一名体躯臃肿、满脸戾气的凶戾权臣一手拄剑，冷眼看着城下士卒举着火把，把一排民居点着',
   '镜头向右缓缓摇过城头，这名体躯臃肿的权臣拄剑而立，冷眼俯瞰城角一字排开的火把与民居',
   '35mm 广角，中景深','权臣 + 侧前平视俯瞰','引导线构图','城下民居','锁定权臣冷毒的目光','stable'),
  (2.5,[2,2],'wide','Static Shot',['C09'],[],
   '全景，火头一处接一处窜起，浓烟滚滚直冲天际，城下百姓哭喊着拖家带口往外逃，乱作一团',
   '固定镜头，城下火头接连窜起，浓烟滚滚，百姓拖家带口哭喊着向外奔逃，全然乱作一团',
   '35mm 广角，中景深','城下景 + 俯拍','中心构图','奔逃的百姓','锁定窜起的火头与浓烟','slight-shake'),
  (4.0,[3,3],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣转头望向火光冲天的城郭，浓眉下一双眼没有半分怜悯，沉声开口，说得理所当然',
   '固定镜头，这名凶戾权臣侧头望向冲天的火光，脸上没有半分怜悯，声音沉冷而理所当然',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','火光中的城郭','锁定权臣冷硬的眉眼','stable',
   'A static close-up holds the tyrant\u2019s face as he turns toward the blazing city with no trace of pity, and the cold voice declares: <d>[Chinese] 一把火烧了，省得留个踞地给那些诸侯！</d>'),
 ])
E7_1B = dict(scene=1,
 overall='A helpless old woman is robbed in the fire and a grey-bearded minister looks on in mute grief, then speaks out at last.',
 music_en='The drone tightens; low strings press forward under the minister\u2019s words.',
 blocking='王允（C08）在阶下远远看着火场的惨状，攥拳欲言；董卓（C09）于城头冷眼。',
 soundscape='火声越烧越猛，老妇的哭喊与老臣低沉的痛诉相继落入滚滚浓烟',
 music='底音越拧越紧，一列低弦压上来，把老臣那句话托得又沉又重',
 cuts=[
  (3.0,[4,4],'medium','Static Shot',['C08'],[],
   '中景，火光里一名老妇抱着包袱被挤倒在地，几个军士扑上前一把扯走她仅存的一点细软；一名须发花白的老臣在阶下远远看在眼里',
   '固定镜头，火场边几名军士抢走倒地老妇的包袱细软，老妇哭喊；远处一名须发花白的老臣把这一幕尽收眼底',
   '50mm 标准，中浅景深','老臣 + 平视正侧面','三分法','被抢的包袱','锁定老臣绷紧的侧影','stable'),
  (2.5,[5,5],'close','Push In',['C08'],[],
   '特写，须发花白的老臣立在阶下，望着这一幕双拳攥得青筋直跳，喉头滚动，一双老眼里满是屈辱与愤怒',
   '镜头朝这名须发花白的老臣缓缓推近，他望着火场双拳紧攥，青筋暴起，喉头艰难地滚动着',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','火场那幕惨状','锁定老臣泛红的眼眶','stable'),
  (4.0,[6,6],'close','Static Shot',['C08'],[],
   '特写，这名须发花白的老臣再也压不住，颤声开口，字字都像从牙缝里挤出来',
   '固定镜头，这名须发花白的老臣终于忍不住出声，声音颤抖却字字分明，带着压不住的痛心',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','城头的权臣','锁定老臣悲愤的面容','stable',
   'A static close-up holds the grey-bearded old minister as he speaks through a trembling breath, the anguished voice breaking out: <d>[Chinese] 相国，这是要弃这一城百姓于水火啊！</d>'),
  (4.5,[7,7],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣冷冷瞥来，眉头一挑，声音里没有半分波动，把那救助的话头生生掐断',
   '固定镜头，这名凶戾权臣冷冷瞥向老臣，眉头一挑，一句话说得又冷又慢，不带半分商量',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','阶下的老臣','锁定权臣阴沉的神色','stable',
   'A static close-up holds the tyrant as he flicks a cold glance over, and the flat, brutal voice answers without a flicker: <d>[Chinese] 百姓算什么东西？杀了烧了，都给我腾地方。</d>'),
 ])
E7_1C = dict(scene=1,
 overall='The minister steps up but is held back and threatened, while the warrior beside them feigns indifference.',
 music_en='A press of low strings; the horn answers flat and hard.',
 blocking='王允（C08）上前欲拦被老兵拽住；董卓（C09）居高威吓；吕布（C06）抱画戟立在一旁冷眼。',
 soundscape='火势轰鸣，权臣低沉的威压话语与一阵紧弦，老臣不甘的争辩',
 music='底音越拧越紧，一列低弦压上来，那杆号跟着硬邦邦地回应一记',
 cuts=[
  (2.5,[8,8],'medium','Static Shot',['C08'],[],
   '中景，须发花白的老臣上前一步想要拦阻，腰间衣角却被身后一名老兵死死拽住，只得生生站定当场',
   '固定镜头，这名须发花白的老臣欲上前拦阻，身后一名老兵扯住他的衣角，把他定在原地',
   '50mm 标准，中浅景深','老臣 + 平视侧面','三分法','身后的老兵','锁定被扯住定住的老臣','stable'),
  (4.0,[9,9],'close','Static Shot',['C08'],[],
   '特写，被拉住的老臣回头望一眼那老兵，又转向城头的权臣，一字一句地说，声音愈发沉',
   '固定镜头，这名须发花白的老臣沉着声一字一句地开口，话越说越沉，像是把生死都押上了',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','城头权臣','锁定老臣决绝的目光','stable',
   'A static close-up holds the old minister as he turns to the tyrant on the wall and speaks heavily, each word weighed: <d>[Chinese] 夺人产业、绝人后路，天怨人怒啊相国！</d>'),
  (4.0,[10,10],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣眯起眼，声音陡然一沉，当面把那老臣的名字连同样的狠话一同甩出',
   '固定镜头，这名凶戾权臣眯起双眼，声音一沉，一句威胁又冷又重地压向阶下的老臣',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','阶下老臣','锁定权臣眯起的眼','stable',
   'A static close-up holds the tyrant\u2019s narrowing eyes as the voice drops to a cold menace, spat straight at the minister: <d>[Chinese] 王允，你再多嘴，连你一起扔进火里。</d>'),
  (2.5,[11,11],'medium','Static Shot',['C06'],[],
   '中景，一名头戴雉尾紫金冠、持画戟的猛将立在旁侧，冷眼旁观这场争执与漫天火光，并无要拦的样子',
   '固定镜头，这名头戴雉尾紫金冠的猛将抱着画戟立在旁侧，对眼前这一幕看得很淡，半步也没有动',
   '50mm 标准，中浅景深','猛将 + 平视正侧面','三分法','争执的老臣与权臣','锁定猛将无波的眼神','stable'),
 ])
E7_1D = dict(scene=1,
 overall='The minister pleads once more; the warrior answers that an adopted father\u2019s word admits no refusal, and the tyrant turns to laugh as he leaves the wall.',
 music_en='The horn drops to a low pause; a dry wind amid the cracking fire.',
 blocking='王允（C08）向吕布（C06）质问；吕布回话；董卓（C09）回头一望，大笑拂袖下城，王允呆立城头。',
 soundscape='火声依旧，老臣的询问与猛将平淡的回话先后落下，随后权臣一声大笑、袍角拂动',
 music='那号低下去顿住一拍，火与风的干涩声在两句对话之间填满',
 cuts=[
  (4.0,[12,12],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣望向抱着画戟的猛将，声音又急又哑，最后那句话里带着一丝质问',
   '固定镜头，这名须发花白的老臣望向旁立的猛将，声音又急又哑，问得毫不客气',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','抱戟的猛将','锁定老臣逼问的目光','stable',
   'A static close-up holds the old minister as he turns to the warrior and presses him in a hoarse, urgent voice: <d>[Chinese] 奉先，你也眼睁睁看着他们烧杀不成？</d>'),
  (2.5,[13,13],'close','Static Shot',['C06'],[],
   '特写，抱画戟的猛将垂下眼，声音平而冷，一句回话答得干脆，不带一丝波动',
   '固定镜头，这名头戴雉尾紫金冠的猛将垂下眼帘，声音平冷，一句回话答得干脆利落',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','质问的老臣','锁定猛将垂下的眼','stable',
   'A static close-up holds the warrior as he meets the question with a flat, dry answer, his eyes lowered: <d>[Chinese] 义父之命，谁敢不从。</d>'),
  (3.0,[14,14],'medium','Pan Left',['C09','C06'],[],
   '中景，凶戾权臣回头瞥一眼抱戟的猛将，望着火光冲天的城郭放声大笑，一拂袍袖大步走下城头',
   '镜头向左随权臣的身形轻轻摇开，他回头一瞥那猛将，对着漫天火光大笑，拂袖下城',
   '50mm 标准，中浅景深','权臣 + 平视侧面','三分法','火光中的城郭','锁定权臣大笑扬起的袍角','stable'),
  (3.0,[15,15],'close','Push In',['C08'],[],
   '特写，须发花白的老臣呆立当场，望着满城浓烟，眼底一点点沉下去，像是个盘算了很久的人',
   '镜头朝这名须发花白的老臣缓缓推近，他望着满城浓烟目光渐定，眼里的沉怒一点点凝成决断',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','满城浓烟','锁定老臣沉定的眼底','stable'),
 ])
E7_1E = dict(scene=1,
 overall='An order is given to burn the palaces and move the capital; the warrior drives the citizens out onto the road.',
 music_en='A low war pulse; the crack of tramping feet and the drone of displaced crowds.',
 blocking='王允（C08）整衣下城；董卓（C09）下令焚宫迁都；吕布（C06）带兵驱赶百姓上路。',
 soundscape='号令一声，宫阙那侧又腾起火头，随后是无数脚步杂沓、流民拖沓前行的声响',
 music='低沉的战鼓步点，夹杂踩踏的闷响与被驱赶人群的呜咽嗡鸣',
 cuts=[
  (3.0,[16,16],'medium','Truck Left',['C08'],[],
   '中景，老臣缓缓整了整衣冠，转身一步步走下城楼，背影挺直，脚步却比来时更为沉重',
   '镜头随老臣沿廊左移，他整整衣冠转身，一步步走下城楼，每一步都落得又重又稳',
   '50mm 标准，中浅景深','老臣 + 侧后平视跟随','引导线构图','城楼下方的官道','锁定老臣沉稳的背影','stable'),
  (3.0,[17,17],'wide','Pan Right',['C09','C06'],[],
   '全景，凶戾权臣抬手一挥，下令烧了洛阳宫阙，宫墙那侧立刻腾起大片火光，浓烟冲天蔽日',
   '镜头向右摇过城头，权臣抬手下令，远处宫阙随即腾起冲天火光与浓烟，一片烽烟弥漫',
   '35mm 广角，中景深','城头 + 平视远眺','引导线构图','腾火的宫阙','锁定被点燃的宫墙','slight-shake'),
  (3.0,[18,18],'wide','Tracking Shot',['C06','C08'],[],
   '全景，一名持画戟的猛将率兵驱赶百姓上路，官道上老弱一步一踉跄，人流拖成望不见尾的长线',
   '镜头平稳跟随这名持画戟的猛将沿官道前行，两旁老弱百姓被驱赶着一路踉跄，人流绵延不断',
   '35mm 广角，中景深','猛将 + 侧后平视跟随','引导线构图','前方官道上的流民','锁定被驱赶的民众','slight-shake'),
 ])
E7_1F = dict(scene=1,
 overall='The tyrant\u2019s order leaves the slow behind; the old minister rides along the column, tight-lipped.',
 music_en='A dragging, sorrowful line over the shuffling crowd; the horn sounds only once, low.',
 blocking='董卓（C09）马上下令弃弱；王允（C08）策马行在车队旁望着流民一言不发。',
 soundscape='流民拖沓的脚步声与低低的啜泣，权臣的一声令下，随后马嘶与一句压低的劝阻',
 music='一段拖曳悲怆的旋律垫在人群之上，那号只低低响了一记便不再起',
 cuts=[
  (4.5,[19,19],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣骑在马上回头朝人流丢下一句，语气平平，却透着不把人命当回事的凉薄',
   '固定镜头，这名凶戾权臣骑在马上，头也不回地丢下一句话，语气平淡而凉薄',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','身后拖沓的流民','锁定权臣无所谓的侧脸','stable',
   'A static close-up holds the tyrant on horseback as he tosses a flat order back over his shoulder: <d>[Chinese] 走不动的，就地留下，不必费那口气力。</d>'),
  (2.5,[20,20],'medium','Static Shot',['C08'],[],
   '中景，须发花白的老臣策马行在车队旁，望着这满道流民，紧抿着唇，一句话也没有说',
   '固定镜头，这名须发花白的老臣策马行在车队旁，望着满道流民神色凝重，始终一言不发',
   '50mm 标准，中浅景深','老臣 + 平视正侧面','三分法','前头拖沓的流民','锁定老臣紧抿的唇','stable'),
 ])
E7_1G = dict(scene=1,
 overall='The minister questions the purpose of the march and is quietly warned by the warrior to save his breath.',
 music_en='A dragging line over the crowd; the horn sounds only once, low.',
 blocking='王允（C08）在马上质问迁都；吕布（C06）策马近前低劝一句。',
 soundscape='流民拖沓的脚步与低泣，老臣沉声质问，随后猛将压低的劝阻',
 music='拖曳的旋律垫在人群上，两句对话后那点声息被风声盖过',
 cuts=[
  (4.5,[21,21],'close','Static Shot',['C08'],[],
   '特写，老臣终于忍不住在马上开口，声音不高，却字字都落在权臣的迁都令上',
   '固定镜头，这名须发花白的老臣在马上开口，声音不高却字字分明，正落在迁都这道令上',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','前方的权臣','锁定老臣执拗的目光','stable',
   'A static close-up holds the old minister as he speaks his mind at last, low but measured: <d>[Chinese] 相国迁都，为何偏要累及这一城的无辜百姓。</d>'),
  (4.0,[22,22],'close','Static Shot',['C06'],[],
   '特写，持画戟的猛将策马贴近，压低声音劝了一句，语气里带着一丝真心的劝告',
   '固定镜头，这名持画戟的猛将策马贴近老臣，把声音压低，劝的话听起来算是动了三分恻隐',
   '85mm 长焦，浅景深','猛将 + 平视正侧面','三分法','老臣','锁定猛将压下话茬的神情','stable',
   'A static close-up holds the warrior as he rides close and drops his voice in a half-kind warning: <d>[Chinese] 御史大人省些气力罢，别平白送了性命。</d>'),
 ])

# =============== scene 2 : 长安廷议 (beats 1-18) C06/C08/C09 ===============
E7_2A = dict(scene=2,
 overall='Behind the high walls of Chang\u2019an the tyrant rules by fear, his word the only law.',
 music_en='A tense, martial court pulse; a sharp stroke of a low mallet drum at each blow.',
 blocking='董卓（C09）高踞案后下令抄斩；吕布（C06）奉命把人拖出殿外。',
 soundscape='大殿回响着权臣沉沉的语调，间或一声重鼓、一声闷响，群臣屏息的静肃',
 music='紧张的行军式宫调，每下一道狠令便有一记低音鼓槌砸下',
 cuts=[
  (3.0,[1,1],'wide','Push In',['C09'],[],
   '全景，长安宫阙大殿内灯烛通明，一名体躯臃肿的凶戾权臣高踞案后，抬手丢下一签，命人抄斩顶嘴的谏官',
   '镜头朝高踞案后的权臣缓缓推近，他抬手丢下一签，殿上有人应声而动，气氛骤然凝滞',
   '35mm 广角，中景深','权臣 + 仰视主位','中心构图','殿前伏跪的谏官','锁定权臣抬手丢签的动作','stable'),
  (3.0,[2,2],'wide','Static Shot',['C06','C09'],[],
   '全景，一名持画戟的猛将奉命将人拖出殿外，一声闷响，阶前溅起一摊血色，殿上群臣噤若寒蝉',
   '固定镜头，猛将把一名谏官拖出殿门，帘外传来一声闷响，阶前血色渗开，满殿死一般安静',
   '35mm 广角，中景深','殿门 + 平视侧面','中心构图','殿外台阶与帐帘','锁定帘外那摊血色','stable'),
  (4.5,[3,3],'close','Push In',['C09'],[],
   '特写，凶戾权臣缓步踱回案后，扬手高声宣称，一双眼扫过满殿俯首的群臣，睥睨四顾',
   '镜头朝这名凶戾权臣缓缓推近，他扬手宣称，声震大殿，目光碾过殿上每一个俯首的人',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','满殿俯首的群臣','锁定权臣睥睨的目光','stable',
   'A slow push in on the tyrant as he strides back and proclaims in a voice that fills the hall: <d>[Chinese] 大丈夫当称雄封侯！谁挡路，就送谁上路！</d>'),
 ])
E7_2B = dict(scene=2,
 overall='The old minister bows low and murmurs his assent; the tyrant is pleased and turns to weigh the warrior beside him.',
 music_en='A colder pause; a low cello line, then a forced warmth as the tyrant turns to his adopted son.',
 blocking='群臣噤声，王允（C08）在座中低头奉盏、连声应和；董卓（C09）满意点头，转向吕布（C06）拍了拍肩。',
 soundscape='满殿静得发空，老臣一句低低的应和，随后权臣满意的颔首与拍肩声',
 music='冷场一拍，低音提琴拉过一滑，权臣转向猛将时那弦声勉强暖了一瞬又转冷',
 cuts=[
  (3.0,[4,4],'medium','Static Shot',['C08','C09'],[],
   '中景，满殿群臣噤若寒蝉，须发花白的老臣在座中低下头，捧着茶盏的一只手几不可察地颤了颤',
   '固定镜头，一名须发花白的老臣坐在班列中低头奉盏，手不受控制地轻颤，又强自稳住',
   '50mm 标准，中浅景深','老臣 + 平视侧面','三分法','手中的茶盏','锁定老臣轻颤的手','stable'),
  (2.0,[5,5],'close','Static Shot',['C08'],[],
    '特写，这名须发花白的老臣垂首，低低应了一声，声音压得几乎听不见',
   '固定镜头，这名须发花白的老臣低垂着头，把话应得很低很轻，气若游丝',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','主位上的人影','锁定老臣低垂的眼','stable',
   'A static close-up holds the old minister as he lowers his head and murmurs the single thread of assent: <d>[Chinese] 相国英明。</d>'),
  (2.5,[6,6],'medium','Pan Left',['C09','C06'],[],
   '中景，凶戾权臣满意地一点头，转向立在殿侧的猛将，伸手不轻不重地拍了拍他的肩',
   '镜头向左一摇，权臣满意颔首，转身抬手拍了拍旁立猛将的肩，语气因势而温和',
   '50mm 标准，中浅景深','权臣 + 平视侧面','三分法','殿侧站立的猛将','锁定权臣拍肩的手','stable'),
 ])
E7_2C = dict(scene=2,
 overall='Promises of kinship pass between the two, while a cold spark hides beneath the warrior\u2019s lowered lashes.',
 music_en='A cello line slides into a distrustful low; the empty warmth does not hold.',
 blocking='董卓（C09）以翁婿父子相称；吕布（C06）微微颔首，垂下的眼帘里掠过冷意，再开口却恭顺。',
 soundscape='权臣一句称许翁婿父子的笑语，猛将恭顺的回应，声音底下却压着一丝冷',
 music='低音提琴滑进一段藏疑的低区，那点勉强拾起的暖意没撑住就转冷',
 cuts=[
  (4.0,[7,7],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣搂着猛将的肩头，声音带着三分称许七分压人，把翁婿父子四个字咬得很重',
   '固定镜头，这名凶戾权臣搭着猛将的肩，声音又热又压人，把亲近的血缘说得格外用力',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','面前猛将','锁定权臣称许里藏着的威压','stable',
   'A static close-up holds the tyrant as he grips the warrior\u2019s shoulder and speaks with an oily warmth: <d>[Chinese] 贤侄，这天下迟早是我们翁婿父子的。</d>'),
  (3.0,[8,8],'close','Push In',['C06'],[],
   '特写，猛将微微颔首，垂下的眼帘里却掠上一丝不易察觉的冷意，一瞬便收得干干净净',
   '镜头朝这名猛将的脸缓缓推近，他点头应承，眼底一掠而过的寒光随即敛得无影无踪',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','主位的权臣','锁定猛将眼底那丝冷意','stable'),
  (4.0,[9,9],'close','Static Shot',['C06'],[],
   '特写，猛将恭顺地开口回话，声音不高不低，把一句安心的话说得滴水不漏',
   '固定镜头，这名猛将恭顺地开口，一句话答得不卑不亢，把该表的忠说完',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','主位的权臣','锁定猛将恭顺的面容','stable',
   'A static close-up holds the warrior as he answers in courteous, level tones: <d>[Chinese] 义父放心，有我在，无人敢犯长安。</d>'),
 ])
E7_2D = dict(scene=2,
 overall='The tyrant laughs and finds fresh cruelty in trifles, his decree that only his word governs the city ringing through the hall.',
 music_en='The martial pulse swells; a brass sting lands on his declaration.',
 blocking='董卓（C09）大笑起身，又捡起一件小事当众发落得极狠，扬声宣称城中只有他的话算数。',
 soundscape='权臣一声大笑，殿上再起一条狠令，重鼓连响、群臣静得只剩衣袍摩擦',
 music='战鼓脉动加厚，他一宣称时一记铜管刺进来，把满殿压得发闷',
 cuts=[
  (3.0,[10,10],'medium','Tracking Shot',['C09'],[],
   '中景，凶戾权臣大笑起身，原本的笑脸转瞬一沉，拿起一件鸡毛蒜皮的小事，当着满殿的人发落得极狠',
   '镜头平稳跟随权臣起身，他笑着一转便沉下脸，就着一件小事当众发落，语气极恶',
   '50mm 标准，中浅景深','权臣 + 平视正面','引导线构图','满殿伏首的群臣','锁定权臣喜怒骤变的脸色','stable'),
  (5.0,[11,11],'close','Push In',['C09'],[],
   '特写，凶戾权臣顿步，扬声宣告，一字一句把满殿的目光都钉在自己身上',
   '镜头朝这名凶戾权臣推近，他顿住脚步扬声宣示，话里全是碾过殿上所有人的蛮横',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','满殿群臣','锁定权臣睥睨四方的神色','stable',
   'A slow push in on the tyrant as he halts and declares it to the whole hushed hall, unrivaled and absolute: <d>[Chinese] 都给我记着，这长安城中，只有我的话才算数！</d>'),
 ])
E7_2E = dict(scene=2,
 overall='New towers rise at his bidding while a grey minister reads the danger beneath the heights.',
 music_en='A grim building pulse over distant hammering; a low horn, then a whispered cello.',
 blocking='董卓（C09）命人广起高台新殿，役夫昼夜不绝。',
 soundscape='工地上役夫昼夜不绝的凿击声，权臣炫耀的语调',
 music='低沉的筑城脉动垫着远处锤凿，一杆低号过后滑入低音的提琴低语',
 cuts=[
  (3.0,[12,12],'wide','Pan Right',['C09'],[],
   '全景，长安城外新辟的工地上高台基座拔地而起，役夫密密麻麻昼夜劳作，累倒者被拖走',
   '镜头向右摇过工地，高台基座拔地而起、规模骇人，密密麻麻的役夫轮转不休，有累毙者当即被拖走',
   '35mm 广角，中景深','工地 + 平视远眺','引导线构图','拔地而起的高台','锁定不断累倒的役夫','slight-shake'),
  (4.5,[13,13],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣骑在马上指着工地说，眉眼里全是得意的野心，把那座新城当作自己的凭仗',
   '固定镜头，这名凶戾权臣捻须指点工地，语气里掩不住的得意与野心，把那新城看得极重',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','拔地的高台','锁定权臣得意的神色','stable',
   'A static close-up holds the tyrant as he surveys the rising works and declares with naked ambition: <d>[Chinese] 这长安，要建得比洛阳更气派，方配我董卓。</d>'),
 ])
E7_2F = dict(scene=2,
 overall='Amid the adulation a lone minister reads the writing on the wall, and is nudged back into silence by a wary aide.',
 music_en='A thin, uneasy tremolo; the cello drops and is swallowed by footfalls.',
 blocking='王允（C08）立在百官之列望向台基，低声感慨；身后随从忙低声唤住，他敛了神色随人流退去。',
 soundscape='人群中老臣一句极低的感慨，随从压着声音的提醒，随后一片宫靴退回府的脚步声',
 music='一段细薄不安的颤音，低音提琴落下去，被回府密集的脚步声吞没',
 cuts=[
  (3.0,[14,14],'close','Push In',['C08'],[],
   '特写，须发花白的老臣立在百官之列，望着拔地而起的台基，悄悄攥紧了藏在袖中的拳',
   '镜头朝这名须发花白的老臣推近，他望着那高台攥紧袖中的拳，眼底深不见底',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','拔地的高台','锁定老臣攥紧的指节','stable'),
  (3.0,[15,15],'close','Static Shot',['C08'],[],
   '特写，老臣微微侧脸，压低了嗓子把那句话说出来，声音轻得像怕被风带去告密',
   '固定镜头，这名须发花白的老臣侧脸低语，把一句慨叹说得极轻极险',
   '85mm 长焦，浅景深','老臣 + 平视正面','三分法','脚下的台基','锁定老臣低语时的神情','stable',
   'A static close-up holds the old minister as he turns and murmurs, half to himself, wary of being heard: <d>[Chinese] 高台起得越高，摔得就越重。</d>'),
  (2.5,[16,16],'medium','Static Shot',['C08'],[],
   '中景，老臣话音刚落，身后一名随从忙追上低声劝了两句，他恍然回神，敛了神色退回官署之后的府中',
   '固定镜头，老臣话落，身后随从赶上来低声拦劝，他回神整了整神色，随人流退回府邸',
   '50mm 标准，中浅景深','老臣 + 平视侧面','三分法','身后的随从','锁定老臣敛起的神色','stable'),
 ])
E7_2G = dict(scene=2,
 overall='Court is dismissed; alone along the corridor the minister makes straight for his study, a resolve settling on his shoulders.',
 music_en='A spare, searching line; a door closes with a soft thud and the room goes quiet.',
 blocking='散朝后，王允（C08）独自沿长廊而去，脚步不停，直入自己的书室。',
 soundscape='散朝的纷沓脚步声渐渐散尽，长廊上只剩老臣一个人的脚步声，随后一门轻合归寂',
 music='一段疏落而探询的旋律，门轻轻合上一声响，余下全静',
 cuts=[
  (2.5,[17,17],'wide','Tracking Shot',['C08'],[],
   '全景，散朝后百官引出殿门，须发花白的老臣独自落在其后，沿画廊一步步走去，脚步始终不停',
   '镜头平稳跟随这名须发花白的老臣沿走廊前行，人群在他身后散尽，只他一人走个不停',
   '35mm 广角，中景深','老臣 + 侧后平视跟随','引导线构图','长廊尽头的书室','锁定老臣独自的背影','stable'),
  (2.5,[18,18],'medium','Push In',['C08'],[],
   '中景，老臣走到书室门前，回头望一眼空荡的长廊，返身推门迈了进去',
   '镜头朝书室门口缓缓推近，老臣回望一眼长廊，随即推门入内，背影消失在门里',
   '50mm 标准，中浅景深','老臣 + 平视侧面','中心构图','长廊尽头','锁定老臣推门的动作','stable'),
 ])

# =============== scene 3 : 书室受命 (beats 1-18) C07/C08 ===============
E7_3A = dict(scene=3,
 overall='In a shuttered study an old minister unburdens himself; his foster daughter lights his last lamp and sees his grief.',
 music_en='A quiet, warm lute picks up; the wood of the study hums under a held low note.',
 blocking='王允（C08）屏退侍从，返身闩门；养女貂蝉（C07）捧灯而入，见其愁容上前搀扶。',
 soundscape='门闩落下的轻响，一盏烛火被捧进房里的动静，老臣长长呼出的那口气',
 music='一把温厚的琵琶轻轻拨起，书室木质的暖意在托着的低音里嗡鸣',
 cuts=[
  (3.0,[1,1],'medium','Push In',['C08'],[],
   '中景，锁好门的书室里，须发花白的老臣屏退侍从，返身把门闩落下，长长吐出一口气',
   '镜头朝这名须发花白的老臣缓缓推近，他屏退侍从、返身落闩，卸下满身戒务般长出一口气',
   '50mm 标准，中浅景深','老臣 + 平视侧面','中心构图','合拢的门','锁定老臣落闩后松下的肩','stable'),
  (3.0,[2,2],'medium','Tracking Shot',['C07','C08'],[],
   '中景，一名华服的年轻女子捧着一盏灯从门边进来，见老臣眉宇深锁，忙搁下灯上前搀扶',
   '镜头平稳跟随这名华服年轻女子进门，她见老臣满面愁容，立刻搁灯、上前扶住他的手臂',
   '50mm 标准，中浅景深','二人 + 平视侧面','三分法','老臣的面容','锁定女子关切的目光','stable'),
 ])
E7_3B = dict(scene=3,
 overall='Filial care meets the weight of state: the girl reads the trouble in his face, and the minister speaks of a realm betrayed.',
 music_en='The lute thins to a questioning line; a slower, graver phrase settles.',
 blocking='貂蝉（C07）搀扶王允（C08）至案边；王允一开口便道出董卓祸乱神器之事，面容沉重。',
 soundscape='年轻女子温声相询，老臣一声长叹，烛火在案上微微晃动，字字带着痛心',
 music='琵琶弦转细而探询，随后落成一句更慢更深沉的乐句',
 cuts=[
  (4.0,[3,3],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子捧着老臣的手臂，眉间带着担忧，温声开口相询',
   '固定镜头，这名华服的年轻女子捧着老臣的手，眉宇间满是担忧，温声问起他的心事',
   '85mm 长焦，浅景深','女子 + 平视正面','三分法','老臣的面容','锁定女子担忧的眉眼','stable',
   'A static close-up holds the young woman in ornate robes as she takes her foster father\u2019s arm and asks in a soft, caring voice: <d>[Chinese] 义父这般愁容，可是朝中又起了风波？</d>'),
  (5.0,[4,4],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣望着烛火沉默一瞬，才沉声开口，把那些压在心头的话一句句说开',
   '固定镜头，这名须发花白的老臣望着烛火沉默片刻，才沉声把心事和盘托出，语气痛而重',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','案上的烛火','锁定老臣沉痛的面容','stable',
   'A static close-up holds the old minister as he fixes his eyes on the flame and speaks the grave truth: <d>[Chinese] 董卓暴虐，我身为汉臣，岂能坐视他祸乱神器。</d>'),
 ])
E7_3C = dict(scene=3,
 overall='He kneels before her and weeps; the girl kneels too, alarmed and moved, and the weight of Heaven is laid upon her.',
 music_en='The lute trembles and stills; a deep, grave bow note holds the room.',
 blocking='王允（C08）忽地撩袍在貂蝉（C07）面前跪倒，老泪纵横；貂蝉慌忙跟着跪下膝行上前搀扶。',
 soundscape='袍角扑地一声，老臣压抑的老泪，女子惊呼着跪下，烛火都被带得晃了一晃',
 music='琵琶一颤后静下，一记极低沉的大提琴音把满室压得发闷',
 cuts=[
  (3.0,[5,5],'medium','Static Shot',['C08','C07'],[],
   '中景，须发花白的老臣忽然撩袍，在年轻女子面前直挺挺跪了下去，老泪纵横，身子微微发抖',
   '固定镜头，这名须发花白的老臣突然撩袍跪地，对着年轻女子老泪纵横，苍老的身形微微发颤',
   '50mm 标准，中浅景深','二人 + 平视侧面','中心构图','跪地的老臣','锁定老臣纵横的老泪','stable'),
  (3.0,[6,6],'medium','Static Shot',['C07','C08'],[],
   '中景，华服的年轻女子慌忙跟着跪下，膝行上前伸出双手要去扶起义父，一脸惊惶',
   '固定镜头，这名华服的年轻女子慌忙跪行上前，伸手去扶跪倒的老臣，神情惊惶而不忍',
   '50mm 标准，中浅景深','女子 + 平视侧面','三分法','跪地的老臣','锁定女子慌乱伸出的手','stable'),
 ])
E7_3D = dict(scene=3,
 overall='The daughter pleads, and the minister weighs the fate of the Han on her shoulders; her eyes go still.',
 music_en='The low note resolves into a lucid, heavy line; a soft bell rings once.',
 blocking='貂蝉（C07）跪地惊问；王允（C08）沉声道明汉室存亡系于她一身；貂蝉神色一凛抬眼回话。',
 soundscape='老臣忽然跪下的声响，女子惊惶的惊呼，随后一句沉沉的托付落在满室烛光里',
 music='那低沉音解作一句清亮而沉重的主线，一声轻钟鸣过',
 cuts=[
  (3.5,[7,7],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子跪在跟前，眼角挂着泪，声音又急又颤，一句折煞说得真切',
   '固定镜头，这名华服的年轻女子跪在跟前，声音又急又颤，把一句惶恐的心事说出口',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','对面的老臣','锁定女子含泪的双眼','stable',
   'A static close-up holds the young woman as she kneels, voice breaking with alarm and filial distress: <d>[Chinese] 义父这是做什么！折煞女儿了！</d>'),
  (4.0,[8,8],'close','Push In',['C08'],[],
   '特写，须发花白的老臣直起身，望着面前的年轻女子一字一字地说，把整个汉室的存亡都托在她身上',
   '镜头朝老臣的面容推近，他一字一字把话说定，声如磐石，把一件天地般的重托交到女子手里',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','跪着的女子','锁定老臣托付的注视','stable',
   'A slow push in on the old minister as he speaks with iron resolve, entrusting the fate of a dynasty: <d>[Chinese] 貂蝉，汉室存亡，系于你一人之身了。</d>'),
  (3.0,[9,9],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子神色一凛，抬起眼，眼底蒙着的一层水汽很快沉沉定住，像换了个人',
   '固定镜头，这名华服的年轻女子先是一怔，随即抬眼，慌乱的目光寸寸沉定为决绝',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','老臣','锁定女子渐定下来的目光','stable'),
 ])
E7_3E = dict(scene=3,
 overall='She pledges herself, body and will, to the task; he names the pair of tigers only she can sunder.',
 music_en='A firm, rising lute ripple; a single held note hangs where she swears.',
 blocking='貂蝉（C07）抬眼回话，愿赴汤蹈火在所不辞；王允（C08）沉声点明唯她能拆开董卓父子这对虎狼。',
 soundscape='女子一句斩钉截铁的应承，随后老臣低而郑重地点出那对虎狼的名',
 music='琵琶一记上扬的涟漪，女子立誓的当口一音悬在空处',
 cuts=[
  (4.5,[10,10],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子抬起下巴，目光清亮，一句应承说得斩钉截铁，没有半分迟疑',
   '固定镜头，这名华服的年轻女子抬眼回话，目光清亮而坚决，把一句赴死的话说得利落',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','对面的老臣','锁定女子决然的双眼','stable',
   'A static close-up holds the young woman as she lifts her chin and answers without a moment\u2019s doubt: <d>[Chinese] 义父要我做什么，貂蝉赴汤蹈火在所不辞。</d>'),
  (4.5,[11,11],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣目光落在她脸上，声音压得更低，把那句最要紧的话挑明',
   '固定镜头，这名须发花白的老臣压低声音，把那句最关键的话一字一字说透',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','年轻的女子','锁定老臣凝重的目光','stable',
   'A static close-up holds the old minister as he lowers his voice and lays the crux of the scheme bare: <d>[Chinese] 董卓父子贪图女色，唯你能拆开这对虎狼。</d>'),
  (3.0,[12,12],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子听完这话垂首沉吟半晌，指尖在袖口轻轻捻着，烛光在她脸上明明灭灭',
   '固定镜头，这名华服的年轻女子垂首沉吟，指尖捻着袖口，烛火的光影在她脸上轻轻晃着',
   '85mm 长焦，浅景深','女子 + 平视正侧面','三分法','案上烛火','锁定女子沉思的侧影','stable'),
 ])
E7_3F = dict(scene=3,
 overall='The pact is sealed with a jade token: the girl steps off the edge of her old life.',
 music_en='A gentle, fateful melody; a soft chime as the jade settles into place.',
 blocking='貂蝉（C07）开口言明自身已无退路；王允（C08）颤手取出一块温玉，郑重系到女子颈间。',
 soundscape='女子一句没有退路的低语，衣料摩擦声，老人颤手取玉、系颈时玉扣的一声轻响',
 music='一段柔和而宿命般的旋律，玉入颈间时一声轻铃落定',
 cuts=[
  (4.0,[13,13],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子抬眼，目光定定地落在老臣脸上，一句没有退路说得又轻又硬',
   '固定镜头，这名华服的年轻女子抬眸，把一句決绝的话说得又轻又硬，眼底已无半分犹豫',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','老臣','锁定女子已定的眼神','stable',
   'A static close-up holds the young woman as she meets his eyes and declares with quiet finality: <d>[Chinese] 女儿此去，义父可还认我回这书室的门？</d>'),
  (4.0,[14,14],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣颤着手从怀中取出一块温玉，郑重地捧起，声音里带着一丝苍凉',
   '固定镜头，这名须发花白的老臣颤手掏出温玉，郑重捧起，把它看得比命还重',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','掌心的温玉','锁定老臣托玉的手','stable',
   'A static close-up holds the old minister as he brings out a warm jade and cradles it, the solemn voice promising: <d>[Chinese] 只要汉室得救，义父这条命都可以不要。</d>'),
 ])
E7_3G = dict(scene=3,
 overall='A keepsake binds them, a promise of return for the one who steps into the tigers\u2019 den; the girl bows to her fate.',
 music_en='The fateful melody swells and falls; a low, tender note as the jade is tied.',
 blocking='王允（C08）将温玉系到貂蝉（C07）颈间，应允他日功成亲迎；貂蝉垂首受命。',
 soundscape='玉系上颈间的一声轻响，老人一句低沉的许诺，随后年轻女子垂首受命、呼吸沉落',
 music='宿命的旋律扬起又落下，系玉时一记低柔的音收住',
 cuts=[
  (2.5,[15,15],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子垂着眼帘，声音很轻，把一句已无退路的话说给自己听',
   '固定镜头，这名华服的年轻女子垂眸低声，把这句话说得像是定下了自己的命',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','颈上的玉','锁定女子低垂的眼','stable',
   'A static close-up holds the young woman as she murmurs to herself, sealing her own fate: <d>[Chinese] 那貂蝉便没有退路了。</d>'),
  (4.0,[16,16],'close','Static Shot',['C08','C07'],[],
   '特写，须发花白的老臣颤着手，把那块温玉郑重系到年轻女子颈间，指尖拂过她的鬓发',
   '固定镜头，这名须发花白的老臣颤着手指，将温玉轻轻系到年轻女子颈间，一举一动都透着珍重',
   '85mm 长焦，浅景深','二人 + 平视正面','中心构图','系玉的指尖','锁定系在颈间的温玉','stable'),
  (4.0,[17,17],'close','Static Shot',['C08'],[],
   '特写，老臣系好温玉，望着眼前的女子，声音低而郑重，应下那桩他日相迎的诺',
   '固定镜头，这名须发花白的老臣系好玉，望着女子低声许诺，眼里带着苍凉与希冀',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','颈上的温玉','锁定老臣郑重的神色','stable',
   'A static close-up holds the old minister as he finishes tying the jade and promises in a low, grave voice: <d>[Chinese] 留个念想。他日功成，义父亲自来迎你。</d>'),
  (3.0,[18,18],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子垂首受命，暗影里那双眼睛却亮得像刀，一眼便压下了所有怯意',
   '固定镜头，这名华服的年轻女子垂首应命抬眸，暗影里那双眼光亮锋利，如出鞘的刀',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','暗处的烛影','锁定女子发亮锋利的眼','stable'),
 ])

EP7_SC1 = [E7_1A, E7_1B, E7_1C, E7_1D, E7_1E, E7_1F, E7_1G]
EP7_SC2 = [E7_2A, E7_2B, E7_2C, E7_2D, E7_2E, E7_2F, E7_2G]
EP7_SC3 = [E7_3A, E7_3B, E7_3C, E7_3D, E7_3E, E7_3F, E7_3G]
for seg in EP7_SC1: seg['sceneIndex'] = 1
for seg in EP7_SC2: seg['sceneIndex'] = 2
for seg in EP7_SC3: seg['sceneIndex'] = 3
EP7 = EP7_SC1 + EP7_SC2 + EP7_SC3