# -*- coding: utf-8 -*-
"""EP6 segments. Tuples:
(seconds, beats, size, camera, chars, props, frame, shot, lens, camPos, comp, eye, focus, stab, en)
en = H3 passage for this cut (English body, <d>[Chinese] 原文</d> for lines)."""

# ---------------- scene 1 : 虎牢关对垒 (beats 1-31) ----------------
EP6_SC1 = [
 dict(scene=1, overall='A dry wind over an open plain, distant war-drums and a lone horn ring out as hooves thunder and a halberd whips the air.',
  music_en='Low war-drums in a grim 4/4 with one long horn held over each cut of the charge.',
  blocking='吕布（紫金冠猛将，C06）居中偏右纵马直冲联军阵前，尘土从马蹄下翻起；联军众将（C01/C02/C03）沿画面左侧一线观阵，相距约二十步。',
  soundscape='旷野上一阵干燥的风，远处战鼓与一杆号角长鸣，马蹄声如闷雷翻涌，画戟破空带出一声锐响',
  music='低沉战鼓按四四拍推进，一杆野号在每个切点拉长拖过',
  cuts=[
   (3,[1,1],'wide','Tracking Shot',['C06'],['P03'],
    '全景，虎牢关前尘土蔽日的旷野，一名头戴雉尾紫金冠的猛将纵赤兔马、横方天画戟直冲联军阵前，关城与营旗隐在烟尘里',
    '镜头从侧后平稳跟拍这名单手横画戟的紫金冠猛将，他纵马直冲阵前，马蹄掀起大团尘土，画戟在身侧拖出一道弧光',
    '35mm 广角，中景深','猛将 + 侧后平视跟随','中心构图','前方联军阵前','锁定纵马的猛将与画戟','slight-shake',
    'A low tracking shot follows the crowned warrior of <Picture 1> as he charges abreast, hooves throwing up dust and the crescent halberd trailing a gleam of light.'),
   (2,[2,2],'wide','Arc Shot',['C06'],['P03'],
    '全景，这名猛将纵马斜掠，单手用画戟削落城门前一杆大纛，又一记横扫扫飞数名守关军士，尘土四溅、旗帜翻倒',
    '镜头呈半圈环绕这名纵马的猛将，他斜掠过关前，画戟先削断门旗、又向一侧横扫，几名守关军士应声翻倒',
    '35mm 广角，中景深','猛将 + 侧前平视环绕','对角线构图','翻倒的旗与兵','锁定横扫的画戟','slight-shake',
    'An arc shot circles the warrior of <Picture 2>: one sweep of the halberd cuts the gate banner, a second sweep sends the guards tumbling.'),
   (4,[3,3],'close','Static Shot',['C06'],['P03'],
    '特写，尘土中这名猛将勒马横戟，雉尾紫金冠下浓眉大眼目光如电，嘴角挂着一丝傲慢，画戟横在身前，正在开口叫阵',
    '固定镜头，这名单手横画戟的猛将勒住战马，浓眉下目光如电，声音沉而倨傲地朝联军阵前叫阵',
    '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','联军阵前','锁定猛将面部','stable',
    'A static shot holds the close framing of <Picture 3>: the crowned warrior reins in, draws the halberd across his chest, and the arrogant voice growls: <d>[Chinese] 就凭你们，也配拦我吕布的去路！</d>'),
   (3,[4,4],'wide','Pan Right',['C01','C02','C03'],['P05'],
    '全景，联军阵前众将相顾失色，一名绿袍长髯、一名黑甲环眼、一名白衣的将领先后勒马后缩，无人敢上前迎战',
    '镜头从左向右缓摇扫过联军阵前，几名联军将领面面相觑，各自勒马朝后退缩，无一人敢出阵',
    '35mm 广角，中景深','联军众将 + 平视侧面','引导线构图','阵前的猛将','锁定众将后退的身影','stable',
    'A slow pan right sweeps the coalition line in <Picture 4>: the generals glance at one another, rein back and shrink away, none daring to step out.'),
  ]),
 dict(scene=1, overall='A battle cry rips through the dust; a brittle clash of spear and halberd rings out, hooves shift and armor scrapes.',
  music_en='The same grim drums with rising tension, a short percussive strike on each steel clash.',
  blocking='张飞（黑甲猛汉，C03）在画面左侧、吕布（C06）在画面右侧，两骑相隔约十步纵马对峙；联军众将沿画面深处一字观望。',
  soundscape='尘土里炸开一声暴喝，长矛与画戟当空一撞脆响拔得很高，随后是马蹄错动和甲叶摩擦的声响',
  music='战鼓持续低沉推进，每道兵刃交锋时一段短促打击乐砸下',
  cuts=[
   (3,[5,5],'close','Static Shot',['C03'],[],
    '特写，尘烟中一名豹头环眼的黑甲猛汉瞪圆双眼朝阵前暴喝一声，胡须根根竖起，丈八蛇矛斜指前方',
    '固定镜头，这名黑甲猛汉瞪圆双眼朝阵前暴喝一声，胡须根根竖起，天不怕地不怕地叫阵',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','阵前的猛将','锁定猛汉暴喝的面容','stable',
    'A static shot holds the close-up of <Picture 3>: the black-armoured warrior with bristling beard and round glaring eyes bellows toward the field, and the thundering, hot-tempered one shouts: <d>[Chinese] 列位闪开，俺来会会他！</d>'),
   (2,[6,6],'wide','Tracking Shot',['C03'],[],
    '全景，这名黑甲猛汉一骑当先，纵马提矛直取阵前，口中连声暴喝震得尘土乱飞，身后营旗猎猎',
    '镜头平稳跟随一名黑甲猛汉纵马当先冲出，长矛直指前方，口中连声暴喝，尘土被声浪震得乱飞',
    '35mm 广角，中景深','黑甲猛汉 + 侧后平视跟随','对角线构图','前方猛将','锁定冲阵的猛汉与长矛','slight-shake',
    'A tracking shot follows the black-armoured warrior of <Picture 5> as he charges out ahead, spear leveled, bellowing till the dust scatters.'),
   (3,[7,7],'medium','Static Shot',['C03','C06'],['P03'],
    '中景，两马相交处一根长矛与一杆画戟当空相撞，金铁震响、火星迸出，尘土翻卷，战马都被震得一顿',
    '固定镜头，两匹战马交错，一根长矛与一杆画戟当空悍然相撞，金铁交鸣、火星迸射',
    '50mm 标准，中浅景深','双骑 + 平视侧面','中心构图','兵刃相撞处','锁定交错的两件兵器','slight-shake',
    'A static shot catches <Picture 7>: the spear and halberd collide midair with a crack and sparks, both war-horses jolting.'),
   (3,[8,8],'medium','Pull Out',['C03'],[],
    '中景，黑甲猛汉咬牙硬挡虎口发麻，座下战马被震得连退数步，身子在马鞍上后仰',
    '镜头缓缓拉开，黑甲猛汉咬牙硬扛住这一击，虎口发麻，整匹战马被震得连退数步，身子一晃',
    '50mm 标准，中浅景深','黑甲猛汉 + 平视侧面','三分法','对方画戟','锁定被震退的猛汉','slight-shake',
    'A slow pull out from <Picture 8>: the black-armoured warrior grits his teeth under the blow, a numb grip forcing his war-horse to stagger back several paces.'),
  ]),
 dict(scene=1, overall='Dust settles for a heartbeat, then fresh hooves churn the earth; a sore grunt and the rasp of a spear being reset.',
  music_en='Drums soften for a lull and swell again, a single deep horn when the second contender issues his taunt.',
  blocking='吕布（C06）在画面右侧横戟立马，张飞（C03）在左侧被震退后重新稳住战马，两骑相距约八步，四目相对。',
  soundscape='尘土短暂落定，随即马蹄又重重踏地，一声压低的闷哼和长矛重新握稳的摩擦声相继传来',
  music='战鼓低沉地顿一拍作停顿，随即重新抬起，挑战者出声时一声极低号角压上来',
  cuts=[
   (4,[9,9],'close','Static Shot',['C06'],['P03'],
    '特写，这名猛将稳坐马上，居高临下地瞥向对面的黑甲猛汉，浓眉下一双电目，嘴角微扬带着玩味与不屑',
    '固定镜头，这名单手横画戟的猛将稳坐马上，居高临下地瞥向对面的黑甲猛汉，声音带着几分玩味与不屑',
    '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','对面的猛汉','锁定猛将玩味的眉眼','stable',
    'A static shot holds the close framing of <Picture 9>: the lofty warrior glances over, and the drawling, cocky voice says: <d>[Chinese] 劲倒是有一把，可惜还差得远。</d>'),
   (4,[10,10],'close','Static Shot',['C03'],[],
    '特写，黑甲猛汉虎目圆睁，隔着马首梗着脖子回敬，胡须抖个不住，手中长矛又握紧了几分',
    '固定镜头，这名黑甲猛汉梗着脖子隔着马首回敬一句，虎目圆睁，胡须抖动，手里的矛又攥紧了些',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','对面的猛将','锁定猛汉发狠的面容','stable',
    'A static shot holds the close-up of <Picture 10>: the black-armoured warrior bristles, gripping his spear tighter, and the hot-tempered one fires back: <d>[Chinese] 再来！俺倒要看看你还有几斤几两！</d>'),
   (3,[11,11],'medium','Truck Left',['C03'],[],
    '中景，黑甲猛汉拍马复又冲上，长矛连刺数下，铛铛数声都被对面的画戟一一架开，尘土四腾',
    '镜头随黑甲猛汉的冲势向左平移跟进，他连刺数矛，都被对方一一拨开，两马错而复返',
    '50mm 标准，中浅景深','黑甲猛汉 + 平视侧面跟随','引导线构图','对方的画戟','锁定连刺的长矛','slight-shake',
    'A truck left follows the black-armoured warrior of <Picture 11> pressing forward, spear thrusting again and again, each jab parried by the halberd.'),
  ]),
 dict(scene=1, overall='A second horse arrives at full gallop; three blades and two spears clash in a tight storm of iron and dust.',
  music_en='Drums thicken into a heavier pulse under the joined fight, cymbals marking each new strike.',
  blocking='关羽（绿袍长髯猛将，C02）催马自画面右侧切入战团，与张飞（C03）分居吕布（C06）两侧，三骑在尘里盘旋。',
  soundscape='又一阵疾蹄由右侧逼近，大刀劈风与画戟格挡交鸣，铁器密集碰撞声连成一片',
  music='战鼓转为更沉的脉搏，双刀合围后每击一声短促铜钹砸下',
  cuts=[
   (3,[12,12],'wide','Arc Shot',['C02'],['P05'],
    '全景，一名绿袍长髯的将领目光一厉，催马抡起青龙偃月刀自右侧加入战团，一刀劈向阵前猛将，刀光如练',
    '镜头呈半圈环绕一名绿袍长髯的将领，他目光一厉、催马而起，抡长柄大刀自侧面加入战团，当头一刀劈下',
    '35mm 广角，中景深','猛将 + 侧前平视环绕','对角线构图','阵前猛将','锁定劈落的大刀','slight-shake',
    'An arc shot frames <Picture 12>: the long-bearded general in green spurs forward with a sweep of the long-handled blade, cutting in from the side.'),
   (3,[13,13],'medium','Static Shot',['C02','C03','C06'],['P05','P03'],
    '中景，三骑在尘埃里挤作一团，画戟一分堪堪架住左右袭来的刀与矛，双方兵刃绞在一处',
    '固定镜头，一名猛将横戟一分，同时架住左右两路袭来的刀与矛，三件兵器当空绞作一处，火星迸射',
    '50mm 标准，中浅景深','三骑 + 平视侧面','中心构图','兵刃交错处','锁定拼架的三件兵器','slight-shake',
    'A static shot catches <Picture 13>: the halberd splits to parry the blade and the spear at once, all three weapons grinding together.'),
   (3,[14,14],'close','Static Shot',['C06'],['P03'],
    '特写，这名猛将把画戟一挽横在身前，嘴角勾着一丝激赏又满是战意，目光扫过面前两骑，朗声大笑',
    '固定镜头，这名单手横画戟的猛将把画戟一挽，目光扫过面前两骑，声音里带着激赏与不惧',
    '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','面前两骑','锁定猛将战意勃发的眉眼','stable',
    'A static shot holds the close framing of <Picture 14>: the warrior swings his halberd and the bold voice declares: <d>[Chinese] 有点意思！再来几个也不怕！</d>'),
   (3,[15,15],'wide','Shake Slightly',['C02','C03','C06'],['P05','P03'],
    '全景，三匹战马在尘埃里盘旋冲杀，刀光矛影与画戟上下翻飞，喝声与兵刃交鸣搅作一片尘土',
    '镜头轻微晃动，三匹战马在尘土里盘旋冲杀，刀、矛、画戟上下翻飞，喝声与铁甲交鸣一片',
    '35mm 广角，中景深','三骑 + 平视侧面','引导线构图','交战的刀光','锁定盘旋冲杀的三骑','handheld',
    'A shaken tracking view of <Picture 15>: three war-horses wheel and clash, blades and halberd flashing in the swirling dust.'),
  ]),
 dict(scene=1, overall='Quick shouted commands between brothers, then the white-robed lord spurs in with twin swords joining the storm.',
  music_en='A slight pause in the drums, then the pace quickens as a third horse joins the melee.',
  blocking='刘备（白衣主公，C01）在远处阵中抽出双股剑催马冲入，与张飞、关羽并作犄角，把吕布（C06）围在当中。',
  soundscape='兄弟间的短促口令你来我往，马蹄密集，随后又一匹战马长嘶冲入，铁器交鸣更急',
  music='战鼓稍顿，随即提速，第三骑并进来时节奏陡然加紧',
  cuts=[
   (3,[16,16],'close','Static Shot',['C03'],[],
    '特写，黑甲猛汉一边挥矛一边侧头朝身后喊话，声音急促，眼角仍盯着面前的画戟',
    '固定镜头，这名单手持矛的黑甲猛汉一边挥矛一边侧头朝身后急促喊话，眼仍不离前方',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正侧面','三分法','身后的大哥','锁定猛汉喊话的侧脸','stable',
    'A static shot holds the close-up of <Picture 16>: the black-armoured warrior shouts over his shoulder while parrying, the urgent voice calling: <d>[Chinese] 二哥，你堵他右路！</d>'),
   (3,[17,17],'close','Static Shot',['C02'],['P05'],
    '特写，绿袍长髯的将领神色威严，一面抡刀护着侧翼一面沉声提醒，长髯被尘土吹得微微飘动',
    '固定镜头，这名绿袍长髯的将领神色威严，一面抡刀护住侧翼一面沉声开口提醒',
    '85mm 长焦，浅景深','将领 + 平视正面','中心构图','交战的画戟','锁定将领沉凝的面容','stable',
    'A static shot holds the close framing of <Picture 17>: the long-bearded general guards the flank, and the steady voice warns: <d>[Chinese] 三弟当心，此戟霸道！</d>'),
   (3,[18,18],'wide','Tracking Shot',['C01'],[],
    '全景，阵中一名白衣将领看得焦急，一把抽出双股剑，驱马冲入战圈，衣袂翻飞带起尘土',
    '镜头平稳跟随一名白衣将领纵马冲入战圈，他双手各持一剑，衣袂在尘里翻飞，直朝那猛将逼近',
    '35mm 广角，中景深','白衣将领 + 侧后平视跟随','引导线构图','前方战圈','锁定冲入的双剑将领','slight-shake',
    'A tracking shot follows the white-robed lord of <Picture 18> spurring into the fight, a blade in each hand, robes streaming in the dust.'),
   (3,[19,19],'close','Static Shot',['C01'],[],
    '特写，白衣将领持双剑冲到近前，朝两位兄弟朗声开口，眉宇焦急又不失沉稳',
    '固定镜头，这名白衣将领双手持剑冲到近前，朗声朝并肩作战的两人开口，眉宇焦急而沉稳',
    '85mm 长焦，浅景深','白衣将领 + 平视正面','中心构图','两位兄弟','锁定将领的面容','stable',
    'A static shot holds the close framing of <Picture 19>: the white-robed lord levels his blades and calls out: <d>[Chinese] 二位贤弟，愚兄来助你们！</d>'),
  ]),
 dict(scene=1, overall='Three blades and a spear press together into one unbroken assault around the halberd; iron rings and dust billows.',
  music_en='The drums roll in a steady, driving march under the three-on-one encirclement.',
  blocking='刘、关、张呈犄角围住吕布（C06）缠斗，三件兵器如同出自同一双手，把猛将困在正中。',
  soundscape='三兄弟刀剑矛锋与画戟连环交撞，铁器鸣响连绵不绝，马蹄在尘土里不断踩踏',
  music='战鼓以齐齐的队列节奏滚动，三面合围时节奏稳定而有力',
  cuts=[
   (3,[20,20],'medium','Arc Shot',['C02','C03','C06'],['P05','P03'],
    '中景，三人呈犄角之势，剑光刀影矛锋齐齐罩住中间的猛将，缠斗不休，四骑在尘里转成一团',
    '镜头呈半圈环绕，三名联军武将各持白刃围住横戟的猛将缠斗，四骑在尘埃里转成一团',
    '50mm 标准，中浅景深','四骑 + 侧前平视环绕','中心构图','中心的猛将','锁定节点处交错的兵器','slight-shake',
    'An arc shot frames <Picture 20>: three coalition blades close in on the halberd-wielding warrior, the four horses wheeling as one.'),
   (3,[21,21],'medium','Static Shot',['C02','C03','C06'],['P05','P03'],
    '中景，猛将再勇也被这三面死死缠住，画戟几次想脱身，都被刀矛封了回去，无从走脱',
    '固定镜头，中间的猛将几番想荡开画戟脱身，都被两旁的刀矛封住回路，困在当中进退两难',
    '50mm 标准，中浅景深','四骑 + 平视侧面','中心构图','封路的刀矛','锁定被困的猛将','slight-shake',
    'A static shot holds <Picture 21>: however fierce the warrior, the surrounding blades block every escape, penning him in the middle.'),
   (3,[22,22],'close','Static Shot',['C06'],['P03'],
    '特写，被围的猛将眉峰一竖，画戟横扫荡开一线空隙，边斗边扬声怒斥，眼底满是不甘',
    '固定镜头，被围的这名猛将横眉扫开一线空隙，边斗边扬声怒斥面前的三人',
    '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','围上的三人','锁定猛将恼怒的眉眼','stable',
    'A static shot holds the close-up of <Picture 22>: the encircled warrior sweeps a gap and snarls in disbelief: <d>[Chinese] 三打一，算什么好汉！</d>'),
   (4,[23,23],'close','Static Shot',['C03'],[],
    '特写，黑甲猛汉咧嘴一笑，隔着画戟梗着脖子呛回去，虎目里满是不服输的亮光',
    '固定镜头，这名黑甲猛汉咧嘴一笑，隔着画戟梗着脖子呛回去一句，声音洪亮而满是不服',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','对面的猛将','锁定猛汉不甘的神情','stable',
    'A static shot holds the close framing of <Picture 23>: the black-armoured warrior grins and bawls back over the halberd: <d>[Chinese] 谁跟你讲什么好汉，俺只认输赢！</d>'),
  ]),
 dict(scene=1, overall='The encirclement tightens into a deadlock, the warrior wearing thin, then one feint and he breaks free toward his own gates.',
  music_en='The drums hold a rolling tension; a slowing beat as the foe recoils and replies short.',
  blocking='吕布（C06）在阵中反复突围，画戟连荡；刘、关、张紧咬不放，一路反逼回虎牢关下。',
  soundscape='兵刃交撞声渐渐绷紧，猛将喘息的闷哼传出，随即一声短喝、马蹄骤然转向朝来路撤去',
  music='战鼓持续滚动绷紧，对方收势败走时鼓点随之放缓一折',
  cuts=[
   (3,[24,24],'medium','Truck Right',['C02','C03','C06'],['P05','P03'],
    '中景，猛将画戟连荡荡开一个缺口，却仍被黑甲猛汉的蛇矛牢牢咬住，两旁的刀又合拢过来',
    '镜头随猛将的退势向右平移，他连荡画戟破开一线，仍被黑甲猛汉的长矛咬住，两侧刀光又合拢',
    '50mm 标准，中浅景深','三骑 + 平视侧面跟随','三分法','纠缠的矛','锁定被咬住不放的退路','slight-shake',
    'A truck right follows <Picture 24>: the warrior sweeps a gap but the long spear keeps him pinned while the flanking blades close back in.'),
   (4,[25,25],'wide','Static Shot',['C02','C03','C01'],['P05'],
    '全景，三兄弟六只手、刀剑如同一体，把中间的猛将困在当中进退两难，尘土在他们脚下旋成圈',
    '固定镜头，三名联军武将刀剑如同出自一手，把横戟的猛将困在当中进退两难，尘土在脚下旋成圈',
    '35mm 广角，中景深','四骑 + 平视侧面','中心构图','被困的猛将','锁定铁壁般的三人合围','stable',
    'A static shot holds <Picture 25>: the three brothers move as one, boxing the warrior in the middle, hemming him from every side.'),
   (3,[26,26],'close','Static Shot',['C06'],['P03'],
    '特写，猛将汗湿眉峰，画戟往前一虚晃拉开空隙，边退边扬声丢下一句，神色已然松动',
    '固定镜头，这名横戟的猛将把画戟朝前一虚晃拉开空隙，边收势边扬声丢下一句，已露退意',
    '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','围上的三人','锁定猛将收势的眉目','stable',
    'A static shot holds the close framing of <Picture 26>: the warrior feints forward to buy a gap and, retreating, the voice concedes: <d>[Chinese] 罢了！今日不陪你们玩了！</d>'),
   (3,[27,27],'wide','Tracking Shot',['C06'],['P03'],
    '全景，猛将虚晃一戟荡开空隙，拨转马头便朝阵后撤去，尘土在他身后拖出长长一道烟',
    '镜头平稳跟随这名猛将拨转马头朝阵后撤去，荡开空隙后一路放缰，悬起的尘土拖成一道烟',
    '35mm 广角，中景深','猛将 + 侧后平视跟随','引导线构图','人族阵后','锁定纵马败走的猛将','slight-shake',
    'A tracking shot follows <Picture 27>: the warrior feints, turns his horse and bolts, trailing a long plume of dust behind him.'),
  ]),
 dict(scene=1, overall='The three ride down the fleeing figure back under the walls, banner shadow falling over the closing scene.',
  music_en='A steady pursuit rhythm, then a holding drone as the dust settles on the gate.',
  blocking='刘、关、张三骑并排追赶吕布（C06）至虎牢关下，随及勒马扬尘而立，关城垛口悬旗阴影半遮。',
  soundscape='三骑一路紧追的蹄声急密，逼近关墙时骤缓，尘土落定，只剩旗幡被风扯动',
  music='一路追击节奏平稳，逼近关门时转为托长的低音，尘土落下归于沉寂',
  cuts=[
   (3,[28,28],'wide','Tracking Shot',['C01','C02','C03'],['P05'],
    '全景，刘、关、张三骑紧追不舍，直把前面败走的猛将逼退回虎牢关下，尘土一线铺开',
    '镜头平稳跟随三名并辔而追的联军武将，一路把前方败走的猛将逼退回城门之下',
    '35mm 广角，中景深','三骑 + 侧后平视跟随','引导线构图','前方虎牢关','锁定紧追的三骑','slight-shake',
    'A tracking shot follows <Picture 28>: the three lords ride close behind, driving the routed warrior all the way back under the gate of Tiger Prison Pass.'),
   (3,[29,29],'wide','Pan Right',['C03'],[],
    '全景，黑甲猛汉在尘土里勒住马，望着逃进关门的背影扬声叫嚣，一副意犹未尽的样子',
    '镜头向右缓缓摇过，黑甲猛汉勒住战马望向逃进关门的背影，扬着嗓子叫嚣，仍不解气',
    '35mm 广角，中景深','黑甲猛汉 + 平视正侧面','三分法','关城下的败将','锁定叫嚣的猛汉','stable',
    'A pan right sweeps <Picture 29>: the black-armoured warrior reins in at the dust line and howls after the vanished figure, eager for more: <d>[Chinese] 有种别跑！俺还没打够呢！</d>'),
   (3,[30,30],'wide','Static Shot',['C06'],['P03'],
    '全景，关城上董卓军旗倒卷，虎牢关前一片肃杀，那帮败退回城下的军士挤作一团，尘埃未落',
    '固定镜头，关城上军旗倒卷，虎牢关前一片肃杀，败退的守军挤在门下，尘埃悬在半空未落',
    '35mm 广角，中景深','关门 + 平视远眺','引导线构图','关下败军','锁定倒卷的战旗','stable',
    'A static shot holds <Picture 30>: the banner over the gate is whipped back and the pass turns grim as the routed guards huddle beneath the wall.'),
   (3,[31,31],'wide','Static Shot',['C01','C02','C03'],['P05'],
    '全景，三人勒马扬尘而立，被关城垛口那盏悬旗的阴影半遮，气势却逼得城头不敢妄动',
    '固定镜头，三名联军武将勒马扬尘立于关前，身影被垛口悬旗的阴影半掩，气势压得住城头',
    '35mm 广角，中景深','三骑 + 平视远眺','中心构图','虎牢关城头','锁定扬尘而立的三人剪影','stable',
    'A static shot holds <Picture 31>: the three lords stand rearing in the dust, half-shadowed by the war-banner, cowing the wall.'),
  ]),
]

# ---------------- scene 2 : 联军营中庆功 (beats 1-23) ----------------
EP6_SC2 = [
 dict(scene=2, overall='Night falls over the coalition camp, bonfires crackle, and inside one tent a victory feast is set under warm lamplight.',
  music_en='A mellow pipa plucked in leisurely phrases over the feast, warm and unhurried.',
  blocking='帐中一桌庆功酒席：曹操（C04）把壶立席前，袁绍（C10）端爵坐主位，关羽、¬张飞、刘备围坐其间。',
  soundscape='柴火劈啪轻响，杯盏相碰，帐外夜风偶尔掀起帘响，人语低而热络',
  music='一支柔和的琵琶闲闲拨过酒席，和暖而从容',
  cuts=[
   (3,[1,1],'wide','Static Shot',['C04','C10'],[],
    '全景，夜色四合，联军营中点起团团篝火，一顶大帐中摆开庆功的酒席，烛火映着杯盏',
    '固定镜头，夜色中联军营地的篝火团团亮起，帐中摆开庆功酒席，暖黄烛光映着杯盏与酒樽',
    '35mm 广角，中景深','帐内全景 + 平视正面','引导线构图','酒席主位','锁定满桌酒与筹码','stable',
    'A static shot frames <Picture 1>: night settles over the camp, bonfires blaze and a victory feast is spread inside the great tent under warm lamplight.'),
   (3,[2,2],'medium','Tracking Shot',['C04','C02'],[],
    '中景，一名细眼长髯的贵介亲自擎壶，为面前一名绿袍长髯的武将斟满一爵，动作从容',
    '镜头平稳跟随这名细眼长髯的贵介为面前绿袍武将斟酒，动作从容，酒线稳稳落入爵中',
    '50mm 标准，中浅景深','贵介 + 平视侧面跟随','三分法','席前的绿袍武将','锁定斟酒的双手','stable',
    'A tracking shot follows <Picture 2>: the narrow-eyed noble in formal robes pours a full goblet for the long-bearded general before him, then raises it in turn.'),
  ]),
 dict(scene=2, overall='The noble clinks goblets in praise and the white-robed lord acknowledges it with composure; warm lamplight glints on the wine edge.',
  music_en='The pipa plucks a bright, rising phrase as the toasted lord returns the courtesy.',
  blocking='曹操（C04）擎爵相贺；刘备（C01）欠身回敬，席间酒满眼弯。',
  soundscape='酒爵相碰一声脆响，席间说笑再起一番，灯火暖暖映着杯沿',
  music='琵琶拨出一句清亮上行，被敬的头领回礼时那线微微一扬',
  cuts=[
   (5,[3,3],'close','Static Shot',['C04'],[],
    '特写，这名细眼长髯的贵介一手擎爵，笑着开口，目光扫过席间几人，满是对英雄的赞叹',
    '固定镜头，这名细眼长髯的贵介一手擎爵，笑吟吟地开口，目光在席间几人脸上一一扫过',
    '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','席上众人','锁定贵介含笑的眉眼','stable',
    'A static shot holds the close framing of <Picture 3>: the narrow-eyed noble lifts his goblet and the admiring voice declares: <d>[Chinese] 虎牢关前，天下英雄，尽收刘皇叔麾下了。</d>'),
   (5,[4,4],'close','Static Shot',['C01'],[],
    '特写，白衣头领微微欠身，拱手回敬，神色谦和而不居功，声音不高却稳稳当当',
    '固定镜头，这名白衣头领微微欠身拱手回敬，神色谦和，声音不高却稳稳当当把这番夸轻轻接住',
    '85mm 长焦，浅景深','白衣头领 + 平视正面','中心构图','擎爵的贵介','锁定头领谦和的面容','stable',
    'A static shot holds the close framing of <Picture 4>: the white-robed lord inclines in a bow and the modest, steady voice returns: <d>[Chinese] 曹公谬赞。云长翼德皆是义气，不足为功。</d>'),
   ]),
 dict(scene=2, overall='The wine flows; the brothers trade good-natured boasts while the noble in the chief seat watches coldly.',
  music_en='The pipa chords pause mid-phrase as the proud noble speaks, a cool low note answering.',
  blocking='张飞（C03）席间兴起扬声夸功；袁绍（C10）端爵在旁，冷眼看了半晌，忽慢悠悠开口。',
  soundscape='席间说笑声起，杯盏一碰，随后一处话音冷下来，帐内静这几息',
  music='琵琶拉出一句高音后顿住，倨傲的话音落下时一节低音冷冷回敬',
  cuts=[
   (5,[5,5],'close','Static Shot',['C03'],[],
    '特写，黑甲猛汉酒到兴头嗓门响亮，一边比划当日那一戟的架势，一边冲兄长竖起大拇指',
    '固定镜头，这名黑甲猛汉书喝了几盏兴起，比划着当日一戟的分寸，嗓门洪亮地夸着自家兄弟',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','酒席众人','锁定猛汉眉飞色舞的神情','stable',
    'A static shot holds the close framing of <Picture 5>: the black-armoured warrior, happy on wine, gestures broadly and the booming voice crows: <d>[Chinese] 那一戟下去可真带劲，大哥出手更是时机绝妙！</d>'),
   (3,[6,6],'medium','Push In',['C10'],[],
    '中景，主位上端爵的倨傲贵胄冷眼看了半晌，忽地慢悠悠端起酒爵，眼光从几人身上挪开',
    '镜头朝端爵的倨傲贵胄缓缓推近，他冷眼看席半晌，才慢条斯理地端起爵，话未开口已压全场',
    '50mm 标准，中浅景深','倨傲贵胄 + 平视正面','中心构图','席上的兄弟几人','锁定贵胄冷峻的目光','stable',
    'A slow push in on <Picture 6>: the haughty noble in the chief seat watches coldly for a long moment before unhurriedly raising his cup.'),
  ]),
 dict(scene=2, overall='A proud sneer is met by restraint as the white-robed lord holds his brother back under the table.',
  music_en='A cool low note answers the boast; the lute runs a thin, wary line.',
  blocking='袁绍（C10）倨傲开口；张飞（C03）欲发作，被身旁刘备（C01）在桌下悄捏了把手压住。',
  soundscape='倨傲贵胄冷冷一句，黑甲猛汉差点翻脸，被白衣头领按住，满席静了一瞬',
  music='低音冷冷跟了一句，琵琶顺势拉一条细而戒备的弦线',
  cuts=[
   (5,[7,7],'close','Static Shot',['C10'],[],
    '特写，这名单髯倨傲的贵胄端着爵，唇角微微一沉，一字一字地说出，语气里全是名门高门的架子',
    '固定镜头，这名单髯倨傲的贵胄端着爵，唇角一沉，一字一字地开口，论的是名门高门的法度',
    '85mm 长焦，浅景深','倨傲贵胄 + 平视正面','中心构图','席上的兄弟几人','锁定贵胄倨傲的神色','stable',
    'A static shot holds the close framing of <Picture 7>: the haughty noble sets down his cup and the lofty voice sneers: <d>[Chinese] 戚戚之义，终是野路子。哪比得上名门之法度。</d>'),
   (3,[8,8],'medium','Static Shot',['C03','C01'],[],
    '中景，黑甲猛汉眉头一竖就要发作，被身旁的白衣头领在桌下悄捏了把手，硬生生压住火气',
    '固定镜头，黑甲猛汉眉头一竖作势要发作，旁边白衣头领在桌下悄悄按了按他的手，把这话压回去',
    '50mm 标准，中浅景深','二人 + 平视侧面','三分法','桌面','锁定桌下那只暗地里按住的手','stable',
    'A static shot catches <Picture 8>: the black-armoured warrior bristles to snap back, but the white-robed lord quietly presses his hand under the table to hold him back.'),
  ]),
 dict(scene=2, overall='A quiet bridge: the lord answers with composure and the noble presses his gain.',
  music_en='The pipa picks up a thin line; a low register creeps in beneath the talk.',
  blocking='刘备（C01）谦称谨记；曹操（C04）又进言劝进。',
  soundscape='白衣头领稳稳回话，酒席话声再起一瞬，帐内暖意未散',
  music='琵琶拨出细线，一句一句托着两人的对答',
  cuts=[
   (4,[9,9],'close','Static Shot',['C01'],[],
    '特写，白衣头领欠身应了一声，态度恭敬得体，把方才那句锋芒不软不硬地接住',
    '固定镜头，这名白衣头领欠身应了一声，姿态恭敬得体，不卑不亢地把方才那句话接住',
    '85mm 长焦，浅景深','白衣头领 + 平视正面','中心构图','主位上的贵胄','锁定头领恭谨的眉眼','stable',
    'A static shot holds the close framing of <Picture 9>: the white-robed lord inclines politely, and the measured voice replies: <d>[Chinese] 蒙盟主指点，我兄弟必当谨记。</d>'),
   (5,[10,10],'close','Static Shot',['C04'],[],
    '特写，细眼长髯的贵介抬手拍案，声音一扬，说的正是趁胜追进、莫要错过战机的话',
    '固定镜头，这名细眼长髯的贵介抬手轻拍案沿，声音一扬，讲的是趁胜进击、莫错战机的道理',
    '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','白衣头领','锁定贵介发亮的眼','stable',
    'A static shot holds the close-up of <Picture 10>: the narrow-eyed noble raps the table and the eager voice urges: <d>[Chinese] 此战斩锐，大军正该趁势进击，二位何必自谦。</d>'),
  ]),
 dict(scene=2, overall='A scout bursts in with ill news and the nobleman\u2019s composure cracks.',
  music_en='A low register creeps in beneath the scout\u2019s hurried report.',
  blocking='帐帘一挑，探马入报，附耳于袁绍（C10）。',
  soundscape='帐帘忽地挑开，探马脚步急促、附耳低语，随后倨傲贵胄声音陡变',
  music='一段低音从下方悄悄渗进来，探马入帐那刻骤然收紧',
  cuts=[
   (3,[11,11],'medium','Pan Right',['C10'],[],
    '中景，帐帘陡然一挑，一名探马分众而入，几步赶到主位，附到倨傲贵胄耳边低声急语',
    '镜头向右轻轻一摇，帐帘挑开、一名探马快步走到主位旁，附身凑到倨傲贵胄耳边低语',
    '50mm 标准，中浅景深','探马 + 平视侧面','三分法','主位上的贵胄','锁定附耳低语的探马','stable',
    'A pan right follows <Picture 11>: a scout pushes through the flap, hurries to the chief seat and leans in to whisper urgently in the nobleman\u2019s ear.'),
   (5,[12,12],'close','Push In',['C10'],[],
    '特写，倨傲贵胄听罢脸上的矜持一撤，眉峰陡地拧起，声音沉下来带着惊与怒',
    '镜头朝这名倨傲贵胄的脸缓缓推近，他听罢探马之言神色一变，眉峰拧起，声音又惊又怒',
    '85mm 长焦，浅景深','倨傲贵胄 + 平视正面','中心构图','探马','锁定贵胄骤变的面容','stable',
    'A slow push in on <Picture 12>: the nobleman\u2019s composure cracks as the news lands, and the startled, angry voice bursts out: <d>[Chinese] 什么？董卓已调西凉精骑，今夜要再夺虎牢！</d>'),
  ]),
 dict(scene=2, overall='The tent falls still, and one hand tightens on a blade under the table.',
  music_en='The warm pipa stops; a cold, held string hangs over the silence of the tent.',
  blocking='满帐一静，火苗劈啪；关羽（C02）在案下攥紧刀柄缓缓抬眼。',
  soundscape='帐内骤然安静，只剩柴火劈啪，随后一人攥刀骨的闷响传来',
  music='暖琵琶顿歇，取而代之一段悬空的冷弦，压在满帐的沉默上',
  cuts=[
   (3,[13,13],'medium','Static Shot',['C04','C01','C10'],[],
    '中景，满帐顿时一静，方才的热闹一扫而空，只剩火苗劈啪作响，众人目光都落在主位上',
    '固定镜头，满帐骤然安静，方才的热闹一扫而空，火苗劈啪，众人视线不约而同落向主位',
    '50mm 标准，中浅景深','帐内全景 + 平视正面','中心构图','主位','锁定众人敛住的脸色','stable',
    'A static shot holds <Picture 13>: the tent falls abruptly still, the merriment dissolving into the crackle of the fire, every gaze turning to the chief seat.'),
   (4,[14,14],'close','Static Shot',['C02'],[],
    '特写，一名绿袍长髯的将领未发一言，只在案下把长柄大刀的刀柄攥紧一寸，缓缓抬眼看众人',
    '固定镜头，这名绿袍长髯的将领不发一言，案下那只手把大刀柄攥紧一寸，再缓缓抬眼扫过众人',
    '85mm 长焦，浅景深','将领 + 平视正面','中心构图','满帐众人','锁定攥紧刀柄的手','stable',
    'A static shot holds the close framing of <Picture 14>: the long-bearded general says nothing, only gripping his blade\u2019s haft a notch tighter before slowly lifting his eyes.'),
  ]),
 dict(scene=2, overall='The general vows to lead the charge at dawn, and the bold brother declares he fears no second fight.',
  music_en='A quiet resolve in the lute; a warm, rising line as the pledge lands.',
  blocking='关羽（C02）沉声言明早仍由兄弟打头阵；张飞（C03）把爵一墩放声应和。',
  soundscape='绿袍将领一句不高的定话，随后黑甲猛汉把酒爵一墩、嗓门一亮',
  music='琵琶一句低稳的弦托住将领的话，猛汉接话时那线扬起一暖',
  cuts=[
   (4,[15,15],'close','Static Shot',['C02'],[],
    '特写，这名绿袍长髯的将领终于出声，声音不高却稳，说的正是明了早仍由兄弟打头阵的话',
    '固定镜头，这名绿袍长髯的将领终于开口，声音不高却极稳，把明明轮到自己这一队的事说定',
    '85mm 长焦，浅景深','将领 + 平视正面','中心构图','主位','锁定将领沉静的神色','stable',
    'A static shot holds the close framing of <Picture 15>: at last the long-bearded general speaks, low and firm, pledging: <d>[Chinese] 既如此，明早仍由我兄弟打头阵便是。</d>'),
   (5,[16,16],'close','Static Shot',['C03'],[],
    '特写，黑甲猛汉把爵往桌上一墩，嗓门一亮，说的是虎口都闯过、还怕再来一遭的横话',
    '固定镜头，这名黑甲猛汉把酒爵往桌上一墩，嗓门一亮，满不在乎地回了一句横话',
    '85mm 长焦，浅景深','黑甲猛汉 + 平视正面','中心构图','主位','锁定猛汉满不在乎的神色','stable',
    'A static shot holds the close framing of <Picture 16>: the black-armoured warrior slams his cup down and declares with a grin: <d>[Chinese] 怕什么！虎口都闯过了，还怕再来一回！</d>'),
  ]),
 dict(scene=2, overall='The chief seat closes the matter coldly, while the narrow-eyed noble half-smiles into his wine.',
  music_en='A low, somber reed plays under the parting.',
  blocking='袁绍（C10）冷声定号令；曹操（C04）垂眼啜酒，嘴角一勾，余光掠向白衣头领。',
  soundscape='倨傲贵胄冷声收场，随后贵介垂眼啜酒、嘴角几不可察地一勾',
  music='一支低沉幽咽的芦管在散席时响起，火把熄去、余烬只剩一点红光',
  cuts=[
   (3,[17,17],'medium','Push In',['C10'],[],
    '中景，倨傲贵胄眉峰紧锁，目光在席上几人身上转了几转，欲言又止，终究冷声定下全营的号令',
    '镜头朝倨傲贵胄缓缓推近，他目光在几人身上转了几转，几度欲言又止，终究冷声把号令定死',
    '50mm 标准，中浅景深','倨傲贵胄 + 平视正面','中心构图','席上几人','锁定贵胄阴沉的面容','stable',
    'A slow push in on <Picture 17>: the haughty noble\u2019s brows knit, his gaze weighing the men at the table before he coldly fixes the decree for the whole camp.'),
   (5,[18,18],'close','Static Shot',['C10'],[],
    '特写，倨傲贵胄端着爵，一字一字地说完那句全营听其号令的话，把话柄钉死在主位上',
    '固定镜头，这名单髯倨傲的贵胄端着爵，一字一字把话说完，意思再清楚不过——各营须听其号令',
    '85mm 长焦，浅景深','倨傲贵胄 + 平视正面','中心构图','席上几人','锁定贵胄不容商议的神色','stable',
    'A static shot holds the close framing of <Picture 18>: the haughty noble raises his cup and states flatly, leaving no room to argue: <d>[Chinese] 联军本为一体，明日各营听我号令，不得独进。</d>'),
  ]),
 dict(scene=2, overall='The noble beside the chief seat half-smiles into his wine, watching the white-robed lord rise to leave.',
  music_en='A low, somber reed keeps playing under the parting.',
  blocking='曹操（C04）垂眼啜酒，嘴角一勾，余光掠向正要起身的白衣头领。',
  soundscape='贵介垂眼啜酒、嘴角几不可察地一勾，火把将熄，余烬只剩一点红光',
  music='一支低沉幽咽的芦管仍在散席时低低吹着',
  cuts=[
   (3,[19,19],'medium','Pan Left',['C04'],[],
    '中景，细眼长髯的贵介垂下眼品了一口酒，嘴角几不可察地微微一勾，余光扫过正要起身的白衣头领',
    '镜头向左轻轻一摇，这名细眼长髯的贵介垂眼啜了口酒，嘴角几不可察地一勾，余光掠向白衣头领',
    '50mm 标准，中浅景深','贵介 + 平视正侧面','三分法','白衣头领','锁定贵介唇边那一丝笑意','stable',
    'A pan left holds <Picture 19>: the narrow-eyed noble sips his wine, a faint smile caught at the corner of his mouth as his eye flicks to the white-robed lord.'),
   (6,[20,20],'close','Static Shot',['C04'],[],
    '特写，细眼长髯的贵介搁下酒盏，朝白衣头领缓声吩咐，像是随口再说一句，又像是记在心里',
    '固定镜头，这名细眼长髯的贵介搁下酒盏，朝白衣头领缓声吩咐一句，语气不轻不重却像有深意',
    '85mm 长焦，浅景深','贵介 + 平视正面','中心构图','白衣头领','锁定贵介那双眼','stable',
    'A static shot holds the close framing of <Picture 20>: the narrow-eyed noble sets down his cup and addresses the white-robed lord, the voice both casual and pointed: <d>[Chinese] 那便依盟主。皇叔，今晚好生歇息，明日还有硬仗。</d>'),
  ]),
 dict(scene=2, overall='They rise and leave under the dying torches; a low order follows them, and beyond the camp a far fire eats at the sky.',
  music_en='A lone bamboo flute fades; a held drone keeps the image open into the coming night.',
  blocking='曹操（C04）目送三人背影离帐，低声吩咐亲随多记着这三人；帐外火把逐盏暗去。',
  soundscape='三人起身离帐的脚步，帘声一低；贵介低声吩咐亲随，帐外夜风里火把一盏盏熄灭',
  music='笛声渐远收住，剩下空荡低音托住画面，铺进将临的长夜',
  cuts=[
   (4,[21,21],'medium','Static Shot',['C04'],[],
    '中景，细眼长髯的贵介立在帐口，目送三人背影走远，忽压低声音对身旁亲随吩咐几句',
    '固定镜头，这名细眼长髯的贵介立着目送三人离帐，忽压低声音对身边亲随低声交代',
    '50mm 标准，中浅景深','贵介 + 平视正侧面','三分法','帐外三人背影','锁定贵介沉定的目光','stable',
    'A static shot holds <Picture 21>: the narrow-eyed noble watches the three retreat into the night, then drops his voice to a low instruction at his aide\u2019s ear.'),
  ]),
 dict(scene=2, overall='The torches dim outside; a smoke still rises toward the pass, and far off a spark gutters like an unblinking beast.',
  music_en='A held drone over a fading flute as the night closes in.',
  blocking='帐外火把逐盏暗去，虎牢关方向的烟火一线一线升起；曹操（C04）的身影立在帘边。',
  soundscape='帐外夜风里火把一盏盏熄灭，西南烟火在夜色中一线一线翻起，风声低咽',
  music='笛声收住，空荡低音托住夜幕，推向远方那一点忽明忽暗的火',
  cuts=[
   (3,[22,22],'wide','Static Shot',['C04'],[],
    '全景，帐外的火把一盏一盏黯淡下去，虎牢关方向的炊烟却仍在夜色里一线一线升起，夜色四合',
    '固定镜头，帐外火把逐盏暗去，夜色四合，虎牢关方向那缕炊烟却仍在夜色里一线一线升着',
    '35mm 广角，中景深','营帐外景 + 平视远眺','引导线构图','远方的关城','锁定渐暗的火把与炊烟','stable',
    'A static shot holds <Picture 22>: the torches outside dim one by one while a thread of smoke still rises beyond the camp toward the pass in the night.'),
   (3,[23,23],'extreme-wide','Static Shot',['C04'],[],
    '大远景，夜风把虎牢关方向的一点火光吹得忽明忽暗，像一头不闭眼的兽卧在远方的夜色里',
    '固定镜头远眺，夜风将虎牢关方向的一点火光吹得忽明忽暗，如同夜色里一头不闭眼的兽',
    '24mm 广角，深景深','营地远方 + 平视远眺','中心构图','远方的火光','锁定那点忽明忽暗的火','stable',
    'An extreme wide static shot holds <Picture 23>: the wind breathes a far spark beyond the pass so it gutters on and off, like an unblinking beast in the dark.'),
  ]),
]

EP6 = []
for seg in EP6_SC1: seg['sceneIndex'] = 1
for seg in EP6_SC2: seg['sceneIndex'] = 2
EP6 = EP6_SC1 + EP6_SC2