# -*- coding: utf-8 -*-
"""EP8 segments (each segment <=15s, one dict per segment).
cut tuple: (seconds, beats, size, camera, chars, props, frame, shot, lens, camPos, comp, eye, focus, stab, en)
beats per-scene 1-based. All EP8 scenes props None -> cut props=[]. Names only inside <d>; en/shot use descriptors."""

# =============== scene 1 : 王允夜恳貂蝉 (beats 1-12) C07/C08 ===============
E8_1A = dict(scene=1,
 overall='Deep night in a study; a grey-bearded old minister dismisses his servants and sinks to his knees before a young woman, tears crossing his face.',
 music_en='A low, sorrowful string drone; a faint rustle as the room empties.',
 blocking='王允（C08）屏退侍从，扑通跪在貂蝉（C07）面前；貂蝉慌忙俯身去扶。',
 soundscape='夜深人静，衣袍拂地的窸窣，老臣一声压低的哽咽与女子慌乱的惊声',
 music='一段低沉哀切的弦鸣垫底，屋内人影散去时一声极轻的沙沙',
 cuts=[
  (2.5,[1,1],'wide','Tracking Shot',['C08'],[],
   '全景，深夜书室，一名须发花白的老臣挥退四周侍从，待门合拢，忽然扑通一声跪在一名华服的年轻女子面前，老泪纵横',
   '镜头平稳跟随这名须发花白的老臣，他屏退侍从、合上门，随即扑通跪在年轻女子面前，老泪纵横',
   '35mm 广角，中景深','老臣 + 侧后平视跟随','中心构图','跪前的女子','锁定老臣跪下的身形','stable'),
  (2.5,[2,2],'medium','Static Shot',['C07'],[],
   '中景，华服的年轻女子慌忙俯身去搀扶，把人扶回座上，自己也跪到老臣膝前，神情惶恐无措',
   '固定镜头，这名华服的年轻女子慌忙俯身把人扶回座，又自觉跪到膝前，一脸惶恐',
   '50mm 标准，中浅景深','女子 + 平视侧面','三分法','跪地的老人','锁定女子慌忙的身形','stable'),
 ])
E8_1B = dict(scene=1,
 overall='The minister lays a bitter charge before her, and the young woman answers that she will obey whatever her father bids.',
 music_en='The strings tighten; a soft, resolute pulse answers the older man\u2019s words.',
 blocking='王允（C08）膝前沉声托付；貂蝉（C07）跪在对面低声应下。',
 soundscape='老臣低而急的托付，女子柔而定的应答，烛火在两人之间摇曳',
 music='弦鸣收紧，一句坚定的低音随女子的话稳稳落下',
 cuts=[
  (3.6,[3,3],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣双膝跪地，颤着声音开口，眼里含着一层老泪，说出那句要她舍身去办的话',
   '固定镜头，这名须发花白的老臣跪着哽咽开口，声音压得又低又急，把一个重担托到女子面前',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的女子','锁定老臣含泪的眼','stable',
   'A static close-up holds the grey-bearded old minister as he kneels and speaks in a low, urgent voice, laying the heavy charge before her: <d>[Chinese] 貂蝉，义父有一事，须你舍身去办。</d>'),
  (2.7,[4,4],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子抬眼望着老臣，目光没有一丝迟疑，低声应下，答得干脆',
   '固定镜头，这名华服的年轻女子抬眼看向老臣，声音不高却稳稳当当地应下',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','对面的老臣','锁定女子应下的眼','stable',
   'A static close-up holds the young woman as she lifts her gaze and answers without hesitation, in a low, clear voice: <d>[Chinese] 义父但说，貂蝉无不从命。</d>'),
 ])
E8_1C = dict(scene=1,
 overall='The minister names the peril that grips the land and the one person who can split the tyrant father and son apart.',
 music_en='The strings press forward, grave and insistent.',
 blocking='王允（C08）膝前一字一字说破天下祸害；貂蝉（C07）垂眸听着，睫毛微颤。',
 soundscape='老臣沉声历数祸害，句句压心；女子垂眸听着，呼吸都屏住了一瞬',
 music='一段沉而铿锵的弦音步步压来，把话头托得又重又紧',
 cuts=[
  (5.6,[5,5],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣一字一字地开口，把天下遭其荼毒、唯有一人能令他们反目的话说破，神色悲愤又郑重',
   '固定镜头，这名须发花白的老臣悲愤又郑重地把话一字一字说透，字字都像带着千斤分量',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面的女子','锁定老臣悲愤的目光','stable',
   'A static close-up holds the grey-bearded old minister as he speaks the bitter truth line by line, grief and resolve fighting in his face: <d>[Chinese] 董卓父子凶横，天下遭其荼毒。唯你一人能令他们反目。</d>'),
  (2.5,[6,6],'close','Push In',['C07'],[],
   '特写，华服的年轻女子长长的睫毛微微一颤，随即倔强地抬起眼，直直望着老臣，没有躲开的打算',
   '镜头朝这名华服的年轻女子缓缓推近，她睫毛颤了一下，却倔强抬头，目光清亮而坚定',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','对面的老臣','锁定女子抬起的倔强眼神','stable'),
 ])
E8_1D = dict(scene=1,
 overall='She asks to be sure of the tiger\u2019s den she is being sent into, and the minister owns how mortal the gamble is.',
 music_en='A thin, almost breathless line as the answer wavers, then a firmer pulse.',
 blocking='貂蝉（C07）跪地问明虎穴所在；王允（C08）点头承认这一步凶险万分。',
 soundscape='女子一句轻声的追问，老臣低低应下，烛火被窗风推得晃了一晃',
 music='弦线一端纤细几近屏息，答话落下时一抹更沉的低音稳稳接住',
 cuts=[
  (3.6,[7,7],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子轻声问出一句，目光直直落在老臣脸上，问的是她此去的是不是那虎穴狼窝',
   '固定镜头，这名华服的年轻女子轻声开口，问得又轻又直，眼底却已隐约有了决意',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','老臣','锁定女子追问的目光','stable',
   'A static close-up holds the young woman as she asks softly and directly, already glimpsing her answer: <d>[Chinese] 义父是要貂蝉去那虎穴狼窝里周旋？</d>'),
  (4.7,[8,8],'close','Static Shot',['C08'],[],
   '特写，须发花白的老臣没有回避，点头承认，把那一步凶险、一步错便是万劫不复的话，低声说了出来',
   '固定镜头，这名须发花白的老臣点着头低声承认，神色凝重得近乎沉痛，把最坏的一步也一并说出',
   '85mm 长焦，浅景深','老臣 + 平视正面','中心构图','对面女子','锁定老臣凝重的神色','stable',
   'A static close-up holds the old minister as he admits without flinching to how mortal the gamble is: <d>[Chinese] 是。这一步棋凶险万分，一步错便是万劫不复。</d>'),
 ])
E8_1E = dict(scene=1,
 overall='The minister bows to her in parting earnest and the young woman, steadied, promises to give her life for the Han throne.',
 music_en='The melody turns to a solemn, fateful chord; a quiet vow in the lute.',
 blocking='王允（C08）颤手为貂蝉抹泪、郑重躬身一礼；貂蝉（C07）慌忙回礼，抬眼时已敛尽怯意。',
 soundscape='老臣颤手抹泪的衣料声、郑重躬身的一礼，随后女子一句定了心的低沉应诺',
 music='旋律转为一句庄重而宿命的和弦，琵琶低低托住那句誓言的重量',
 cuts=[
  (2.5,[9,9],'medium','Static Shot',['C08'],[],
   '中景，须发花白的老臣颤着手为年轻女子抹去泪痕，站直了身子，郑重地朝她躬身一礼，像把整副担子都托付了出去',
   '固定镜头，这名须发花白的老臣颤手抹去女子泪痕，站直后郑重朝她躬身，姿态近乎托付',
   '50mm 标准，中浅景深','老臣 + 平视侧面','三分法','面前的女子','锁定老臣躬身郑重','stable'),
  (2.5,[10,10],'medium','Static Shot',['C07'],[],
   '中景，华服的年轻女子慌忙回礼，垂眸定了定神，再抬眼时，眼底那点女儿家的怯意已尽数敛去',
   '固定镜头，这名华服的年轻女子慌忙回礼，低头定了定神，再抬眸时神色已然沉稳',
   '50mm 标准，中浅景深','女子 + 平视正面','三分法','躬身的老臣','锁定女子敛去怯意的眉眼','stable'),
  (3.6,[11,11],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子抬眸，声音不高却字字笃定，把那句拼死走一遭的承诺说得清亮决然',
   '固定镜头，这名华服的年轻女子抬眸开口，声音不高而稳，把一句杀伐果决的诺言说得清清楚楚',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','老臣','锁定女子笃定的双眼','stable',
   'A static close-up holds the young woman as she lifts her eyes and declares in a steady, clear voice: <d>[Chinese] 汉室存亡，貂蝉自当拼死走这一遭。</d>'),
 ])
E8_1F = dict(scene=1,
 overall='The candle flickers as the young woman bows her head to the charge, and in the shadow her eyes are bright as a blade.',
 music_en='The fateful melody recedes into a held, firelit quiet.',
 blocking='貂蝉（C07）垂首受命，烛火摇动，暗影里双眼亮得像刀。',
 soundscape='烛火噼啪一声，女子一声低低的受命，随后满室复归沉静',
 music='宿命的旋律渐远，收入一段持久的、映着烛火的静默',
 cuts=[
  (2.5,[12,12],'extreme-wide','Static Shot',['C07'],[],
   '大远景，深夜书室，华服的年轻女子垂首跪坐在烛影里，烛火摇动，暗影中那双眼睛亮得像一柄出鞘的刀',
   '固定大远景，这名华服的年轻女子垂首跪坐在摇曳的烛影里，火光在眼底明明灭灭，锋利如刀',
   '24mm 广角，深景深','书室全景 + 俯视远眺','中心构图','烛影中的女子','锁定那点亮如刀的眼','stable'),
 ])

# =============== scene 2 : 凤仪亭诉衷情 (beats 1-18) C06/C07 ===============
E8_2A = dict(scene=1,
 overall='By a pagoda pavilion at dusk a young woman weeps with her back to the path, until footsteps stop behind her.',
 music_en='A calm, wistful pluck over the evening; a soft hush as the visitor draws near.',
 blocking='貂蝉（C07）在凤仪亭下掩面垂泪；吕布（C06）自长廊走近，开口询问。',
 soundscape='黄昏亭下的一阵风，女子低低的抽泣，随后一道步伐走近、停在她身后',
 music='一段舒缓怀旧的拨弦笼住暮色，来人的脚步悄然临近时声音微微一收',
 cuts=[
  (2.5,[1,1],'wide','Static Shot',['C07'],[],
   '全景，黄昏的凤仪亭下，一名华服的年轻女子背对长廊站着，正掩面垂泪，霞光淡淡落在她肩头',
   '固定镜头，亭下这名华服的年轻女子背对长廊掩面垂泪，暮色与霞光淡淡铺满一身',
   '35mm 广角，中景深','女子 + 侧后平视','三分法','长廊方向','锁定女子垂泪的背影','stable'),
  (2.9,[2,2],'close','Static Shot',['C06'],[],
   '特写，一名头戴雉尾紫金冠、横着画戟的猛将自廊下走近，放轻了声音开口询问，眉目间有关切',
   '固定镜头，这名头戴雉尾紫金冠的猛将走近，声音放得又轻又低，关切地问了一句',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','垂泪的女子','锁定猛将询问的目光','stable',
   'A static close-up holds the crowned warrior as he draws near and asks in a softened, concerned voice: <d>[Chinese] 貂蝉，你怎的独自在此伤心？</d>'),
 ])
E8_2B = dict(scene=1,
 overall='He reaches to turn her around, and she answers that a weak woman is no more than driftwood in men\u2019s hands.',
 music_en='The plucking pauses, a thin, sad line answers.',
 blocking='吕布（C06）伸手搭上貂蝉（C07）的肩要将她扳过身；貂蝉低声答话。',
 soundscape='脚步声停驻，一声男子低问，随后女子一句如浮萍般的低语落在暮色里',
 music='拨弦顿了一拍，一句纤细而哀伤的音线轻轻接上',
 cuts=[
  (2.5,[3,3],'medium','Truck Left',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将上前一步，伸手搭上背对着他的女子肩头，要把她扳过身来',
   '镜头随猛将左移跟进，他伸手搭上女子的肩，想让她转过身来面对自己',
   '50mm 标准，中浅景深','猛将 + 侧后平视跟随','三分法','垂泪的女子','锁定猛将搭肩的手','stable'),
  (4.2,[4,4],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子仍不回头，声音低低地从风里传来，把自己比作随波逐流的浮萍',
   '固定镜头，这名华服的年轻女子依然背身，声音低低哑哑，透着无依的凄清',
   '85mm 长焦，浅景深','女子 + 侧面平视','中心构图','身后的人','锁定女子低垂的眉眼','stable',
   'A static close-up holds the young woman as she answers in a low, forlorn voice without turning, likening herself to driftwood at men\u2019s mercy: <d>[Chinese] 妾身一个弱女子，如浮萍般任人摆布罢了。</d>'),
 ])
E8_2C = dict(scene=1,
 overall='His temper flashes and he swears to punish whoever has wronged her, but she shrinks back shaking her head.',
 music_en='A sudden, harder pluck at his anger, then a wavering retreat.',
 blocking='吕布（C06）怒声追问要替她出气；貂蝉（C07）惶恐摇头、拨开他的手、后退两步。',
 soundscape='猛将一声怒问拔起，随后女子慌乱地连声否认，衣料细响、脚步后退',
 music='一道骤然硬起的拨弦随怒声砸下，又随女子的退却化为零落的音节',
 cuts=[
  (3.6,[5,5],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将沉声追问，眉宇浮起一层怒意，口口声声要替她讨个公道',
   '固定镜头，这名猛将沉声追问，眉目间怒意浮起，一副定要替她出气的架势',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','面前的女子','锁定猛将生怒的眉眼','stable',
   'A static close-up holds the crowned warrior as his temper rises and he demands to know the culprit: <d>[Chinese] 谁欺负了你？告诉我，我替你出气！</d>'),
  (2.5,[6,6],'medium','Static Shot',['C07'],[],
   '中景，华服的年轻女子惶恐地摇头，把猛将搭来的手指一根一根拨开，又往后退开两步',
   '固定镜头，这名华服的年轻女子连连摇头，拨开对方的手，脚步慌乱地退开两步',
   '50mm 标准，中浅景深','女子 + 侧前平视','三分法','逼问的猛将','锁定女子退避的身形','stable'),
 ])
E8_2D = dict(scene=1,
 overall='She begs him not to ask, lest it bring more trouble; he seizes her wrist in rising alarm and raises his voice.',
 music_en='The line quivers, then a strained urgency enters the strings.',
 blocking='貂蝉（C07）恳请吕布（C06）莫问；吕布情急一把攥住她的腕子，声音拔高。',
 soundscape='女子低低求恳、似有难言之隐，随后猛将情急攥腕、连声急问',
 music='纤细音线轻轻发颤，一股绷紧的急迫弦音随后灌了进来',
 cuts=[
  (4.7,[7,7],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子低眉不敢直说，只一遍遍求他莫要再问，声音里透着深深的畏惧与难言',
   '固定镜头，这名华服的年轻女子低眉垂目，声音发颤地恳求，似有满腹难言之隐不敢道破',
   '85mm 长焦，浅景深','女子 + 平视侧面','三分法','对面的猛将','锁定女子低垂颤抖的眉眼','stable',
   'A static close-up holds the young woman as she begs him softly not to ask further, fear and a hidden woe trembling in her voice: <d>[Chinese] 将军勿问。问了，不过是徒增烦忧，反惹祸端。</d>'),
  (2.5,[8,8],'medium','Push In',['C06'],[],
   '中景，这名头戴雉尾紫金冠的猛将情急之下上前一步，一把攥住她的腕子，声音也提了起来',
   '镜头朝这名猛将缓缓推近，他情急攥住女子的腕子，眉头一竖，声音提高了几分',
   '50mm 标准，中浅景深','猛将 + 侧前平视','三分法','被握住腕的女子','锁定猛将攥腕的手','slight-shake'),
 ])
E8_2E = dict(scene=1,
 overall='He protests that two hearts already know each other; she lifts tear-bright eyes and, in a trembling voice, at last speaks the unspoken aloud.',
 music_en='A held, aching note as the truth is about to break out.',
 blocking='吕布（C06）诉心意；貂蝉（C07）含泪抬眼，终于抖着声音说破。',
 soundscape='猛将一句情急的剖白，随后女子含泪抬眼、声音颤抖着一字一字说破',
 music='一段凝住、隐痛的音在真相将破未破处悬着',
 cuts=[
  (4.2,[9,9],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将情急剖白，一字一句全是素日的两心相印，却全不解她为何避而不谈',
   '固定镜头，这名猛将情急之下剖白心意，字字恳切，眉间满是急切与不解',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','面前的女子','锁定猛将恳切的目光','stable',
   'A static close-up holds the crowned warrior as he pours out his heart, baffled why she now holds back: <d>[Chinese] 你我心心相印，你却连话都不肯同我说了！</d>'),
  (2.5,[10,10],'close','Push In',['C07'],[],
   '特写，华服的年轻女子含泪抬眼，忽然抖着声音开口，一字一字，像是在把最深的伤口生生撕开',
   '镜头朝这名华服的年轻女子缓缓推近，她含泪抬眸，声音发着抖，一字一字把那话逼了出来',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','猛将','锁定女子含泪决然的眼睛','slight-shake'),
 ])
E8_2F = dict(scene=1,
 overall='She confesses how the tyrant took her by force; the warrior turns white as a sheet, the veins standing out on the hand that grips his halberd.',
 music_en='The music cuts; a low, shuddering tremolo beneath the confession',
 blocking='貂蝉（C07）说破原委；吕布（C06）如遭雷击，握戟的手背青筋暴起。',
 soundscape='女子抖着声音说破那桩屈辱，随即满亭一静，只剩猛将几乎压不住的粗重呼吸',
 music='乐声骤然一落，一段低沉的颤音垫在女子的话底下',
 cuts=[
  (4.4,[11,11],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子抖着声音说出那句屈辱的话，眼眶泛红，泪珠一颗颗滚落也顾不得擦',
   '固定镜头，这名华服的年轻女子抖着声把委屈说破，泪滚了满脸却倔强地不肯别过眼',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','猛将','锁定女子含泪说破的眼','slight-shake',
   'A static close-up holds the young woman as she confesses between tears, each word torn from her: <d>[Chinese] 是相国……占了我的身子，要我做了他的妾。</d>'),
  (2.5,[12,12],'extreme-close','Static Shot',['C06'],[],
   '大特写，这名单手持画戟的猛将脸色刷地一白，眉目骤然凝住，握戟的手背上青筋一根根暴起',
   '固定大特写，这名猛将脸色瞬间煞白，握住画戟的指节猛地一根根收紧，青筋尽起',
   '100mm 微距，极浅景深','猛将的手 + 平视','中心构图','僵住的面容','锁定暴起的青筋','slight-shake'),
 ])
E8_2G = dict(scene=1,
 overall='Through a clench of fury the warrior cannot bring himself to believe it, and the woman sinks into his arms weeping.',
 music_en='A low, trembling string; a muffled sob beneath.',
 blocking='吕布（C06）扼腕难信地低声质问；貂蝉（C07）扑进他怀里泪如雨下。',
 soundscape='猛将一声又惊又怒的低问，随即女子扑入怀中泣不成声，衣料相触一声闷响',
 music='低颤的弦音一颤再颤，掩着那句无能为力的泣声',
 cuts=[
  (3.1,[13,13],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将满脸不可置信，声音里半分嘶吼半分茫然，握着画戟的手不住轻颤',
   '固定镜头，这名猛将不可置信地低声喃喃，握戟的手指微微发颤，整个人像被抽去了力气',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','泣中的女子','锁定猛将失神的眼','stable',
   'A static close-up holds the crowned warrior, disbelief draining the color from his face as he murmurs: <d>[Chinese] 义父他怎能……做出这等事来！</d>'),
  (2.5,[14,14],'wide','Static Shot',['C07','C06'],[],
   '全景，华服的年轻女子扑进猛将怀里，哭得上气不接下气；猛将僵在当场，浑身发抖却挣不开这股火',
   '固定镜头，年轻女子扑入猛将怀中放声哭，猛将僵立原地，双手想扶又不敢，整座亭子都被这哭声填满',
   '35mm 广角，中景深','二人 + 平视侧面','中心构图','相拥的两人','锁定猛将僵住的身形','stable'),
 ])
E8_2H = dict(scene=1,
 overall='He promises to win her justice; a shadow flickers among the trees and slips away toward the pavilion master.',
 music_en='A warmer promise, then a faint, ominous thread as the shadow departs.',
 blocking='吕布（C06）沉声许下替她讨公道的话；廊角树影里一个黑影闪了闪随即退去。',
 soundscape='猛将一句沉甸甸的承诺，随后树林里一声极轻的脚步响动，风过叶梢',
 music='一句转暖的乐句许下承诺，继而一缕不祥的细弦随那退去的黑影轻轻滑过',
 cuts=[
  (3.6,[15,15],'close','Static Shot',['C06'],[],
   '特写，这名猛将握住女子的肩，沉声许下那句定要替她讨个公道的话，眉目间怒与怜交织',
   '固定镜头，这名猛将一手按着她的肩，沉声许下承诺，字字都像是烙进骨子里',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','怀中的女子','锁定猛将郑重的眼','stable',
   'A static close-up holds the crowned warrior as he makes a solemn vow, fury and tenderness crossing his face: <d>[Chinese] 貂蝉，你放心，我定替你讨个公道。</d>'),
  (2.5,[16,16],'wide','Pan Left',['C06'],[],
   '全景，廊角一人高的树影里，一道黑影闪了闪，随即悄无声息地隐没，正是要去向亭主报信的暗哨',
   '镜头缓缓向左摇过树影，一道黑影从暗处飞快一闪后隐没，动作轻得几乎没有声响',
   '35mm 广角，中景深','树影 + 平视远眺','引导线构图','隐没的黑影','锁定那道一闪即没的黑影','stable'),
 ])
E8_2I = dict(scene=1,
 overall='She asks only for his safety, and holding her close he answers the same while his gaze slowly turns to ice.',
 music_en='A tender murmur, then a low, cold thread as his eyes harden.',
 blocking='貂蝉（C07）只盼猛将平安；吕布（C06）把她往怀里一收，目光却冷冷一寸寸沉下去。',
 soundscape='女子只求一句平安的软话，猛将低头应下，亭外风过，暮色更深',
 music='一句柔和的低语，随后一缕低冷弦音压住，眼中寒意一寸寸漫开',
 cuts=[
  (4.4,[17,17],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子把脸埋在他胸前，声音闷闷地只求他平安，隐隐透着一丝不安',
   '固定镜头，这名华服的年轻女子埋首低语，声音又轻又软，只盼他莫要为她涉险',
   '85mm 长焦，浅景深','女子 + 侧面平视','中心构图','猛将胸口','锁定女子低垂的眉眼','stable',
   'A static close-up holds the young woman as she murmurs against his chest, asking only for his safety: <d>[Chinese] 将军千万莫要轻举妄动，妾身只盼将军平安。</d>'),
  (2.5,[18,18],'extreme-close','Static Shot',['C06'],[],
   '大特写，这名猛将把女子往怀里一收，垂着眼低声应下那句平安，眼底却一寸一寸地变冷，冷得像结了霜',
   '固定大特写，这名猛将把人收紧在怀里，嘴上应得温存，目光却冷冷地一寸寸沉下去',
   '100mm 微距，极浅景深','猛将的眼 + 平视','中心构图','怀中的女子','锁定猛将逐渐结冰的眼神','stable'),
 ])

# =============== scene 3 : 董卓居所 (beats 1-12) C07/C09 ===============
E8_3A = dict(scene=1,
 overall='In the tyrant\u2019s chambers at night the young woman kneels on a cushion, weeping, and the bloated ruler asks who has displeased her.',
 music_en='A heavy, sluggish pluck; low and menacing around a softer thread.',
 blocking='董卓（C09）居所内，貂蝉（C07）跪坐垂泪；董卓开口询问。',
 soundscape='夜深，烛影摇乱，女子低低的抽泣，随后一道沉而骄横的声音开口询问',
 music='一段沉重懒怠的音调垫底，绕着女子那弱软的一线渗出威胁',
 cuts=[
  (2.5,[1,1],'medium','Static Shot',['C07'],[],
   '中景，夜，董卓居所内，一名华服的年轻女子跪坐在软垫上，垂着头掩面低泣，烛影在梁上一片摇乱',
   '固定镜头，这名华服的年轻女子跪坐软垫垂泪不语，烛影把她的身影摇成一片慌',
   '50mm 标准，中浅景深','女子 + 平视侧面','三分法','烛影','锁定女子垂泪的身形','stable'),
  (2.7,[2,2],'close','Static Shot',['C09'],[],
   '特写，一名体躯臃肿、满脸戾气的凶戾权臣走近，放软了声音开口，神情亲昵却透着不容拒绝的威压',
   '固定镜头，这名体躯臃肿的权臣走近，声音放得和缓，眉眼间的戾气却依旧压人',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','垂泪的女子','锁定权臣假作温存的神情','stable',
   'A static close-up holds the bloated tyrant as he speaks with feigned tenderness: <d>[Chinese] 美人，谁又惹你不痛快了？</d>'),
 ])
E8_3B = dict(scene=1,
 overall='Through her tears she voices the wound of idle gossip, then suddenly draws a hairpin to her own throat until the tyrant snatches it away.',
 music_en='A trembling complaint, cut by a sharp, frightened jolt.',
 blocking='貂蝉（C07）含泪诉苦；董卓（C09）见她要拔簪自戕，慌上前一把抢下。',
 soundscape='女子泣诉着里里外外的闲话伤人，忽地一声金簪出鞘，随即权臣惊喝的闷响',
 music='颤巍巍的诉苦弦音其后陡然一乱，被一声惊惧的断音打断',
 cuts=[
  (4.9,[3,3],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子含泪把委屈一五一十说出来，说那闲话里外伤人，自己受尽委屈',
   '固定镜头，这名华服的年轻女子拭泪诉苦，声音低软凄惶，字字都像受了天大委屈',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','权臣','锁定女子含泪的眉眼','stable',
   'A static close-up holds the young woman as she weeps out the sting of idle tongues wounding her: <d>[Chinese] 相国待妾再好，也拗不过那里里外外的闲话伤人。</d>'),
  (2.5,[4,4],'medium','Pan Right',['C07','C09'],[],
   '中景，这名华服的年轻女子说着说着竟拔下簪子抵住自己的咽喉，吓得那凶戾权臣慌上前一把抢下',
   '镜头向右轻摇，女子忽地拔簪抵喉，权臣慌忙抢步上前一把夺下簪子，惊出一身冷汗',
   '50mm 标准，中浅景深','二人 + 平视侧面','三分法','女子腕间的簪','锁定抢夺簪子的手','slight-shake'),
 ])
E8_3C = dict(scene=1,
 overall='The tyrant swears to make anyone who wrongs her pay, and she weeps that even so someone does not treat her as a person.',
 music_en='A blunt, heavy oath; the woman\u2019s thread dips low and raw.',
 blocking='董卓（C09）大怒放话替她撑腰；貂蝉（C07）哭诉仍有人不将她当人看。',
 soundscape='权臣一声震怒的许诺，随后女子夹着泣的控诉，屋里气压陡低',
 music='一句钝重的誓言砸下，女子那线音随之沉低、发哑',
 cuts=[
  (5.1,[5,5],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣脸色一沉，声音里带着暴怒与狠劲放话，一副谁伤了爱妾就要谁命的架势',
   '固定镜头，这名凶戾权臣沉下脸放话，眉间戾气尽显，话语满是凶狠的威慑',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','眼前的美妾','锁定权臣怒狠的眉眼','stable',
   'A static close-up holds the tyrant as rage colors his voice and he vows to make any offender pay: <d>[Chinese] 美人这是做什么！谁欺负你，我让他吃不了兜着走！</d>'),
  (4.9,[6,6],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子哭得更咽，说有人一面护着她一面却从不将她当人看，委屈到了极点',
   '固定镜头，这名华服的年轻女子哽咽着诉,语带幽怨，似有所指又不敢言尽',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','权臣','锁定女子幽怨欲泣的眼','stable',
   'A static close-up holds the young woman as she weeps that even shielded she is never treated as a person: <d>[Chinese] 将军以妾身如此护着，偏有人不将妾身视作人看。</d>'),
 ])
E8_3D = dict(scene=1,
 overall='The tyrant\u2019s suspicion kindles and he turns toward the corridor; the woman feigns dread and begs him not to blame the man.',
 music_en='A low, creeping suspicion; a fluttered denial.',
 blocking='董卓（C09）猛地抬眼看向廊外，问是不是奉先；貂蝉（C07）低头只求莫怪罪于他。',
 soundscape='权臣一声森然低问，随后女子慌乱的推脱声，烛影在窗纸上一阵急晃',
 music='一缕低而趋前的疑音漫上，紧着一声慌乱的否认轻轻荡开',
 cuts=[
  (2.5,[7,7],'medium','Push In',['C09'],[],
   '中景，这名综合其凶戾的权臣猛地抬眼，森然望着廊外方向，只是短短一瞬，眉眼便染上戒备',
   '镜头朝这名权臣缓缓推近，他突然抬眼望向廊外，目光森然，像已经锁定了某个身影',
   '50mm 标准，中浅景深','权臣 + 侧前平视','三分法','廊外黑影','锁定权臣骤凝的目光','stable'),
  (2.7,[8,8],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣眯起眼，试探着问出一句，声音压得又低又冷，像蛇信吐着毒',
   '固定镜头，这名凶戾权臣眯眼低问，话里带着试探与凶意，一字字压得极沉',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','跪坐的女子','锁定权臣眯起的眼','stable',
   'A static close-up holds the tyrant as he narrows his eyes and asks in a cold, serpentine voice: <d>[Chinese] 你说的是……奉先那小子？</d>'),
  (3.8,[9,9],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子低头不敢妄议，只求他莫要因此怪罪于人，声音低得几乎听不见',
   '固定镜头，这名华服的年轻女子低垂眉眼，声音轻轻，只一味求情莫怪罪于人',
   '85mm 长焦，浅景深','女子 + 平视正侧面','三分法','权臣','锁定女子低垂示弱的眉眼','stable',
   'A static close-up holds the young woman as she lowers her head and pleads him not to blame anyone: <d>[Chinese] 妾身不敢妄议，只求相国莫怪罪于他。</d>'),
 ])
E8_3E = dict(scene=1,
 overall='Beyond the door the warrior passing duty hears the weeping; a cold threat is hurled at the tyrant, and father-son ties crack apart.',
 music_en='A blade-sharp string cuts the night; the room goes still and hollow.',
 blocking='门外吕布（不在框内）听见哭声；董卓（C09）在室内，闻言脸色一变；那道身影随即一甩袖转身远去。',
 soundscape='门外一道几不可闻的握戟声响，随即一句冷恻恻的话隔着门板传来，像刀锋悬落',
 music='一声刀锋般锋利的弦音斩开夜色，室内随之一片萧索的铁皮死寂',
 cuts=[
  (2.5,[10,10],'medium','Static Shot',['C09'],[],
   '中景，凶戾权臣在室内步伐微微一顿，像是觉察到门外有异，眉眼间浮起一丝戒备',
   '固定镜头，这名凶戾权臣在烛光里脚步一顿，侧耳望向门扉方向，神色微变',
   '50mm 标准，中浅景深','权臣 + 平视侧面','三分法','门扉','锁定权臣顿住的侧影','stable'),
  (4.0,[11,11],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣像是听见门外一句极冷的话，脸色刷地一紧，握在手中的杯盏几不可察地凝住',
   '固定镜头，这名凶戾权臣神色一凝，门外的冷话隔着门板压进来，屋里静得落针可闻',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','门扉','锁定权臣骤变的面容','stable',
   'A static close-up holds the tyrant as a cold voice cuts through from beyond the door, the words hanging like a drawn blade: <d>[Chinese] 董卓，你占了我的女人，此仇不共戴天。</d>'),
  (2.5,[12,12],'wide','Pan Right',['C09'],[],
   '全景，窗外一道身影像是一甩袍袖，随即大步转身远去，那一瞬，父子情谊便已裂作两半',
   '镜头向右摇过窗棂，一道身影猛地一甩袖转身离去的剪影很快融入夜色，仅余一声袍响',
   '35mm 广角，中景深','窗外 + 平视远眺','引导线构图','远去的背影','锁定那道转开的背影','stable'),
 ])

# =============== scene 4 : 凤仪亭兴师 (beats 1-16) C06/C07/C09 ===============
E8_4A = dict(scene=1,
 overall='At dusk the tyrant summons the young woman to drink and spies her instead talking with the warrior alone in the pavilion.',
 music_en='A heavy, wrathful drumbeat begins to gather under the scene.',
 blocking='董卓（C09）正欲召貂蝉共饮，却见凤仪亭下貂蝉（C07）与吕布（C06）并肩低语。',
 soundscape='黄昏的风，远处滕挪的杯盏声，随即权臣脚步一顿、目光骤沉',
 music='一段沉重而渐怒的鼓点，从画面底部缓缓聚拢上来',
 cuts=[
  (2.5,[1,1],'medium','Static Shot',['C09'],[],
   '中景，黄昏，凶戾权臣远远立于廊上，正欲召那华服女子来共饮，却见她站在凤仪亭下与另一人说话',
   '固定镜头，这名凶戾权臣立于廊上，目光越过花木望向亭下，正要开口唤人',
   '50mm 标准，中浅景深','权臣 + 平视正面','三分法','远处的亭子','锁定权臣望去的目光','stable'),
  (2.5,[2,2],'wide','Push In',['C09'],[],
   '全景，权臣定睛一看，亭中立着一名头戴雉尾紫金冠的猛将，两人正并肩低语、挨得极近',
   '镜头朝权臣缓缓推近的视野里，亭中猛将与年轻女子并肩低语，挨得极近，举止亲密',
   '35mm 广角，中景深','权臣视野 + 平视远眺','引导线构图','亭中并肩的二人','锁定亲密交谈的二人','stable'),
 ])
E8_4B = dict(scene=1,
 overall='The tyrant strides grimly through the flowers and the warrior steps protectively in front of the woman.',
 music_en='The drums close; heavy, unhurried steps on the path.',
 blocking='董卓（C09）脸色铁青大步穿过花木直奔亭子；吕布（C06）闻声一步横到貂蝉（C07）身前。',
 soundscape='权臣急促逼近的脚步碾过花木，狂风卷起一地落花，亭中二人同时回头',
 music='鼓点收紧，一阵急促而不乱的脚步压在花枝翻动的声响里',
 cuts=[
  (2.5,[3,3],'medium','Truck Left',['C09'],[],
   '中景，凶戾权臣脸色铁青，大步穿过花木直奔亭子，袍角带起一地落花乱飞',
   '镜头随权臣向左跟进，他面色铁青踏过花径，激起落花乱舞，气势汹汹逼近亭子',
   '50mm 标准，中浅景深','权臣 + 侧前平视跟随','引导线构图','前方亭子','锁定权臣大步逼近','slight-shake'),
  (2.5,[4,4],'medium','Static Shot',['C06','C07'],[],
   '中景，亭中的猛将闻声回头，见权臣一脸怒容，下意识一步横到年轻女子身前，把她护在身后',
   '固定镜头，猛将闻声侧身一横，稳稳挡到年轻女子身前，下意识地把她护住',
   '50mm 标准，中浅景深','二人 + 平视侧面','三分法','逼来的权臣','锁定挡身的猛将','stable'),
 ])
E8_4C = dict(scene=1,
 overall='A furious accusation over the two of them, met by the warrior\u2019s denial that they acted beyond conversation.',
 music_en='An angry clash of strings, then a wary deflection.',
 blocking='董卓（C09）怒斥；吕布（C06）忙辩解二人并无逾矩。',
 soundscape='权臣一声暴怒的喝问刺破暮色，紧着猛将急急的辩解声',
 music='一段怒弦当头砸下，转为一节戒备而小心辩白的音',
 cuts=[
  (2.7,[5,5],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣怒目圆睁，暴喝出声，唾沫几乎喷到两人脸上，气势逼人',
   '固定镜头，这名凶戾权臣怒目暴喝，眉间戾气暴涨，一声比一声高',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','亭中二人','锁定权臣怒目','slight-shake',
   'A static close-up holds the tyrant as he roars in fury, spittle flying: <d>[Chinese] 逆子！你背着我在此作甚！</d>'),
  (4.2,[6,6],'close','Static Shot',['C06'],[],
   '特写，这名头戴雉尾紫金冠的猛将忙上前一步，放软声音辩解，只说两人并无逾矩，只是话话家常',
   '固定镜头，这名猛将急急上前辩解，态度尽力放软，想把这番误会轻轻揭过',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','怒中的权臣','锁定猛将辩解的神色','stable',
   'A static close-up holds the crowned warrior as he steps forward with a placating tone: <d>[Chinese] 义父！我与貂蝉并无逾矩，只是话话家常。</d>'),
 ])
E8_4D = dict(scene=1,
 overall='The tyrant hurls his halberd and names her his own; the warrior parries the blade aside, and the woman falls to the feet of the tyrant in tears.',
 music_en='A sharp clash of metal, a frightened cry, a sob.',
 blocking='董卓（C09）掷出画戟却被吕布（C06）架开；貂蝉（C07）顺势扑倒哭诉。',
 soundscape='一声金铁暴响，画戟被架开，随后女子一声惊呼与哭诉，冠盖俱落',
 music='一声尖利的金铁撞击，随后一句惊恐的惊呼夹着低泣',
 cuts=[
  (2.4,[7,7],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣一字一字地说出那句我的美人你也敢染指，目光死死钉着挡身的那名猛将',
   '固定镜头，这名凶戾权臣一字一顿地低喝，目光如刀，直直刺向挡身的猛将',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','猛将','锁定权臣恨毒的目光','stable',
   'A static close-up holds the tyrant as he spits out the poisoned accusation: <d>[Chinese] 我的美人，你也敢染指！</d>'),
  (2.5,[8,8],'medium','Static Shot',['C06'],[],
   '中景，猛将侧身一把架开掷来的画戟，金石相撞，火星四溅，二人剑拔弩张',
   '固定镜头，猛将侧身挥戟一格，将掷来的画戟荡开，火星迸射，两人隔着兵刃对峙',
   '50mm 标准，中浅景深','猛将 + 平视侧面','中心构图','相撞的兵刃','锁定架开的画戟','slight-shake'),
  (2.5,[9,9],'medium','Static Shot',['C07'],[],
   '中景，年轻女子被这场面一吓，惊呼一声，顺势扑倒在凶戾权臣脚边，哭得梨花带雨',
   '固定镜头，这名华服的年轻女子一声惊呼，顺势扑到权臣脚边，哭得肩膀一耸一耸',
   '50mm 标准，中浅景深','女子 + 平视侧面','三分法','权臣的袍角','锁定扑倒哭诉的女子','stable'),
 ])
E8_4E = dict(scene=1,
 overall='She begs the tyrant to relent for the sake of father and son; the warrior declares he will leave Chang\u2019an if he is counted an enemy.',
 music_en='A pleading thread under the tyrant\u2019s wrath, then a steely resolve in the warrior.',
 blocking='貂蝉（C07）哭求权臣息怒莫伤父子情分；吕布（C06）扬言若视为儿为仇便远离。',
 soundscape='女子带着泣的哀求，随后猛将一句硬邦邦的决绝话掷到两人之间',
 music='一段哀求的细弦压在权臣的怒火底下，再接一句钢铁般冷硬的决意',
 cuts=[
  (4.7,[10,10],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子扑在权臣脚边，仰着脸哭求，句句都是让如今这父子情分得保全',
   '固定镜头，这名华服的年轻女子仰脸哭求，声音又软又急，一心只想平息这场兵戈',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','权臣','锁定女子仰脸哀求的眼神','slight-shake',
   'A static close-up holds the young woman as she weeps and begs the tyrant to spare their father-son bond: <d>[Chinese] 相国息怒！都是妾身不好，莫要伤了父子情分！</d>'),
  (4.0,[11,11],'close','Static Shot',['C06'],[],
   '特写，猛将却硬起心肠，一句决绝的话掷出，说若被视为仇敌，他便离开长安',
   '固定镜头，这名猛将神色转冷，硬声说出决绝之语，摆出一副若不容我我便走的姿态',
   '85mm 长焦，浅景深','猛将 + 平视正面','中心构图','权臣','锁定猛将决绝的眼','stable',
   'A static close-up holds the crowned warrior as his voice turns steely: <d>[Chinese] 义父若视为儿为仇，儿今日便远离长安！</d>'),
 ])
E8_4F = dict(scene=1,
 overall='The tyrant, hand trembling, flings down his halberd and vows to see what storm the warrior can raise.',
 music_en='A held, ominous calm before the tyrant\u2019s cold laugh.',
 blocking='董卓（C09）手一抖丢开画戟，指着吕布（C06）半晌说不出话，随即冷笑放话。',
 soundscape='画戟脱手落地一声闷响，权臣指着对方半晌无声，终于挤出一声冷笑与狠话',
 music='一段凝滞的不祥静默，随后伴着冷笑压下一句低沉的威胁',
 cuts=[
  (2.5,[12,12],'medium','Static Shot',['C09'],[],
   '中景，凶戾权臣手一抖，把画戟当啷丢开，指着那名猛将，一时气得说不出话，胸脯急剧起伏',
   '固定镜头，这名凶戾权臣手一抖脱手丢开画戟，指着对面，气到胸膛剧烈起伏',
   '50mm 标准，中浅景深','权臣 + 平视正面','三分法','被指的猛将','锁定权臣气得发抖的手','slight-shake'),
  (4.0,[13,13],'close','Static Shot',['C09'],[],
   '特写，凶戾权臣终于缓过一口气，冷笑着开口放话，说倒要看看你还能翻出什么浪来',
   '固定镜头，这名凶戾权臣冷笑放话，目光阴冷狠厉，一言一字都是挑战',
   '85mm 长焦，浅景深','权臣 + 平视正面','中心构图','猛将','锁定权臣冷笑的唇','stable',
   'A static close-up holds the tyrant as he recovers himself and sneers out a cold challenge: <d>[Chinese] 好，好！我倒要看看你能翻出什么浪来！</d>'),
 ])
E8_4G = dict(scene=1,
 overall='The woman begs him to keep his peace of mind; the tyrant helps her up while glaring at the warrior, who bows and strides away with clenched fists.',
 music_en='A final tender plea, a low threat, and the heavy tread of leaving.',
 blocking='貂蝉（C07）求权臣宽心；董卓（C09）扶起她仍猛剜吕布（C06）；吕布抱拳大步而去。',
 soundscape='女子一句低低的宽慰，随后权臣一声闷哼，脚步杂沓中猛将抱拳离去、袖中攥拳',
 music='一句轻柔的恳求收尾，接权臣低沉的威胁，再以猛将离开的沉重脚步碾过',
 cuts=[
  (4.7,[14,14],'close','Static Shot',['C07'],[],
   '特写，华服的年轻女子被权臣扶着站起，仍柔声劝他宽心，千万别气坏了自己身子',
   '固定镜头，这名华服的年轻女子借着权臣的搀扶起身，低声软语地劝慰，只求他消气',
   '85mm 长焦，浅景深','女子 + 平视正面','中心构图','权臣','锁定女子温顺示弱的眉眼','stable',
   'A static close-up holds the young woman as she pleads with the tyrant to keep his peace: <d>[Chinese] 相国，妾身只求相国宽心，千万别气坏了身子。</d>'),
  (2.5,[15,15],'medium','Static Shot',['C09'],[],
   '中景，凶戾权臣哼了一声，弯腰扶起华服的年轻女子，一双眼睛却恶狠狠剜向一旁的猛将',
   '固定镜头，这名凶戾权臣弯腰扶起女子，抬眼时那恶狠狠的目光仍不放过立在一旁的猛将',
   '50mm 标准，中浅景深','权臣 + 平视侧面','三分法','一旁的猛将','锁定权臣剜出的目光','stable'),
  (2.5,[16,16],'wide','Static Shot',['C06'],[],
   '全景，那名猛将退到廊檐下，一抱拳，随即大步而去，袖中的手早已攥得青筋直冒',
   '固定镜头，猛将退至廊下抱拳一礼，转身大步离去，步伐又急又重，掩不住的怒与屈',
   '35mm 广角，中景深','猛将 + 侧后平视','引导线构图','前方的回廊','锁定猛将离去的背影','stable'),
 ])

EP8_SC1 = [E8_1A, E8_1B, E8_1C, E8_1D, E8_1E, E8_1F]
EP8_SC2 = [E8_2A, E8_2B, E8_2C, E8_2D, E8_2E, E8_2F, E8_2G, E8_2H, E8_2I]
EP8_SC3 = [E8_3A, E8_3B, E8_3C, E8_3D, E8_3E]
EP8_SC4 = [E8_4A, E8_4B, E8_4C, E8_4D, E8_4E, E8_4F, E8_4G]
for seg in EP8_SC1: seg['sceneIndex'] = 1
for seg in EP8_SC2: seg['sceneIndex'] = 2
for seg in EP8_SC3: seg['sceneIndex'] = 3
for seg in EP8_SC4: seg['sceneIndex'] = 4
EP8 = EP8_SC1 + EP8_SC2 + EP8_SC3 + EP8_SC4